### ISSUE TITLE
Support request: Python3 builds "suddenly" failing

### ISSUE THREAD

**Issue by joakim-hove** [travis-ci/travis-ci#10079]
NB: This is more of support request based on the account "Statoil" than a normal community style github issue.

We have codebase consisting of a C/C++ core and Python wrappers. We mainly use Python version 2.7, but we are building Python3 on Travis and try to prepare for a long overdue upgrade of Python version. The codebase is split over three repositories:

1. https://github.com/Statoil/libecl/
2. https://github.com/Statoil/libres/
3. https://github.com/Statoil/ert/

The travis build is based on this script: https://github.com/Statoil/ert/blob/master/travis/build_total.py This has worked for quite some time, but "suddenly" the Python3 build has started to fail:

Examples of a failed PR is: https://github.com/Statoil/libecl/pull/463 If we could get some help in looking into this issue that would be very good. Conda problem/changes??

**Comment by BanzaiMan** [comment]
Hello, there.

It is unfortunately immediately clear to me how the builds are failing. We have enabled [debug feature](https://docs.travis-ci.com/user/running-build-in-debug-mode/#restarting-a-job-in-debug-mode-via-api) for these repositories, so that you can troubleshoot interactively.

Let us know if we can help you further.
