### ISSUE TITLE
Jobs hanging before `Build system information`

### ISSUE THREAD

**Issue by yufangong** [travis-ci/travis-ci#10130]
We have jobs randomly hang on TravisCI. The logs show they stopped after printing out `Work information` but before `Build system information` so I assume this is not related to job config. 
Here's an example: https://travis-ci.org/twitter/finagle/jobs/430257481. Thanks in advance.

**Comment by cotsog** [comment]
This is a known issue with one of the infrastructure providers we are using for the `sudo: false` builds. We have an internal issue opened and our Engineering Team is looking into it but we haven't found the root cause yet. Sorry for the inconvenience.

In the meantime, I would suggest you run your builds on our sudo-enabled infrastructure instead with `sudo: required` in your .travis.yml file. The issue doesn't happen over there. Hope this helps!

**Comment by yufangong** [comment]
@cotsog thanks!
