### ISSUE TITLE
Duplicate builds

### ISSUE THREAD

**Issue by Seluj78** [travis-ci/travis-ci#10152]
Hi  there ! It seems like my builds are duplicated... One succeeds and the other errors... Any idea why ?

Success
https://travis-ci.org/Seluj78/juleslasne/jobs/433385175
Error
https://travis-ci.com/Seluj78/juleslasne/jobs/147999813

**Comment by BanzaiMan** [comment]
Hello, there. Looks like your repository is somehow active on both https://travis-ci.org and https://travis-ci.com. Do you remember how you enabled Travis CI?

**Comment by Seluj78** [comment]
Hey ! Oh wow I didn't even notice the URL difference ! Well that's strange, I enabled the repo this morning on .org, and I've used the .com in the past but not for this repo for sure !

**Comment by cotsog** [comment]
I think what happened is that you had Travis CI enabled for "All repos" in our app on GitHub. So when you created that repo (or added a .travis.yml file), it was automatically enabled on travis-ci.com and builds started there. You have manually enabled it on travis-ci.org afterward causing the duplication.

[Since we are in the process of moving all open source repos on travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps), we would suggest you disable the repo on travis-ci.org by going to your profile page: https://travis-ci.org/profile.

Let us know if this helps.

Thanks!

**Comment by Seluj78** [comment]
Hey ! Thanks for the answer ! I've disabled my repo on `.org` and enabled it on `.com` but now I'm getting the `This project hasn’t been migrated` message on the repo :sob:

**Comment by Seluj78** [comment]
``` The following repositories cannot be migrated to travis-ci.com at this time because they are currently active on our legacy platform travis-ci.org.```
That's weird, i've disabled everything from the `.org` travis

**Comment by Seluj78** [comment]
![screenshot from 2018-09-26 15-10-48](https://user-images.githubusercontent.com/4641317/46082062-63504a80-c19e-11e8-9c82-2e9682cacd37.png)

**Comment by Seluj78** [comment]
And here's `https://travis-ci.com`
![screenshot from 2018-09-26 15-11-51](https://user-images.githubusercontent.com/4641317/46082106-90046200-c19e-11e8-8546-b6e9ffee512b.png)

**Comment by cotsog** [comment]
@Seluj78 Sorry for the continued troubles!

I've just proceeded to migrate it from our side. Could you tell me if it works?

We are gonna look into why that happen and try to fix this workflow.

Sorry again for the inconvenience!

**Comment by Seluj78** [comment]
It worked perfectly, and apart from the env var, everything was migrated ! Thanks a lot

Keep up the AMAZING work you do and cheers !
