### ISSUE TITLE
Expected — Waiting for status to be reported (GitHub - Travis-CI)

### ISSUE THREAD

**Issue by smruticrealytics** [travis-ci/travis-ci#10187]
Is https://github.com/travis-ci/travis-ci/issues/7460 really fixed?
I saw it again today 

![image](https://user-images.githubusercontent.com/39901401/46544692-94c6c580-c8c4-11e8-9d8c-d667e32f3cba.png)

**Comment by yiyangfei** [comment]
Same here.  
![image](https://user-images.githubusercontent.com/3411472/46545918-89e84280-c87c-11e8-8ce6-0142d98e70a1.png)

**Comment by BanzaiMan** [comment]
Please read this blog post and follow the advice. Thanks. https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories

**Comment by BanzaiMan** [comment]
I've written https://github.com/travis-ci/travis-ci/issues/10204 for a more direct explanation.

**Comment by CaddyDz** [comment]
Hello, this is really frustrating, we're not using GitHub Services, in fact we never did since the repo was created recently with GitHub apps by default but we do see this
![screenshot from 2018-11-29 08-07-39](https://user-images.githubusercontent.com/13698160/49205303-e6646b80-f3ae-11e8-882d-32834e719927.png)

and status is never received even after a triggered build or CRON build

And here are the protected branch rules
![screenshot from 2018-11-29 08-16-47](https://user-images.githubusercontent.com/13698160/49205406-35aa9c00-f3af-11e8-94da-cf94afa9e23e.png)
Are we doing something wrong or is this an issue with Travis CI itself?

**Comment by dalonsoa** [comment]
Has there been any progress on this lately? I'm having the same issue and the explanations given in the related links are of no use: I am already doing that!
<img width="713" alt="image" src="https://user-images.githubusercontent.com/6095790/54618537-17020b00-4a5b-11e9-9f8a-392d3a22946b.png">

Do you have any suggestion?

**Comment by edwardhartnett** [comment]
Any progress on this issue? I am seeing this also. It's frustrating!

**Comment by tholu** [comment]
Seeing it in https://github.com/matomo-org/piwik-java-tracker/pull/30 - build has passed: https://travis-ci.org/github/matomo-org/piwik-java-tracker/builds/665191664

**Comment by iamareebjamal** [comment]
Same for us

**Comment by Helveg** [comment]
An answer on this would be nice? Seems like the first client-facing very frequent symptom of underlying "catch-all"/"Travis downtime" issues?

**Comment by josiahsrc** [comment]
Just ran into this as well. My workaround was to close and reopen the pull request. This doesn't solve the bug, but could at least get the checks unstuck
