### ISSUE TITLE
Is there a way to know from environment variables if build was restarted?

### ISSUE THREAD

**Issue by bahmutov** [travis-ci/travis-ci#10209]
When we load balance end-to-end tests using Cypress.io test runner we look at the environment variables to tie builds from different machines together. Which means that if a build has been restarted manually, everything goes wrong - the builds seem to have all the same environment variables. 

Is there a way to "know" if the build has been restarted?

**Comment by BanzaiMan** [comment]
There is no way to do so currently.

**Comment by amirrustam** [comment]
Are there any plans to signify a build restart via env vars?

**Comment by BanzaiMan** [comment]
I am afraid not. It seems to me that you would want to tie that process to deployment rather than the build itself. Within the deployment process, you would be looking at the state of your end-to-end testing machine setup and not do the thing that breaks stuff, rather than failing miserably.

It also seems like a process problem. Who is restarting the build, and why?

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
