### ISSUE TITLE
Travis handle deploy stage failure

### ISSUE THREAD

**Issue by sriramts** [travis-ci/travis-ci#10202]
I have a deploy scripts that fails during deployment and the build errors out saying Your build has been stopped. I do want to run another script upon failure to notify some other application of the build failure. Right now, when the deploy phase fails, the build just is stopped. It does not seem to enter the after_script section at all. What is the best way to handle this?

**Comment by jamietsao** [comment]
We are observing the same behavior.  When the `deploy` step fails, neither `after_deploy` or `after_script` is run.  This seems to contradict this post: https://blog.travis-ci.com/after_script_behavior_changes (the post is from 2012 so maybe the behavior has changed?)

It's not super clear (unless I'm missing it) what the expected behavior should be even after reading this: https://docs.travis-ci.com/user/customizing-the-build

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
