### ISSUE TITLE
PR build using WRONG COMMIT entirely

### ISSUE THREAD

**Issue by remram44** [travis-ci/travis-ci#10210]
I updated my pull request during this build: https://travis-ci.org/jbardin/scp.py/builds/439188626

While a new build was started with the updated branch, some jobs of the running build picked up the UPDATED branch, while others used the old one (the ones that succeeded).

**Comment by mmcc007** [comment]
If there is a deploy during the build, this can result in the wrong code being deployed

**Comment by BanzaiMan** [comment]
Deployment should not happen on PR builds.

**Comment by mmcc007** [comment]
I know, I was pointing out that the same clone command, one that doesn't specify the commit, is used during non PR builds. So the same problem probably applies to all builds.

**Comment by BanzaiMan** [comment]
> I was pointing out that the same clone command, one that doesn't specify the commit, is used during non PR builds.

I don't think this is true. We check out the HEAD SHA in this case. https://travis-ci.org/BanzaiMan/travis_production_test/builds/436965215#L418 If you are seeing this, could you point to a build log that does this?

**Comment by BanzaiMan** [comment]
I believe this is a refrain of #8577. As I explained in https://github.com/travis-ci/travis-ci/issues/8577#issuecomment-336596843, I do not think this is something we can overcome easily.

I think autocanceling the PR builds might be our best option. https://docs.travis-ci.com/user/web-ui/#auto-cancel-pull-request-builds

**Comment by mmcc007** [comment]
Disregard my last comment, it is not correct. Had not looked into this in much depth. Since, as you say in the linked comment, git only permits checking out the FETCH_HEAD, then stopping any jobs that start after a subsequent commit is a good option since the FETCH_HEAD SHA has changed and it is no longer possible to guarantee the integrity of the build.

Another possible option, based on my limited understanding of all the nuances of git, is to cache the checkout of the original FETCH_HEAD using a pull or something instead of a fetch, and use this in all jobs of the original build. Then, if the FETCH_HEAD changes, trigger a new build and repeat the process. This would be a smoother user experience, but might be a hassle to implement if even possible.

**Comment by szeder** [comment]
The payload of the ```pull_request``` webhook event contains a ```merge_commit_sha``` key, which, I presume, is the commit object name pointed to by the corresponding ```refs/pull/<NR>/merge``` ref.  If that's indeed the case, then after fetching ```refs/pull/<NR>/merge``` build jobs should explicitly check out that particular commit instead of FETCH_HEAD, and if that fails because FETCH_HEAD already points to a different merge commit, then the build job must not proceed.

**Comment by szeder** [comment]
However, for the sake of better user experience, Travis CI could try harder to build the original pull request, even after a pull request is updated and the corresponding ```refs/pull/<NR>/merge``` ref points to a different merge commit, if the to-be-pulled branch was fast-forwarded.

Upon arrival of a ```pull_request``` webhook event, Travis CI should take note of the value of ```merge_commit_sha``` in the event payload.  First it should query the GitHub API for information about that merge commit, in particular to get the object names of its tree and its parent commits, and take note of those as well.  After that it should go on and fetch ```refs/pull/<NR>/merge``` as usual, and then try to check out the commit in ```merge_commit_sha``` (instead of FETCH_HEAD, as suggested in my previous comment).  Now, even if checking out that particular merge commit were to fail because the pull request was updated, there is still the possibility that the to-be-pulled branch was fast-forwarded, which would mean that the two commits merged together are likely already there in the build job's repo.  So, at this point Travis CI could use the parent object names retrieved by that GitHub API query, and could try to recreate the original merge by checking out the first parent and merging the second.  If this merge succeeds, then Travis CI should still err on the side of caution, and should make sure that the tree of the resulting merge commit matches the tree of the original merge commit, and if it does, then the build job could proceed.

Build jobs of branches already handle fast-forwards of the branch appropriately: they build from the right commit as long as that commit is available in the 50 commit shallow clone, otherwise they error out.

With the above proposed approach build jobs of pull requests would do so as well (OK, technically not from the exact same merge commit, but from the exact same tree, and that's what really matters.)

**Comment by hyperthunk** [comment]
I am running into this problem too, by the looks of things...

My PR [here](https://github.com/haskell-distributed/distributed-process/pull/331) has it's latest commit as [a48b822](https://github.com/haskell-distributed/distributed-process/pull/331/commits/a48b82248994b242fe6a3a7751eb44ff989148cc), however travis is building the PR against [this commit](https://github.com/haskell-distributed/distributed-process/commit/d3d739ee44a4ff2ffff57b943a02cd8f6264362d). Basically PR building seems to be completely broken for my project now, I *cannot* seem to get any PR to build against the correct commit for this branch. I am going to attempt to build a squashed commit and force it across into a new branch and see if that works...

**Comment by hyperthunk** [comment]
See build logs [here](https://travis-ci.org/haskell-distributed/distributed-process/jobs/458972755)

**Comment by DrTorte** [comment]
Hello,

As we're no longer supporting GitHub issues but this issue remains open, I'm creating a copy of this on the forum. [Please see this link](https://travis-ci.community/t/issue-pr-build-using-wrong-commit-entirely-migrated-from-github/1153).

Thanks and happy building!

**Comment by OliverJAsh** [comment]
Is there any update on what happened to @szeder's proposal?
