### ISSUE TITLE
Pagination within org page is broken

### ISSUE THREAD

**Issue by maciossek** [travis-ci/travis-ci#10246]
I am on the following page:

https://travis-ci.org/organizations/hft-stuttgart-ipr/repositories

The pagination on the bottom links to the folling pages:

https://travis-ci.org/account/repositories
https://travis-ci.org/account/repositories?page=2

**Comment by BanzaiMan** [comment]
Thanks for opening the issue. Indeed, those links should reflect the organization you are currently viewing.

**Comment by DrTorte** [comment]
Hello,

I've made sure this issue is tracked internally. In the meantime, we're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If you run into anything else, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
