### ISSUE TITLE
osx: "brew upgrade" failed and exited with 1 during

### ISSUE THREAD

**Issue by BorzdeG** [travis-ci/travis-ci#10275]
https://travis-ci.org/itbasis/jvm-wrapper-ide-plugins/jobs/444295749#L2201

**Comment by Minoru** [comment]
My builds started failing too, even though I didn't change .travis.yml and can't see any version changes in the build logs:
- [the failing one](https://travis-ci.org/newsboat/newsboat/jobs/444297923)
- [one that worked fine just 16 hours ago](https://travis-ci.org/newsboat/newsboat/jobs/444138864)

**Comment by acgetchell** [comment]
Likewise. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Minoru** [comment]
I reported this [upstream](https://github.com/Homebrew/homebrew-core/issues/33309), but they didn't see any failures in the output either. It was noted that Xcode 9.4 is no longer supported by Homebrew, but Travis didn't change Xcode version recently, so this can't be it.

**Comment by BanzaiMan** [comment]
Hmmm. OK. I will look at this again soon.

**Comment by Minoru** [comment]
Thank you!

I `diff`ed raw logs between successful build and failure, and the only 
difference that stood out to me was that successful build didn't update 
Homebrew. Perhaps you had exactly this in mind when you were comparing 
"no brew update" to "brew update"; I didn't catch your meaning back 
then. That's also the reason why I reported the issue to homebrew-core 
and not brew itself—I thought the issue must be with sqlite tap.

I think this has to be reproduced on real hardware before it can be 
brought to Homebrew developers again, but I don't have any Apple 
hardware.

**Comment by Minoru** [comment]
Upgrading to XCode 10 didn't help:
* https://travis-ci.org/newsboat/newsboat/jobs/445822066
* https://travis-ci.org/newsboat/newsboat/jobs/445822069

**Comment by BanzaiMan** [comment]
I ran the commands again, and I am pretty certain that this is an issue with Homebrew.

<details>
<summary><tt>brew upgrade "sqlite"</tt> output</summary>
Traviss-Mac-7:travis_production_test travis$ brew upgrade "sqlite"
==> Upgrading 1 outdated package:
sqlite 3.25.0 -> 3.25.2
==> Upgrading sqlite
==> Downloading https://homebrew.bintray.com/bottles/sqlite-3.25.2.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring sqlite-3.25.2.high_sierra.bottle.tar.gz
==> Caveats
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have sqlite first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

==> Summary
  /usr/local/Cellar/sqlite/3.25.2: 11 files, 3.7MB
==> Upgrading 5 dependents:
ansible 2.6.4 -> 2.7.0, geos 3.6.3 -> 3.7.0, mercurial 4.7.1 -> 4.7.2, numpy 1.15.1 -> 1.15.3, postgis 2.4.4_1 -> 2.5.0
==> Upgrading ansible
==> Downloading https://homebrew.bintray.com/bottles/ansible-2.7.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring ansible-2.7.0.high_sierra.bottle.tar.gz
⋮
==> Installing numpy dependency: gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-8.2.0.high_sierra.bottle.1.tar.gz
######################################################################## 100.0%
==> Pouring gcc-8.2.0.high_sierra.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'

To force the link and overwrite all conflicting files:
  brew link --overwrite gcc

To list all files that would be deleted:
⋮
libpq is keg-only, which means it was not symlinked into /usr/local,
because conflicts with postgres formula.

If you need to have libpq first in your PATH run:
  echo 'export PATH="/usr/local/opt/libpq/bin:$PATH"' >> ~/.bash_profile

For compilers to find libpq you may need to set:
  export LDFLAGS="-L/usr/local/opt/libpq/lib"
  export CPPFLAGS="-I/usr/local/opt/libpq/include"

For pkg-config to find libpq you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/libpq/lib/pkgconfig"

==> postgis
To create a spatially-enabled database, see the documentation:
  https://postgis.net/docs/manual-2.4/postgis_installation.html#create_new_db_extensions
If you are currently using PostGIS 2.0+, you can go the soft upgrade path:
  ALTER EXTENSION postgis UPDATE TO "2.5.0";
Users of 1.5 and below will need to go the hard-upgrade path, see here:
  https://postgis.net/docs/manual-2.4/postgis_installation.html#upgrading

PostGIS SQL scripts installed to:
  /usr/local/opt/postgis/share/postgis
PostGIS plugin libraries installed to:
  /usr/local/lib
PostGIS extension modules installed to:
  /usr/local/share/postgresql/extension
Traviss-Mac-7:travis_production_test travis$ echo $?
1
</details>

Upgrading a different package, say `git`, we get:

<details>
<summary><tt>brew upgrade "git"</tt> output</summary>
Traviss-Mac-7:travis_production_test travis$ brew upgrade git
==> Upgrading 1 outdated package:
git 2.19.0_1 -> 2.19.1
==> Upgrading git
==> Downloading https://homebrew.bintray.com/bottles/git-2.19.1.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring git-2.19.1.high_sierra.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
  /usr/local/Cellar/git/2.19.1: 1,518 files, 40.1MB
Traviss-Mac-7:travis_production_test travis$ echo $?
0
</summary>

One thing I do note here is that, in the case of `sqlite` is that Homebrew complains about link being updated correctly, and this is most likely the cause of the nonzero exit status.

I think you will have to account for that.

**Comment by dictoon** [comment]
We also have the issue over at [appleseed](https://github.com/appleseedhq/appleseed), here's a post I made on Travis forum:

https://travis-ci.community/t/macos-build-fails-when-brew-pouring-gcc-8-2-0/

I don't know of a solution (yet).

**Comment by Mizux** [comment]
Current working solution, try to force the gcc compilation **and** the *link* step:
```yml
brew update
brew install gcc || brew link --overwrite gcc
brew upgrade
```
src:  https://travis-ci.community/t/macos-build-fails-when-brew-pouring-gcc-8-2-0/442/11?u=mizux

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
