### ISSUE TITLE
oraclejdk8 with xcode10

### ISSUE THREAD

**Issue by 666tos** [travis-ci/travis-ci#10307]
Hi, i need to use `oraclejdk8` together with with `xcode10.1`, but `osx_image: xcode10.1` means `JDK11.0.1+13`. `jdk_switcher` seems to be not available on `osx`.

I also tried using following script with no luck

```
brew cask install caskroom/versions/java8
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

# Fail unless we installed JDK 8 correctly.
/usr/libexec/java_home --failfast --version 1.8

```

**Comment by BanzaiMan** [comment]
Sorry, but I don't think we can support this combination. High Sierra's default is Java 10, I believe, so if Homebrew can't work its magic, you'd have to make a compromise one way or another.

**Comment by maestor** [comment]
Related to this so I won't open new issue. Apple Store forces soon build stuff with XCode10.1. Problem is that Travis image comes with JDK11 and Android won't support Java 11. Because I have React Native application, it make sense to build and deploy both at the same process. But I haven't find any working solutions to get Android succesfully builded, (probably don't have enough skills to do something to get rid of that Java 11 and use 10 instead where you can get Android working with little tricks).

So question: Is there @BanzaiMan any way to get JDK10 installed to that xcode10.1 image? Since it's High Sierra and Java 10 is default as you said. And if yes, how that happens?
