### ISSUE TITLE
Emails thread confusingly in Gmail

### ISSUE THREAD

**Issue by mattbasta** [travis-ci/travis-ci#1048]
If a build is still failing, you get an email with a subject like "[Still Failing] mozilla/fireplace#93 (master - e77ef93)".

If the build is then fixed, the "[Fixed] ..." email gets threaded with the [Still Failing] email (on Gmail, at least). This means that when you click "[Still Failing]" in your inbox, you might see a green banner saying "The build was fixed."

An example:

![Capture](https://f.cloud.github.com/assets/279498/394972/153481c2-a7e1-11e2-84a2-c6df39269750.JPG)

Changing the sending address (`notifications+failing@travis-ci.org`, `notifications+passing@travis-ci.org`), or somehow differentiating the subject line in a more substantial way should prevent Gmail from threading these emails wildly. You can't tell what the result of a build is without opening the email because of this issue.

**Comment by eprogramgo** [comment]
Git"￼
￼
￼
￼
￼
Filters and Topics
All
Videos
Images
Shopping
News
Books
Maps
Flights
Finance
Search tools
Feedback
Search Results
Web results
￼
Tech Support Guy
https://www.techguy.org › threads
Whay do I see this when clicking on TG email links?
Dec 6, 2022 — Suddenly, I'm getting this a lot. When I receive an email notice from TechGuy that there is a post in a thread I'm following I see this ...
Missing: putting- ‎ crypto- ‎ wiz/ ‎ world- ‎ pentagon- ‎ 1291619/
Tech Support Guy
Apr 22, 2014
Need Help with Game File | Tech Support Guy
Mar 13, 2015
Please help - Tech Support Guy
Jan 13, 2022
GMAIL sign up? (#2) | Tech Support Guy
Feb 10, 2024
More results from www.techguy.org
￼
Reddit · r/Scams
10+ comments · 3 months ago
Got this email today on my Work email. Should I be worried or ignore it?
Greetings, I am sorry, but I have to start with the bad news. A few months ago, I gained access to your account linked to OS, and therefore to all the ...
Missing: techguy. ‎ org/ ‎ threads/ ‎ putting- ‎ wiz/ ‎ world- ‎ pentagon- ‎ 1291619/
Top answer · 4 votes
Ignore it, it's a mass message sent to thousands of people with your details subbed in. Update ...  More
3 votes
It is incredibly common scam, just delete it. My 20 year old Hotmail account I haven't used ...  More
Continue the conversation
￼
￼￼
￼
Google Help
https://support.google.com › thread
Email received from Google Notifications in relation to automated ...
Nov 8, 2022 — Received email from: notify-noreply@google.com It says the following: invited you to view a collection 364 days ago, you registered on our platform ...
Missing: techguy. ‎ org/ ‎ threads/ ‎ game- ‎ wiz/ ‎ world- ‎ pentagon- ‎ 1291619/
Top answer · 143 votes
This is not an email from Google. I repeat This is not an email from Google. It is simply a notification email that the scammers are using to trick unsuspecting ...  More
Account (Possibly) Compromised - Gmail Community - Google Help
Feb 16, 2023
Message blocked. I realized I keyed in an email incorrectly. Email still fails
Jul 8, 2022
someone send me urgent msg, plz help, i'm i in trouble.. help me plz
Sep 19, 2022
This was in my junk mail - Google Account Community
Mar 5, 2020
More results from support.google.com
￼
Reddit · r/NiceHash
20+ comments · 3 years ago
Urgent! Please someone help, someone is aggressively attempting ...
Urgent! Please someone help, someone is aggressively attempting to hack every e-mail address that I own that's tied to crypto wallets/exchanges!
Missing: techguy. ‎ org/ ‎ threads/ ‎ clicker- ‎ wiz/ ‎ pentagon- ‎ 1291619/
￼
GitHub
App installed
Emails thread confusingly in Gmail · Issue #1048 · travis-ci ...
Apr 17, 2013 — " email gets threaded with the [Still Failing] email (on Gmail, at least). This means that when you click "[Still Failing]" in your inbox ...
Missing: techguy. ‎ putting- ‎ crypto- ‎ game- ‎ wiz/ ‎ world- ‎ pentagon- ‎ 1291619/
￼
Google Groups
https://groups.google.com › opensci...
blockchain
Well, it's a currency, it's money, and money are used to pay for legal things as well as illegal things. EUR or USD are not bad because some people use it to ...
Missing: techguy. ‎ threads/ ‎ game- ‎ clicker- ‎ wiz/ ‎ pentagon- ‎ 1291619/
￼
YouTube · Rob Braxman Tech
22.1K+ views · 2 years ago
Live - Bad News! Gmail Sneaks on Your Device (OAUTH) + Q&A
￼
1:30:54
I discovered some really incredible spying done by Google. I found out that it was tracking my De-Googled Pixel.
10 key moments in this video
Missing: techguy. ‎ threads/ ‎ putting- ‎ files- ‎ crypto- ‎ game- ‎ clicker- ‎ wiz/ ‎ pentagon- ‎ 1291619/
￼
Microsoft Community
https://answers.microsoft.com › all
Bitcoin blackmail
May 15, 2023 — I recently saw an e-mail that was trashed and sent on May 1st. It had a bunch of my passwords and a random Roblox screenshot. But that's not all ...
Missing: techguy. ‎ org/ ‎ threads/ ‎ putting- ‎ wiz/ ‎ world- ‎ pentagon- ‎ 1291619/
Images
Images
￼
Emails thread confusingly in Gmail · Issue #1048 · travis-ci ...
￼
GitHub
￼
Tech Support Guy
￼
www.techguy.org
￼
Tech Support Guy
￼
www.techguy.org
￼
TOBII GAME HUB IMPORT AND EXPORT GAME CONFIGS
￼
YouTube
More images
Get the answer you’re looking for added to the web
Your question will be shared with online publishers who may be able to answer it. When shared, it won’t be associated with your Google Account.
￼
Make sure you don’t include any private info
Learn more
￼Submit
Notices about Filtered Results
In order to show you the most relevant results, we have omitted some entries very similar to the 8 already displayed.
If you like, you can repeat the search with the omitted reshoot://www.google.com/search?q=git%3A%2F%2Fwww.techguy.org%2Fthreads%2Fputting-my-gmail-files-on-a-the-crypto-game-clicker-wiz%2Fworld-pentagon-i.1291619%2F&oq=git%3A%2F%2Fwww.techguy.org%2Fthreads%2Fputting-my-gmail-files-on-a-the-crypto-game-clicker-wiz%2Fworld-pentagon-i.1291619%2F&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIGCAEQRRg60gEKMTEyOTUzajBqNKgCDrACAQ&client=ms-android-cricket-us-rvc3&sourceid=chrome-mobile&ie=UTF-8#:~:text=git%3A//www.techguy,results%20iincluded
