### ISSUE TITLE
Trying to run LXC containers on travis-ci

### ISSUE THREAD

**Issue by tknerr** [travis-ci/travis-ci#1273]
I'm desperately trying to get an LXC container running on travis-ci:
https://travis-ci.org/tknerr/lxc-test/builds

Right now it fails because `CONFIG_IKCONFIG` is not enabled i.e. the kernel config can not be read from `/proc/config.gz`:

```
$ sudo lxc-checkconfig
Kernel config /proc/config.gz not found, looking in other places...
The kernel configuration can not be retrieved.
Please recompile with IKCONFIG_PROC, or
install the kernel headers, or specify
the path to the config file with: CONFIG=<path> lxc-checkconfig
```

I have installed `linux-headers-generic` but that does not help either.

Any more clues?

**Comment by elopio** [comment]
This seems to be possible now with:

sudo: required
dist: trusty

I'm now trying to figure out how to run newgrp lxd, and how to give internet access to the container.

**Comment by xenithorb** [comment]
What's the state of this currently? I'm trying to test ansible playbooks and the docker container method isn't viable because of the one-process-per-container methodology with which the default images are made. 

Being able to make an LXC container an attach to it in order to run a playbook would be a very nice way to test config management...

**Comment by BanzaiMan** [comment]
There is no plan to support this.
