### ISSUE TITLE
after_script is not executed when build is time outed

### ISSUE THREAD

**Issue by vojtajina** [travis-ci/travis-ci#1353]
I think `after_script` should be executed always, no matter how the build ended.

Here's an example of timeouted build, that didn't run the after_script:
https://travis-ci.org/vojtajina/angular.js/builds/10469941

Here's the .travis.yml from that particular commit:
https://github.com/vojtajina/angular.js/blob/0207d7fe8cab075b342a4116ded221e282ef0581/.travis.yml#L18-L19

**Comment by scott-plutovr** [comment]
We have been experiencing problems where our ```git lfs pull``` appears to hang and were asked to collect a significantly more verbose output. Travis support suggested collecting the output to a file on disk and then in after_failure: adding a curl command to upload the log. In order to deal with the fact that the command has "hung" they also suggested wrapping this command with travis_wait and a timeout.

However, we have found after_failure: isn't getting run when the build is terminated.

I would love this feature!
