### ISSUE TITLE
4MB maximum log size a little low

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#1382]
I have a legitimate smoke which generates about 5MB of output. If it isn't a big deal could the limit be raised to 16M instead?

I will totally understand if this is undesirable due to hardware/financial constraints. But I'll never know until I ask ;)

**Comment by tripleee** [comment]
An alternative proposal is at https://github.com/travis-ci/travis-ci/issues/3865

**Comment by denniszollo** [comment]
I have the same problem with a python project.  If I turn off verbosity, it fails due to lack of output.  If I turn it on, it fails because the log is too big.

**Comment by NHellFire** [comment]
Would be good for this to be configurable. I'm hitting 4MB with a buildroot project, even when using `make --silent`

**Comment by gnachman** [comment]
iTerm2 now hits the limit and I have to pipe xcrun through sed to keep the output small, but it means I can't see all the arguments passed to a failing compilation.

**Comment by dy** [comment]
Tried to run [`regl`](https://travis-ci.org/regl-project/regl) and it just hanged. Is there still no official workaround for that?

**Comment by jimklimov** [comment]
In our large-log case, we don't really care for the UI stalling. It does. We usually have enough time to click on the Raw Output button and get the original text file (I logged elsewhere an issue about providing the link to unparsed log right from the list of builds). Having the job aborted just because it has a lot to built and the `make` is noisy is unfortunate however.

**Comment by vladak** [comment]
Also, the error message at the end of the log (`The job exceeded the maximum log length, and has been terminated.`) should at least say what the current limit is.
