### ISSUE TITLE
Move “read-write access request” for GitHub to when a hook is enabled

### ISSUE THREAD

**Issue by henrikhodne** [travis-ci/travis-ci#1428]
Several users and customers have expressed concern about the fact that read *and* write permissions are being requested immediately after logging in. As far as I know, the only thing we need write access for (at least on travis-ci.org) is to enable the hook. I think it could be a good idea to delay requesting write access until the user tries to enable a hook.

This should probably cover the use cases for read/write access on travis-ci.com as well, since I believe the only other use is setting up deploy keys for cloning the repository, which isn't needed until a repository is enabled.

**Comment by daira** [comment]
This is a huge issue for us, effectively a blocker for us using Travis-CI Pro at all. Here's what I wrote on our internal ticket:

The excess permissions issue for public repos (Travis-CI sans "Pro") was https://github.com/travis-ci/travis-ci/issues/1390 . That was successfully fixed after GitHub updated the OAuth scope definitions on 10 February 2014. I'm not sure why the "Pro" version is still requesting excess permissions, although others have complained about it: https://github.com/travis-ci/travis-ci/issues/1390#issuecomment-40216738

To be clear about the problem, when I visit the link https://magnum.travis-ci.com/Electric-Coin-Company/libzerocash/builds/10921168 for example, I have a request for (in addition to read-only email address access, which is fine):

> This application will be able to read and write all public and private repo data. This includes the following:
>
> * Code
> * Issues
> * Pull requests
> * Wikis
> * Settings
> * Webhooks and services
> * Deploy keys

for *ALL* of the repos I have access to in { @Electric-Coin-Company, @lambdaladies, @LeastAuthority, 
@noether-lang, @python-modernize, @tahoe-lafs, @TheTorProject }. It would be completely unethical for me to grant that access and potentially compromise the security of Noether, Tor, Tahoe-LAFS, etc., even if @Electric-Coin-Company were to accept that risk.

**Comment by roidrage** [comment]
Hey @daira, this kind of fine-grained permission settings is out of our hands, but every organization you're a part of can explicitly approve (or not) specific applications, in this case Travis CI Pro, from reading their respective information. If Travis CI isn't approved for an organization, we won't have access to any data relevant to that organization, including its repositories.

This isn't a proper fix for the permissions we currently ask for, but it should help address your concerns about access to repositories beyond the scope of interest.

**Comment by daira** [comment]
Travis-CI is approved for @tahoe-lafs, though. The setup for that org carefully uses a separate github account (@travis-tahoe), which is on a limited-permission team, to mitigate the possibility of any security breach via Travis. Since I'm a member of @tahoe-lafs, will accepting the OAuth grant effectively bypass the careful privilege separation we set up?

I'm confused as to why you say that this is out of your hands when the issue would seem to be improved substantially by the proposal in the bug description ("delay requesting write access until the user tries to enable a hook"). At the moment I need to accept the permissions in order to just *view* a build output. That's absurd! I realise that for a private repo, it's necessary to authenticate that the user has read access to the repo in order to view a build output, but anything else is excess authority.

**Comment by daira** [comment]
Also, can you explain what the issue with the OAuth scope definitions is that makes this more difficult than for travis-ci.org? Assume I understand OAuth and how github uses it.

**Comment by joshk** [comment]
I'm closing this issue as we do not have plans to change our auth scopes at this time.

Also, with some new developments going on at GitHub, we will be reworking our auth process, which will makes all this a lot simpler.

**Comment by sigvaldm** [comment]
So how is this "rework" going?
