### ISSUE TITLE
Add travis-ignore config

### ISSUE THREAD

**Issue by nkt** [travis-ci/travis-ci#1468]
I mead something like that:

``` yml
skip_build:
    - docs/*
    - README.MD
    - LICENSE
```

If I update readme or docs I don't want run tests, and don't want add to every commit `[ci skip]`, I'd like to describe the rules in one place and forget about it.

**Comment by listx** [comment]
FWIW, I would think that this ticket should be revisited, if only for the added relief it would give the Travis build machines (there will be lesser builds).

I disagree with incorporating `added`, `removed`, and `modified` values in a push payload, because that's just too much added complexity (e.g., what does it mean to ignore a deleted file? but what if that file is essential to a build (i.e., the commit was in error)?).

I mean, there is already `git diff --name-only A..B` which gives a list of all files that have changed (all modified paths). So now the problem is reduced to something like `CHANGED_FILES - IGNORED_FILES_PATTERNS > 0`. The hard part would be the handling of globbing rules and such, but I'm assuming there's abundant literature on this topic.

**Comment by raphaelstolt** [comment]
I also think this ticket should be revisited. Having something like a `.buildignore` or `.travisignore` which allows to exclude files similar to `.gitignore` would reduce the amount of unnecessary builds (e.g. when doing some sole fixes on repository artifacts e.g. `README.md` or content below a `docs` directory).

The option to skip builds via patterns in the commit message IMO adds unrelated metadata to the commit (kind of a SRP violation).

**Comment by Scotchester** [comment]
I would also like to vote for reopening this issue.

**Comment by raphaelstolt** [comment]
Seems like this, is [still](https://github.com/travis-ci/travis-ci/issues/6301) something the people want. 😶

**Comment by BanzaiMan** [comment]
There is further discussion in #6301. We have an internal discussion going, but it is not on the roadmap at this time.

I'm locking this to prevent further comments here.
