### ISSUE TITLE
Deleting repository on GitHub does not delete repository on Travis CI

### ISSUE THREAD

**Issue by tolis-e** [travis-ci/travis-ci#1469]
I've just performed a repositories sync and I see duplicate repositories.

e.g  tolis-e/aerogear-unifiedpush-server is shown three times

**Comment by raisedadead** [comment]
Any updates yet on the issue. I too have the same issue.

**Comment by joshk** [comment]
Sorry, no updates yet, we are improving our GitHub sync which will help us pick up these changes.

**Comment by binarycoded** [comment]
Any progress so far?

**Comment by joshk** [comment]
We have made some improvements, but are working on further ones over the coming months.

**Comment by mareksuscak** [comment]
The same problem here, deleted the repo and created a new one with the same name and travis is not responding to any changes now. (https://travis-ci.org/mareksuscak/mareksuscak.github.io/)

Is there any workaround for that?

**Comment by joshk** [comment]
@mareksuscak sorry but that is a different issue, can you please send an email to support and we can look into it.

**Comment by paulcpederson** [comment]
@paslandau Nice trick! renaming the GitHub repo and then changing it back worked for me!

**Comment by svenfuchs** [comment]
We now automatically resolve repository conflicts in the component that syncs user data from GitHub. I'm going to close this issue for now even thought the feature is not activated for all users just yet. We are planning to do so by next week.

**Comment by paulcpederson** [comment]
:+1:

**Comment by mloskot** [comment]
Thanks!

**Comment by tolis-e** [comment]
:cake: Thanks

**Comment by raisedadead** [comment]
👍 Thanks guys!

**Comment by karelstriegel** [comment]
Still facing this problem, I have a repo listed in Travis that was delete on Github...

**Comment by steazzalini** [comment]
This problem still persists for our organization as well. Any ETA about this?

**Comment by Nosferican** [comment]
Same issue persists.

**Comment by jpawlowski** [comment]
Yep :-/

**Comment by josh-lauer** [comment]
The issue persists, 4 years later.

**Comment by akshayKrSingh** [comment]
@josh-lauer: try clicking on "sync account". travis requires a sync with GitHub, if changes were made to the repository outside of Travis CI.

# Illustration
![capture](https://user-images.githubusercontent.com/8209379/47216739-96fc4a00-d3c3-11e8-8346-d3ea7bebf017.PNG)

It worked for me !

**Comment by mwithi** [comment]
I'm still experimenting this, in my case the problem was I deleted and recreated the repository with same name but different case.

![travis error](https://user-images.githubusercontent.com/2938553/61400435-889a7a80-a8d0-11e9-9114-3baab547167a.PNG)

The camel-case one is greyed out and I cannot remove, even by uninstalling and reinstalling the GitHub Integration, it just keep showing that deleted repository, so I think it's cached in Travis on my account.

**Comment by constrict0r** [comment]
I'm facing this issue on Debian.

**Comment by marco-brandizi** [comment]
It still happening on my side: I created a repo, then deleted, then created again, populated with real stuff and enabled Travis. In the latter, I've one repo that builds correctly, and another with the same name (but, apparently, different URLs), which always fails, due to the fact I didn't add deployment credentials to its settings. I kind of fixed it by going to the Travis settings of the ghost repository and disabling all automatic builds.
