### ISSUE TITLE
The build duration should be wall-clock time, not CPU time

### ISSUE THREAD

**Issue by eric** [travis-ci/travis-ci#1486]
The thing I'm most interested in as a user is the amount of time I had to wait around for an answer to if a given commit was good or not.

This means the most interesting "build duration" to me would be `max(ended_at) - min(started_at)`, instead of `sum(duration)`.

I was surprised (and sad) when I moved my build to use a build matrix to run different parts of my tests in parallel and the total duration went _up_ (because of the duplicated startup time). Obviously now that I understand what is going on, I'm no longer sad, but it still would make things look better if the number were smaller.

**Comment by headius** [comment]
My position, since I've wanted this for a long time:

* I'm interested in several timings:
** Start to finish time, which is useful in determining how well the suite is keeping up with pushes
** Total build time, based on summing job times
** Time from push to build finish, again to know how badly we're clogging up the build queue
* The start-to-finish time is by far the most interesting to me because I want to know how long each *build* is taking, not each *job*. Jobs run in parallel and may overlap, so totaling the job time is not interesting for anyone except the folks allocating resources for builds (e.g. Travis folks).
* If some people really want to keep total build time, I'd say to show both. This is similar to the `time` command on unix, which shows various forms of CPU time *and* real time. If it's good enough for unix, it's good enough for Travis.

Please add :-)

**Comment by headius** [comment]
Occurred to me that the time-from-push-to-finish metric may actually be the more interesting one for many people, since it indicates how long your pushes are taking to get results in Travis. But it can be determined based on start-to-finish time and push-to-start time (inferable by looking at when the build started and when the push came in).

More metrics is always good. It's up to the UI folks to present them in a nice way.

**Comment by benben** [comment]
time from push to finish is the only thing I'm interested in, especially since travis getting slower and slower to start a build. For us it shows several minutes (>5) "created" or "booting" and nothing happens.

**Comment by ErisDS** [comment]
I also agree, I'm way more interested in the real amount time I as a maintainer had to wait. Travis runs builds concurrently, each build takes 3-6 minutes. I'm probably waiting around 20minutes, but Travis reports over 40.

Mean while the elapsed time is also incorrect:

During the build:
![](http://puu.sh/lWlp8.png)

After:
![](http://puu.sh/lWlz0.png)

Neither the elapsed nor total time are correct for this build. It would be ok if it was reporting 7:36, or the ~20mins it took to run the full matrix, or perhaps the time from push until green, but neither of the numbers here are reflecting a useful number :disappointed:

**Comment by olivierlacan** [comment]
Why not give maintainers the choice to decide what gets reported? I usually noticed the time a build took in our Slack integration, from our team's perspective, I pushed, then the build started, then it finished either successfully or not. That frame of time is what I'd want reported to Slack, even if the real execution time remains the canonical metric on Travis.
