### ISSUE TITLE
Problems with updating status images cache 

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#1597]
There seems to be a problem with updating status images cache for some repositories or builds. The cache may not be updated because of connectivity issues, which would explain why status cache is not updated after one of the builds, but sometimes it stays unchanged after several new builds.

I couldn't track the issue, so the best thing to do to tackle this is to add some debug logs for the places where states cache is populated (api and hub)

**Comment by kgrodzicki** [comment]
Same problem here: https://travis-ci.org/kgrodzicki/shaker

**Comment by miguel-branco** [comment]
hum, same problem here: https://travis-ci.org/dias-epfl/raw

I never got a green sign on travis-ci.org even though there have been various successful builds.

any idea?

**Comment by sampablokuper** [comment]
I'm experiencing a similar problem to the one @pbellec described:

- My most recent push is reflected in build 5, which passed.
- An earlier push was reflected in build 2, which failed.
- For some reason, build 2 completed *after* build 5: https://travis-ci.org/sampablokuper/dwgen/builds .
- Therefore (and this is, I agree with @pbellec , a bug in Travis CI), my project's status as a whole is currently showing as "failed": https://travis-ci.org/sampablokuper/dwgen/ .

The expected behaviour, at least from my perspective, is that the project status Travis CI reports should refer to the build reflecting the most recent push. It should **not** refer to the build that completed most recently on Travis CI's worker infrastructure, because that is something out of the control of the user and irrelevant to the status of the latest push to the relevant branch.

**Comment by denneulin** [comment]
Same issue even after restarting [last build](https://travis-ci.org/denneulin/kidiari-api)

**Comment by jamesdbloom** [comment]
Is there any update on this as I'm also getting the same problem for https://travis-ci.org/jamesdbloom/mockserver.  The last 3 builds have passed but the status icon shows the build as having failed.

**Comment by deltreey** [comment]
I can confirm I have this problem at the moment https://travis-ci.org/deltreey/moreon

**Comment by repent** [comment]
Same problem at the moment: latest build passing, image showing failure: https://travis-ci.org/repent/rwanda

**Comment by famuvie** [comment]
Same here https://travis-ci.org/famuvie/breedR

I'm not totally sure, but can be related with the fact that I have force-pushed the last build after an interactive rebase, and some squashing of commits.
I realized that confused Travis-CI for a while who tried to build a commit that was no longer there.
After that, new pushes build ok, but the badge is stucked.

**Comment by elkdanger** [comment]
Having the same issue with https://travis-ci.org/elkdanger/express-autoapi - build and test passes, but icon is red and is of course replicated to GitHub and npmjs.org

**Comment by haisum** [comment]
Same issue with https://travis-ci.org/haisum/urlshortner/builds build passed but icon is red.

**Comment by brann** [comment]
same:

https://github.com/infoxchange/docker-forklift

There was a build error on travis where one of the 3 python versions had a time out error. The last 2 commits (actually adding the travis build badge and coverage.io badge) have passed, but it still says error.

Nothing special about the commits. Made directly to master for the README.md using the github edit interface.

**Comment by deltreey** [comment]
seems that my project updated this morning and has the correct image now.

**Comment by BanzaiMan** [comment]
#4024 supersedes this.
