### ISSUE TITLE
on: tags condition for deploys still not working

### ISSUE THREAD

**Issue by rkh** [travis-ci/travis-ci#1675]

**Comment by skiwi2** [comment]
Any news on this?

**Comment by djindjic** [comment]
It would be extremely worth to support deployment of tagged builds on selected branch(es) instead of trigger it on for every (unsafe) branch which could be tagged accidentally of maliciously.

**Comment by 2m** [comment]
Still requires `all_branches: true`. Tried with deployment to PyPi in this repo: https://github.com/2m/test-pypi-deploy

**Comment by BanzaiMan** [comment]
Hello, kids! I believe I fixed this with https://github.com/travis-ci/travis-build/commit/28c1b85. This has been deployed. Please test this on your repository. (It worked on my tests, but it might have left some stones unturned.)

Thank you!

**Comment by 2m** [comment]
Thanks. It works on my [test](https://github.com/2m/test-pypi-deploy) repo.

**Comment by thedrow** [comment]
I'm glad that this issue is finally resolved.

**Comment by skiwi2** [comment]
Is there now a way to prevent that accidental tags on any branch other than master create a release?
(In an intended situation where only tagging on master creates a new release)

**Comment by BanzaiMan** [comment]
@2m @thedrow Thanks for the confirmation.

@skiwi2 I am not quite sure what you are describing. Perhaps that merits a new issue?

I'm closing this now, but if you still see a problem, do let us know.

**Comment by atomicules** [comment]
Hi, still not working for me with PyPi on mrtazz/simplenote.py (I'm a 
maintainer). Just tried two tagged commits (one lightweight 183221a 
and one annotated 600595f in case it matters) and Travis is reporting 
"Skipping deployment with the pypi provider because this is not a 
tagged commit".

It could well be something I'm doing wrong, but I'm stumped as to 
what.

I notice via 'travis requests' I do have a couple of builds that say 
"received (validation pending)" if that means anything?

**Comment by BanzaiMan** [comment]
@atomicules Neither https://travis-ci.org/mrtazz/simplenote.py/builds/50820565 nor https://travis-ci.org/mrtazz/simplenote.py/builds/50827064 is a tagged build. You are only building the `master` branch (https://github.com/mrtazz/simplenote.py/blob/600595fe9582e0ad4781fe533e8accddc8f81082/.travis.yml#L5-L7). You should change that.

**Comment by atomicules** [comment]
@BanzaiMan thank you for pointing that out to me. I have fixed that 
and it is now trying to deploy now, but failing with:

"invalid option "--password=""

**Comment by BanzaiMan** [comment]
@atomicules Sounds like your encrypted password was not decrypted correctly. Please review the documentation.

**Comment by atomicules** [comment]
@BanzaiMan we re-added the password and deploys are now working. Thank you very much for your responses.

**Comment by vaibhavsagar** [comment]
I'm getting nowhere with my attempts to use releases, even after adding `all_branches: true` on [my repo](https://github.com/vaibhavsagar/resumate). Travis is also [giving me](https://travis-ci.org/vaibhavsagar/resumate/requests) a 'branch not included or excluded' error with my attempts to push up tags, am I doing this wrong?

**Comment by atomicules** [comment]
@vaibhavsagar Looks like the same mistake [I made](https://github.com/mrtazz/simplenote.py/commit/c338302b60ffeb6ba50a24de7de382fd2fbeff8f). Remove [these lines](https://github.com/vaibhavsagar/resumate/blob/master/.travis.yml#L1-L2) and try it again.

**Comment by vaibhavsagar** [comment]
That worked! Thanks so much @atomicules!

**Comment by chrisbaldauf** [comment]
I'm just getting started with travis and npm deployments and I am having trouble getting travis to push to npmjs.com on tagged commits, seeing the same behavior as described in this ticket. Hopefully someone can point out something obvious that I'm missing.

* [travis.yml](https://github.com/Cimpress-MCP/deployment-tracker/blob/v0.1.8/.travis.yml)
* [build output](https://travis-ci.org/Cimpress-MCP/deployment-tracker/builds/69929232)

Result: `Skipping a deployment with the npm provider because this is not a tagged commit`

I added "all_branches: true" per the workaround instructions in this issue.

My process for committing / pushing was 
```
echo "..." >> README.md
git commit -am "comment"
npm version patch
git push origin master --tags
```
Thanks in advance for any direction or advice you might be able to provide.

**Comment by BanzaiMan** [comment]
@chrisbaldauf Sorry to hear about this issue. I think it's a separate issue, though, so please open a new issue.
