### ISSUE TITLE
Travis working in "Detached Head' mode can cause confusion if end users have git-oriented build processes

### ISSUE THREAD

**Issue by kentfredric** [travis-ci/travis-ci#1701]
Part of how travis executes branch testing means the state of git differs from the state of the git tree at the time the relevant commit was authored.

This specific issue is that travis operates trees in "detached head" mode, which means any tooling has to be aware of this, and know how to respond in kind, which isn't always straight forward ( and doing it wrong has confusing side effects ).

For a while, I was getting randomly occurring errors with "could not lock ref" errors, which seemed to randomly happen in batches for certain commits, but not others.

At its core, the issue is simply that travis does:

```bash
git clone --branch=$branch $repo
git checkout $sha1
```

Which leaves the repository in a "detached head" state, which is notably different to how the state of the repository would have been when that commit was authored. ( And my tooling was simply not designed to work with building things in detached head conditions )

I suggest that in order to get a closer approximation to the build environment, that travis instead does:

```bash
git clone --branch=$branch $repo
git reset --hard $sha1
```
Which will locally roll back the pointer of $branch to point to $sha1, so that the test environment more closely matches that of the commit environment.

This will not solve the issue about auxiliary tags being visible on rebuilds, but that's a separate issue.  

### Background on "could not lock ref"
To give context on why exactly the detached head condition is counter-productive for me, I'll give my example case:

1. My build process on `master` generates an additional branch `build/master`.
2. This is the case for all "source" branches, so for a source branch `foo`, the generated branch is `build/foo`.
3. Git, in "detached head" state cannot determine a `current branch` , because by definition, in detached head, there is no current branch.
4. Because of this, the "generated" branch for me was something obscure like "build/master~2", which caused git to fail with "could not lock ref". ( Which I expect is the case because "~2" is invalid at the end of a branch name )
5. I have locally worked around the stated issue with a local script to force the state back to a sane branch condition: 
https://github.com/kentfredric/GraphViz2-Abstract-Node/commit/f00a68764afcf053595622f21b71d133be17b368#diff-0a2776b44a49c403f038b8d5a9b1fda2R14
6. Though I don't know for sure how futureproof this strategy will be.

Hence, why I'm suggesting a potential change.

If this solution is not applicable for all users, then it could be an option, and if not an option, hopefully this issue will serve as some kind of direction if anyone experiences similar "detached head" related issues. ( Which I'd been having intermittently for several weeks before I realised what the cause might be )

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to pursue this further.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by DanySK** [comment]
This issue is also affecting my builds. In fact, I am checking via grgit wether or not I am on a master or release branch in order to decide how to version the artifacts (either with the version alone or followed by the short commit hash identifier).
I'd like the build not to be able to generate the same artifacts within or without travis, so I will probably need to complicate the branch detection considerably (looking at the hashes of every branch, trying to match them with the current, if it matches picking the branch name, and otherwise "detached").

**Comment by mitchellkrogza** [comment]
I hope someone can help me because this has been driving me mad. During my Travis build I modify one file adding a build number into the file and then try commit that file and push it back to the repo with the git tag I create. 

The release is pushed to the repo with it's latest Tag and the release includes the modified file but the actual modified file is not pushed as a commit due to this (HEAD detached at 35de529). I am a bit stumped on how to get Travis to commit this file and push tags at the same time.

**Comment by ddgenome** [comment]
@michaelklishin here's a solution I got working:

https://gist.github.com/ddgenome/f3a60fe4c2af0cbe758556d982fbeea9

You basically make sure the current detached HEAD and the branch point to the same reference, then check out the branch.

You need to make sure neither the tag nor the commit trigger builds indefinitely, i.e., create a Travis CI [fork bomb](https://en.wikipedia.org/wiki/Fork_bomb). I put `[ci skip]` in the commit message to disable Travis for the commit and I put build tag on the tag, `+travis$TRAVIS_BUILD_NUMBER`, that you can disable builds for by adding this to your `.travis.yml`:

```yaml
branches:
  except:
  - "/\\+travis\\d+$/"
```

**Comment by mitchellkrogza** [comment]
Thanks @ddgenome I eventually figured out the [ci skip] tag and have my repo pushing commits perfectly for the past few weeks now with the files modified during the build without throwing travis into what you call a "fork bomb" 😁 

I also found travis was having issues pushing back to the repo with the commits due to incorrect permissions, so in my deploy.sh script I added the following which deletes the remote that Travis adds by itself and then re-creates the remote with my secure key.

```
git remote rm origin
git remote add origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
```

**Comment by ddgenome** [comment]
Yes, that this bit here: https://gist.github.com/ddgenome/f3a60fe4c2af0cbe758556d982fbeea9#file-travis-ci-git-commit-bash-L42-L45

Private repo builds already have write access to the repo on GitHub so you can just push to `origin` and need not supply the `GITHUB_TOKEN` as a secure environment variable.

**Comment by mitchellkrogza** [comment]
@ddgenome perfect 😉  will give that a whirl, much better solution. Thanks for that Gist will have a look through it for other improvements to my Travis scripting. Much obliged.

**Comment by worc** [comment]
is there any option to have travis checkout with a named branch instead of detached head? i'm looking at some deploy scripts here that are keying off the branch name... which gets butchered by the detached head.
