### ISSUE TITLE
Console logs secure env value when parsing fails

### ISSUE THREAD

**Issue by Synesso** [travis-ci/travis-ci#1775]
Put an "unexpected value" character in a secure env variable and that variable will be logged at the console.

e.g. the encrypted value `PASSWORD=winnie(the pooh)` might become

```
secure: abcd1234..01
```

At build time this will log:

```
$ export PASSWORD=[secure]
/home/travis/build.sh: line 107: syntax error near unexpected token `('
/home/travis/build.sh: line 107: `export PASSWORD=winnie(the pooh)'
```

**Comment by bguerin** [comment]
@henrikhodne 
> If there is a way to do a syntax check on a bash script before running it

bash -n

**Comment by camelspeed** [comment]
@henrikhodne @BanzaiMan Any progress on this issue?  I just had my hosting environment access token exposed due to a malformed character in the string. I purged my log but it is still concerning that secrets are exposed (and this issue is 18mos old and still unresolved) even though the information entered the system in a protected state.  Any way to detect you are dealing with an encrypted value and upon logging to use the encrypted state and not the decrypted state? Thank you guys.

**Comment by kpstolk** [comment]
I configured a (apparently malformed) secure variable via the settings in Travis, why can't that be checked before it is saved?

**Comment by langri-sha** [comment]
Hello everyone! Would it not be possible to export these values before the build begins and re-export them for verbosity and clerical purposes?

I am happy with any way you manage to fix this, as this seems to be a critical security error, because it's easy to use robots to divulge logs that have partially leaked a secret in public.

**Comment by BanzaiMan** [comment]
I've opened the PR to at least partially address this issue. I welcome comments there. Thank you!

**Comment by BanzaiMan** [comment]
I'm closing this now. We now send `export`'s STDOUT to `/dev/null`, so that parts are not leaked to the logs, and show link for further information on Bash special characters if the command fails.

If you see a similar issue going forward, please open a new issue.

Thank you!

**Comment by BanzaiMan** [comment]
The PR was reverted.

**Comment by Swyter** [comment]
The fix is easy, just escape them as literal strings like everyone else. That's it.

Spent the entire afternoon scratching my head before figuring out why my URLs weren't working.
That I had to base64-encode them to use them in scripts is just ridiculous.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/942 is live. Accidental leakage is far less likely now.

I'm closing this.
