### ISSUE TITLE
Provide the ability to build Arch Linux packages

### ISSUE THREAD

**Issue by Lance0312** [travis-ci/travis-ci#1849]
Arch Linux is a very popular Linux distro which has its own packaging system. There are currently over 10000 packages in [the official repositories](https://www.archlinux.org/packages/) and over 45000 packages in the [AUR (Arch User Repository)](https://aur.archlinux.org/). It would be very helpful to be able to build and test Arch Linux packages on Travis-ci for increasing package quality.

Here are some wiki pages about the packaging system.
* Package basis
    - [Pacman](https://wiki.archlinux.org/index.php/Pacman)
    - [Arch Packaging Standards](https://wiki.archlinux.org/index.php/Arch_Packaging_Standards)
    - [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD)
* Package building
    - [makepkg](https://wiki.archlinux.org/index.php/Makepkg)
    - [Creating Packages](https://wiki.archlinux.org/index.php/Creating_Packages)
    - [DeveloperWiki:Building in a Clean Chroot](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot)
* Misc
    - [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository)

**Comment by KyleSanderson** [comment]
Hi guys,

I'm playing with Juju ( https://github.com/fsquillace/juju ) on Travis due to the Docker change. Our builds were otherwise failing sporadically due to a weaker set of machines with only 600M~ of Memory by default. So far on my Gentoo machine it's pretty great. I just put it into a Travis file, which took a bit more coercion, but it's definitely working.

https://github.com/alliedmodders/sourcemod/pull/311 for reference. Hopefully this helps with Arch package building :-)

**Comment by urras** [comment]
Any update on this?

**Comment by BanzaiMan** [comment]
Sorry, but there is no update.

**Comment by gutenye** [comment]
:+1: This is a great feature to build a ArchLinux package on Travis CI  with a single `git push --tags` command.

Sometimes, you may not need to build an actual ArchLinux package, you only need to upload a PKGBUILD to https://aur.archlinux.org/, has anyone did this and share the experience?

**Comment by roidrage** [comment]
Closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.
