### ISSUE TITLE
Automatic detection of repo and branch for badges

### ISSUE THREAD

**Issue by defunctzombie** [travis-ci/travis-ci#1892]
By looking at the `Origin` header, travis badge images on readmes could autodetect the repo and branch. This would be very helpful for long lived project branches and pull requests. Instead of hard coding the repo and branch in the image url, a generic image url would suffice. Now when a fork or branch happens, the README doesn't need to be updated in order to see the status of that particular branch/fork. This helps avoid confusion about what is actually passing and what isn't.

**Comment by msc-** [comment]
Both the issues referred to here, #974 & #779 have been closed due to apparent issues with the suggested Referrer header. This has been closed as well so where is this problem now being discussed.

A solution is sorely needed. I have long-lived incoming and master branches and the requirement for explicit links in the README is causing massive merge headaches.

**Comment by 3lnc** [comment]
Any news on this?

**Comment by rishichawda** [comment]
@3lnc I ended up making a [plugin](https://github.com/rishichawda/markdown-magic-build-badge) and using it on githooks. Hope this helps!

**Comment by rishichawda** [comment]
@3lnc I ended up making a [plugin](https://github.com/rishichawda/markdown-magic-build-badge) and using it on githooks. Hope this helps you as well!
