### ISSUE TITLE
Failed connect to github.com:443; Connection timed out

### ISSUE THREAD

**Issue by andyli** [travis-ci/travis-ci#2061]
Over the [haxe](https://github.com/HaxeFoundation/haxe) repo we have [a build matrix that contains 10 builds](https://travis-ci.org/HaxeFoundation/haxe). It was perfect. However in this week we observe that very often 1 of the 10 builds will fail to start in the beginning:

```
$ git submodule update
Cloning into 'extra/haxelib_src'...
fatal: unable to access 'https://github.com/HaxeFoundation/haxelib.git/': Failed connect to github.com:443; Connection timed out
Clone of 'https://github.com/HaxeFoundation/haxelib.git' into submodule path 'extra/haxelib_src' failed
The command "git submodule update" failed and exited with 1 during checkout.
```

The above is from https://travis-ci.org/HaxeFoundation/haxe/jobs/20816651

Manually restarting the build will fix it. But shouldn't all the starting cmds are run with `travis_retry`?

**Comment by Jeff-Tian** [comment]
It occurs again today, and the status is still green?

![image](https://user-images.githubusercontent.com/3367820/62677982-abf1aa80-b9e2-11e9-97cc-afa784101eaf.png)


My builds started to fail caused by that error today, does anyone know workarounds for it?

![image](https://user-images.githubusercontent.com/3367820/62678027-d04d8700-b9e2-11e9-8f8c-23499b55bd0f.png)
