### ISSUE TITLE
Organization level secure variables

### ISSUE THREAD

**Issue by till** [travis-ci/travis-ci#2069]
Maybe a data bag which is _organization-wide_ to manage/maintain some keys instead of adding them to all my `.travis.yml` files.

**Comment by joshk** [comment]
Closing this as the issue has become stale and is not likely to be done in the next 3-6 months.

**Comment by till** [comment]
@joshk just for the record, still an issue for us.

**Comment by joshk** [comment]
I :heart: you @till 

I can understand why this would be good, but do not think it is something we will be adding in the next 3-6 months. We may reopen and relook at this in the future though.

**Comment by jehine-MSFT** [comment]
Hello Travis CI folks,

My team has run into the same issue. It would be great to have a dynamic way of adding encrypted lines of text after the config has been loaded that Travis could then decode API keys and such. With current limitations, we are left with having to run a job that will update each of our repos's travis configs for each branch whenever we rotate our keys.

There are valid scenarios where customers would need this functionality without performing poor security habits.

Any plans yet to develop this feature? Something as simple as being able to call a travis API decryptLine API within the test script would solve this problem. Since these tests only run in your environment I don't see this being a security risk.

Thanks!

**Comment by till** [comment]
@jehine-MSFT you can automate some of this with custom scripting around the [travis ci cli](https://github.com/travis-ci/travis.rb). I believe that is what we to mass-update, etc.. Still wish there was a better option.

**Comment by till** [comment]
(You're welcome, @joshk)

**Comment by deitch** [comment]
I know this is an old issue, but it is an issue. It probably should be open.

I can list many different use cases, but I think @till describes it best:

> We have 60 or so repositories enabled. It makes rotating keys very tedious.

Not just rotating keys. A common scenario is an organization with 6 or 60 repos, and a common artifact store (e.g. Docker registry). Those creds should *not* be in the repo, even as a secret. Management of it is impossible.

Think of the current flow for adding a project:

1. Create new repo
2. Add it as project in Travis part of target org
3. Ask whoever manages the artifact repository for a key, or have them retrieve it
4. Create encrypted
5. Add it to `travis.yml`

And what happens when we need to invalidate or change keys, as @jehine-MSFT said? Mess.

Here is a far better flow:

1. Create new repo
2. Add it as project in Travis part of target org

Done. Because it is org-wide env vars, *all* of my deployment and build scripts inherit them.

Of course a local script or travis.yml could override, but by default, everything works cleanly.

**Comment by gajus** [comment]
So, as the result of the recent incident (https://blog.travis-ci.com/2017-05-08-security-advisory), a user needs to go to every single repository and update the ENV variable. In my case, thats over 100 repositories.

**Comment by gajus** [comment]
This is how I've done it:

```bash
export GITHUB_USER=gajus
export GH_TOKEN=...

travis login
travis repos -o $GITHUB_USER -a --no-interactive | xargs -n1 travis env set GH_TOKEN $GH_TOKEN --private --repo

```

**Comment by matthewcummings** [comment]
Can you even set regular (non-encrypted) environment variables at the org level?  I would love to be able to do both.

Team Travis. . . please add this functionality!

**Comment by jmahowald** [comment]
@gajus Thanks for that tip. Created a mini script to encapsulate it just a little more for more my needs.

```
cat ~/bin/travisset.sh
#!/bin/bash

PATTERN=$1
ENV_VAR=$2

travis repos --pro --no-interactive -m $1 | xargs -n1 travis env set $ENV_VAR ${!ENV_VAR} --private --repo
```

`travisset.sh 'myorg/*' AWS_ACCESS_KEY_ID`

**Comment by JChanceHud** [comment]
Hello Everyone,

My company recently switched from circleci to travis and this issue was a pretty big roadblock in the transition. Circle has a really nice feature called organization contexts that allows shared variables across an entire organization to be set.

I wrote a utility called [travis-env](https://github.com/eventology/travis-env) that reads a JSON configuration file from S3 and then outputs the content to stdout in a way that can be used by `eval` like the following:

`npm i -g travis-env && eval "$(travis-env)"`

This allows me to provision each ci repo using a single configuration variable that is a JSON formatted string including AWS credentials and the bucket containing the JSON config file.

More information about usage can be found in the [readme](https://github.com/eventology/travis-env/blob/master/README.md), and these are some of our open source projects with `.travis.yml` configs that use the tool:

- [`eventology/alpine-node`](https://github.com/eventology/alpine-node) - [Build link](https://travis-ci.org/eventology/alpine-node)
- [`eventology/alpine-static`](https://github.com/eventology/alpine-static) - [Build link](https://travis-ci.org/eventology/alpine-static)
- [`eventology/alpine-vips`](https://github.com/eventology/alpine-vips) - [Build link](https://travis-ci.org/eventology/alpine-vips)

Hopefully some others find this tool helpful, issues and pr's welcome!

**Comment by rhanton** [comment]
We could really use this too. Seeing that Circle CI has it kind of makes me consider moving to them for CI.

**Comment by severusdenton** [comment]
Just run into a need for this. 

Seems like an obvious feature, really surprised to see it isn't already available, and would really like this ticket re-opened.

**Comment by rlgreen91** [comment]
Cosigning on this - it would be great to have some sort of organization level environment variables.  We currently use Travis for our repo, and when new people want to contribute we quickly run into a problem - Travis won't allow env variables to be shared across forks.  This requires people to instead make PRs directly from our repo, which requires us to add them as collaborators.  We can't do that, however, if we don't know about the person, and most people skip over that step in our setup guide or ignore it altogether and just fork instead.  It just adds unnecessary back and forth and during programs like Hacktoberfest acts as a bottleneck.

Maybe this will solve this, maybe not, but it seems like this could move towards solving this issue for us.

**Comment by arietrouw** [comment]
I agree that this is a must have.  The problem we run into is that many of the keys we use are one-time view keys and thus can not be added to a later repo without regenerating the key and updating all the repos that need the same key.  Of course we can make a S3 account for every single repo that we CI/CD, but that causes a mass amount of noise in IAM and causes more risk for security in chaos.

**Comment by JonJagger** [comment]
I would also like this ticket re-opened.
I have a lot of open-source github repos (100+) across two organizations and I've already moved one of the orgs to CircleCI largely because Travis lacks this feature. I'm about to start moving the other org. In short, not having this feature is costing you users. Sorry to leave Travis as it has been very good apart from this.

**Comment by gerryster** [comment]
FYI: this is how it is done in CirlceCI: https://circleci.com/docs/2.0/contexts/ . For now, I will probably use @JChanceHud 's script to update various repos when rotating AWS keys.

**Comment by deitch** [comment]
Thanks for the pointer @gerryster ; I have also started recommending CircleCI for orgs for that reason.

**Comment by chasebrignac** [comment]
I would also like this ticket reopened. I have many repo forks that I would need to rotate keys for (over two dozen). It's extremely tedious to make everyone add separate environment variables for each fork.

**Comment by Stanzilla** [comment]
Yup, reopen please

**Comment by yves-chevallier** [comment]
Again I think this issue should be reopened. 

I am using TravisCI along with GitHub Classroom so I have: 

- A classroom organization that contains assignment templates
- Some files such as the solution of the assignment is encrypted with openssl in .gitattributes
  - It allows me to have one repository for the assignment, the tests and the solutions
  - Travis can decrypt everything to run the tests on the students commits
     - It uses a secured environment variable `PASSPHRASE`
- When classroom copies the template for each students
  - The `PHASSPHRASE` is not accessible anymore because the repository has a different name. 

With a global environment variable to the organization it would solve my issue.

**Comment by smolster** [comment]
Agreed with all above! Please re-open!

**Comment by till** [comment]
Just use CircleCI. It's never gonna happen.

`/unsubscribe`

**Comment by devth** [comment]
I plan to migrate to GitHub Actions.

**Comment by deitch** [comment]
Depending on project, I’ve migrated to circle, actions or drone. Oh well.

**Comment by devth** [comment]
@t12g yeah but I'm confident they'll address it soon. There's already convention for org-wide settings using a `.github` repo under an org.

**Comment by boonware** [comment]
Has there been any update on this? It's over one year since the last comment. Travis CI really needs a convenient mechanism to manage configuration/credentials across multiple repos in an org.

**Comment by thaonguyen-ct** [comment]
Can we use this to share secrets environment from a repository to all rest of the repositories in an organization?
https://docs.travis-ci.com/user/build-config-imports/#sharing-encrypted-secrets

**Comment by joebnc** [comment]
Any update on this please?

**Comment by imcuster** [comment]
I'm going to add my voice to the choir on this one.  I manage over 100 Travis repos and have to do regular key rotations.  This feature would save an absolutely enormous amount of time for a lot of people.

**Comment by marianabocoi** [comment]
+1 on that this is an issue and I would love a better solution than the cli to update each repo individually

**Comment by henhal** [comment]
Here in 2022 to request the same feature 8 years later...

**Comment by razyalov** [comment]
+1 to this feature request.
I can't really understand the security concern here if it is built like suggested in this thread:
1. have an organization-wide place to set shared encrypted env variables
2. Allow to select which repos get access to these (so it can't leak without intention)
3. If a repo set its own value to the same env name, it should override the org-wide env

On the other hand, going repo-by-repo to update rotating keys is just not scaleable and error-prone, especially since, if you use the UI, there isn't even a way to "update" an environment variable, only delete and re-create it with a new value, which frankly already hurt me a few times when the newly entered variable was fat-fingered with a typo, and it took me forever to understand what happened... 😬🤦‍♂️

So, I'm basically +1 a vote to implement this org-wide env feature, but also, I like to see if we can allow to "update" an existing variable, vs. just supporting delete/re-create...

And finally, the suggestion to use a script is the least secured option in my mind, because now we need to have all these clear-text keys be sent from some script on someone's machine, which I can promise you will end up being either preserved in their terminal's history or logged into some file in clear text in the process...

**Comment by fcraposo** [comment]
Yup. Came here to request the same thing. It would be super helpful.

**Comment by henhal** [comment]
@joshk 
> do not think it is something we will be adding in the next 3-6 months. We may reopen and relook at this in the future though.

We may not have flying cars _everywhere_ [yet](https://www.youtube.com/watch?v=hUhzk8lCtL4), but surely we're in the future! 😁 Perhaps we can ask you to consider reopening this after 8 years? 🙏

**Comment by joshk** [comment]
Hi, I'm no longer at Travis so can't help with this. Sorry. All the best.
