### ISSUE TITLE
Build non-reachable commits

### ISSUE THREAD

**Issue by Celelibi** [travis-ci/travis-ci#2118]
Some commits are no longer reachable at the time travis try to build them. This is no reason to make it fail! :)

Being able to build commits that are no longer reachable is not always a non-sense.
Let's imagine this scenario (that happened to me yesterday):
- Make a few commits and push them one at time so they get built (a bit later since travis is a bit busy at the time).
- Spot a typo in the commit message of master~3, rebase the branch to correct it.
- Force push that new branch.
- Wait for travis to fail to fetch the commits in the pending builds.

I may use a "nonce" branch to push one new commit at time. But then, I would have to manually stop the old builds from happening (issue #961) and to leave this nonce branch until the build finish, and not delete it (issue #2117 ).

I guess the right solution would be to allow the user to chose whether he wants the unreachable commits to be built or canceled.

This could be solved together with issue #964 by letting the user tweak the scheduling policy for its travis jobs.
He may want:
-  branch-oriented builds where only the tip of the branch is build every time and other pending build jobs for this branch are canceled, and deleted branches don't get built at all;
-  push-oriented builds which is the current policy;
-  commit-oriented builds where every commits are built as long as github has them.

And maybe the push-oriented policy could be split in push-build-unreachable that build the pushed commits anyway, and push-ignore-unreachable to just skip these commits.

But hey, this is just an idea. :)

**Comment by jhalterman** [comment]
I'm not sure if the build should necessarily fail when a git checkout fails. Perhaps going into an unknown state or just leaving the build at the previous state until some (presumably) later build based on a commit that does still exist can succeed.

**Comment by lucafavatella** [comment]
I think I just hit this in a build with multiple jobs: I pushed a commit to a branch; Travis CI started build B1 i.e. it started the first 5 (out of N) jobs of the build (checkout went ok for all 5 jobs); I force-pushed update to the same branch; build B2 got queued (not started, as B1 was still not finished); one of the non-started-yet jobs of B1 got started and checkout for it failed; checkout failed for all of the non-started-yet jobs of B1 too.

```
$ git checkout -qf <hash>
fatal: reference is not a tree: <hash>
The command "git checkout -qf <hash>" failed and exited with 128 during .
Your build has been stopped.
```

May I suggest that **at least for a build with more than one job** the checkout is performed only once - at the beginning of the build - and then that same checked-out repo is passed to each job of the build?
I would do it myself with cache, but apparently it is not possible to specify in .travis.yml any "initialization" steps performed at the build-level rather than at the job-level (BTW neither it is possible to decide when to store cache - it is always stored somewhen at the end as documented).

**Comment by joshk** [comment]
Thanks for creating this issue.
I have talked about it with the team and we have decided that it does not fall onto our roadmap for the next 6-12 months, so we are going to close this for now.
@lucafavatella I'm sorry but as all VMs and Jobs are different and could be running on different machines, we are not able to reuse them as suggested.
Thank you everyone for your feedback and input.
