### ISSUE TITLE
Automatically remove caches

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/travis-ci#2131]
There are some cases where we might want to remove caches. For example, if the branch the cache exists for doesn't exist anymore, the repository was removed, or the cache hasn't been accessed for a while.

**Comment by fommil** [comment]
It would give you a lot of diskspace back earlier if the caches for deleted branches were removed. We just moved to docker and we might clock up of TBs of caches from PR caches because we have a matrix of 4 (times 3 times 2, currently disabled) each of about 500MB.

Actually we're happy **not** caching the PRs at all.

**Comment by joshk** [comment]
Each job doesn't get its own cache, instead we create a cache based on language versions. Although each PR might update a cache and thus create a new one, it will be cleaned up automatically after 45 days. This isn't a diskspace issue for us.
