### ISSUE TITLE
GO lang needs cross compiling support

### ISSUE THREAD

**Issue by anuengineer** [travis-ci/travis-ci#2207]
Go lang we need cross compiling support in travis since we build for linux ARM. 
if we were to build the go sources from scratch each time this would just make our builds really long.

Here is a script that does the cross compile for you 

https://github.com/davecheney/golang-crosscompile/blob/master/crosscompile.bash

I am hoping when Go gets populated in the travis VM/Container it will populate a go which is cross compiler tool chain enabled.

Thanks
Anu

**Comment by sschuberth** [comment]
Just like #2517 I'm interested in cross-compiling for Windows (and Mac OS X, but no ARM). What's the current status as neither `gvm` nor `gox` seem to be installed on the nodes, see [here](https://travis-ci.org/sschuberth/karn/jobs/60707951).

**Comment by mislav** [comment]
@tianon Now that Travis uses `gimme`, do you think this can be closed? https://github.com/meatballhat/gimme/pull/15

**Comment by sschuberth** [comment]
FYI, I just replaced gox with gimme for testing in [my fork of karn](https://github.com/sschuberth/karn). While [the gox builds](https://travis-ci.org/sschuberth/karn/builds/61110082) usually take slightly more than 2 minutes, [the gimme build](https://travis-ci.org/sschuberth/karn/builds/65134958) takes more than 5 minutes. I guess this is due to the overhead of spawning different matrix builds with gimme, while gox builds all variants in the same build.

**Comment by mislav** [comment]
@sschuberth I'm guessing (haven't tried) that you could cross-compile using gimme in a single job, without using a Travis build matrix. You would just have to interface with `gimme` directly in a loop.

**Comment by sschuberth** [comment]
Probably possible, but IMO using gimme with a build matrix already was more verbose than using gox, and using a loop would make it even more so. I'll stick to gox for now.

**Comment by mislav** [comment]
I've did an experiment how to cross-compile on Travis using nothing but Gimme. gox is fine but I wanted to see whether it could be done without extra dependencies. Using the Travis matrix isn't needed and doesn't make sense either, because you can't run tests for cross-compiled builds. Here's the script:

```sh
echo '
  darwin   amd64    OS X
  freebsd  386      FreeBSD 32-bit
  freebsd  amd64    FreeBSD 64-bit
  linux    386      Linux 32-bit
  linux    amd64    Linux 64-bit
  windows  386      Windows 32-bit
  windows  amd64    Windows 64-bit
' | {
  while read os arch label; do
    [ -n "$os" ] || continue
    export GIMME_OS="$os"
    export GIMME_ARCH="$arch"
    time eval "$(gimme 1.4.2)"

    exename="hub-${os}-${arch}"
    [ "$os" != "windows" ] || exename="${exename}.exe"
    go build -o "$exename" || {
      echo "FAILED FOR $os $arch" >&2
      continue
    }
  done
}
```

Gimme spends ~40–50s setting up each runtime (except linux-amd64, which is the current system on Travis).
