### ISSUE TITLE
Attempt to unlock an npm package, which hasn't been locked

### ISSUE THREAD

**Issue by jdalton** [travis-ci/travis-ci#2244]
I've getting this error every once in a while, I simply rerun the job and it works:
![screenshot](https://cloud.githubusercontent.com/assets/4303/2855230/5607222e-d15a-11e3-838d-6319b8e3c93e.png)

**Comment by karussell** [comment]
Since some days it looks like we get this again https://github.com/graphhopper/graphhopper/pull/631
We run maven too so we call `npm install` in the shell script and this has worked (at least until yesterday).

See
https://github.com/graphhopper/graphhopper/blob/master/.travis.yml
https://github.com/graphhopper/graphhopper/blob/master/core/files/travis-build.sh
