### ISSUE TITLE
error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by sloria** [travis-ci/travis-ci#2389]
Example failing build: https://travis-ci.org/sloria/webargs/jobs/26812177

I have successfully run the tests on my local machine running PyPy 2.3.0 (Travis PyPy version is 2.2.1 as of this writing)

**Comment by ZECTBynmo** [comment]
I'm still seeing this issue

**Comment by jesserobertson** [comment]
I had this issue over the last couple of days as well. 

I found that calls to pip to install a large number of packages seemed to cause this - separating each package out into its own pip call seemed to fix this. Not ideal because you have to worry about the order of packages, but it might help someone.

**Comment by dstufft** [comment]
Does Travis-CI have pip 6.0+ installed now?

**Comment by BanzaiMan** [comment]
No. It'll be in the next round of update. Probably at the end of the month.

**Comment by dstufft** [comment]
@jesserobertson Try doing ``pip install -U pip`` before trying to install everything first and see if that fixes things for you.

**Comment by Microserf** [comment]
We're seeing this too, and it's particularly bad today. We've had to manually restart 5 or 6 builds, and some just fail again right away.

It's very frustrating, and it's preventing our engineers from deploying and getting timely alerts about their builds failing, and why.

@dstufft The `pip install -U pip` solution doesn't seem to work for us, unfortunately. Pip seems to have updated itself properly, but later in the build, we get:

```
Collecting SQLAlchemy==0.9.8 (from -r reqs/common.txt (line 74))
  Downloading SQLAlchemy-0.9.8.tar.gz (4.1MB)
    47% |###############                 | 2.0MB 22.9MB/s eta 0:00:01  Hash of the package https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.9.8.tar.gz#md5=470ca4da4a0081efc830f0d90dd91682 (from https://pypi.python.org/simple/sqlalchemy/) (d9a1b28509a60434b677a1f05c4552ac) doesn't match the expected hash 470ca4da4a0081efc830f0d90dd91682!
  Bad md5 hash for package https://pypi.python.org/packages/source/S/SQLAlchemy/SQLAlchemy-0.9.8.tar.gz#md5=470ca4da4a0081efc830f0d90dd91682 (from https://pypi.python.org/simple/sqlalchemy/)
```

(It's not too surprising that a hash doesn't match after only 47% of the download has completed...)

**Comment by jesserobertson** [comment]
@dstufft Didn't change anything unfortunately. Still getting broken builds with multiple pip installs at once.

**Comment by ZECTBynmo** [comment]
We're still seeing this issue. Is there a plan for this getting fixed?

**Comment by Microserf** [comment]
FWIW, setting `sudo: false` in our `.travis.yml` file as @joshk suggested worked like a charm for our builds.

**Comment by EmergentBehavior** [comment]
I'm also seeing this error in a Python project. Here's a relevant trace:

````
Searching for execnet>=1.1.dev1
Reading https://pypi.python.org/simple/execnet/
Best match: execnet 1.2.0
Downloading https://pypi.python.org/packages/source/e/execnet/execnet-1.2.0.tar.gz#md5=1886d12726b912fc2fd05dfccd7e6432
error: [Errno 104] Connection reset by peer
```

**Comment by amadornimbis** [comment]
Still seeing this as well. Using `sudo: false` is great if your Travis builds don't require sudo, but unfortunately our builds now do and so we had to remove this from our `.travis.yaml` file. Now we're back to having this problem interrupt every other one of our builds. Are there any plans to fix it?

**Comment by dstufft** [comment]
Speaking as one of the authors of pip and a PyPI administrator, from what we can tell this is a problem that seems to be specific to Travis, but I'm unsure where exactly the problem is at.

On the pip side of thing the recent pip 6.0 (which I believe that Travis just upgraded to) should make this better because we'll automatically retry failed connections up to 5 times. However we still are not retrying failed downloads themselves (e.g. if the failure happens while the file is being downloaded) simply because that's a harder problem to solve and we haven't done it yet.

**Comment by Microserf** [comment]
Containerization is the only thing I've found which seems to reliably help the problem.

If the Travis sites are distinct, where the container'd and the non-container'd environments are kept, this would seem to point to a networking problem between the non-container'd site and PyPI.

**Comment by daira** [comment]
We're also seeing this since 7 days ago (see the greyed-out builds at https://travis-ci.org/tahoe-lafs/tahoe-lafs/builds ). I've added ``sudo: false``; please do the feature flip to enable that.

**Comment by IanLee1521** [comment]
I've seen this outside of travis-ci when downloading virtualenv inside my work's firewall. But if I continue trying, it'll eventually download.

**Comment by joshk** [comment]
Hi Everyone,

Thank you for reporting these issues.

I am going to forward this to our infrastructure team to investigate further and see what we can dig up.

cc. @meatballhat @BanzaiMan

**Comment by ArturDorochowicz** [comment]
I stumbled upon this issue when googling for something that may be related and thought that I'd share my 2 cents. Firstly I must admit that I know nothing about Python nor Travis CI.

At my job I work with TeamCity, on Windows machines doing mainly .NET development. With build agents deployed to virtual servers in our data center we are having issues with NuGet package restore and npm package installs. The issue is the same as here: connection reset. (BTW, build agents deployed to servers in Microsoft Azure cloud don't experience it).

Guess what all three services (pypi, nuget, npm) have in common - **Fastly**, http://www.fastly.com/, a CDN provider.

I gathered some more clues that confirm this

1. Massive download problems using https://  - https://mail.python.org/pipermail/catalog-sig/2013-February/005266.html

2. pypi.python.org error Connection reset by peer - https://bugs.launchpad.net/openstack-ci/+bug/1334898
> Donald Stufft has acknowledged that from time to time their Fastly CDN has issues with HTTPS connections resulting in a connection reset (TCP/RST) and exposing the error you see here.

3. Persistent "Connection reset by peer" when uploading wheel to pypi.python.org - https://bitbucket.org/pypa/pypi/issue/234/persistent-connection-reset-by-peer-when

4. 65 issues for npm for ECONNRESET - https://github.com/npm/npm/search?q=econnreset&type=Issues&utf8=%E2%9C%93

   People solve this (?) by switching to http npm registry e.g. npm/npm#2866, npm/npm#6621

I also have packet captures for this with Nuget as well as with npm registry.

Anyway, good luck with this.

**Comment by joshk** [comment]
Hi @ArturDorochowicz 

Thank you for the very detailed comment, that is very helpful.

I will talk to our infrastructure team and have someone reach out to Fastly to see how we can best resolve this.

Thank you once more! You are a legend!

Josh

**Comment by aspires** [comment]
Hey @ArturDorochowicz can you send the packet captures you have to austin @ fastly.com? We're looking into this.

**Comment by ArturDorochowicz** [comment]
@aspires Sent what I have. 

The machine that experiences the issue for me is Windows Server 2012 R2. Today I tried to repro it on two other machines I have access to in the same network and couldn't. These machines are Windows Server 2008 R2.

**Comment by jaraco** [comment]
I observed this issue with a [Travis build](https://travis-ci.org/jaraco/pmxbot/builds/50890278) this evening. At the time the build was failing, I also attempted to download the URL reported from my iOS tablet on Comcast Internet, and Safari was also reporting problems (fails immediately with "Safari cannot download this file"). So the issue seems not to be an issue with Travis specifically. Furthermore, the project under Travis, although Python, is not using pip but instead using setuptools directly. All these findings lead me to believe the issue lies with PyPI or Fastly and its SSL handling.

I've opened [this ticket](https://bitbucket.org/pypa/pypi/issue/241/connection-reset-attempting-to-download) with the project.

**Comment by dstufft** [comment]
@jaraco You're in DC right? I think that the Travis Infra is in Ashburn (Maybe @joshk or someone can confirm that?) I recall Openstack having problems before with datacenters in NY. It seems like it could be centered around this region? I did get shown this the other day http://blog.edgecast.com/post/110230974176/being-good-stewards-of-the-internet, no idea if it's related or not but it's in the same region. It says that was fixed though so I guess probably not.

**Comment by jaraco** [comment]
That's a fun read. Yes, I'm in DC. You're probably right that it is likely an issue in transit rather than any endpoint. The issue has subsided for me at this time.

**Comment by gldnspud** [comment]
I am also getting this error today, spuriously but semi-frequently. Example builds: [here](https://travis-ci.org/fanscribed/django-react/jobs/50983458#L95), [here](https://travis-ci.org/fanscribed/django-react/jobs/50976718#L95).

**Comment by ArturDorochowicz** [comment]
FYI I found a solution/workaround for my case. Maybe this will help someone.

As a reminder, my case are TCP connection resets when doing _nuget restore_ and _npm install_ operations on Windows Server 2012 R2. Both services (api.nuget.org, registry.npmjs.org) resolve to hosts in *.fastly.net domain. My problematic server is a virtual machine (Vmware), located in a data center in Norway.

First thing I found is that the issue is not connected with SSL. I switched nuget to http package source and the problem persisted.

Next I compared the traffic from the problematic machine with traffic on Windows Server 2008 R2 located in the same network which does not exhibit the problem and found the culprit: **Explicit Congestion Notification**. On Wikipedia https://en.wikipedia.org/wiki/Explicit_Congestion_Notification

Windows Server 2012 R2 machine connects with a packet that has SYN, ECN and CWR flags set. Windows Server 2008 R2 machine sends typical packet, i.e. with just the SYN flag set. The Wikipedia page above describes how to disable the ECN mechanism (```netsh interface tcp set global ecncapability=enabled```). After doing that, Windows Server 2012 R2 machine stopped sending ECN and CWR flags and the connection reset problem went away. Success!

The observed behavior also matches exactly the description on Wikipedia: the ECN mechanism is disabled on client OSes and servers up to 2012 where it got enabled. One thing that does not match is why my Azure machines don't exhibit the problem (and they are all Windows Server 2012 R2). One possible explanation is that the issue is not with Fastly, but with something on my way from Norway to Fastly.  The Wikipedia page explicitly notes _Rather than responding properly or ignoring the bits, some outdated or faulty network equipment drop packets that have ECN bits set._

**Comment by BanzaiMan** [comment]
@ArturDorochowicz Thank you very much for the extra information. Your help is greatly appreciated.

We'll look into testing if disabling ECN helps.

One thing that is not clear to me is whether or not the problem occurs on the container builds (which is on a different network). Ones I've looked are happening on the standard builds. If anyone has seen this issue on a container, could they point it out to me? Thank you.

**Comment by BanzaiMan** [comment]
Hello, everyone! We have disabled ECN on the standard infrastructure just a few minutes ago. We are hoping that this improves the connections issue. (Containers are not affected at the moment yet.)

Could you try your builds **without `sudo: false`** and see if you notice any improvement?

Thank you.

**Comment by BanzaiMan** [comment]
Has anyone noticed any improvement or degradation in this regard on .org?

I am trying to gauge the effectiveness of this change, and to decide whether or not we should apply the same change to .com workers as well.

**Comment by daira** [comment]
It might be a bit early to tell since many projects will have had relatively few builds since the change, and the problem was always nondeterministic.

**Comment by BanzaiMan** [comment]
OK. It's been a few days, and seems to have calmed down. ECN has been disabled on our .com hosts as well.

If you see errors still, do let us know.

**Comment by tebello-thejane** [comment]
I see that the issue is now closed, and this might not be entirely related, but "me too!"

https://travis-ci.org/tebello-thejane/bitx-haskell/jobs/67013481
https://travis-ci.org/tebello-thejane/bitx-haskell/jobs/67013937

This is using Haskell, while downloading dependencies from Hackage. Note that in both cases the rest of the builds in the matrix succeed, and indeed the matrix environment variables are different between the two failures.

Seems to be related.

**Comment by engelmav** [comment]
I had the same issue using pip specifically in the python base docker image when trying to install (specifically) pymssql. Fascinating. At any rate, disabling ECN worked! For ubuntu, I had to do this by adding net.ipv4.tcp_ecn = 0 to /etc/sysctl.conf.
