### ISSUE TITLE
Builds run against FETCH_HEAD not specific commit

### ISSUE THREAD

**Issue by jehiah** [travis-ci/travis-ci#2430]
When an integration kicks off for a pull request because of a new commit being pushed up, it's possible that subsequent commits are tested, not the one that is pushed. This makes test status misleading (pass could indicate a pass of a later commit, or a fail could be a fail from a later commit) and a moving target.

The problem is that the test is run with

```
git fetch origin +refs/pull/52/merge: 
git checkout -qf FETCH_HEAD
```

And at this state `FETCH_HEAD` is a moving target that is not the commit being tested.

An example of this happening is https://travis-ci.org/bitly/go-nsq/builds/27686585 where the last build in the matrix ran against a different commit (not the one listed on TravisCI as https://github.com/bitly/go-nsq/commit/4ffb3751ed375f15d3bed037338d42a961b0ca08 )

**Comment by guidomb** [comment]
I think I am having a problem related to this. My PR build is failing and the problem is that travis is checking out the wrong commit and my project does not compile. I've realized about this because the compiler is complaining about something that has been added to a different branch in a different PR that was merged.

**Comment by BanzaiMan** [comment]
@guidomb Sorry to hear about the issue. Do you have a build log URL that shows this problem?

**Comment by guidomb** [comment]
Yes I have a build link but is a private repository. I will send an email to support.

| Guido Marucci Blas |

**Comment by asmeurer** [comment]
I just hit this strange behavior (https://github.com/sympy/sympy-paper/pull/22). Isn't GitHub smart enough to not mark a PR as failed if only an older commit is marked as failed? I know a lot has changed in the status API since 2014, so I'm wondering if it's still relevant.  

The way this works, if you push three commits up separately and they all get queued so that none of them start until all three are pushed, then you end up running the same build three times, which is wasteful at best (and confusing at worst). It seems at least if you are going to keep this behavior then you should implement https://github.com/travis-ci/travis-ci/issues/964 for pull requests.
