### ISSUE TITLE
Duplicate build numbers. Normal ?

### ISSUE THREAD

**Issue by fxlb** [travis-ci/travis-ci#2582]
Hi,

There is sometimes duplicate build numbers. Is it normal ?

example in `the-tcpdump-group/libpcap`. There are others in history.

![travis](https://cloud.githubusercontent.com/assets/2846004/3717151/33f06ef0-1621-11e4-9501-14cb1ec25191.jpg)

Greetings

**Comment by jayvdb** [comment]
I found number '80' appears twice for the project https://github.com/menegazzo/travispy .  They both appear in the API.

1. https://travis-ci.org/menegazzo/travispy/builds/45019395 (https://github.com/menegazzo/travispy/commit/3381bc15e3f9c99df6c7f955f73dbf1c5479ae06) - appears on https://travis-ci.org/menegazzo/travispy/builds 
2. https://travis-ci.org/menegazzo/travispy/builds/45019396 (https://github.com/menegazzo/travispy/pull/15) - appears on https://travis-ci.org/menegazzo/travispy/pull_requests

I peaked at https://github.com/twbs/bootstrap, and found it was really common there

12069:

1. https://travis-ci.org/twbs/bootstrap/builds/53437235
2. https://travis-ci.org/twbs/bootstrap/builds/53437234

12062:

1. https://travis-ci.org/twbs/bootstrap/builds/53350535
2. https://travis-ci.org/twbs/bootstrap/builds/53350534

12061:

1. https://travis-ci.org/twbs/bootstrap/builds/53350027
2. https://travis-ci.org/twbs/bootstrap/builds/53350026

12054:

1. https://travis-ci.org/twbs/bootstrap/builds/53263732
2. https://travis-ci.org/twbs/bootstrap/builds/53263731
3. https://travis-ci.org/twbs/bootstrap/builds/53263730

12049:

1. https://travis-ci.org/twbs/bootstrap/builds/53180442
2. https://travis-ci.org/twbs/bootstrap/builds/53180440

12048:

1. https://travis-ci.org/twbs/bootstrap/builds/53179847
2. https://travis-ci.org/twbs/bootstrap/builds/53179846

12041:

1. https://travis-ci.org/twbs/bootstrap/builds/53062897
2. https://travis-ci.org/twbs/bootstrap/builds/53062896

12038:

1. https://travis-ci.org/twbs/bootstrap/builds/53019569
2. https://travis-ci.org/twbs/bootstrap/builds/53019568

12037:

1. https://travis-ci.org/twbs/bootstrap/builds/53004897
2. https://travis-ci.org/twbs/bootstrap/builds/53004896

and probably more but I didnt check back further.

12041 is especially interesting, as they are also the exact same sha1 `2532c9b` (see https://github.com/twbs/bootstrap/pull/15994).  Is there another bug (feature?) which caused https://travis-ci.org/twbs/bootstrap/builds/53062897 to be a repeat of https://travis-ci.org/twbs/bootstrap/builds/53062896 ?

It appears that all cases of this have the same (project, author, committer) combination.
Perhaps instead of locking the repository row in a central table (which from my armchair is easy enough, but no doubt is hairy otherwise this would be closed already), maybe it is easier to create a temporary lock table recording the (project, author, committer) combination as a unique key while the project build number is being generated, and removed once the number has been generated.  That could be used to force the 'second' event triggered by the same committer to fail and re-try until the first has finished, and would workaround the problem for all of the cases that I've seen mentioned and found.

**Comment by joshk** [comment]
Thanks for reporting this.

All the builds you have listed are 8-10 months ago, from what I could see. That is before we fixed the issue.

Are there any recent builds which have duplicate build numbers which you know of?

Thanks a bundle

**Comment by jayvdb** [comment]
I dont have an easy way to find duplicate build numbers.
If you can tell us roughly when it was fixed, Travis API clients can add an assertion in the code to report if a duplicate occurs after the expected fixed date, with a link to this issue.
Then this could be closed, and we can re-open if it re-occurs again.

**Comment by joshk** [comment]
Hi @jayvdb 

Sorry, I don't fully understand the issue. We fixed the duplicate build number generation, the exact date I'm not sure, but either way, it is fixed and thus why the issue is closed.

Is it causing issues for you that there are duplicate build numbers from 8-10 months ago?

**Comment by jayvdb** [comment]
This issue is open...??

I can work around the fact that there are duplicate build numbers, especially now that I know that they can be expected to be unique now.

**Comment by joshk** [comment]
Ohhhhh, interesting, I am blind it seems.

Closed :)

**Comment by fxlb** [comment]
Thanks for fixing this.
