### ISSUE TITLE
Install the de_DE locale

### ISSUE THREAD

**Issue by lorenzo** [travis-ci/travis-ci#2598]
For CakePHP tests we use `sudo locale-gen de_DE`. This is used for environment integration tests when number formatting is involved.

It would be nice to have this locale (and maybe the most common ones) preinstalled, to avoid calling `sudo`

**Comment by BanzaiMan** [comment]
This will be available in the next round of build environment updates.

**Comment by dracos** [comment]
Thanks (though I've left a comment about a UK/GB typo) – sadly our tests currently use `cy_GB.UTF-8 en_GB.UTF-8 nb_NO.UTF-8 de_CH.UTF-8 sv_SE.UTF-8` so we'll have to continue using sudo for the moment, or change it to skip a few tests I guess :)

**Comment by AbdealiJK** [comment]
How can I change my locale to `de_DE` right now ?

Using:
`LANG=de_DE` doesn't change anything - and `locale` still shows `en_US`

**Comment by BanzaiMan** [comment]
Further work seems necessary. Sorry.

**Comment by theofidry** [comment]
Hi guys, is there any plan to be able to install different locales without requiring `sudo`?

**Comment by moylop260** [comment]
What about install `es_*` locale?
I have the following error on based-containers infrastructure:
 - `locale-gen "en_US.UTF-8" "fr_FR.UTF-8" "es_PE.UTF-8"`
 - `/usr/sbin/locale-gen: line 97: /var/lib/locales/supported.d/local: Permission denied`

Because using it I saw:
`Unable to get information for locale es_PE. Information from the default locale (en_US) have been used.`

**Comment by mpasternak** [comment]
Hope jasny's comment helps: https://github.com/travis-ci/travis-ci/issues/4416#issuecomment-278163295 and see my own comment below.
