### ISSUE TITLE
Can travis not properly build rebases on owned branches? 

### ISSUE THREAD

**Issue by hamiltont** [travis-ci/travis-ci#2668]
I'm looking at [this build](https://travis-ci.org/hamiltont/FrameworkBenchmarks/builds/32542329) where I performed a rebase and push. The travis commit range is `506ae2387cda...999c444d224f`, and 
the [github compare page](https://github.com/hamiltont/FrameworkBenchmarks/compare/506ae2387cda...999c444d224f) still works because the repository on github still contains the original commit `506ae2387cda`. However I can't use `git log` inside the worker, because the commit `506ae2387cda` does not exist there, it has been replaced by the rebase commit of `2cde067`. 

Given that the documentation really expresses that Travis can handle rebasing correctly (which it 100% can on PR's), I was surprised to see that the commit range does not properly reflect the history I am checking out

Is this a bug, or am I missing something?

**Comment by jirutka** [comment]
> …why would it make sense for it to be mentioned in TRAVIS_COMMIT_RANGE? … Unfortunately, it's also a useless value

Exactly! This has really confused me and took me about half a hour to figure out what’s going on here. It’s really not an expected behaviour. :(

**Comment by WasabiFan** [comment]
I'm being affected by this issue too (for me, the main issue I have is with force-pushes). If the problem can't be fixed, it would be great if information on this were at least added to the documentation so others don't struggle for hours before realizing that the range is invalid.

**Comment by pkch** [comment]
In the case the `START` of `TRAVIS_COMMIT_RANGE` is not in the cloned repo (due to a rebase or forced push), wouldn't it be both safe and intuitive to simply set `START` to the nearest ancestor of the current commit that was already tested by Travis?

The way I think about it is that `TRAVIS_COMMIT_RANGE` answers this question: 

> What is the delta relative to some past commit which was already seen by Travis?

When the `START` is invalid, we can still produce a correct answer by going through the ancestors. Sure, it will be somewhat conservative since it will include some changes that were already tested in the orphaned commit -- but it still seems to be appropriate for the purpose of determining what (if anything) needs to be built to test the new commit.

**Comment by php-coder** [comment]
I've got an error when executing `git diff $TRAVIS_COMMIT_RANGE`:
```
fatal: ambiguous argument 'cf017f33435a...46806326215a': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
It happens only after force push. Is it the same issue? Is this variable still useless?

**Comment by dagwieers** [comment]
It would be nice if Travis would expose something like `$TRAVIS_COMMIT_FILES`. You can get this through the Github API, so it must be possible to provide it within Travis.
