### ISSUE TITLE
Add non-thread safe versions of PHP

### ISSUE THREAD

**Issue by BenMorel** [travis-ci/travis-ci#2800]
I'm trying to run tests on Travis depending on the [libgeos](https://github.com/libgeos/libgeos) bindings for PHP, but this extension won't compile against a thread safe version of PHP.

It would be nice to be provide NTS versions of PHP as well, such as:
- 5.5-nts
- 5.6-nts

etc.

**Comment by monque** [comment]
We have the same problem, this [PHP extension](https://github.com/Qihoo360/phptrace) does not support ZTS. So it's a hard time that build each minor versions of PHP without ZTS manually in travis-ci.

I agreed with @BenMorel , providing both version would be a good idea.

**Comment by beberlei** [comment]
+1 here, PHP being ZTS by default is quite annoying for extension developers. Its not the default in PHP world.

**Comment by BanzaiMan** [comment]
Currently, our PHP runtimes are compiled (and subsequently installed on build images) using  https://github.com/travis-ci/php-src-builder.

If anyone wants to adapt `php-src-builder` build script to make this happen (using https://github.com/php-build/php-build/), we are happy to look at PRs. While it is highly unlikely that we will have these non-thread-safe runtimes pre-installed on the build images, it would be available for on-demand installations.

For now, I'm closing this, since it seems like a niche feature with not much demand.
