### ISSUE TITLE
`find -execdir` complains about `.node_modules/bin` relative path

### ISSUE THREAD

**Issue by drogus** [travis-ci/travis-ci#2811]
When `find -execdir` is used on Travis CI, it will fail with the following message:

```
find: The relative path `./node_modules/.bin' is included in the PATH environment variable, which is insecure in combination with the -execdir action of find. Please remove that entry from $PATH
```

We should consider if putting `.node_modules/bin` to the `PATH` by default is needed.

**Comment by kenorb** [comment]
The same problem here, is  there any permanent solution available?

**Comment by BanzaiMan** [comment]
Do we know what is injecting `./node_modules/.bin` into `$PATH` (the first and the second time)?

**Comment by kenorb** [comment]
Maybe [`dotbin`](https://github.com/moander/node-dotbin)?

**Comment by kenorb** [comment]
We did workaround for Travis, `nvm deactivate` didn't work, but removing entry from `PATH` worked, e.g.

    before_script:
      - PATH=${PATH//:\.\/node_modules\/\.bin/}

**Comment by BanzaiMan** [comment]
Sorry. I missed the crucial detail. I do not think it is `nvm` that is modifying `$PATH` (so `nvm deactivate` doesn't do the job), but our own `/etc/profile.d/nvm.sh`.

This has been there since https://github.com/travis-ci/travis-cookbooks/commit/670cb77cab03adb60986425cf192d753797ffd8a. I doubt this was ever effective.

@kenorb Could you open a separate issue? We should remove this from the cookbooks.
