### ISSUE TITLE
Feature request: caching objects downloaded by a git clone

### ISSUE THREAD

**Issue by snim2** [travis-ci/travis-ci#2939]
Recently I have been trying to set up a complex Travis build for some embedded software which needs to be compiled with a "Canadian" cross-compiler. This meant that as well as installing some dependencies with `apt-get` I also needed to install customised versions of tools like `gcc`, which have to be downloaded via a `git clone` and built. This is a long and wasteful process - much of the build time is spent dealing with dependencies, before the system under test can be downloaded (or cloned).

Currently, dependencies which are installed via `apt-get` can be cached. Complex environments, like the one described here, could be set up more efficiently by adding an option to cache some (or all) of the objects downloaded via a `git clone`. That would mean that, after caching, only the most recent deltas would need to be downloaded in future builds of the project under test. 

Another way around this might be to create Docker image with the relevant toolchain built and installed. Then CI could be done on Travis by loading the Docker container and running CI tests inside the container (and perhaps caching the Docker container).

**Comment by joshk** [comment]
Thanks for creating this issue.

I think there is a misunderstanding, we do not currently support `apt-get` caching.

Also, you can cache if you are using the new Container setup (`sudo: false` in your `.travis.yml`) and create compiled binaries without using `apt-get`. Your code would need to check if the binary exists, otherwise it would do the clone and compile the binary, then Travis would cache it.

I'm going to close this issue as this isn't something which needs to change in Travis.

Have an awesome day,

Josh
