### ISSUE TITLE
[C# support] Make Mono version configurable

### ISSUE THREAD

**Issue by akoeplinger** [travis-ci/travis-ci#3018]
While replying to [this comment](https://github.com/travis-ci/travis-ci/issues/649#issuecomment-66625394) I thought about whether we should allow users to choose the Mono version they want to use.

Always getting the latest version might not be ideal e.g. when a regression is introduced in the new version that fails people's builds, or when the build should be tested against a minimum Mono version.

Installing older versions is quite easy, see "Accessing older releases" on [this page](http://www.mono-project.com/docs/getting-started/install/linux/#accessing-older-releases), we could expose that as a configuration option, e.g.
``` yml
language: csharp
mono:
  - latest
  - 3.8.0
```

What do you think?

/cc @Joshua-Anderson @nterry

**Comment by akoeplinger** [comment]
@Joshua-Anderson did you already have time to look in this?

**Comment by nterry** [comment]
I think we'll have to compile the major milestones pre-3.8, zip them up,
and put them in an s3 bucket. Possibly even manually make pre-3.8
packages...

**Comment by akoeplinger** [comment]
@nterry yeah, I'll ask @directhex if we can get some earlier milestones into the Xamarin repos. Anyway, we should first start with the ones that are already there, i.e. 3.8+, and then look at expanding.

**Comment by directhex** [comment]
It's not possible, with the way the archive manager software I'm using (reprepro) is written. Version numbers must *always* increment. Providing older versions is only possible by abusing the "snapshot" function it has, which introduces a lot of "this will bite you later" into its back-end database.

**Comment by akoeplinger** [comment]
@directhex we were specifically talking about the `wheezy/snapshots/X.XX.X`, not the regular repository. I think those restrictions don't apply there?

**Comment by directhex** [comment]
Nah, that's the point. reprepro's snapshot functionality supports taking a snapshot of the current archive & giving it a codename (I use numbers as codenames), and that's it - you can't inject packages into a snapshot. Or remove packages. Or, in fact, do anything at all with a snapshot once it's made. It breaks reprepro's GC, amongst other features.

If I switch archive manager to something else (like OBS) then maybe more options are possible.

**Comment by akoeplinger** [comment]
Ah, ok, that's a pity then, thanks for the explanation. We would've find other ways then, or just stick with having 3.8 as the lowest version for now (which should be perfectly fine IMO).

**Comment by Joshua-Anderson** [comment]
@akoeplinger Sorry I haven't looked into this yet, I've been busy :frown:. Since there are only two snapshot versions available right now, is it worth adding the feature right now? Since the part of the code that installs mono runs in the configure stage currently, to allow sudo usage on docker workers, I also suspect that allowing user supplied variables at that time could be a potential security concern. @nterry, like you said, I also considered uploading built binaries to s3, but the built binaries contain things like references to full paths to where the binary was originally installed, which makes distributing a binary difficult.

**Comment by akoeplinger** [comment]
@Joshua-Anderson no worries, I was busy myself :)

I do think it's worth adding the feature, even if there are only two snapshot versions. It's a PITA for users right now if a new Mono version comes out with a regression and the Travis build suddenly starts failing (and I suspect we'll see a lot more failures with Mono 4.0 which removes the net_2_0 profile). Having an option to easily downgrade solves this.

Obviously, security is a concern here when we're accepting user input, so we'd need to ensure the value is in the right format (I think we can safely assume it'll always be `X.XX.X` so should be pretty easy to verify with a regex).

Re earlier versions: I tend to think that most users testing against earlier versions will want to target those that are included in the Ubuntu repos (i.e. Mono 2.10 for Ubuntu 12.04 and Mono 3.2.8 for Ubuntu 14.04). For 2.10 we could just skip the Xamarin repo.

**Comment by akoeplinger** [comment]
I talked to Jo and one way to get Mono 3.2.8 on Ubuntu 12.04 would be to use his badgerports repo: https://launchpad.net/~directhex/+archive/ubuntu/ppa?field.series_filter=precise

The Pash guys also would like to test against 2.10 and 3.2.8 to make sure they don't regress there: https://github.com/Pash-Project/Pash/issues/334#issuecomment-69448140

**Comment by akoeplinger** [comment]
@Joshua-Anderson did you get a chance to look into this yet? Mono 4.0 is on the horizon and I fear the outrage of people when it breaks their Travis builds without workaround :smile:

**Comment by Joshua-Anderson** [comment]
I have done some light looking into this but not too much. Since my life is now less crazy, I should be able to put some time into this. Apt really is not really designed at all to support handeling multiple versions of a package. We might want to do this for now, but it doesn't seem like a good long term solution to me. Primarily, this prevents us from installing multiple versions mono at the same time. Idealy, at some point in the future, C# gains enough users to get a VM with C# preinstalled. If we use apt to manage versions we would be prevented from doing this. In addition, juggling several different ppas and Debian repositories each with different versions of mono with different install setups and versioning systems ( x.x.x vs x.x.x- ubuntux vs x.x.x-xamarinx) seems unstable and difficult to maintain long term.

Ideally, we would install mono from a version switcher, but since I haven't seen any we will have to get creative.

The most feasibile sustainable solution is if we could download mono, nuget, and xbuild as a tarball. This could allow us to be very flexible and support every version of mono created. The problem is that mono doesn't offer binary tarball downloads that I have found yet, and when you build from source mono creates lots of absolute path links, preventing the build from being portable. It's strange because Mono offers packages for Mac OS X in this manner, but doesn't offer portable Linux builds.

Any ideasfor how to do this @akoeplinger?

**Comment by akoeplinger** [comment]
> Primarily, this prevents us from installing multiple versions mono at the same time.

Yeah, though I'm actually not sure this is something we should strive for. How do other languages do this, e.g. is there an image with multiple Java versions installed?

I don't think relying on the apt repo is a bad thing and honestly the setup we have now is pretty fast already, so personally I don't see how having a prepopulated C# image would gain us much (other than additional work for whoever manages the image). We can even speed up the current setup by requesting caching for the apt repo from Travis (this is on my list).

To be clear: my underlying assumption is that we should generally only need the Xamarin repo for all future Mono versions. Building Mono from source is something I very much want to avoid.

The other Debian repo/PPA would only be a temporary workaround for now so people can test against old Mono versions. I see this going away in the next year or so when demand for those old versions declines.

My plan for now would be to do this (in stages):
1. Add a way to specify Mono version that will be fetched from the Xamarin snapshot repo: Mono >=3.8
2. Add a way to get Mono as it ships with Ubuntu 12.04 that Travis uses
3. Add a way to get Mono as it ships with Ubuntu 14.04, via the PPA from directhex

@Joshua-Anderson it would be great if we could do step 1 before Mono 4.0 is released so we have a workaround for people broken by it :)

**Comment by Joshua-Anderson** [comment]
@akoeplinger Every language features a way to switch versions. I think that at least the first point makes sense and I can probably do it in the next few days.
