### ISSUE TITLE
Native support for tox for Python projects

### ISSUE THREAD

**Issue by mgedmin** [travis-ci/travis-ci#3024]
[tox](https://testrun.org/tox/) is a Python tool that runs the test suite against multiple Python versions, according to the configuration specified in `tox.ini`.  Rather like a local Travis, actually.  It's rather popular in Pythonland.

The `tox.ini` looks something like this:
```
[tox]
envlist = py26, py27, py32, py33, py34, pypy, pypy3

[testenv]
commands = python tests.py
```

Duplicating the same information in `.travis.yml` is a bit annoying, so I (and many people) do something like this:

```
language: python
env:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
    - pip install tox
script:
    - tox
```

As you can see one still has to duplicate the list of tox environment names.

It would be awesome if Travis CI had native tox support for Python projects.  By that I mean:
if the project has a `tox.ini` and it has a `.travis.yml` that specifies `language: python`, Travis could create a build matrix automatically, by extracting the `[tox] envlist` option from `tox.ini`  and using `tox` as the test script.  (This assumes `tox` would be preinstalled in the VM image, like `virtualenv` currently is.)

Some notes:

- tox has a bunch of predefined environment names (pyXY, pypy, pypy3) but you can also define your own (and people sometimes use things like `tox -e docs` to test that their [Sphinx documentation](http://sphinx-doc.org/) can be built without errors)
- you can define environments but not include them to `envlist` if you don't want to run them by default
(people often use `tox -e coverage` but don't want to run it by default)
- `tox -l` prints the list of environments from `envlist` to standard output, one name per line (so you can use this instead of parsing `tox.ini` manually)
- mere presence of `tox.ini` shouldn't override people's existing .travis.yml build scripts.

**Comment by jezdez** [comment]
You may be interested in @msabramo's panci: https://github.com/msabramo/python-panci

**Comment by msabramo** [comment]
I can understand why travis wouldn't want  to do this as it's very specific to Python and to tox specifically - that's a slippery slope of maintaining a lot of special stuff.

Thinking out loud here so this could get messy and nonsensical... :smile: ...

I wonder if a more generalized feature would be more palatable. I'm thinking basically, introduce some dynamic features into Travis like:

1. Add templating of some sort to `.travis.yml` or perhaps to a slightly different named file -- e.g.: `.travis.yml.jinja2`, `.travis.yml.erb`, etc. So if travis doesn't find a `.travis.yml`, but it sees a `.travis.yml.jinja2`, `.travis.yml.erb`, `.travis.yml.mustache`, etc., it processes the template to create `.travis.yml` and then runs that.

2. Allow project to specify a script that is a generator or filter for the `.travis.yml` -- e.g.:

```yaml
# .travis.yml

language: python
yaml_preprocessor: .travis/yaml_preprocessor
```

```
# .travis/yaml_preprocessor

#!/usr/bin/env python

import sys
import yaml

travis_yml = yaml.load(sys.stdin)
travis_yml['env'] = []

for env in ('py26', 'py27', 'py33', 'py34', 'pypy'):
    travis_yml['env'].append(env)

print(yaml.dump(travis_yml, default_flow_style=False))
```

Obviously `.travis/yaml_preprocessor` doesn't have to be Python; it can be Ruby or NodeJS or whatever. And instead of looping through a static list of envs, it could process a `tox.ini` or similar file. In the case of `tox.ini`, perhaps it could simply shell out to [panci](https://github.com/msabramo/python-panci).

**Comment by joshk** [comment]
Thanks for the suggestion but I think this is complex in itself, and can be a bit of a security risk.

I'm going to close this issue for the time being.

Thank you everyone for your suggestions and feedback.
