### ISSUE TITLE
Add an external config source url

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#306]
An increasing number of people are concerned with adding a .travis.yml file to their repository.

We _could_ add a UI that allows to overwrite the .travis.yml from the repository. We have a bunch of issues with this approach though, as the current client app is merely a viewer.

A more simplistic but still acceptable approach would be to allow passing a config source url from the service hook.

So, people could enter an optional config source url (like a gist raw url) to the service hook. The service hook would send this url every time Github pings. We'd accept that url and pass it to the worker as part of the configure payload. The worker gets then gets that url instead of the one from the Github repository.

**Comment by jakepetroules** [comment]
Not everyone is 100% in the GitHub ecosystem. I test projects on AppVeyor using a post-receive hook on a GitHub mirror of a Git repository on an external server with the CI configuration in the web UI. I cannot put a .travis.yml file in this repository without seriously impeding my workflow (having to cherry pick a commit adding the file all the time to my numerous and short-lived branches), because we will not accept such a file in the upstream repo. Why can't Travis be as good and flexible as AppVeyor?

**Comment by karolherbst** [comment]
Yeah, this is also needed if you fork/clone a project from somewhere else without a .travis.yml file and if you don't want a crappy "add .travis.yml file" commit within your tree, there is no alternative.

**Comment by karolherbst** [comment]
well it hasn't to be an URL, it would be also fine to have a new branch called ".travis.yml" with a single ".travis.yml" file in it. I guess that would be acceptable?

**Comment by jayvdb** [comment]
A URL could be configured to point to a raw file hosted on github , in any branch, or even in another repository. Allowing variables in the URL would mean the current behaviour can be replicated (roughly) using

> https://raw.githubusercontent.com/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/master/.travis.yml

It will be a bit more complicated than that, to support building PR & non-tip commits.
