### ISSUE TITLE
Upgrade to pip 6.x

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#3060]
pip has a new version which enables download caching by default.
It will enable Travis to provide caching similarly to how you cache bundler dependencies e.g.
```yaml
cache:
  - pip
```

**Comment by dstufft** [comment]
I don't know much about bundler or how their cache works, but pip stores it's cache in ``~/.cache/pip`` on linux unless the user specifies differently. Without being told to cache elsewhere it'll cache there for every single invocation of pip no matter how you invoke it, in what environment you invoke it, etc. The only exceptions are if someone explicitly says to cache to a different location (or don't cache at all) or they change their effective user using somehting like ``sudo pip``. This follows the XDG spec and is also able to be set via environment variable, ``/etc/`` based config file, user based config file, and a per virtualenv based config file.

Also as far as the burden of maintaining it goes, it's probably easier for Travis CI team to maintain it (especially since y'all can just ping me ;) if there are questions) than it is for each and every user of pip on Travis to duplicate the effort in maintaining it.

**Comment by thedrow** [comment]
@dstufft Thanks for the support :+1:

**Comment by joshk** [comment]
@dstufft I :heart: you!

**Comment by BanzaiMan** [comment]
See travis-ci/travis-build#368. @dstufft Is `pip`'s cache location configurable? If so, we'll need to add some logic for it to the PR.

**Comment by dstufft** [comment]
Yes it's configurable. You can either configure it with ``--cache-dir`` CLI flag, ``PIP_CACHE_DIR`` environment variable, ``cache-dir=`` in a configuration file, or it also follows XDG so it works with the ``XDG_CACHE_HOME`` environment variable on Linux as well.

**Comment by BanzaiMan** [comment]
OK. `$PIP_CACHE_DIR` env var can be accommodated. I assume `$XDG_CACHE_HOME/pip` is the directory `pip` looks at. That is probably manageable, too. Others, probably not.

Of `$PIP_CACHE_DIR` and `$XDG_CACHE_HOME/pip`, which takes precedence?

**Comment by dstufft** [comment]
um, I'm pretty sure that ``$PIP_CACHE_DIR`` will be used if both are set.

**Comment by moorepants** [comment]
I'm getting pip 6+ on my Travis builds now (and it's unfortunately breaking my build system due to the PEP 440 backwards incompatibility). Has this been officially implemented and what's the easiest way to undo it? Should I just call `pip install pip<6` as the first thing in my `travis.yml`?

**Comment by dstufft** [comment]
If you're attempting to turn of PEP 440 support you'll need to do ``pip install pip<6 setuptools<8``.

**Comment by thedrow** [comment]
Is the pip cache bucket available?

**Comment by BanzaiMan** [comment]
@thedrow yes, it is. `cache: pip` caches `~/.cache/pip`.

**Comment by dstufft** [comment]
Nice!

**Comment by thedrow** [comment]
@BanzaiMan I don't see it documented though.
