### ISSUE TITLE
Cache OpenWrt SDKs

### ISSUE THREAD

**Issue by probonopd** [travis-ci/travis-ci#3070]
OpenWrt is an embedded operating and build system, mainly geared toward wireless routers. Packages for OpenWrt can be compiled using OpenWrt SDKs for the target platforms shown on https://dev.openwrt.org/wiki/platforms

It is possible today to use travis-ci together with OpenWrt SDKs to build packages for OpenWrt, e.g., https://github.com/probonopd/announce/blob/master/.travis.yml (this does not use all of the target platforms yet).

It would be nice if the OpenWrt SDKs could be cached officially. Possibly travis-ci could also make using the OpenWrt SDKs for all target platforms a bit easier than it currently is.

**Comment by mkschreder** [comment]
Is it possible to build from THE SAME repo on travis multiple times without it resetting the system each time? Is it possible to tell travis to just do a git pull and then rebuild?

**Comment by BanzaiMan** [comment]
@mkschreder No, it is not. To some extent, you can persist certain build artifacts with [caches](https://docs.travis-ci.com/user/caching/).

**Comment by mkschreder** [comment]
I'm trying out cache.. but can it be used to save off state if for example build times out? 

I'm building openwrt but the build times out after 50 minutes. It would take longer to build an initial repo with all necessary tools. After that is done it would be much faster - but will the cache be saved when it times out?

**Comment by BanzaiMan** [comment]
No states are saved. VMs are terminated at the end of the build.

**Comment by mkschreder** [comment]
Can maximum build time be extended?

**Comment by dumblob** [comment]
@mkschreder did you succeeded with building it somehow?

**Comment by mkschreder** [comment]
I can build openwrt on travis but it only works sometimes (probably when
server load is not that high and it builds faster)

**Comment by mkschreder** [comment]
It is kindof random.. my travis script runs my uml build script. Besides
building it sometimes it doesn't really do anything else:
https://github.com/mkschreder/juci-openwrt-feed/blob/master/build-uml-image.sh

**Comment by dumblob** [comment]
Thank you for the info. So the build just runs too long (i.e. about 1 hour), right? We can save every single minute with e.g. the following:

* changing the git clone command to `git clone --depth 1 ...` (with my internet connection it was 3:25 for full clone against 0:11 for the `--depth 1` clone; not sure what is the bandwidth for non-paying projects on Travis)
* using a [Travis caches](https://docs.travis-ci.com/user/caching/#Arbitrary-directories ) for the cloned repository (and just put there `[ -d openwrt ] && cd openwrt && git pull` to update the repo) instead of fetching the `--depth 1` clone every single time (well, it's `11` seconds or slightly more, but why not if it's so easy to setup)
* splitting the build into stages, whereas each stage will get cached separately using the above-mentioned Travis caches - we'll need to transactionally save the state of this simple finite state automaton (it's enough to safe just a keyword to a uniquely labeled file like `last_successful_stage.txt` which needs to be also cached by Travis)
   * `./openwrt-bootstrap.sh` takes some time, so we might first run this for a different directory then `openwrt`, i.e. `stage1/` and if it succeeds, run `printf stage1 > last_successful_stage.txt`
   * `cp -r -a --reflink=auto -- stage1/ stage2 && cd stage2/ && make -j8` takes probably more than half of the overall time, so this should be another stage which if succeeds, will get noted by `printf stage2 > last_successful_stage.txt`
   * `mv stage2/bin/uml/openwrt-uml-vmlinux stage2/bin/uml/openwrt-uml-ext4.img ./ && tar -czf openwrt-juci-uml.tar.gz stage2/openwrt-uml* && printf stage3 > last_successful_stage.txt` is the last stage (this can be actually skipped as the compression may take the last few minutes which are very valuable for us)

This should make it possible to restart the last unfinished stage. We should start over (with `git pull`, stage1, ...) only after the we succeed with stage3.
