### ISSUE TITLE
Our Golang builds are sporadically failing with some kind of MongoDB or memory failure

### ISSUE THREAD

**Issue by msabramo** [travis-ci/travis-ci#3075]
https://github.com/tsuru/tsuru/issues/1045

Errors include:

- `value *errors.errorString = &errors.errorString{s:"no reachable servers"} ("no reachable servers")`
- `... value *errors.errorString = &errors.errorString{s:"EOF"} ("EOF")`

Latest example failure: https://travis-ci.org/tsuru/tsuru/jobs/45629271

We have tried another of things to solve the problem but nothing has worked:

- https://github.com/tsuru/tsuru/pull/1046 (Allow go tip to fail)
- https://github.com/tsuru/tsuru/pull/1048 (Add `sleep 15` to `before_script`)
- https://github.com/tsuru/tsuru/pull/1049 (Use `nc` to check that ports are accessible)
- https://github.com/tsuru/tsuru/pull/1050 (`travis_retry`)
- https://github.com/tsuru/tsuru/pull/1051 (Use `nc` to check that ports are accessible)

Any ideas why this fails intermittently?

**Comment by ribasushi** [comment]
@msabramo You may be experiencing intermittent OOMs - arrange for a [`dmesg` dump on failure](https://github.com/dbsrgits/dbix-class/blob/fe92f179/maint/travis-ci_scripts/50_after_failure.bash#L12) in order to confirm this. An [OOM-ed build looks like this](https://s3.amazonaws.com/archive.travis-ci.org/jobs/38904324/log.txt) (scroll to the end)

If the case - not much you can do aside from [shutting down as much as possible](https://github.com/dbsrgits/dbix-class/blob/fe92f179/maint/travis-ci_scripts/10_before_install.bash#L3-L6) and sometimes [using configs that take less memory](https://github.com/dbsrgits/dbix-class/blob/fe92f179/maint/travis-ci_scripts/configs/minimal_mysql_travis.cnf). For more info: https://github.com/travis-ci/travis-ci/issues/2904

**Comment by msabramo** [comment]
@ribasushi: Thanks for taking the time to respond. Going to try adding `sudo dmesg`.

**Comment by msabramo** [comment]
Yep, it's OOMs.

**Comment by msabramo** [comment]
Thanks again, @ribasushi!

**Comment by tripleee** [comment]
@msabramo I'm guessing this no longer needs to remain open, then?

**Comment by ribasushi** [comment]
@msabramo You may be interested in cribbing more from here: https://github.com/travis-ci/travis-ci/issues/2904#issuecomment-148485284

Cheers

**Comment by msabramo** [comment]
Yeah, I think this can be closed. Thanks!
