### ISSUE TITLE
Getting local hostname with IPv4 on Docker crashes OpenJDK with buffer overflow

### ISSUE THREAD

**Issue by travisbrown** [travis-ci/travis-ci#3120]
I've got the following simple configuration:

```
sudo: false
language: java
jdk: openjdk7
script: javac Test.java && java -Djava.net.preferIPv4Stack=true Test
```

Where [`Test.java`](https://github.com/travisbrown/travis-ci-sandbox/blob/java/openjdk7-ipv4/Test.java) just calls `InetAddress.getLocalHost().getHostName()`. This crashes the Travis CI build with a [buffer overflow](https://travis-ci.org/travisbrown/travis-ci-sandbox/builds/47270766).

Removing `sudo: false` makes it work just fine, as does using any of the Oracle JDKs, but I need to test against OpenJDK and I'd like to use the container-based infrastructure.

**Comment by BanzaiMan** [comment]
Compare https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/400329 and https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/400333

This happens only on OpenJDK 7 on the Docker worker. Not clear what the cause is; perhaps the new OpenJDK 7u71 (http://packages.ubuntu.com/precise/openjdk-7-jdk) would fix this, but at this time we do not have a means to test this hypothesis easily.

**Comment by BanzaiMan** [comment]
Still an issue after the latest update (7u75).

**Comment by jgeraerts** [comment]
Having the same issue here. https://travis-ci.org/jgeraerts/imageresizer/jobs/96831113 although i'm not doing explitly a getHostByName.

**Comment by BanzaiMan** [comment]
I think this was reported again as #5227. I'm closing this one, since the other issue has more info.
