### ISSUE TITLE
Allow users to opt-out from emails at the web interface

### ISSUE THREAD

**Issue by Mikaela** [travis-ci/travis-ci#3121]
Every project where I contribute to and which uses Travis has IRC channel where the notifications are. Some of these projects wish to keep email notifications on, but I wish to not have to receive the notifications as they are just useless spam to me as I see the status at IRC faster than I read my email.

.travis.yml doesn't seem good place to do this so it would be useful if I could opt-out from email notifications at the web interface.

**Comment by joshk** [comment]
Hi @Mikaela, we are working towards this feature, as well as the bigger feature of moving all notification logic into the UI. We are sorry for the delay with this.

**Comment by Mikaela** [comment]
> the bigger feature of moving all notification logic into the UI.

This probably means https://github.com/travis-ci/travis-ci/issues/1094 ? Has anything happened towards it? All comments seem to be +1 and if anything has happened.

**Comment by nikolas** [comment]
I'm also looking forward to this feature. Currently, travis automatically emails every account that I have associated with my github account. It's really annoying, because I get the same email 3 times, in email accounts that aren't relevant to the repositories I'm working on.

Ideally I'd like to tell travis to "only ever email this address", without having to put that in the `.travis.yml` file for each project, which I might not want to alter since it might not really be "my project".

**Comment by joshk** [comment]
@nikolas this sounds like a different issue, as we only send emails based on the email addresses in the commit info. Can you please email support about this and we can dive in deeper.

@Mikaela we are making progress towards this, and it is high on the product roadmap, we are currently laying some foundation work which will help us iterate on our UI faster.

**Comment by joshk** [comment]
Soooooo, I'm gonna reopen this, as this work is in the pipeline :)

**Comment by Mikaela** [comment]
@joshk I am not seeing this in the UI, so I think this was mistakenly closed or I am looking at the wrong place?
