### ISSUE TITLE
The same code, different results

### ISSUE THREAD

**Issue by lite3** [travis-ci/travis-ci#3143]
I fork github project.
upstream : https://travis-ci.org/DragonBones/DragonBonesCPP/builds/47737912
my: https://travis-ci.org/lite3/DragonBonesCPP
now, the code is same.
but, somethime, my project build success. an other time upstream project build success.
if build failed, i need to rebuild it again, sometimes successfully , sometimes fails.
now, my project is failed, upstream is success, but  they are the same code.

**Comment by BanzaiMan** [comment]
Looks like the compiler is getting killed, perhaps because it is using too much memory, or there are other resource starvation. If you don't need `sudo` in your build, adding `sudo: false` should get the build on a bigger VM. http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/

**Comment by lite3** [comment]
I must use sudo. 
Why upstream is successful , and my is a failure , they are the same code , the same configuration.

**Comment by BanzaiMan** [comment]
They run in different times. The resource constraints are different every time a job runs. We try to minimize such differences, but some things can still get in the way. The upstream also fails sometimes: https://travis-ci.org/DragonBones/DragonBonesCPP/jobs/47201899#L248
