### ISSUE TITLE
travis-cookbooks fail to compile PHP 5.2.17

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3152]
See the comments in https://github.com/travis-ci/travis-cookbooks/commit/32a364be50b96268f6e937deaf0834291eae4032.

5.3.3 seems to compile correctly.

**Comment by BanzaiMan** [comment]
If we can't resolve this problem before Monday, the choices are:

1. Postpone PHP update until we can figure this out
2. Drop 5.2.17.

A combination of both (postpone PHP update by 1 week, say, and drop 5.2.17 at that point) might be best.

**Comment by BanzaiMan** [comment]
Stats show that usage of PHP 5.2.x is quite insignificant (on both .org and .com), so we might just drop it.

**Comment by GrahamCampbell** [comment]
> Drop 5.2.17.

:+1: for that. We're already having an issue with phpunit on 5.2.17 after phpunit's pear server was removed.

**Comment by BanzaiMan** [comment]
Resolved by https://github.com/travis-ci/travis-cookbooks/commit/e4d7d1e358bf028d8b14b59acc351dc905778e39.

**Comment by BanzaiMan** [comment]
If anyone is interested in resurrecting the PHP 5.2.17 support, see the php-build log shown in https://github.com/travis-ci/travis-cookbooks/commit/32a364be50b96268f6e937deaf0834291eae4032#commitcomment-9520802.

**Comment by GrahamCampbell** [comment]
@BanzaiMan I think we should just drop php 5.2 anyway. Anyone wishing to support php 5.2 on public repos is frankly irresponsible.

**Comment by joshk** [comment]
How about private repos? Is 5.2 a default php version?

**Comment by BanzaiMan** [comment]
5.3.x is the default for 12.04 LTS, IIRC. http://packages.ubuntu.com/precise/php5

**Comment by GrahamCampbell** [comment]
5.3 isn't even maintained by the php team anymore either.

**Comment by nacin** [comment]
@BanzaiMan @GrahamCampbell: Howdy! WordPress still works on 5.2 because there are tens of millions of servers out there that still use it. It sucks, but breaking it would abandon a lot of users (millions). Since the open source project thankfully collects some good data here, we're directly engaging major hosts and getting them to forcibly migrate user accounts and turn off 5.2 all together. Our work is very specific on hosting configurations, tools, and what they allow their users to do (the concern is always breaking other random PHP stuff). It also means that the needle can be moved in a big way. We're pushing 5.4+, and doing this for both 5.2 and 5.3. (It should be noted that WordPress works great on the latest stable PHP version, and in fact WordPress.org and WordPress.com both run 5.6.)

We would really appreciate PHP 5.2 support in Travis, perhaps at least through the end of the year. At some point, we do think we might be comfortable enough bumping our minimum requirements. But 5.3 is still something like 10 million sites for us, and it's only recently started finally trending down, extremely slowly (it was still going *up* even after it was EOL'd by PHP). It's the minimum requirement for a much longer list of projects, and removing it (especially while it isn't broken) would be less than ideal.

While we can potentially spin up our own infrastructure for this, there are tens of thousands of plugins that aim to support all users. Keep in mind these users may have no idea what PHP even is, forget about how to navigate cPanel or worse. It's certainly likely that the majority of the the small number of projects that used 5.2 are WordPress-related. So, I recognize how little of a priority this would be for you. I'm not asking time to be spent on this; rather, just a request that our use case is recognized. I'll try to spend some time on this (or barring that, I'll find someone else), and if someone can get it working, we'd appreciate it being brought back.

**Comment by rmccue** [comment]
> I'll try to spend some time on this (or barring that, I'll find someone else), and if someone can get it working, we'd appreciate it being brought back.

I'm going to take a look this weekend as well; it's an important part of the WordPress feature plugin testing (WP-API/WP-API mentioned above), alongside several of my own projects. (In fact, I'd say it's the most important reason for using Travis, as it ensures that we test compatibility across the versions we support.)

If I read the original commit comments correctly, it appears that XDebug isn't compiling with 5.2.17 any more? Worst case scenario, can we drop XDebug from 5.2, or do we need to get that working again?

**Comment by BanzaiMan** [comment]
Thanks for the offer to help out on this situation.

@rmccue Removing xdebug from the equation did not improve the situation.

**Comment by GrahamCampbell** [comment]
Actually, it's not true that so many servers run php 5.2. Any server running composer is using 5.3+.

Those servers using 5.2 are likely insecure, and indeed using 5.3 also. There are known un-fixed security vulnerabilities in both 5.2 and 5.3.

**Comment by GrahamCampbell** [comment]
Related:

http://blog.ircmaxell.com/2014/12/on-php-version-requirements.html
http://blog.ircmaxell.com/2014/12/being-responsible-developer.html
http://blog.ircmaxell.com/2014/12/php-install-statistics.html

We should not be encouraging irresponsibility, or at worse, total negligence.

**Comment by garex** [comment]
@GrahamCampbell droppin out something stable that people use on many real-world systems just because you couldn't resolve build problem on new system is a huge irresponsibility.

WordPress real stats of PHP versions popularity gives 5.2 version 1st place. TRavis is a CI. CI is not for experiments it's for INTEGRATION. Integration means old with new, v1 with v2 and etc.

Just because we can't figure out something somewhere — is not a reason for completely drop version support. I'm just in shock! FAcepalm..

**Comment by BanzaiMan** [comment]
@garex The decision was mine, and it was driven by my inability to make it work. I explained what I tried in the comment above. We still have an old image that has 5.2.17. Rolling back is still an option, but it will also mean dropping the recent updates. http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#PHP-VM

**Comment by GrahamCampbell** [comment]
> droppin out something stable

It's insecure.

**Comment by garex** [comment]
@GrahamCampbell 

> It's insecure.

On a realworld production system — yes. On a CI hosts, where each time we have fresh system from start — it's not place where we need security. It's a CI!

It's similar to write 100 tests for app, then after some changes in code just drop out 1st 10 tests, because we just a little lazy.

**Comment by GrahamCampbell** [comment]
> where each time we have fresh system from start

Is that true for the container builds still?

**Comment by garex** [comment]
@GrahamCampbell  How containers/non-containers related with security?

**Comment by GrahamCampbell** [comment]
I don't know the full extent of the vulnerabilities in php - I've never really cared since I only support php 5.4 in all the libraires I maintain, and use 5.5/5.6 in production. I hope the wouldn't compromise the host os, but I'm not an expert.

**Comment by garex** [comment]
@GrahamCampbell after latest ghost and heartbleed vulnerabilities are you seriously thinking, that php version is a serious blocker? I dont'. And even if we think that having latest versions of some lang is good to have (just looks at those slides by Rasmus), it's our own choice.

But there are other people, that have more serious tasks — they are creating content, supporting their sites, optimizing it and etc. PHP version upgrade will not solve their actual problems — it's worth $0 for them. It will not get new customers or visitors. It will not helps them in any way. And main problem here is that most popular sites tends to have most old versions of software. Just because they were created not yesterday. And they are generating money — not something built from latest edge versions.

Also pls remember that edge versions is not always good — they have more bugs than stable versions. Just because they are new and untested.

**Comment by GrahamCampbell** [comment]
php 5.4 is hardly an edge version. It's so old it's only getting security fixes now. Anyway, this is not the right place for this, and I'm done here anyway. We can't change each other's opinions. :)

**Comment by garex** [comment]
![pochemu-rebenok-plachet](https://cloud.githubusercontent.com/assets/77981/6138446/20fcb6aa-b1a3-11e4-8bdd-834549575b5a.jpg)

Yes. You are right. Im' just leave this caprice here too.

**Comment by BanzaiMan** [comment]
I've locked this issue, since the discussion is drifting in a wrong direction. If you have something constructive to add to this issue, please email us at support@travis-ci.com.

**Comment by BanzaiMan** [comment]
I'm working on bringing 5.2 back. I have some Extra Information™ that I didn't have before. No ETA, though.

**Comment by BanzaiMan** [comment]
See https://github.com/travis-ci/travis-cookbooks/pull/451

(I've locked the issue, so mentions from other issues, commits and PRs don't show up here.)

**Comment by BanzaiMan** [comment]
We'll be rolling out a new image containing 5.2.17 tomorrow around 15:00 UTC.

**Comment by BanzaiMan** [comment]
This is live. I'm closing this now.

If you see problems with 5.2.17, leave comments here.

**Comment by JDGrimes** [comment]
Thank you for reviving 5.2 for us, @BanzaiMan. 

It appears that this is working for traditional builds, but not the new container-based infrastructure. Will PHP 5.2 support be coming back for container-based builds?

**Comment by BanzaiMan** [comment]
That's weird. We rolled the new image out on the same day. I'll take a look Monday. Do you have a build log URL?

**Comment by JDGrimes** [comment]
https://travis-ci.org/JDGrimes/edd-sl-free

Thank you!

**Comment by JDGrimes** [comment]
This appears to be working for the container-based builds now.
