### ISSUE TITLE
dart: Add pub cache bin dir to PATH

### ISSUE THREAD

**Issue by seaneagan** [travis-ci/travis-ci#3176]
https://www.dartlang.org/tools/pub/cmd/pub-global.html#running-a-script-from-your-path

@a14n @devoncarew @sethladd

**Comment by a14n** [comment]
I didn't add `~/.pub-cache/bin` to the path because:

1. nothing in the current default build needs it.
2. adding `~/.pub-cache/bin` to the PATH is an opt-in in `pub` and I wanted to have the same behaviour.

I suppose you need this because you have a custom build ? In this case you can do that inside your custom tasks like in [dartdoc](https://github.com/dart-lang/dartdoc/blob/master/tool/travis.sh) for instance.

What do you think ?

**Comment by seaneagan** [comment]
Thanks for the quick response!  I don't *need* it, just thought it would make sense to do it here, so people don't have to repeat it, or think about it, in each of their travis scripts.  I think one reason why pub doesn't do it is because there is no official installer for dart, it's just a zip, so the dart sdk bin dir doesn't get added either.  The installer for nodeJS adds the npm bin PATH, and I think it would make sense for dart too.  The [chocolatey dart package](https://chocolatey.org/packages/dart-sdk) does it.  Also, If folks do run into a PATH conflict it's still pretty easy to avoid using e.g. `pub global activate grinder --no-executables` for the conflicting executable.
