### ISSUE TITLE
Include extensions in PHP nightly builds

### ISSUE THREAD

**Issue by colinodell** [travis-ci/travis-ci#3286]
#2480 added the ability to test against PHP 7 nightly builds.  These builds [do not include extensions](https://github.com/travis-ci/travis-ci/issues/2480#issuecomment-75988205) though, which are required for some projects.  (For example, https://github.com/thephpleague/commonmark requires the `mbstring` extension.)

Would it be possible to include [the standard extensions](http://docs.travis-ci.com/user/ci-environment/#Extensions) in those builds, or is there a method we can use to build them ourselves before running tests?

**Comment by BanzaiMan** [comment]
I looked at this in more detail. I *believe* that extensions on PHP nightly are now on par with other recent PHP versions (by way of using the same default options that php-build uses to build PHP runtimes), and that about half of PECL packages are installed.

I do not have the expertise to test them, though, so please use caution.

Exceptions to the PECL packages:

1. [memcached](http://php.net/memcached) fails to compile while looking for a file named `ext/standard/php_smart_str.h`.
1. [redis](http://pecl.php.net/package/redis) is not compatible with PHP versions above 5.
1. zmq yields lots of compilation errors.

**Comment by heiglandreas** [comment]
My last build of [Org_Heigl_Hyphenator](https://travis-ci.org/heiglandreas/Org_Heigl_Hyphenator/jobs/52189657) and [OrgHeiglFileFinder](https://travis-ci.org/heiglandreas/OrgHeiglFileFinder/jobs/52191134) showed that the curl and the mbstring-extension are missing.

**Comment by heiglandreas** [comment]
Seems to be OK now 8 hours later! Works as expected! At least mbstring and curl are now available!

**Comment by BanzaiMan** [comment]
[mongo](http://pecl.php.net/package/mongo) PECL package also fails to compile.

**Comment by BanzaiMan** [comment]
Upon further inspection, none of the [PECL extensions](http://docs.travis-ci.com/user/languages/php/#Preinstalled-PHP-extensions) works.

Rather than figuring out which ones can be compiled, I'm going to forget about PECL extensions altogether and let the users decide which ones to use with nightly. They may or may not succeed, but it is up to the users.

This has been documented.

As far as I know, there is nothing else to do on this ticket. At this point, if something is missing, it is most likely because it is not configured so with [php-build](https://github.com/CHH/php-build).

**Comment by colinodell** [comment]
Thanks!
