### ISSUE TITLE
segfault during R package checking doesn't lead to failed test run

### ISSUE THREAD

**Issue by craigcitro** [travis-ci/travis-ci#3305]
@hadley ran into this:
  https://travis-ci.org/rstats-db/RPostgres/builds/52423211

here `R CMD check` is clearly hitting a segfault while running tests, but travis doesn't error out. i've set up postgres in vagrant, and i can confirm that the `R CMD check` call **is** setting the exit status to 1. 

@BanzaiMan -- is there some situation where a command in `script` failing doesn't mark the run as failed? is the fact that we're running another command after this one as part of the `script` block (which *does* exit with `0`) the problem?

**Comment by BanzaiMan** [comment]
I believe that if you want the command to fail the build entirely, you'll need to pass `assert: true` here: https://github.com/travis-ci/travis-build/blob/cb1bcb2a97bf1102b2970d4c013bbf6ed091bf8d/lib/travis/build/script/r.rb#L132

Since there is not, build moves on to the next step, and the `script` phase exits cleanly when the last command (https://github.com/travis-ci/travis-build/blob/cb1bcb2a97bf1102b2970d4c013bbf6ed091bf8d/lib/travis/build/script/r.rb#L147-L148) returns 0.

**Comment by craigcitro** [comment]
aha -- perfect, that makes sense. PR coming in a sec.
