### ISSUE TITLE
Parameterized service hooks

### ISSUE THREAD

**Issue by kbrock** [travis-ci/travis-ci#3327]
For a single repo like rails, sometimes it is not necessary to run every node of a matrix.

Would it be possible to specify in the pull hook which nodes of the matrix would be necessary?

e.g.: when active record changes, it would create a request that says please build active record but not active support.

This would probably require people creating a separate service to properly generate a PR hook url with knowledge of the structure of the repo.

**Comment by joshk** [comment]
Hi @kbrock 

Sorry but this is not possible with service hooks.

The only other idea which comes to mind is to inspect which files are changed then determine the commands based on that, but even that is prone to issues due to AR using AS heavily.

I'm going to close this issue for now as the idea of Parameterized service hooks is not possible.

We will have a requests api soon, which will allow you to build something custom to do something similar to what you want.

Have a great day, and thanks for opening this.

**Comment by kbrock** [comment]
thanks @joshk
