### ISSUE TITLE
Setup fails, Switch request fails

### ISSUE THREAD

**Issue by tejasmanohar** [travis-ci/travis-ci#3335]
https://github.com/node-schedule/node-schedule/issues/92#issuecomment-77252959

>Looks like travis ci is erroring. The flip switches but the request made by flipping the switch fails, as seen by console error (chrome JS console when flipping switch on travis for this repo):
>
>XMLHttpRequest cannot load https://api.travis-ci.org/hooks/3635277. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://travis-ci.org' is therefore not allowed access. The response had HTTP status code 500.
>
>Going to make an issue on Travis CI for this

Can';t setup Travis CI. See above linked repo + the comment in blockquote.

**Comment by BanzaiMan** [comment]
@tejasmanohar Has the node-schedule organization turn on the trusted apps recently? If so, is Travis CI approved to access data?

**Comment by tejasmanohar** [comment]
@BanzaiMan Ah, it's now approved in organization settings. That said, there's now a yellow circle unlike green next to repo name on my repositories sidebar  in Travis. What does this indicate? build status is unknown

https://github.com/node-schedule/node-schedule

**Comment by joshk** [comment]
The yellow circle means that a build request from GitHub hasn't been received yet.

Closing this as the main issue is resolved now.

**Comment by MattiSG** [comment]
I got this too and it was indeed “organisation-approved third-party apps”… Pretty hard to figure out both the problem and how to fix it. Since I lost half an hour, I documented [how to regain access to Travis](http://stackoverflow.com/questions/28876137/how-to-allow-travis-ci-access-to-a-github-organisation-with-restricted-applicati/28876138) for future users  ;)
