### ISSUE TITLE
Build image incorrectly displays build error

### ISSUE THREAD

**Issue by pbrianmackey** [travis-ci/travis-ci#3349]
[My Project](https://travis-ci.org/pbrianmackey/ES6) incorrectly displays "Build Error" image.  The build is passing.  Build #12

**Comment by BanzaiMan** [comment]
This is a known issue with how badge image is updated. [Build #11](https://api.travis-ci.org/repositories/pbrianmackey/ES6/builds/53537378.json) finished 6 minutes after [Build #12](https://api.travis-ci.org/repositories/pbrianmackey/ES6/builds/53537769.json), so that it overwrote the badge. Rerun the build 12, and it should be updated to green.
