### ISSUE TITLE
Chrome does not work in sudo: false mode

### ISSUE THREAD

**Issue by lookfirst** [travis-ci/travis-ci#3354]
From issue #938:

Ok, without installing chrome, `no-sandbox` and DISPLAY commented out, chrome still crashes on the new arch:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53600350

uncommented no-sandbox and i get this:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53600788

and uncommenting `DISPLAY`, i get this:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53601000

Note that I added `env` before I set `DISPLAY` by hand:

https://travis-ci.org/lookfirst/systemjs-seed/jobs/53601000#L99

I can't install a newer chrome cause I don't have sudo. =(

**Comment by BanzaiMan** [comment]
Do you know what the problem is with the container? Is it the old version of Chromium? What is the version of Chromium required? The version we use come from the official Ubuntu PPA, which could very well be too old anyway (http://packages.ubuntu.com/precise/chromium-browser), so having a `sudo` may not save you (or have you already tested it).

You can try downloading from https://download-chromium.appspot.com/?platform=Linux_x64 into a directory under `$HOME` and manipulate your `$PATH` to use that version.

**Comment by lookfirst** [comment]
1. Chrome is too old
1. Missing DISPLAY (not necessary, but it was suggested by @joshk that it should exist)
1. No sudo (we need to be able to install software in these vm's, from packages)

**Comment by BanzaiMan** [comment]
If the newer version of Chromium is the answer, I suggest downloading it from the site above, and set up your environment.

**Comment by lookfirst** [comment]
Travis just broke my build, but it seems like it broke it just for node 0.12. Is that now running special in sudo: false and the rest aren't?

https://travis-ci.org/lookfirst/systemjs-seed/builds/55204335

**Comment by BanzaiMan** [comment]
I don't think so. There was a problem with downloading Chrome. https://travis-ci.org/lookfirst/systemjs-seed/jobs/55204336#L221

**Comment by lookfirst** [comment]
Ah, thanks!

**Comment by lookfirst** [comment]
Due to the recent change over to docker by default and the fact that it has an ancient version of chrome, this is what I'm using now...

```
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip
```
