### ISSUE TITLE
skipping coverity_scan builds

### ISSUE THREAD

**Issue by umlaeute** [travis-ci/travis-ci#3473]
i'm using travis-ci for a C++-project. the build-matrix is configured to run builds for

- linux (amd64)
- osx (amd64)
- osx (i386)

since the project is rather biggish, i would like to skip some of the builds when using the  coverity_scan module, in order to not overuse my quota.

my coverity quota only allows me to submit a single build (per day). since travis-ci automatically wants to run three builds, all but the 1st build fail due to over-quota.

first of all, i think that an coverity over-quota should **not** result in a **failed** build, as the build is actually *cancelled* automatically.

however, if the correct interpretation of over-quota is *failed*, then i would like to only have a single build submitted to coverity (e.g. the *linux* build; or just the 1st sub-job), and skip all others.

since there is no *easy* way to skip builds in the coverity_scan module, i followed the advice in #1975 and created my own [travisci_build_coverity_scan](/umlaeute/Gem/blob/coverity_scan/build/travis-ci/travisci_build_coverity_scan.sh) script that skips builds if they are not the 1st sub-job (`TRAVIS_JOB_NUMBER` does not end in `.1`).

unfortunately, after setting up everything and starting a test run, it turned out that this does not help at all, as the `coverity_scan` module performs some tests (including a *quota* test) **prior** to running the script (which performs *another quota* test).

so what is the correct way to (successfully) skip a coverity_build run?

**Comment by umlaeute** [comment]
and i wanted to add: i'm really looking for something to generically disable a build in the `coverity_scan` module, rather than having yet another exemption for (say) building with OSX (it seems that the solution for #1975 was actually to disable coverity_scan when `clang` was used; i would prefer if *I* could define what i wanted to submit to coverity)

**Comment by kulp** [comment]
> first of all, i think that an coverity over-quota should not result in a failed build, as the build is actually cancelled automatically.

Maybe my issue is slightly different (I don't want to skip the build, just skip Coverity Scan if the quota is full), but I agree with the statement by @umlaeute, and to my mind the issue could be renamed "don't check quota before running custom build_script". It is good that we can specify an arbitrary build_script_url ([for example, in my project](https://github.com/kulp/tenyr/blob/develop/.travis.yml#L64), with the [corresponding script](https://github.com/kulp/tenyr/blob/develop/scripts/travis-coverity-scan-build.sh#L53)), but since the quota is checked before the custom build script, one apparently cannot prevent a build from failing for quota reasons.

Shouldn't the custom-build script be run first, obviating the need for initial quota checks ?

**Comment by BanzaiMan** [comment]
Hi, @umlaeute,

As @kulp suggested, you can devise a build matrix in such a way that only one sets up coverity scan. You can see one here: https://github.com/kulp/tenyr/blob/9a3f3d85ba913aaeb342e482a2f9a239979602c7/.travis.yml#L73-L83

Please try it, and close this ticket if it works for you. Thanks.

**Comment by umlaeute** [comment]
kind of works (though clumsy, as you have to define each node in the matrix explicitly)
