### ISSUE TITLE
Build fails because it could not fetch apt files

### ISSUE THREAD

**Issue by vmalloc** [travis-ci/travis-ci#3497]
For example: `https://travis-ci.org/vmalloc/weber-frontend/builds/56278668`

The build fails because:
```
failed: [127.0.0.1] => (item=software-properties-common,python-software-properties,curl,wget,ca-certificates,libxml2-dev,libxslt1-dev,git,supervisor,python-setuptools,python-virtualenv,python-pycurl,python-dev,libevent-dev,libpq-dev,redis-server) => {"failed": true, "item": "software-properties-common,python-software-properties,curl,wget,ca-certificates,libxml2-dev,libxslt1-dev,git,supervisor,python-setuptools,python-virtualenv,python-pycurl,python-dev,libevent-dev,libpq-dev,redis-server"}
msg: Could not fetch updated apt files
```

**Comment by meatballhat** [comment]
@vmalloc Thanks for the report, and sorry about the delay.  I'm willing to bet this is due to the increasing connectivity issues we're seeing with rabbitmq.com, with your task failing during `apt-get update` (https://github.com/vmalloc/weber-frontend/blob/55d3903956cf67cb8a5d85090c701decd1c00b29/ansible/roles/common/tasks/main.yml#L6).  We're evaluating next steps and will be updating the incident here: http://www.traviscistatus.com/incidents/6xtkpm1zglg3
