### ISSUE TITLE
travis-build: env vars not properly escaped

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#3503]
Adding an env var through settings:

$ export FOO=LqwlPa)O&^?Wrf_c!3
/home/travis/build.sh: eval: line 41: syntax error near unexpected token `)'
/home/travis/build.sh: eval: line 41:`export FOO=LqwlPa)O&^?Wrf_c!3'

It seems vars are not properly escpaed?

**Comment by nazar-pc** [comment]
When add value surrounded with quotes, meaning `"LqwlPa)O&^?Wrf_c!3"` everything works as expected.
Might be a solution to check if value is not alphanumeric and not surrounded with single or double quotes - do that automatically.

**Comment by joshk** [comment]
Sounds like we should be adding `" "` by default.

@henrikhodne @meatballhat @BanzaiMan thoughts?

**Comment by henrikhodne** [comment]
This is similar to the caveat we've always had with `travis encrypt` and other env vars. If we want to allow things like `${ENV_VAR}`, we can't escape the environment vars. We could maybe have a checkbox next to the env var field that denotes whether the env var should be exported as-is and expanded, or if it should be escaped.

If we do escape it, we should use [shellwords](http://ruby-doc.org/stdlib-2.2.1/libdoc/shellwords/rdoc/index.html) instead of just surrounding it in quotes.

**Comment by meatballhat** [comment]
^--- Yes this :+1:

**Comment by brabster** [comment]
Adding a checkbox or some documentation (maybe it only shows if you have non-alphas in the field?) sounds like a useful step, I can imagine I will forget to do this on a regular basis.

**Comment by cben** [comment]
dup of #2477 ?
