### ISSUE TITLE
Support for multiple .travis.yml files

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#3540]
Is there any plan to support multiple `.travis.yml` files within one repos? Currently my repos is laid out as:
```
/
  s1/
  s2/
  s3/
  ...
  .travis.yml
```
where s1,... are various microservices. Right now I have to cram all of the settings for all services into the one travis file.

There seems to be a trends toward monorepos such as Google and [now Facebook](http://gregoryszorc.com/blog/2015/03/28/notes-from-facebook%27s-developer-infrastructure-at-scale-f8-talk/) so having the ability to specify different configs within one repos is important.

**Comment by BanzaiMan** [comment]
I think this has been requested before, though I can't find specific issues.

One problem I see is that we do not know ahead of time where `.travis.yml` might be, so we need to check out the entire repository before processing the build (or is there a GitHub API calls that allow this inexpensively?).

**Comment by cancan101** [comment]
I could not find an existing issue either.

I guess there are a few questions here. Would the user set up in advance each of the subdirectories to build against (and in which to find a `.travis.yml` or would that be discovered)? 

If in advance, then this could be used: http://schacon.github.io/git/git-read-tree.html#_sparse_checkout.
If discovered then there would be something in the root of the repos that points to the list of other `.travis.yml`s.

**Comment by humzashah** [comment]
@BanzaiMan A solution could be to have a base yml where paths of the other ymls (the ones in the sub-repos) will be explicitly set.

@cancan101, I was brought here because I was googling for something similar. I've now spread out my "services" into individual repos that I add to the original project as git submodules. This helps not only to isolate tests, logic, etc. but also to ensure that a test-failure would mean the failure of a submodule and not of the entire project, thereby saving test execution time, amongst other things.

**Comment by johanatan** [comment]
Is there any alternative to creating submodules for this?

**Comment by joshk** [comment]
Thank you for opening this issue to discuss the idea.

I'm sorry but I am going to close this issue for the time being as we don't have plans to add multi `.travis.yml` file support, at least for the foreseeable future.

Have an awesome weekend

Josh

**Comment by roidrage** [comment]
Thank you for your suggestion, but I'm closing this issue for now, as we have no immediate plans to add this feature.

Should we add it to the roadmap eventually, we'll make sure to update this ticket.

**Comment by therealplato** [comment]
This ticket was one of the first results for my search `travis only modified subfolder`. Similar to OP i have a monorepo with multiple services and languages. I'd like to find something better than "test every service on every push." Since 2015 has the community come up with a workflow for testing one monorepo service at a time?

**Comment by CallumHogg** [comment]
@therealplato The best I've come up with for the time being is conditionally running test suites based on the output of git diff e.g. `if git diff --name-only HEAD^ | grep "API/"; then npm run test-api; fi` so it will only run my API tests when something in the API folder changed.

**Comment by markeissler** [comment]
Because of this opinion [Status badge for each OS of a build](https://github.com/travis-ci/travis-ci/issues/4623) (#4623)

> We prefer to view a build as a whole, with the status badge being an indicator, and the build's matrix results being the single source of truth. @roidrage 

It would be helpful if we could at least use separate `.travis.yml` files (one for each build target) and then just specify the name of the specific`.yml` file for a build in the build settings (defaulting to the standard `.travis.yml` file).

For instance, for a project that targets both macOS and Linux you could have a standard `.travis.yml` for the Linux build and then also a `.travis-macOS.yml` for the other build. That way we can accurately provide status badges for different builds.

While it's obviously possible to configure multiple builds in a matrix defined in a single configuration that lumps all of the builds together with a single overall status that workflow clearly doesn't work for everyone.

**Comment by napalm272** [comment]
Any updates on this?

**Comment by kurianbenoy** [comment]
Is this feature now supported?

**Comment by MalteMagnussen** [comment]
I have one large repo as well, with multiple projects inside. How do I set up Travis for that, or will I have to split my projects that use Travis into their own repositories?

**Comment by szeitlin** [comment]
Same. I voted up all the comments above and would really like to see better support for this use case.

**Comment by tmjeee** [comment]
Would love to see this feature. I'm having a single repos with subfolder for each modules eg. front-end, back-end, e2e, cypress-testing, etc.

**Comment by ericsysmin** [comment]
GitHub Actions supports this type of stuff now so is there any plan yet for Travis-CI to so it can compete?

**Comment by TheBadong** [comment]
> GitHub Actions supports this type of stuff now 
How would you set it up with GitHub Actions ?

**Comment by jleonard-r7** [comment]
`paths:`
