### ISSUE TITLE
Node-js version set on travis.yml is ignored

### ISSUE THREAD

**Issue by edmundoa** [travis-ci/travis-ci#3661]
Hello,

We have a branch in our repo that doesn't work with the latest node (0.12), so we pinned the node version to `0.10` on the `.travis.yml` file. After a couple of weeks without commits on that branch, we found out earlier today that this is not working any more. The worker has now only the newest node installed, so the build is failing all the time.

Here is the head of our `.travis.yml` file (whole file [here](https://github.com/Graylog2/graylog2-web-interface/blob/1.0/.travis.yml)):
```
language:
  - java
  - node_js
jdk:
  - oraclejdk7
  - oraclejdk8
node_js:
  - "0.10"
```

This is the information build system information from the worker (whole log [here](https://travis-ci.org/Graylog2/graylog2-web-interface/jobs/58455580)):
```
Pre-installed Node.js versions
v0.12.2
```

Could you give us a hand with that?

Thank you.

**Comment by BanzaiMan** [comment]
`language` is not a build matrix key, so only the first one is considered. Consequently, `node_js` is ignored.

We updated the build environment to have Node.js 0.12.2 (http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/), so your builds fail. If you want to force 0.10.x, you can invoke `nvm use 0.10` in your build script.

(We'll roll back the current update due to a different issue, but at some point in the future the default Node.js version will change and your build will start to break if the configuration is left alone.)

**Comment by edmundoa** [comment]
Oh, I didn't know that :)

Thank you for your help, will try to use nvm then.
