### ISSUE TITLE
Storing Build Cache Much Slower Today

### ISSUE THREAD

**Issue by cancan101** [travis-ci/travis-ci#3675]
Compare:
```
30.55s
store build cache
change detected: /home/travis/.cache/pip/http/0/1/d/2/7/XXXXX2eea37d6fbd3ef73af95d7b964f702cb89a77b4520XXXXXX
changes detected, packing new archive
uploading archive
```
to:
```
6.03s
store build cache
change detected: /home/travis/.cache/pip/http/0/1/d/2/7/0xxxxd2eea37d6fbd3ef73af95d7b964f702xxx77b45201xxx1
changes detected, packing new archive
uploading archive
```

**Comment by BanzaiMan** [comment]
How big are the caches?

**Comment by BanzaiMan** [comment]
Also, are the pip cache changes important? If not, you can clean it up with `before_cache` phase, and not upload the cache at all.

**Comment by cancan101** [comment]
I think this time changed on basically the same repository with the same requirements, etc.

I like the cache as it makes the install stage faster.

**Comment by BanzaiMan** [comment]
What I meant was that the updated part of the cache: `/home/travis/.cache/pip/http/0/1/d/2/7/XXXXX2eea37d6fbd3ef73af95d7b964f702cb89a77b4520XXXXXX`— is that important? The last path component seems random, and might mean that it is not essential to the "correctness" of the cache. If you can convince the caching utility to not upload the cache (because there is no critical changes to the cache), you can bypass this issue altogether.

If the time variance is happening in a short amount of time, then, I tend to think this is within margins of error.

**Comment by cancan101** [comment]
It seems like across the board the saving cache stage is significantly slower today.
