### ISSUE TITLE
APT whitelist request for gridengine

### ISSUE THREAD

**Issue by jakirkham** [travis-ci/travis-ci#3773]
It would be nice to have the basic gridengine dependencies to emulate an extremely small cluster for those of us, who have tests that rely on such an environment. This includes a few dependencies to get going namely the following `gridengine-common`, `gridengine-master`, `gridengine-client`, and `gridengine-exec`.

**Comment by cancan101** [comment]
I am having trouble using gridengine without sudo. This is how one user currently uses the package with sudo: https://github.com/pygridtools/drmaa-python/blob/5c157204b64384d3658063e4e4335474d42bb9b6/travis/install_sge.sh. 
The issue is that the `travis` user is not set up as a manager in the grid config so attempts to modify the cluster result in:
```
$ qconf -as localhost
denied: "travis" must be manager for this operation
```

Looking closely at the install logs:
```
Setting up gridengine-master (6.2u5-4) ...
Initializing cluster with the following parameters:
 => SGE_ROOT: /var/lib/gridengine
 => SGE_CELL: default
 => Spool directory: /var/spool/gridengine/spooldb
 => Initial manager user: sgeadmin
...
Adding user sgeadmin as a manager
```

**Comment by jakirkham** [comment]
@cancan101, sorry, I had meant to open another issue regarding this, but hadn't done so. Would you like to do the honors?

**Comment by jakirkham** [comment]
Also, I have a Docker container here for Ubuntu that may give some pointers as to how this would need to work ( https://github.com/jakirkham/docker_ubuntu_drmaa_conda ).

**Comment by cancan101** [comment]
Done #4524.
