### ISSUE TITLE
language: cpp doesn't respect compiler in build matrix

### ISSUE THREAD

**Issue by mikemorris** [travis-ci/travis-ci#3871]
Setting `language: c` with `compiler: clang++-3.5` will `export CC=clang++-3.5` as I would expect, but with `language: cpp` the `compiler` I set in the build matrix is ignored, and the following happens instead:

```
export CXX=clang++
export CC=clang
```

Even setting `CXX=clang++-3.5` in the build matrix `env` doesn't work, as the defaults are exported AFTER exporting `env` from the build matrix.

Working around this requires either setting `language: c` for a C++ project and `CXX=clang++-3.5` in `env`, or keeping `language: cpp` but resorting to [a hack to properly set the compiler later on in the build script](https://github.com/mapbox/pbf.hpp/blob/master/.travis.yml#L45).

Refs #979

**Comment by weitjong** [comment]
If you looked at this implementation file (https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/cpp.rb) for ```cpp``` language then you will understand why it happens. Not sure what is (was) the intention here where it sanitizes the ```compiler``` string. There is no extra benefit in doing so because user could execute any "harmful" command in the VM directly instead of stuffing it into ```compiler```. Just my two cents.

As for the workaround, I think you can try ```alternatives``` package to create a ```/usr/bin/clang++``` symlink pointing to ```clang++-3.5``` executable. Or just create the symlink manually if you know what you are doing.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-ci/issues/5293#issuecomment-165674622

**Comment by billyquith** [comment]
I tried setting `COMPILER`, which seems to be ignored by Travis. It isn't passed onto `CXX`. The only way I could specify the compiler was to pass `COMPILER` as an argument to my build file generator.

C++1y support could do with a bit of effort in Travis. This seems like an easy fix.
