### ISSUE TITLE
Maven build failing due to permgem limits set in /etc/mavenrc

### ISSUE THREAD

**Issue by olivermay** [travis-ci/travis-ci#3893]
Hi, 

Our maven builds are failing, is looks like our maven options get overwritten by the configuration in /etc/mavenrc (set from https://github.com/travis-ci/travis-cookbooks/blob/792db17b1fcfb2c46db95bf6b1e7b60714802890/ci_environment/maven/attributes/default.rb#L26)

Our open source project needs more permgen than 192m. A solution for this is to: 
sudo rm /etc/mavenrc in the travis.yml file, but in this case we don't want to use sudo because of the container based environment.

cheers,

Oliver

**Comment by BanzaiMan** [comment]
Does maven have a command line option or a setting in `pom.xml` that can override these settings?

**Comment by oliverm-be** [comment]
Not in the `pom.xml` no, it *might* be possible to pass them to the command line (not sure), but then the options will not get picked up by any forked maven processes.

I created a small test project that demonstrates the behaviour:
The line in `.travis.yml`: https://github.com/oliverm-be/maven-travis-test/blob/master/.travis.yml#L4
The result in the travis build: https://travis-ci.org/oliverm-be/maven-travis-test/builds/62366283#L280

**Comment by oliverm-be** [comment]
I ran another test with the travis.yml file, the global `mavenrc` get overwritten by a local `~/.mavenrc` file. So this problem can be avoided by adding:
`"echo \"export MAVEN_OPTS='-Dmaven.repo.local=$HOME/.m2/repository -Xmx2g -XX:MaxPermSize=2048m'\" > ~/.mavenrc"`
to the 'travis.yml' files before_install section.

**Comment by mkristian** [comment]
i use
```
before_script:
  - export MAVEN_SKIP_RC=true
```
in order to use mvn-3.3.x via maven-wrappers (not sure if there is another way now to use maven-3.3.x)

**Comment by BanzaiMan** [comment]
Perhaps we should remove `/etc/mavenrc` altogether.

**Comment by gliptak** [comment]
@BanzaiMan Can one select Maven versions (like running with selected Java JDK version)? Thanks

**Comment by BanzaiMan** [comment]
@gliptak That is not possible.

**Comment by gliptak** [comment]
@BanzaiMan In that case removing defaults, effecting (incorrectly) versions a user have to install, sounds desirable ...

**Comment by patrickpilch** [comment]
:+1: 
@BanzaiMan I've also just experienced an issue where forked JVMs from maven-invoker-plugin were not getting the appropriate `mavenOpts` due to Travis's `/etc/mavenrc` overriding them. If removing `/etc/mavenrc` is possible, I would strongly support it. It's introducing environment specific configuration with no mention of it (that I could find) in the documentation.

**Comment by BanzaiMan** [comment]
I am thinking about copying `/etc/mavenrc` to `~/.mavenrc` and removing `/etc/mavenrc`. A desired outcome is such that the current configuration is preserved, but user-modifiable.

**Comment by gliptak** [comment]
@BanzaiMan Moving the default into user (editable) space likely allows for needed configuration overrides.

**Comment by patrickpilch** [comment]
@BanzaiMan While I'm not opposed to that change, I think @mkristian 's solution is the best mitigation for anyone experiencing issues with this, along with some appropriate `env` entries in `.travis.yml` to set `MAVEN_OPTS` and other env-variables necessary for your build.

I think the core issue here is that these overriding configuration values are not documented anywhere. These files are meant to be user/environment specific configurations - and therefore should be avoided. I believe the goal of any build is to be as reproducible as possible on any platform, so that would include specifying things like heap size in the surefire arguments, etc right in the `pom.xml`. And when not possible, Travis environment variables will do the trick. It'll accomplish the same thing as `mavenrc`, just more explicitly and would lead to less surprises in my opinion.

I understand the difficulty of making a change to this though, in order not to break existing builds depending on the heap and permgen configurations set in the current `mavenrc`. So perhaps at a minimum something about this can be mentioned in the documentation?
