### ISSUE TITLE
Can no longer run `git commit ...` during test

### ISSUE THREAD

**Issue by asottile** [travis-ci/travis-ci#3909]
A couple of my projects rely heavily on testing their integration with git.

The latest I know this worked was approximately six days ago: https://travis-ci.org/pre-commit/pre-commit/builds/62017379

I am using (in my setup):

```yaml
# Special snowflake.  Our tests depend on making real commits.
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
```

Which worked wonderfully before.

Now I am getting errors which look like this when running `git commit` inside my tests: https://travis-ci.org/pre-commit/pre-commit/jobs/62864634

```
E           CalledProcessError: Command: ['git', 'commit', '-m', 'Add hooks']
E           Return code: 128
E           Expected return code: 0
E           Output: (none)
E           Errors: 
E               
E               *** Please tell me who you are.
E               
E               Run
E               
E                 git config --global user.email "you@example.com"
E                 git config --global user.name "Your Name"
E               
E               to set your account's default identity.
E               Omit --global to set the identity only in this repository.
E               
E               fatal: empty ident name (for <travis@testing-worker-linux-bb3654bb-1-13722-linux-18-62864634.(none)>) not allowed
```

I've tried this with both `sudo: true` and `sudo: false`

I also tried adding global environment variables for `GIT_(AUTHOR|COMMITER)_(EMAIL|NAME)` which had no effect either.

**Comment by BanzaiMan** [comment]
Can you try creating a new branch off master (from [this commit](https://github.com/pre-commit/pre-commit/commit/a875231be3b89c1803237a336e3b11b60d8ddc9b)) and see if it passes? If it does, [this commit](https://github.com/pre-commit/pre-commit/commit/ad6b75040dbf33388e9e61238936f0622636df09) is most likely to blame.

**Comment by asottile** [comment]
@BanzaiMan this is exactly master: https://travis-ci.org/pre-commit/pre-commit/builds/62863915

The tests pass locally

**Comment by BanzaiMan** [comment]
Interesting.

Looks like the dependency changed during the 6 days between https://travis-ci.org/pre-commit/pre-commit/builds/62017379 and https://travis-ci.org/pre-commit/pre-commit/builds/62863915. In particular, the failing build installs [`pluggy-0.3.0`](https://travis-ci.org/pre-commit/pre-commit/jobs/62863916#L115) that the previous one does not. I don't know what it does, but it might have something to do with the failure.

If you'd still need help, we can spin up a debug VM for you. It would run on the standard infrastructure (instead of the containers that your build runs on), but I believe the build script would behave the same way.

**Comment by asottile** [comment]
Ah, seems to be tox's fault... Thanks for the pointer in the right direction!
