### ISSUE TITLE
Bundler not found for ruby-head on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#3985]
`ruby-head` has been updated to a recent version, but it doesn't have Bundler installed out of the box.

https://travis-ci.org/BanzaiMan/travis_production_test/builds/64605766#L88

**Comment by eregon** [comment]
It seems due to openssl, for instance if trying to compile locally on OS X with just
```
autoconf
./configure --prefix=...
make
```

The configuration of `openssl` fails with:
```
configuring openssl
Ignore OpenSSL broken by Apple.
Please use another openssl. (e.g. using `configure --with-openssl-dir=/path/to/openssl')
Failed to configure openssl. It will not be installed.
```

Which is definitely a problem for any `https` interaction, crypto stuff, etc.

One way to fix it is to install a local openssl (I thought rvm did but not sure) or use Homebrew and then configure with:
```
./configure --prefix=... --with-openssl-dir=/path/to/openssl
```
But of course that openssl should be available on all VMs using that compiled ruby.

**Comment by eregon** [comment]
Any news on this?
ruby/rubyspec works on ruby-head now since Bundler is no more used, but [there are](https://travis-ci.org/ruby/rubyspec/jobs/68520006) quite a few issues with apparently some Digest classes not defined.

**Comment by BanzaiMan** [comment]
Superseded by #5578.

https://github.com/travis-ci/travis-ci/issues/5578#issuecomment-180445244 shows a workaround:

```yaml
before_install:
  - gem install bundler
```
