### ISSUE TITLE
Add 'nightly' channel as a valid mono version 

### ISSUE THREAD

**Issue by alfhenrik** [travis-ci/travis-ci#3997]
I'm currently developing an aspnet5 application and building it with travis-ci, due to a couple of bugs in latest mono version 4.0.1 the build fails. These bugs have been fixed in a newer version (4.3.0) of mono that is available on the nightly mono feed (deb http://download.mono-project.com/repo/debian nightly main). 

I currently have a workaround for it (not the prettiest, but it works):
```
install: 
 - echo "deb http://download.mono-project.com/repo/debian nightly main" | sudo tee /etc/apt/sources.list.d/mono-nightly.list
 - sudo apt-get update
 - sudo apt-get install mono-complete
```

It'd be nicer if I instead could do the following:
```
mono:
 - nightly
```

The functionality is already there for the `alpha` and `beta` channels, but this isn't currently possible with the `nightly` channel as it's not considered a [valid mono version](https://github.com/travis-ci/travis-build/blob/55ce40d104e519503e67f37f61c7af936a9a6762/lib/travis/build/script/csharp.rb#L105).

cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Just curious, did you try with the alpha version? I know there've been some fixes that make aspnet5 less painful there.

Other than that, good idea :) When I added the alpha/beta feeds there was no nightly feed so that's why it's missing. Strictly speaking it's currently a [weekly feed](http://www.mono-project.com/docs/getting-started/install/weekly-packages/) (the exact naming isn't fixed yet afaik) so I guess we might want to be consistent with the naming here.

Feel free to send a PR for the changes to travis-build if you want and I'll coordinate testing with the Travis folks.

**Comment by alfhenrik** [comment]
I tried both alpha and beta and both those installed version 4.0.1...
Alpha channel: https://travis-ci.org/alfhenrik/JabbRv2/builds/64870404
Beta channel: https://travis-ci.org/alfhenrik/JabbRv2/builds/64871169

Yea, the naming could be weekly instead of nightly to keep consistency...I'll see if I'm brave enough to venture into the land of Ruby ;)

**Comment by alfhenrik** [comment]
FYI

I am working on a PR for this :)
________________________________
