### ISSUE TITLE
Leading spaces in front of language and node_js keys are preventing redis-server from running

### ISSUE THREAD

**Issue by cotsog** [travis-ci/travis-ci#4025]
Hi,

I found out that if there are leading whitespaces in front of the `language` and `node_js` keys in the `.travis.yml` file then it will prevent redis-server from running.

Yet when I lint the `.travis.yml` file on the Travis CI linter, everything looks fine.

You can see the problematic file [here](https://github.com/cotsog/config-persistence/blob/master/.travis.yml).

And failing build log [here](https://travis-ci.org/cotsog/config-persistence/builds/65406456).

I'm not sure if you are linting the `.travis.yml` file before running the build, if so it would be nice to detect those leading spaces as an error. Also I don't know what the YAML spec says about leading spaces in front of keys.

Let me know if you need more information.

**Comment by BanzaiMan** [comment]
This looks like a YAML specification problem, where white spaces are significant. Because of the leading white spaces, only the first two key-value pairs are recognized and the rest are dropped. You can see this happening in any YAML parser. For example, try http://yaml-online-parser.appspot.com/.

I am not sure if we can do much about this, since it is a valid YAML file, even though it is not what you intended.

**Comment by cotsog** [comment]
Ok, but it would be nice if there could be at least a warning saying something like:

`The following build directives were ignored because of indentation: [list of ignored directives]'.

**Comment by BanzaiMan** [comment]
Sorry, but YAML parser cannot detect that.

**Comment by BanzaiMan** [comment]
I am closing this, since there is not much to do here.
