### ISSUE TITLE
mono 4.0.1.44 and xunit 2.0

### ISSUE THREAD

**Issue by kspearrin** [travis-ci/travis-ci#4045]
The latest version of mono supports a fix for xunit 2.0:

- https://github.com/mono/mono/pull/1654

I tried using the latest mono version (4.0.1.44, which has this fix), however, travis ci doesn't seem to recognize it:

- https://github.com/kspearrin/MongoRiver.NET/blob/master/.travis.yml
- https://travis-ci.org/kspearrin/MongoRiver.NET
- https://github.com/mono/mono/releases/tag/mono-4.0.1.44

Please add support for the latest versions of mono so we can begin using xunit 2.0.

Thanks.

/cc @joshua-anderson @akoeplinger @nterry

**Comment by Joshua-Anderson** [comment]
It's a little counterintiative, but mono `4.0.0` is what you want, it actually points to mono `4.0.1.44`.  You can also use `latest`, `beta`, `alpha`, or `nightly`, to point to more current versions of mono.

**Comment by akoeplinger** [comment]
Btw. I don't think the xunit fix made it into 4.0.1.44, are you sure about that?

**Comment by kspearrin** [comment]
@akoeplinger According to the PR that I linked, it was merged into master on May 15. `4.0.1.44` was released on May 24.

I have tried `latest` (which I guess should work) and am still getting failures.

https://travis-ci.org/kspearrin/MongoRiver.NET/builds/65667950#L1050

```
$ mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./src/MongoRiver.Tests/bin/Release/MongoRiver.Tests.dll -trait "Build=Runnable"

xUnit.net console test runner (64-bit .NET 4.0.30319.17020)

Copyright (C) 2015 Outercurve Foundation.

Discovering: MongoRiver.Tests

System.TypeLoadException: Could not load type 'Xunit.Sdk.XunitTestFrameworkDiscoverer, xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'.

The command "mono ./packages/xunit.runner.console.*/tools/xunit.console.exe ./src/MongoRiver.Tests/bin/Release/MongoRiver.Tests.dll -trait "Build=Runnable"" exited with 1.
```

I do see that it is loading `4.0.1.44` for mono install now though.

**Comment by akoeplinger** [comment]
@kspearrin `master` is the development branch and is generally way ahead of the official releases, i.e. we're at v4.3 right now. For Mono 4.0, bugfixes now need to first make it into https://github.com/mono/mono/commits/mono-4.0.0-branch and from then on through QA before they hit another release (which means passing through alpha/beta channels). The xunit fix didn't make it in there yet.

You can try `nightly`, which is built directly off of `master` and should work fine (though it may break without notice since it's, well, a nightly build).

**Comment by kspearrin** [comment]
Great. Sorry for the misunderstanding. Thanks for the clarification!
