### ISSUE TITLE
CSC: error CS0518: The predefined type `System.Object' is not defined or imported

### ISSUE THREAD

**Issue by hahoyer** [travis-ci/travis-ci#4076]
Get Errors like "CSC: error CS0518: The predefined type `System.Object' is not defined or imported".
See: https://travis-ci.org/hahoyer/reni.cs/builds/66496588

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@hahoyer There are a two issues here:

> Unable to find framework corresponding to the target framework moniker '.NETFramework,Version=v4.6'. Framework assembly references will be resolved from the GAC, which might not be the intended behavior.

Travis uses Mono to build C# projects and Mono doesn't ship the .NET 4.6 profile since it is not yet released and still in preview

> warning : Could not find project 
file /usr/lib/mono/xbuild/Microsoft/VisualStudio/v/VSSDK/Microsoft.VsSDK.targets, to import.

Mono doesn't ship the Visual Studio SDK. There are [NuGet packages](https://www.nuget.org/profiles/VisualStudioExtensibility) that might have what you need, but I've never used them so not sure if they're sufficient.

**Comment by tim-cools** [comment]
Locally I solved this problem by setting the mono TargetFrameworkVersion to v4.5 manually. Mono 4.5 supports the C# 6 syntax already... (Except for one line of code I had to change)

`xbuild /p:Configuration=Release src/Soloco.ReactiveStarterKit.sln /p:TargetFrameworkVersion="v4.5"`


On Trevis I get a CSC: error CS0041: Unexpected error writing debug information -- 'The requested feature is not implemented.'

**Comment by akoeplinger** [comment]
@tim-cools the error you're getting is because you're using Microsoft's new Roslyn C# compiler (which is brought into your project via some NuGet package) and it doesn't support writing debug information (.pdb files) on non-Windows platforms yet.

You can turn off debug symbols by passing `/p:DebugSymbols=False` in your build script.

**Comment by tim-cools** [comment]
@akoeplinger thanks for the feedback, works like a charm!

**Comment by vatioz** [comment]
Thanks for this thread, actually `/p:TargetFrameworkVersion="v4.5"` helped me to run mine C# 6 build successfully.

**Comment by Phrohdoh** [comment]
@tim-cools Could you share your travis.yml for Roslyn builds?

**Comment by hahoyer** [comment]
https://github.com/hahoyer/reni.cs/blob/master/.travis.yml

**Comment by tim-cools** [comment]
@vatioz I use a build script that I run from Travis

https://github.com/tim-cools/RealTimeWeb.NET/blob/9c48b77403e52f07009347691a2f1b51448912cf/scripts/build.sh

https://github.com/tim-cools/RealTimeWeb.NET/blob/9c48b77403e52f07009347691a2f1b51448912cf/.travis.yml

Please note that the travis build for the github project is broken now because I migrated this to dnx. I still need to fix this...

**Comment by Merwer** [comment]
For anyone that comes across this and is using visual studio (I've been trying to solve this for hours), you can turn off the generation of PDB files by opening the properties for the csproj file; selecting the "build" tab; opening the "Advanced" modal; and selecting "Debug Info: None".
