### ISSUE TITLE
let encrypted env vars available to PR if the build has been restarted by the owner

### ISSUE THREAD

**Issue by sarbbottam** [travis-ci/travis-ci#4079]
Is it possible to let the encrypted environment variables available to Pull Request build, if it has been **restarted** by the owner/collaborator of the main repo?

---

The motivation is to run the PR build against Sauce Labs w/o exposing the Sauce Labs credential. 
There could be two build configurations, one that run against Sauce Labs and one that run against PhantomJS.

If the current build is a Pull Request and not started by the owner/collaborator of the main repo, build configuration against PhantomJS will be used or otherwise.

```js
var buildConfigFile = 'karma.conf.sauce.js';
if (process.env.TRAVIS_PULL_REQUEST && process.env.TRAVIS_STARTED_BY_EXTERNAL)  {
    buildConfigFile = 'karma.conf.phantom.js'; 
 }
```
Can there be a `boolean` environment variable called `TRAVIS_STARTED_BY_EXTERNAL`?

**Comment by BanzaiMan** [comment]
I don't think this is a good idea. There are many ways that seemingly innocent PR can expose secrets.

As for Sauce Labs credentials, we are working on getting the JWT addon out soon. (See https://github.com/travis-ci/travis-build/pull/356 & https://github.com/travis-ci/travis-core/pull/418.)

I'm going to close this for now, since there are other similar tickets exist, and the primary use case proposed is addressed elsewhere.
