### ISSUE TITLE
Consider adding `--recursive` to git `submodule update` by default

### ISSUE THREAD

**Issue by svenfuchs** [travis-ci/travis-ci#4099]
Is there a reason why we do not install git submodules recursively? 

https://github.com/travis-ci/travis-build/blob/18bd04e965b9bfaa49cd6bdcd8dcb1513b8d2fcd/lib/travis/build/git/submodules.rb#L12

**Comment by BanzaiMan** [comment]
What are possible downsides? I don't use submodules, so I can't comment on what could go wrong.

**Comment by Cocoanetics** [comment]
+1

I just lost several hours over this wondering why a sub-sub-sub-module wasn't there on Travis when all the while the build worked on my local machine.

**Comment by noporpoise** [comment]
+1

**Comment by vessi** [comment]
+1
for example, I'm using `mongo-c-driver` as a dependency for my project and it has `libbson` as submodules, so overall project fails to compile without fetching submodules recursively.

**Comment by Seanmatthews** [comment]
+1

**Comment by jcelerier** [comment]
+1 - or, better, just do `git clone --recursive -j2`

**Comment by BanzaiMan** [comment]
Is it still an issue? `--recursive` was added back in April. https://github.com/travis-ci/travis-build/commit/3a5e9844998549b64598625a2bc3e66ba90fa202.

**Comment by BanzaiMan** [comment]
I think we can close this. `-jN` for some `N` might be useful, but I'll hold off on that for now.

**Comment by gsauthof** [comment]
In case somebody runs into build errors due to this changed default - you can switch back to non-recursive submodules updates via putting something like this into your `.travis.yml`:

    git:
      submodules: false

    before_install:
      - git submodule update --init

background: sometimes you really just need the submodule itself and not the recursive ones. Even more so when a submodule references submodules that aren't available in the CI environment (e.g. when referenced via ssh URLs).
