### ISSUE TITLE
Build pipelines

### ISSUE THREAD

**Issue by nilswloka** [travis-ci/travis-ci#413]
``` gherkin
Feature: Build pipelines

  As a developer,
  I want to be able to set up build pipelines in Travis CI
  so that I can implement Continuous Delivery patterns

  Background:
    Given a project
    And build step A for that project
    And a dependent build step B for that project

  Scenario: Success triggers next step
    When build step A succeeds
    Then build step B is triggered

  Scenario: Failure does not trigger next step
    When build step A fails
    Then build step B is not triggered
```

**Comment by danielbodart** [comment]
Anyone solved this in a way that doesn't cause lots and lots of duplication?

I.e I currently have 10-20 open source projects and multiple branches and multiple stages in my pipelines. Currently I use TeamCity and am trying to migrate to Travis. All my projects have similar stages but each stage knows nothing about the stage before.

I don't mind that Travis has a lot less features but I do mind duplication. All stages are in separate GitHub repositories. Currently the best I can come up with is to make the main repository have git submodules for all the stages and make travis iterate through all the submodules. 

The next problem is then when someone forks my project and uses travis to build their fork, again the best I can come up with is make the travis build require certain secure variable and only try and say upload to bin tray is that parameter is there.

This all seems fine with only a single project but with many that's a lot of duplication in each project. It also breaks the Unix philosophy of small reusable tools composed together as I can't think of a way of having have the main build be just what it should be: A function that takes sources files and converts into a binary.

Anyone managed to do this at scale (many projects) without duplication? 
Any one done this another way than submodules? 
Anyone know of another way to trigger travis other than GitHub hooks?

**Comment by joshk** [comment]
Hi @danielbodart 

Thanks for the information. It is best to email support about this as closed issues easily get missed.

We are working on a proper build pipeline solution, but this will still be found to one repo instead of shared pipelines.

I can talk to the team about pipelines which span multiple projects, but I don't have an ETA for this sorry.

Thanks a bundle.

Josh

**Comment by smiller171** [comment]
I think that there is a real advantage of a build pipeline if you need a manual confirmation before deploy, but not otherwise

**Comment by mklimuk** [comment]
@smiller171 I disagree, there might be little value from feasibility point of view (because we can do it using build steps and so on) but information about how your build/deploy process is really structured is valuable. Plus of course one might have manual steps with some kind of access rights management which would be a huge plus for bigger projects.

**Comment by smiller171** [comment]
@mklimuk I think for the purpose of travis the best place to put in manual steps is at a pull request.
