### ISSUE TITLE
Speed up by sharing initial setup

### ISSUE THREAD

**Issue by brauliobo** [travis-ci/travis-ci#4172]
All `before_install` and `bundle install` is ran for all the six tasks of https://github.com/noosfero/noosfero/blob/master/.travis.yml. Instead, they could run once and before all tasks, and then shared by them.

Is it possible that the VM created is firstly setup with this commands so that the tasks can start from there and share/save about 3-4mins for each task?

**Comment by BanzaiMan** [comment]
At the moment, each VM starts with a fresh state.

[Caching](http://docs.travis-ci.com/user/caching/) makes this less painful, but in order to use that for public repositories, you'd need to use [containers](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) by doing away with `sudo`. (See http://docs.travis-ci.com/user/apt/ to see if you can do that.)

We are looking at ways to improve this, but for now, with `sudo`, this is not possible.

**Comment by joshk** [comment]
Thanks for the feedback @brauliobo 

As each Job is it's own isolated VM, we are not able to share build environments at this time.

We do have some planning in the works to improve this in the future, but as this isn't on our roadmap or a priority, I'm going to close this for now. 

As @BanzaiMan suggested, caching should help with env setup.

Have a great day

Josh

**Comment by brauliobo** [comment]
thanks, will give it a try!
