### ISSUE TITLE
Travis-Worker: Always use bleeding edge software

### ISSUE THREAD

**Issue by SecUpwN** [travis-ci/travis-ci#4184]
Good morning @travis-ci, I am filing this Issue because we've noticed during development of our famous [Android IMSI-Catcher Detector](https://secupwn.github.io/Android-IMSI-Catcher-Detector/) that you apparently do not use the very latest tools on your machines, especially the Android SDK. This makes some of our Travis-CI checks fail when adding a pull request. Pretty uncool. **Solution:** Please implement some mechanism that enables your build machines to install the latest tools, Android SDK and dependencies *before* checking any pull requests. Thank you!

**Comment by joshk** [comment]
Hi @SecUpwN 

Thanks for the feedback.

We are currently focusing on more regular updates to the Build Environments so that the latest software is preinstalled.

Are you able to script the updating of build environment dependencies? eg. check if you are using the most bleeding edge, if not, update.

I'm going to close this issue for now as we are not planning to add bleeding edge updates for the time being.

Have an awesome day

Josh
