### ISSUE TITLE
Possible caching issue of conda packages

### ISSUE THREAD

**Issue by bsipocz** [travis-ci/travis-ci#4191]
We got weird failures of  ``photutils`` on travis that traced back to installing with conda an old versions of the package astropy, while a newer one is available. Following the same installation method on a linux box, indeed the newer version gets installed.

Here is a failing example, that install astropy v1.0.1, while it should install v1.0.3:
https://travis-ci.org/astropy/photutils/jobs/69017661

Would it be possible that cached older versions are used, rather than fresh downloads?

https://github.com/astropy/photutils/issues/274

**Comment by joshk** [comment]
Hi @bsipocz 

Could you please point us to the line in the logs were the wrong package is installed, as a link to the newer package in the ubuntu package repository?

Thanks a bundle

Josh

**Comment by bsipocz** [comment]
It's around line 426 in https://travis-ci.org/astropy/photutils/jobs/69017661 (sorry, I couldn't make a link to there).

**Comment by joshk** [comment]
Thanks for the extra info.

Sorry, I am a bit confused, I see your repo is not using caching, nor is it able to as you are using our legacy build environment which does not have it available.

Where are you installing `astropy` initially? where should it be cached?

Thanks a bundle

**Comment by bsipocz** [comment]
Sorry, that's my bad. Everything is installed there from scratch, a caching behind the scene was just a wild guess, as I have no idea why this issue happens. I also admit that don't really know how conda  and conda packaging work as I don't use it myself. It works as expected with ``pip install``

https://github.com/astropy/photutils/blob/master/.travis.yml

**Comment by joshk** [comment]
Ok, great, can this issue be closed?

**Comment by bsipocz** [comment]
Ohh, I think at the end the problem must be unrelated to travis. (When I tested in on a linux box, I accidentally used numpy 1.9, and doing it with numpy 1.8 fails locally, too.)
Sorry for the noise.

**Comment by sebastian-luna-valero** [comment]
If understand well from this thread, caching should not occur if it is not configured in Travis, am I right?

I comment on this due to a problem that I am experiencing with conda installations. This is the commit that I am testing:
https://github.com/CGATOxford/cgat/commit/7d6643f9350d5b267d929e2888e449f85ae04203#diff-190b775810962a542403c7b8da8ed3f0R331

Locally on my desktop, it pulls the latest version of `pysam`, which is `0.10.0_3`. However, conda in Travis only "sees" the previous one `0.10.0_2`. Here are the logs:

For Python 2:
https://travis-ci.org/CGATOxford/cgat/jobs/218514025#L1129

For Python 3:
https://travis-ci.org/CGATOxford/cgat/jobs/218514026#L1132

We have not configured caching in our Travis setting. Any ideas?
