### ISSUE TITLE
on:tags condition for npm deployment reporting "Skipping a deployment with the npm provider because this is not a tagged commit"

### ISSUE THREAD

**Issue by chrisbaldauf** [travis-ci/travis-ci#4197]
I'm just getting started with travis and npm deployments and I am having trouble getting travis to push to npmjs.com on tagged commits, seeing what I believe is the same behavior as described in #1675 . Hopefully someone can point out something obvious that I'm missing.

* [travis.yml](https://github.com/Cimpress-MCP/deployment-tracker/blob/v0.1.8/.travis.yml)
* [build output](https://travis-ci.org/Cimpress-MCP/deployment-tracker/builds/69929232)

Result: `Skipping a deployment with the npm provider because this is not a tagged commit`

I added "all_branches: true" per the workaround instructions in #1675.

My process for committing / pushing was 
```
echo "..." >> README.md
git commit -am "comment"
npm version patch
git push origin master --tags
```
Thanks in advance for any direction or advice you might be able to provide.

**Comment by riggerthegeek** [comment]
I'm also getting this.  I'm only providing this as a +1 and to provide additional info.  This is on a NodeJS environment that was previously working

[Working Example](https://travis-ci.org/riggerthegeek/steeplejack/jobs/68966077)
[Failing Example](https://travis-ci.org/riggerthegeek/steeplejack/jobs/69941964)

There's been no changes to the .travis file.  I've put it below

    language: node_js
    node_js:
    - '0.12'
    - '0.11'
    - '0.10'
    - '0.8'
    - iojs
    - iojs-v1.8.1
    matrix:
      fast_finish: true
    sudo: false
    env:
      matrix:
      - TZ=Etc/UTC
      - TZ=America/Los_Angeles
      global:
        secure: Zh2Z8FyRQMFM5vez1OmIxVZ8s18K6qEzFa3C3g3XNYBxRQ4GzpSN8S3M0QjvnrrGi+XbMmdcV9DRYgOfGHqq55IamhLH9l5neTgPG3IqArRnWDLMulWRZrRznLACZCr1U0+z09WE+ndOCyfRWKNgkGaNdWRQhaQUZjEOevtqjvs=
    before_install:
    - node test/scripts/npm.js
    - npm install -g grunt-cli
    - date
    script:
    - grunt ci
    - grunt coveralls:src
    deploy:
      provider: npm
      email: simon@simonemms.com
      api_key:
        secure: scvV1vsf/S4OgeXjKysHViN4cVjyZQYo+nzl0UY9DsDeYCVoEijnTN4zR46eC7CVCXiUL13kc8VSqmk0w/9ZHNnj37fGE9wfRAuMNGmqIzi8in4ZTaGip/OxKtjW3mmWnst7HyR92C6mo0HtBa1BFa2jw8fhi8TmSbktTvW7UIo=
      on:
        all_branches: true
        tags: true
        repo: riggerthegeek/steeplejack
    notifications:
      webhooks:
        urls:
        - https://webhooks.gitter.im/e/d048e712b735c6cb4cf2
        on_success: change
        on_failure: always
        on_start: false

**Comment by BanzaiMan** [comment]
@svenfuchs I have a hunch that this might be due to recent changes in scheduler. Could you take a look?

**Comment by astorije** [comment]
I also just encountered this on https://github.com/astorije/chai-immutable:

`.travis.yml` says:

```yaml
deploy:
  provider: npm
  ...
  on:
    tags: true
    repo: astorije/chai-immutable
```

but the [tagged commit build](https://travis-ci.org/astorije/chai-immutable/jobs/69978755), although we have ` git clone [...] --branch=v1.1.1` says:

```
Skipping a deployment with the npm provider because this is not a tagged commit
```

Good luck with this bug!

**Comment by david-driscoll** [comment]
We're having a similar issue with Omnisharp-roslyn https://github.com/OmniSharp/omnisharp-roslyn

It was working until just recently.

**Comment by SpainTrain** [comment]
+1 https://github.com/trainiac/express-jsonschema/pull/4

**Comment by jeabakker** [comment]
same issue
https://travis-ci.org/ColdTrick/html_email_handler/builds/70024939

travis.yml
https://github.com/ColdTrick/html_email_handler/blob/master/.travis.yml

**Comment by svenfuchs** [comment]
Sorry about the troubles, folks. I have just deployed a fix for this.

Could you please restart these builds/jobs to see if it's now working?

**Comment by riggerthegeek** [comment]
Seems to have fixed it.  Thanks Sven

[Travis Report](https://travis-ci.org/riggerthegeek/steeplejack/jobs/69941964) (erroring because v1.0.2 already exists but triggering successfully)

**Comment by chrisbaldauf** [comment]
Looks like it worked for me as well. I received a 403 on publish since that version was already in the npm registry, but that is to be expected.

https://travis-ci.org/Cimpress-MCP/deployment-tracker/builds/69929232

@svenfuchs Thanks a lot for the quick turnaround on getting this issue addressed.

**Comment by svenfuchs** [comment]
Thanks @chrisbaldauf!

**Comment by astorije** [comment]
It got triggered on my end (and logically failed since already existing), perfect!

Thanks @svenfuchs!

**Comment by tripu** [comment]
We just had this issue in [Specberus](https://github.com/w3c/specberus).

This is [part of our .travis.yml](https://github.com/w3c/specberus/blob/master/.travis.yml#L18):

```yml
deploy:
  provider: npm
  email: web-human@w3.org
  api_key:
    secure: AyNg[...]Kwg=
  on:
    tags: true
    repo: w3c/specberus
```

We did:

```bash
$ npm version patch    # ie, v1.1.2
$ git push --follow-tags
```

But while building, [Travis said &ldquo;Skipping a deployment with the npm provider because this is not a tagged commit&rdquo;](https://travis-ci.org/w3c/specberus/jobs/72065563). We relaunched the builds manually from Travis, to no avail. (You will see `1.1.2` in npmjs.org now, but that's only because we published manually.)

I understand @svenfuchs fixed this already. Is there anything we're doing wrong?

Thanks!

**Comment by astorije** [comment]
@tripu, this is different. The build you are referring to is the master build (which builds against the merge commit and the commit that were merged), not the build that builds against the tagged commit so it's normal you get this message. To see what really happened you need to go to [this build](https://travis-ci.org/w3c/specberus/jobs/72065566#L451) and you got an issue at deployment:

```
NPM API key format changed recently. If your deployment fails, check your API key in ~/.npmrc.
http://docs.travis-ci.com/user/deployment/npm/
-npm ERR! publish Failed PUT 401
```

Looks like npm made changes to the way you deploy, but I haven't read [the doc](http://docs.travis-ci.com/user/deployment/npm/) yet to see what changes are needed.

On the other end, I'm happy you reported that because lots of repos I set up for automated deployments will be affected and I would have been caught as well...

**Comment by LeiYangGH** [comment]
Hi
I've just tried many times but always failed.
`deploy:
  provider: releases 
  api_key: 7735422ecab4cd4feb5a49116bfaa8b886621e38
  file: ConsoleApp/ConsoleApp/bin/Release/ConsoleApp.exe
  skip_cleanup: true
  on:
          tags: true
          all_branches: true`

`git add .
git commit -m 2.5
git tag -a 2.5 -m 2.5
git push --tags
git push
`
my repository: https://github.com/LeiYangGH/testtravis

Could any one tell my why? I'm always getting this error:
**Skipping a deployment with the releases provider because this is not a tagged commit**

**Comment by Viatorus** [comment]
I get the same error like LeiYangGH:
Running: `npm run test && git tag -l --points-at HEAD ` Returns correct tag.

**Comment by BanzaiMan** [comment]
@LeiYangGH Because it is not a tagged build. [This one](https://travis-ci.org/LeiYangGH/testtravis/builds/255221243), for example, is a push build to the `master` branch.

On a tagged build such as https://travis-ci.org/LeiYangGH/testtravis/builds/255221248#L1862, you see the deployment triggering.

Also, we recommend encrypting your GitHub token for security reasons.
