### ISSUE TITLE
On private Mac builds, requests to upload cache silently fails

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#4211]
When we try to upload the archive to S3 for a private repository, it can fail silently, and the subsequent builds does not (justifiably) find any cache to use.

The STDOUT:

```
$ cat $CASHER_DIR/push.log

<?xml version="1.0" encoding="UTF-8"?>

<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired</Message>
  <X-Amz-Expires>300</X-Amz-Expires>
  <Expires>2015-07-09T17:47:50Z</Expires>
  <ServerTime>2015-07-09T17:58:40Z</ServerTime
  <RequestId>CA3890CC3701E1A1</RequestId
  <HostId>gOfZ1OynwuG27VStQAeeGyiMn76IJc73w+CJPw5ePX66X1gX0urGBjsUKnlrEtdsM7ptiE2IPh8=</HostId>
</Error>
```

HTTP status must be one of success, so that we do not indicate that the upload failed.

**Comment by BanzaiMan** [comment]
First hunch is that the Mac infrastructure's time is not set correctly.

@henrikhodne could you take a look?

**Comment by BanzaiMan** [comment]
The next would be that the timeout that we generate is too stringent.

**Comment by meatballhat** [comment]
I misconfigured the OS X infrastructure workers, setting the cache push and fetch timeouts as seconds rather than the expected durations.  This resulted in the [default values](https://github.com/travis-ci/worker/blob/82fd7da565a8c7e43862f2dce577e0daa143e56c/src/github.com/travis-ci/worker/config/defaults.go#L13-L14) being used.  I've since pushed out the correct configuration and restarted the affected workers.
