### ISSUE TITLE
APT source whitelist request for Elasticsearch 1.6

### ISSUE THREAD

**Issue by saveriomiroddi** [travis-ci/travis-ci#4265]
This repository contains the Elasticsearch v1.6 Debian repository, which is compatible with Ubuntu [verified on Trusty].

Deb source line: deb http://packages.elastic.co/elasticsearch/1.6/debian stable main
Key: https://packages.elastic.co/GPG-KEY-elasticsearch

**Comment by BanzaiMan** [comment]
Installing the Deb package is not handled by the APT addon.

**Comment by saveriomiroddi** [comment]
Is ES 1.6 the version installed container-based infrastructure? The documents don't mention it, and AFAIK, the version installed in the legacy infrastructure was older.

If it isn't, I assume that the only way to have it is to add the APT source (thus the current issue) and add add `elasticsearch` as APT package.

**Comment by BanzaiMan** [comment]
Ah, I see. The 1.6 source will need to be added.

**Comment by AdrianRossouw** [comment]
This is the documentation for elastic.co's apt registry:
https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-repositories.html

It will need to be added to both the apt-source whitelist and the apt-whitelist.

I don't know if I will be able to make use of the new architecture even if the sources are added.

In my current app I am forced to download elasticsearch 1.4.5, because of a [breaking change in the supplied elasticsearch 1.4.0 w.r.t. script files](https://github.com/elastic/elasticsearch/issues/10007).

From my travis.yml:
```
  - "curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-1.4.5.deb && sudo dpkg -i --force-confnew elasticsearch-1.4.5.deb"
```

I've also been needing to use sudo to modify config files and put files into the elasticsearch/scripts, and restart the daemon.

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Elasticsearch 1.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because 'Elasticsearch 1.6' needs source whitelisting

**Comment by BanzaiMan** [comment]
Did not run automated check because title 'APT source whitelist request for Elasticsearch 1.6' is ambiguous. Please specify only one.

**Comment by BanzaiMan** [comment]
This APT request has been moved to https://github.com/travis-ci/apt-source-whitelist/issues/46.

Moving forward, please create new requests at https://github.com/travis-ci/apt-source-whitelist/issues/new?title=APT+source+whitelist+request+for+___SOURCE___

Thank you!
