### ISSUE TITLE
APT whitelist request for gcc-arm-none-eabi

### ISSUE THREAD

**Issue by kulve** [travis-ci/travis-ci#4310]
gcc-arm-none-eabi is an EABI "bare-metal" compiler for e.g. ARMv7 based microcontrollers. The package is found in Trusty and newer.

**Comment by gebart** [comment]
also useful (required by many projects): libnewlib-arm-none-eabi, libstdc++-arm-none-eabi-newlib

**Comment by BanzaiMan** [comment]
@gebart Thanks for the input. We are automating parts of the APT package whitelisting process. The process does not look at comments to figure out which packages to test. Could you open separate tickets for yours? Thanks.

**Comment by BanzaiMan** [comment]
I'm reopening this issue, since I found issues with the previous tests and am re-running them. The whitelist remains in place while I rerun the tests, but may be reverted if the tests reveal problems. Sorry for the mixup.

**Comment by BanzaiMan** [comment]
Re-run did not find a problem. https://travis-ci.org/travis-ci/apt-whitelist-checker/builds/72172306

**Comment by gebart** [comment]
opened #4539 #4540 per request

**Comment by jgouly** [comment]
Can someone explain how to use gcc-arm-none-eabi in a travis build?

**Comment by andysworkshop** [comment]
@jgouly Check out [my repo](https://github.com/andysworkshop/stm32plus). I'm using travis to build an arm-none-eabi project.

**Comment by jgouly** [comment]
Thanks, I took a look. However you're still using 're "old" Travis infrastructure. I should have mentioned I want to run this on the new container based system.

**Comment by jgouly** [comment]
I just noticed in the history that you upgraded to container based, but then reverted it, how come?

**Comment by andysworkshop** [comment]
After upgrading to container-based and using the new apt non-sudo method of package installation the `gcc-arm-none-eabi` package could not be found so I just reverted and carried on as before.

**Comment by jgouly** [comment]
Ok thanks, I hope someone can tell me/us how to use it.

**Comment by BanzaiMan** [comment]
```yaml
addons:
  apt:
    sources:
      - debian-sid
    packages:
      - gcc-arm-none-eabi
```

**Comment by jgouly** [comment]
Thanks I will try it!

**Comment by andysworkshop** [comment]
I now have this working in the new travis/docker infrastructure. See my [.travis.yml file here](https://github.com/andysworkshop/stm32plus/blob/master/.travis.yml). I have a requirement to use a specific version of the `arm-none-eabi-gcc` package so I decided to directly install it prior to the build script step.

Here's what the script does.

* Install the `libc6-i386` libraries using `apt` in the `addons` section. You need this because the travis containers are 64-bit and the arm compilers are 32-bit.
* In the `install` section I use `wget` and `tar` to download the package and install it to the travis `$HOME` directory. Note how this is surrounded by an `if` that skips the download/extract if it's already there because...
* ... in the `cache` section I tell travis to upload the extracted compiler to its network cache, In testing I found travis's preinstall from cache to be MUCH faster than a wget from the launchpad site. This is a significant speedup.
