### ISSUE TITLE
mvn command completely ignores $PATH

### ISSUE THREAD

**Issue by YarekTyshchenko-awin** [travis-ci/travis-ci#4369]
Trying to build using an older version of Maven (3.0.5) because of a plugin bug:

```yaml
before_install:
  - wget http://apache.mirror.iphh.net/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
  - tar xfz apache-maven-3.0.5-bin.tar.gz
  - export PATH=$PWD/apache-maven-3.0.5/bin:$PATH
  - which mvn
  - mvn --version
  - $PWD/apache-maven-3.0.5/bin/mvn --version
  - md5sum $PWD/apache-maven-3.0.5/bin/mvn
```

Both maven commands print the latest version, md5sum prints 7d2bdb60388da32ba499f953389207fe which is 3.0.5 version. What the hell is going on?!

**Comment by BanzaiMan** [comment]
It does not ignore `$PATH`, but we have a problem with our maven installation.

**Comment by BanzaiMan** [comment]
OK. This is halfway fixed by https://github.com/travis-ci/travis-build/commit/d38bb132121ff1d1aa3f1a68a033f2e918bb27a4. The other half is that you need to set `$M2_HOME` in order to correctly set up maven. See https://travis-ci.org/BanzaiMan/travis_production_test/builds/71120542#L108 and its corresponding config file.
