### ISSUE TITLE
Python 3.5 support lost

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#4437]
Python version 'nightly' has been switched from 3.5 to 3.6, and there isnt an alternative virtualenv for 3.5

```
ls /home/travis/virtualenv/
pypy	     python2.6	  python2.7_with_system_site_packages  python3.3
pypy-2.5.0   python2.6.9  python3.2			       python3.3.5
pypy3	     python2.7	  python3.2.5			       python3.4
pypy3-2.4.0  python2.7.9  python3.2_with_system_site_packages  python3.4.2
```

PEP 478: Python 3.5 is slated for release in September 2015.
PEP 494: Python 3.6 is slated for release in late 2016.

Due to the closeness of the 3.5 release, I think it is important to have jobs building against 3.5; much more so that building against 3.6.

I note that https://github.com/travis-ci/travis-build/pull/477 looks like it might provide a way forward.

**Comment by BanzaiMan** [comment]
Please use `nightly` for the time being for the latest development version of Python. http://docs.travis-ci.com/user/languages/python/#Nightly-build-support

If `3.5` ever worked, it was by accident.

**Comment by BanzaiMan** [comment]
I'll look into building the 3.5 branch.

**Comment by jayvdb** [comment]
Sorry I meant `nightly` instead of `latest` in the original issue description, as it was 3.5 until very recently.

**Comment by BanzaiMan** [comment]
Ah, I see. Then see https://github.com/pytest-dev/pytest/issues/744#issuecomment-122577929.

**Comment by takluyver** [comment]
It looks like you can now specify '3.5.0b3' in the .travis.yml file. :-)

**Comment by BanzaiMan** [comment]
'Tis true. And we've documented it, too.

**Comment by nocarryr** [comment]
@BanzaiMan I realize that this is an incredibly old thread, but I believe the documentation for python version specifiers could be a bit clearer and hopefully save others from going through a couple days of trying to get their builds running on specific releases (i.e. python 3.5.2 versus the default of 3.5.0).

There are quite a few changes between the current stable release and the one included in the current travis build (most of them related to asyncio since it's always evolving).

I realize keeping up with the current stable release of so many programming languages and platforms would be nearly impossible, but when a build fails and you see the method call isn't supported by the environment's package, it would be incredibly useful to see something in the docs along the lines of:
```yaml
- python
  - "2.7"
  - "3.5[.x]"
```
Or possibly a more detailed (maybe just an extra sentence) in the [On Demand Installations](https://docs.travis-ci.com/user/languages/python/#On-demand-installations) section.

Just a suggestion or maybe even something that future readers of this issue can read to avoid all of the ugly commits in their repos from trying to reinvent the wheel (_pun intended_) with things like pyenv, etc.

Thank you very much for providing such a great service and platform that so many have come to **_continually integrate_** into our daily lives!  :smile:
