### ISSUE TITLE
No build for tagged commits is triggered

### ISSUE THREAD

**Issue by thedrow** [travis-ci/travis-ci#4464]
https://github.com/idan/oauthlib has a new tag (1.0.0) but no build is triggered for the tagged commit.

https://github.com/idan/oauthlib/tree/1.0.0

**Comment by BanzaiMan** [comment]
On https://github.com/idan/oauthlib/blob/1.0.0/.travis.yml#L19-21, you have 

```yaml
branches:
  only:
  - master
```

This instructs Travis to ignore all tags. If you know what the tags look like, you can at something like `/\d+(\.\d+)?/` to build them.

I'm closing this because I think this is documented behavior (http://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions).

**Comment by thedrow** [comment]
Sorry I missed that.
