### ISSUE TITLE
OracleJDK 8 is no longer available on the Mac

### ISSUE THREAD

**Issue by headius** [travis-ci/travis-ci#4514]
The following build for jnr-posix shows that Java 8 does not appear to be working on OS X builds.

https://travis-ci.org/jnr/jnr-posix/builds/71971555

It also appears that "openjdk8" failed to enable on Linux.

**Comment by BanzaiMan** [comment]
OpenJDK 8 is not yet available. It will be available on our next (not yet planned, unfortunately) updates.

**Comment by headius** [comment]
Ok, I'll take that one out for now.

**Comment by aaime** [comment]
We recently got a OSX build box on Travis, and at the same time, our open source projects are considering moving to Java 8 as the minimum supported version (also known as "the only supported version", we don't have enough devs to man multiple ones), since Oracle Java 7 is no longer supported cross-platform since a few months ago.

So, +1 on getting an upgrade :-)

**Comment by JLLeitschuh** [comment]
Related #2316

**Comment by BanzaiMan** [comment]
I'll close this as a duplicate.
