### ISSUE TITLE
Cache the Mono installation

### ISSUE THREAD

**Issue by Mailaender** [travis-ci/travis-ci#4571]
cc @joshua-anderson @akoeplinger @nterry

Installing Mono (completely) usually takes 10x more time than the actually build even with a large code base and test suite. See https://travis-ci.org/OpenRA/OpenRA for example. Why not cache this instead of installing via apt at every runtime?

**Comment by akoeplinger** [comment]
AFAIK, this is not possible right now due to how travis-build works for community-supported languages. I suspect it'd be a bit better if we had an APT cache for the packages so we don't download them from the Xamarin repos on every build, but that's not possible right now as well.

@BanzaiMan any insights?

**Comment by BanzaiMan** [comment]
@akoeplinger is correct. Our build images are getting bigger, and provisioning a new image for a new language is not likely to happen soon.

**Comment by yellowblood** [comment]
Is there any way to cache the mono installation using the directories cache mechanism?

**Comment by akoeplinger** [comment]
@yellowblood even if caching directories in /usr where Mono is installed would work on Travis, that'd still mean uploading/downloading a large cache file to/from S3 according to https://docs.travis-ci.com/user/caching/ and I doubt it'd be faster in practice.

**Comment by yellowblood** [comment]
It seems that Travis fetches the cache only after the installation phase, so I can't even test this approach.

**Comment by BanzaiMan** [comment]
@yellowblood Mono installation has to happen before `sudo` is disabled (otherwise you can't use C# on containers), and that happens before fetching the cache.

**Comment by yellowblood** [comment]
@BanzaiMan yup. not complaining, I'm getting a free CI here.

**Comment by Mailaender** [comment]
This is still a problem and wasting CI server resources.

**Comment by kasper3** [comment]
@akoeplinger, @BanzaiMan, this is not a complain either, I am just wondering if Java (or any other runtime for that matter) gets the first class status in TravisCI with maven and all the tools preinstalled when we select `language: java`, why .NET/Mono doesn't has enough comparable merit here? Something that you could really reconsider to save everyone's time and your resources.

**Comment by BanzaiMan** [comment]
I understand how this is advantageous for you. However, at the moment, C# is not in heavy use by our users. Creating build images with these packages requires considerable time, tooling, and expertise, and at the moment it does not make sense for us to pursue it.

**Comment by dolkensp** [comment]
> I understand how this is advantageous for you. However, at the moment, C# is not in heavy use by our users. Creating build images with these packages requires considerable time, tooling, and expertise, and at the moment it does not make sense for us to pursue it.

Gee, I wonder why...

Literally evaluating Travis as a possible replacement for Azure DevOps / Team City, as our mobile team is already using Travis. I'll be migrating the mobile team instead.

**Comment by craigfowler** [comment]
*Firstly, apologies for necro'ing an old closed issue, but I have come across some (relatively) new information which could be of benefit to those for who are interested in this issue.*

## Building for .NET Framework targets without Mono
This may be of help if your solution can be built using **the dotnet core SDK** but *'needs Mono'* because it targets .NET Framework (`net45`, `net472` etc), perhaps as part of multi-targeting.  A new (December 2019) technique means that *you no longer need Mono installed at all* in order to build from the dotnet core SDK, even when targeting .NET Framework.

The way this is achieved is by installing [the .NET Framework reference assemblies]: `Microsoft.NETFramework.ReferenceAssemblies` to your projects via NuGet.  These act as a stand-in for the counterpart assemblies which are in the .NET Framework SDK.  Applied to Travis CI builds, you may then build on an environment which has *only the dotnet core SDK*, and skip installing Mono altogether, shaving that time off of your build.

Here's [a longer article about this technique].  Certainly for the vast majority of my open source work, I think that this will be good enough.  For a long time using Travis, the lion's share of my build time has always been due to the installation of Mono.

### My results for a sample project (YMMV)
I have just tried this out with [a trivially small project] - [here is the commit where I made the switch].  The Travis build time dropped from [6 min, 45 sec] for the previous commit, down to [2 min, 2 sec] when I installed the reference assemblies and dropped Mono.

[the .NET Framework reference assemblies]: https://github.com/Microsoft/dotnet/tree/master/releases/reference-assemblies
[a longer article about this technique]: https://andrewlock.net/using-reference-assemblies-to-build-net-framework-libararies-on-linux-without-mono/
[a trivially small project]: https://github.com/csf-dev/CSF.ADO
[here is the commit where I made the switch]: https://github.com/csf-dev/CSF.ADO/commit/0fe41ec8de33906041c44c90093c048faeb7b1df
[6 min, 45 sec]: https://travis-ci.org/github/csf-dev/CSF.Data/builds/718387874
[2 min, 2 sec]: https://travis-ci.org/github/csf-dev/CSF.Data/builds/718392943
