### ISSUE TITLE
Requests created through API doesn't seem to set tag and branch properties of the created request entity

### ISSUE THREAD

**Issue by devoto13** [travis-ci/travis-ci#4577]
I'm following instructions described at [this article](http://docs.travis-ci.com/user/triggering-builds/) to manually trigger build for a project and it actually works (build is triggered), but deployment to PyPI is not working (see idan/oauthlib#367 for more details). It says: "Skipping a deployment with the pypi provider because this is not a tagged commit".

I did some investigation and it looks like no matter what you send `{"request":{"branch":"master"}}`, `{"request":{"commit_id":"xxx"}}` or `{"request":{"tag":"1.0.1"}}` it doesn't set neither `branch`, nor `tag` attribute for the created request object and that's the reason of the skipped PyPI deployment.

You can check it using:

```
$ curl -s \
    -H "Accept: application/vnd.travis-ci.2+json" \
    https://api.travis-ci.org/requests/?repository_id=61266 | python -m json.tool
```

Last four requests were created through API and don't have neither `branch`, nor `tag` set. Previous requests created through GitHub hook has one of the mentioned attributes set. 

Any workaround how to quickly trigger build for a tag is highly appreciated.

**UPD** Builds history: https://travis-ci.org/idan/oauthlib/builds

**Comment by BanzaiMan** [comment]
What is the rationale for triggering a tag build via API rather than pushing the tag to GitHub?

**Comment by devoto13** [comment]
In some cases pushing the tag to GitHub haven't triggered build (see [requests history](https://travis-ci.org/idan/oauthlib/requests)). In this case builds were probably disabled. And now we need to trigger tag build manually to deploy version to PyPI.

**Comment by BanzaiMan** [comment]
Tags are a git repository concern. That means they should live with the repository, which means that git pushes should trigger a build based on tags.

I'm sure we can coerce API into creating data which fools travis-build to trigger a tag-based deployment, but that seems wrong to me.

If the tag push didn't trigger a build because it was disabled, then you can try triggering a new build as follows:

1. Disable push builds again.
1. Tag a different commit with the tag you missed building; e.g., `git tag 1.0.1 0123abc -f`
1. Force push tags: `git push origin --tags -f`
1. Enable push builds.
1. Re-tag the commit you want: `git tag 1.0.1 fecf37b -f`
1. Force push tags again: `git push origin --tags -f`

**Comment by devoto13** [comment]
I won't insist that API should be changed. You have much broader understanding and probably there is a reason, why it is made this way. But from my (end user's) point of view, that's really confusing, that builds with the same parameters behave differently being triggered through GitHub or API .

Thank you for a solution. I'll try it tomorrow.

**Comment by BanzaiMan** [comment]
I have no doubt the documentation can be improved here. I'll talk to others and how we can improve it.
