### ISSUE TITLE
[Haxe] neko download urls changed

### ISSUE THREAD

**Issue by ibilon** [travis-ci/travis-ci#4583]
cc @andyli @waneck @Simn

https://travis-ci.org/HaxePunk/HaxePunk/jobs/73019281

```
Installing Neko
$ mkdir -p ~/neko
$ curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz' | tar -C ~/neko -x -z --strip-components=1 -f -

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

The command "curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz' | tar -C ~/neko -x -z --strip-components=1 -f -" failed and exited with 2 during .
```

Went to the neko website and found the url for linux: `http://nekovm.org/media/neko-2.0.0-linux64.tar.gz`.

Looks like the url changed and `_media/` became `media/`

**Comment by jasononeil** [comment]
Sorry about this - the website backend was replaced and the "_media" paths were some kind of redirect used by the old docuwiki system.  I've fixed it up so that the URL now works, but it's still failing.

This command executes perfectly on my local machine:

    curl -s -L --retry 3 'http://nekovm.org/_media/neko-2.0.0-linux64.tar.gz' | tar -C ~/neko -x -z --strip-components=1 -f -

But is still failing on Travis.  @andyli any ideas?  Is there any sort of request caching (or image caching) on Travis that we have to work around?

**Comment by jasononeil** [comment]
It seems that the build did in fact pass after retrying it:

https://travis-ci.org/fponticelli/thx.core/jobs/72950737

My browser was just not updating the log message... when I closed the tab and came back it showed up correctly.  Please let me know if there are any other issues?

**Comment by andyli** [comment]
I confirm the issue is fixed : )

**Comment by ibilon** [comment]
Confirm too. Thanks.
