### ISSUE TITLE
Upload to coverity-scan

### ISSUE THREAD

**Issue by DankoDJ** [travis-ci/travis-ci#4646]
I'm using the coverity addon.
Since 08. Aug. the upload to coverity fails. After a short research I found this:
https://github.com/xoreos/xoreos-tools/commit/1ca81a7e6e33f55ec708f7ead32c873d0fe5cf63

It seems the "new" upload url is invalid... I get the following error:
http://pastebin.com/a85QjJ7T

Our respository: AscEmu/AscEmu branch coverity_scan

**Comment by roidrage** [comment]
Ping @aceofspades

**Comment by aceofspades** [comment]
@DankoDJ This issue was discovered and fixed early this morning, can you try again?

**Comment by DankoDJ** [comment]
@aceofspades Perfect. It works :+1:

**Comment by kulp** [comment]
The underlying issue is that the [official script from Coverity Scan](https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh) has an old URL that was broken by a recent Coverity Scan (not Travis-CI) update.

I am not able to use the Travis-maintained addon, so I download the script directly from the link above. Coverity Scan has not returned my email request from a week ago to have their script updated.

Could someone at Travis-CI who has a connection with the Coverity Scan staff ping them to update the script ?

Also, what is the new URL to replace the obsoleted https://scan.coverity.com/builds ? I don't immediately find source for the coverity_scan addon, even though I'm sure I've seen it online before.

**Comment by kulp** [comment]
Apparently, while the uploads URL was indeed broken for a little while (see log of https://travis-ci.org/kulp/tenyr/jobs/74908640), the upload URL has not been changed. Coverity Scan got back to me by email and explained the situation ; once I restarted the build, I got success.
