### ISSUE TITLE
Make Error 137 more descriptive

### ISSUE THREAD

**Issue by bilderbuchi** [travis-ci/travis-ci#4665]
When first finding builds Killed with Error 137, you have no idea what this means. The _docs don't mention that error code_. After googling enough you find people saying that it's most likely due to memory. This makes it very hard to debug/improve/fix your builds. Which resource is being exhausted - memory, swap, CPUs, disk quota, fairy dust?

For example, I currently have a build erroring because an apt-get install is killed with [Error 137](https://travis-ci.org/openframeworks/openFrameworks/jobs/76086799#L197). Has anybody ever seen apt-get exhaust system resources? I have no way to find out more and so, no way to fix my build or at least find out what's wrong. I have already tried to install only one package to minimize (hopefully?) memory usage, but this seems to do nothing - am I barking up the wrong tree, and it's in fact e.g. disk space that's running out?

I would love if that error message would declare which resource is being exhausted, either, preferably, with a set of multiple, **documented** error codes, or at least "Error code 137 - disk quota exceeded" or somesuch.

**Comment by Lyoness** [comment]
Hello @bilderbuchi 

Error 137 is not a Travis-CI specific error, but rather bash (shell) specific error specific to the Unix/Linux environment within the running build.  

http://tldp.org/LDP/abs/html/exitcodes.html

In this case this is a fatal error or `kill -9` which terminates the process.  If this happens while running on a Travis CI build, this is likely because the build has consumed too many resources on the build host, likely memory, and so the virtual machine or container killed it.  

We will look for ways to be more explicit about error messages and where they are propagating from within a Travis CI Build.

**Comment by bilderbuchi** [comment]
Thank you for clearing this up. Would be nice if the container or VM could log *why* it killed the process, but anyhow this issue has not been relevant for me for a long time.

**Comment by AJEETRAI707** [comment]
Hello @Lyoness 
The same error 137 (resource error) occured to me , as i am making my build in jenkins and failed occured relation with makefile, can you explain the idea bit clearly .
