### ISSUE TITLE
Allow specification of patch-level versions of Mono

### ISSUE THREAD

**Issue by natemcmaster** [travis-ci/travis-ci#4727]
Presently building against Mono allows specifying only major/minor versions (see #4130 and https://github.com/travis-ci/docs-travis-ci-com/pull/308). This can still cause problems if the build is trying to workaround issues that affect 4.0.3 but not 4.0.2. Travis rounds to 4.0.x.

Example:
My project works fine on 4.0.1, 4.0.2, and fails due to a regression 4.0.3. Travis CI rounds to the latest 4.0.x. I cannot fix the build on Travis CI as there is no way to specify the version of Mono to the exact patch-level.

**Comment by BanzaiMan** [comment]
cc @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
@natemcmaster this is not supported because it's not possible in the underlying Xamarin apt repositories (as mentioned in the [docs](http://docs.travis-ci.com/user/languages/csharp/#Choosing-Mono-version-to-test-against)).

You could try using the `alpha` channel which has 4.2.0 now (I saw you tried directly specifying `4.2.0`, but that'll only work after it is released and available in the Xamarin repos)

The only other way to workaround if you need 4.0.2 is by enabling OSX on the repo since the restriction doesn't apply there. I talked with @NTaylorMullen about enabling it for the aspnet repos, you might want to check with him.

**Comment by natemcmaster** [comment]
Thanks @akoeplinger! It's too bad the Xamarin apt repo's have that limitation. I don't suppose there are alternatives?

**Comment by akoeplinger** [comment]
No :)

**Comment by natemcmaster** [comment]
:cry: bummer. Closing as this is not actionable (unless Xamarin updates their apt repos.)
