### ISSUE TITLE
Support cljc in travis-ci

### ISSUE THREAD

**Issue by JulianBirch** [travis-ci/travis-ci#4791]
Travis CI uses Leiningen 2.4.x, which has the following bug relating to testing cljc Clojure projects: https://github.com/technomancy/leiningen/issues/1940.

This is fixed in Leiningen 2.5. I'm suggesting either documenting how to use 2.5.2 on http://docs.travis-ci.com/user/languages/clojure/ or changing the default.

**Comment by JulianBirch** [comment]
Incidentally, my solution has been `yes | lein2 upgrade 2.5.2`, but that's required me to set `sudo: required`. :(

**Comment by JulianBirch** [comment]
I'm thinking you might want to look into respecting :min-lein-version "2.5.2" in the project.clj file.

**Comment by BanzaiMan** [comment]
Thanks for taking the time to open the issue.

What do you expect to happen when the minimum version requirement is not met?

**Comment by JulianBirch** [comment]
Well, the nice thing would be to guarantee that that didn't happen i.e. automatically run a `lein upgrade` beforehand. You might not want to do that because it'd involve parsing the file. Alternatively, provide a way of running `lein upgrade` that doesn't require sudo.

**Comment by benedekfazekas** [comment]
or alternatively I guess lein2 could be an alias for leiningen 2.5.2 (it is 2.5.1 at the moment I think which still pulls clojure 1.6). so you don't need to upgrade

**Comment by JulianBirch** [comment]
That's certainly solve my original problem. It'd be nice if users could
specify an exact version, although in my experience there's very little
downside to upgrading. (1->2 was a big deal, but nothing after that)

On Wednesday, September 16, 2015, Benedek Fazekas <notifications@github.com>
wrote:

> or alternatively I guess lein2 could be an alias for leiningen 2.5.2 (it
> is 2.5.1 at the moment I think which still pulls clojure 1.6). so you don't
> need to upgrade
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/travis-ci/travis-ci/issues/4791#issuecomment-140665678>
> .
>


-- 
Sent from an iPhone, please excuse brevity and typos.

**Comment by venantius** [comment]
@BanzaiMan The fact that this hasn't been dealt with yet means I'll be moving my Clojure projects to a different CI service. Right now, the lack of this feature essentially keeps Clojure projects locked on Clojure 1.6.0 or prior. The current release of Clojure is 1.8.0 and version 1.9.0 is scheduled to be released soon.

**Comment by BanzaiMan** [comment]
@venantius I'm sorry for the delay. I am unfamiliar with the Clojure ecosystem, so I'd appreciate it if you could explain this part: "the lack of this feature essentially keeps Clojure projects locked on Clojure 1.6.0 or prior"? Thanks.

**Comment by venantius** [comment]
Sure. Forgive the pedantic breakdown that follows - I don't know what you don't know, so some of this might seem obnoxious:

Clojure 1.7.0 introduced two features that were not supported in Clojure 1.6.0: "reader conditionals" and the `.cljc` extension. The two features are closely related - the latter is a "common" file extension for writing dual Clojure-ClojureScript code, and the former is the specific syntax used for (among other things) writing code that is conditionally interpreted depending on the runtime (i.e. JavaScript or Java).

Leiningen 2.5.1, which is the version installed on Travis, does not have support reader conditionals (which means, by definition, that it cannot successfully support `.cljc` files). [This issue](https://github.com/technomancy/leiningen/issues/1827) tracks the eventual merging of the feature into Leiningen master, with the first viable Leiningen release that supports `.cljc` files being 2.5.2.

Since Clojure 1.7.0's release, many projects (perhaps most importantly, all of the biggest community projects) have adopted the use of `.cljc` files. The fact that Travis doesn't permit Clojure developers to test code using a more recent version of Leiningen means that any Clojure code that has a dependency on a `.cljc` file anywhere in the full dependency tree will fail. This means that any Clojure project that wants to be successfully tested on Travis is limited to using functionality and dependencies tied to Clojure 1.6.0 or prior.

**Comment by venantius** [comment]
Hey @BanzaiMan, just wanted to check in on this :)

**Comment by BanzaiMan** [comment]
Does it suffice to update leningen to a reasonably recent version? https://github.com/travis-ci/travis-build/pull/803 updates it to 2.6.1 on the fly (tested here: https://staging.travis-ci.org/BanzaiMan/travis_staging_test/builds/507071#L149; the build fails because the repo is not set up for Clojure builds at all).

https://github.com/travis-ci/travis-build/pull/803 is meant to be a stop-gap until the build environment is updated with the newer Clojure and leiningen.

**Comment by BanzaiMan** [comment]
Reverted the PR, since we still need to worry about Leiningen 1.x.

**Comment by venantius** [comment]
For the project I'm working on, updating to latest is fine, but yeah, as you noted, people will want the ability to specify the precise version. My implementation recommendation would be for you just to keep the various Leiningen jars around somewhere that's cached and then just link `lein` to the relevant jar at runtime based on the `travis.yml`.

**Comment by BanzaiMan** [comment]
See the new PR: https://github.com/travis-ci/travis-build/pull/808

**Comment by BanzaiMan** [comment]
The replacement PR has been deployed.

If your Clojure project needs a recent version, you can specify it with:

```yaml
language: clojure

lein: 2.6.1
```

**Comment by BanzaiMan** [comment]
Document has also been updated: https://docs.travis-ci.com/user/languages/clojure#Using-a-more-recent-versions-of-Leiningen

**Comment by venantius** [comment]
👯 Thanks @BanzaiMan!
