### ISSUE TITLE
All builds fails and exits with 180 during .

### ISSUE THREAD

**Issue by olefredrik** [travis-ci/travis-ci#4832]
All my builds have suddenly begun failing with the same error message

```
$ export WP_DEVELOP_DIR=/tmp/wordpress/
before_script.2
0.00s$ mkdir -p $WP_DEVELOP_DIR
127.19s$ git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR
Cloning into '/tmp/wordpress'...
fatal: unable to connect to develop.git.wordpress.org:
develop.git.wordpress.org[0: 66.155.40.244]: errno=Connection timed out
The command "git clone --depth=1 --branch="$WP_VERSION" git://develop.git.wordpress.org/ $WP_DEVELOP_DIR" failed and exited with 128 during .
Your build has been stopped.
```
https://travis-ci.org/olefredrik/FoundationPress/jobs/81277684

I have not made any changes in travis.yml recently. The problem applies to all pull requests on [my Github repository](https://github.com/olefredrik/foundationpress), and I have no idea where to begin troubleshooting. Any tips?

**Comment by BanzaiMan** [comment]
So the connexion to develop.git.wordpress.org timed out. Does it fail now, if you restart the build?

**Comment by olefredrik** [comment]
No. It's still a timeout. And I have no idea what I can do about it.

**Comment by ntwb** [comment]
Hiro, (@BanzaiMan)

I also sent your an email about this ~36 hours ago ;)

You can see our main https://w.org builds failing constantly here https://travis-ci.org/aaronjorbin/develop.wordpress/builds, most if not all of these failures are due to Travis not being able to connect to `wordpress.org` domains and/or sub domains, this same scenario also happen ~5 days ago for ~7 hours.

Feel free to follow up via email or here, just hoping to get this resolved ASAP please :)

Cheers,

Stephen Edgar

WordPress build and test tools maintainer
https://profiles.wordpress.org/netweb/   https://twitter.com/netweb

**Comment by BanzaiMan** [comment]
This appears to be a network problem that crops up every now and then, and disappears when the issue is resolved. We will look into it.

At the moment, though, it appears to be working (https://travis-ci.org/BanzaiMan/travis_production_test/builds/81428276)

**Comment by olefredrik** [comment]
Thanks. It appears to be working again now.
