### ISSUE TITLE
Latest Python minor versions?

### ISSUE THREAD

**Issue by hugovk** [travis-ci/travis-ci#4859]
It looks like Python 3.4.2 is being used by default for `3.4`:
https://travis-ci.org/hugovk/test/jobs/77461065#L132

That uses:

```
python:
- 'pypy'
- 'pypy3'
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
```

https://github.com/hugovk/test/blob/master/.travis.yml#L3-L10

Python 3.4.3 is the latest 3.4 release from February 2015. 

I see a 3.4.2 to 3.4.3 upgrade was planned but rolled back in April:
http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/#Python-VM

And also that 3.4.3 is available with:

```
python:
  - 3.4.3
  - 3.3.6
```

https://github.com/travis-ci/travis-ci/issues/4632#issuecomment-128837176

But how about using 3.4.3 when just `3.4` is specified?

---

Similarly:
- 2.7.9 is being used when there's a 2.7.10 bug fix release from May 2015
- 3.2.5 and 3.3.5 are being used when there's 3.2.6 and 3.3.6 security releases from October 2014

---

Thank you!

**Comment by BanzaiMan** [comment]
Note 2.7.10 is also available.

Those aliases need to be pre-installed on the image; there is currently no way to detect that a newer version is available and install it on demand.

We are planning a build environment update, but this issue (that MAJOR.MINOR may not point to the latest release) will likely to remain for the future.

**Comment by hugovk** [comment]
In that case, would it be possible to document somewhere the latest available x.y.z versions, and which x.y.z each x.y maps to? Perhaps on http://docs.travis-ci.com/user/languages/python/ ?

Thanks!

**Comment by flinz** [comment]
I also just randomly ran into something related. 

I had build failing on a fork
https://travis-ci.org/django-helpdesk/django-helpdesk/builds/171916745
but not on the original repository
https://travis-ci.org/flinz/django-helpdesk/builds/172233267

The reason is that the fork python "3.4" resolved into python 3.4.2 while the original repository resolved "3.4" into 3.4.4, having us run into some obscure python 3.4.2 bug.

**Comment by BanzaiMan** [comment]
@flinz Your issue is subtle, but worth discussing. The upstream https://github.com/django-helpdesk/django-helpdesk is an old (in terms of Travis activation), and therefore defaults to `sudo: required`. Your fork, on the other hand, is newer, and defaults to `sudo: false`. https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments They are run on different images, and thus you saw the error you did.

**Comment by flinz** [comment]
@BanzaiMan thanks for the information! This is indeed quite subtle - the fallback sudo setting is not mentioned in the log as far as I can see.

**Comment by hugovk** [comment]
See PR https://github.com/travis-ci/docs-travis-ci-com/pull/803 to document these.
