### ISSUE TITLE
[perl6] travis counts failures incorrectly

### ISSUE THREAD

**Issue by teodozjan** [travis-ci/travis-ci#4929]
@paultcochrane, @hoelzro, @ugexe, @tony-o

Example https://travis-ci.org/teodozjan/lacuna-cookbuk/builds/85113602

Failed 3/8 and Failed 1/8 => travis shows 14 that is number of word fail in the log

**Comment by ugexe** [comment]
What is your question? Travis (rightfully) shows it as failing. Any 
failure count is made by the `prove` command but as far as I can tell 
the failure count is correct as well. The count of the word 'Fail' also 
has no relation to the number of actual test failures, since the word 
'Fail' appears in the test summary.

**Comment by ugexe** [comment]
It's also worth noting that `prove` uses tap harness, which reads the 
results printed to STDOUT. If you are doing something like capturing 
`$*OUT` with IO::Capture::Simple in your tests then you could be 
swallowing test results before `prove` can see them.

**Comment by teodozjan** [comment]
My mistake. I misinterpreted #14 failed as failure count while it is buildnumber
