### ISSUE TITLE
Build failed: Unable to connect to downloads-distro.mongodb.org:http:

### ISSUE THREAD

**Issue by tripleee** [travis-ci/travis-ci#4937]
[My latest build failed](https://travis-ci.org/tripleee/emacs-snapshot/builds/85276990) with the following error message:

    $ sudo apt-get update -qq

    W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/binary-i386/Packages Unable to connect to downloads-distro.mongodb.org:http:

    W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/i18n/Translation-en_US Unable to connect to downloads-distro.mongodb.org:http:

    W: Failed to fetch http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/10gen/i18n/Translation-en Unable to connect to downloads-distro.mongodb.org:http:

    E: Some index files failed to download. They have been ignored, or old ones used instead.

My project doesn't need or want to use MongoDB so this failure is rather annoying.

**Comment by BanzaiMan** [comment]
Looks like it was a temporary network issue. Recent builds are able to download package index.

**Comment by tripleee** [comment]
Yeah, but wouldn't it make sense to have a local mirror of stuff which is required by all builds; or make failures non-fatal?

**Comment by BanzaiMan** [comment]
You raise a good point about the balance we need to strike.

Since the command was initiated by your customization in `before_install`, it is up to you to decide how it should fail. In general, we treat command failures in customization fatal, as they should be essential parts of the build. If you can tolerate the failures, you can append `|| true`: `sudo apt-get update -qq || true`. Do keep in mind, though, that if the update fails subsequent `apt-get install` might fail due to outdated index.

It is true that we add mongodb.org source; it is generally a desirable source, since we have it available on all images. If you wish to remove it, you can add the following command prior to `sudo apt-get update`:

    sudo rm /etc/apt/sources.list.d/mongodb.list

**Comment by davidjb** [comment]
Hopefully it's just temporary again, but this same issue is occurring again now: https://travis-ci.org/jcu-eresearch/nginx-custom-build/builds/111389484.  Removing the MongoDB repo worked, though the subsequent build errored again with networking issues (``Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.org" port 443``).

**Comment by tripleee** [comment]
Many users of the `before_install` hooks are probably just copy/pasting from some instructions. If this is a "wontfix" / "works as intended", maybe then these instructions should be fixed to better explain how this can fail and what you should do about it in that case. I'm looking at https://docs.travis-ci.com/user/customizing-the-build/#Installing-Packages-Using-apt and https://docs.travis-ci.com/user/installing-dependencies/ in particular, but those are just my top Google hits.
