### ISSUE TITLE
Xcode 7.2 Beta 2

### ISSUE THREAD

**Issue by mattyohe** [travis-ci/travis-ci#5051]
Hopefully this is down to a science now?

https://developer.apple.com/xcode/download/

**Comment by meatballhat** [comment]
@mattyohe Hey there.  Is this a request?  A bug report?  A critique?  Link ambiguous.

**Comment by solarce** [comment]
Hey Matt,

Thanks for the inquiry. We do monitor Xcode releases and have a goal of getting updates to public stable and beta releases out with 1-2 business days. We are currently at a company offsite this week, so that is delaying any non-critical updates to things like our build environments. We hope to get our 7.2 beta image updated early next week.

Additionally, I’d request that in the future you reach out to support@travis-ci.com first if you have a specific question on an ETA, as GH issues isn’t the primary communication method we want to use for updates like an Xcode release update.

Thanks
