### ISSUE TITLE
The Android Emulator killed before Espresso UI tests would run.

### ISSUE THREAD

**Issue by piotrek1543** [travis-ci/travis-ci#5062]
Hi,

according to this buid report:
https://travis-ci.org/piotrek1543/WeatherforPoznan/builds/89500849

I'm trying to run a build of my Android Project and then check it using Espresso UI tests (unit tests as I noticed are launched by "/.gradlew build" command), but it's still fails. I think the reason of that issue are low available resources.

Could you help me to change this Travis configuration:
https://github.com/piotrek1543/WeatherforPoznan/blob/master/.travis.yml
so I could run it properly? It's very important to me.

Cheers.

**Comment by BanzaiMan** [comment]
How big is the test process? https://travis-ci.org/piotrek1543/WeatherforPoznan/builds/89500849#L1814 points to possible memory exhaustion.

**Comment by piotrek1543** [comment]
@BanzaiMan Yes, it kills emulator before it starts, because of out of memory. My question is: is it possible to configure .travis.yml in that way to run ONLY Espresso UI tests on emulator without this problem? 

MaybeI should instead of "wait-for-emulator" method, choose an alternative method. 
Notice it takes a lot of time (more than one minute). Also resources

**Comment by ardock** [comment]
@piotrek1543  move these tasks here, so you avoid to run simultanously heavy tasks like start the emulator and download dependencies, and your build doesn't depend on external variables like the network connectivity. you can run /gradlew test for unit tests. And assembleDebug and assembleAndroidTest if you dont need to build all.

```
install:
  - ./gradlew --version # Show version and download Gradle Wrapper when is not present in cache
  - ./gradlew clean # Clean project and download Android dependencies when are not present in cache
```

You can find scripts for travis-ci in the fork we talked these days, use what you want. I added rules for disable animations, the ttt-aaa branches. I use an alternative wait-for-emulator script and I add sleep time because is still busy for a phew seconds after the script exits.

**Comment by piotrek1543** [comment]
@ardock, could you put here your sample configuration file to make it more clear ? :-)

I understand that all heavy tasks like running emulator I should put in "install" section, but I would like to see how does it look whole .travis.yml config file and how you disabled animations ;-)

**Comment by ardock** [comment]
No, the idea is to move that two lines I said to the install section so are executed **before** the other.

If you move all, they'll run in parallel because the **&** does that command run in the background.

Run in parallel is faster but if you are running out of resources this can help to avoid your issue.

The emulator is still busy after you exit the wait-for-emulator loop, you can see it locally, and you are just downloading the dependencies at the same time.

Alternatively you can add `sleep 60s` after to send the key event and see if it helps or change the seconds to sleep.

[Caching the dependencies](http://docs.travis-ci.com/user/languages/android/#Caching) would help for next builds too.

No, I said what i said because I'm not going  to comment more here, we already talked about that, I just created an issue in my fork explaining my changes and you are already familiar with that sample.

Cheers.

**Comment by piotrek1543** [comment]
@ardock ok, thanks
