### ISSUE TITLE
unhide .travis.yml

### ISSUE THREAD

**Issue by igagis** [travis-ci/travis-ci#5108]
Allow having travis.yml file instead of .travis.yml to configure travis-ci.

It is in most cases unconvenient to have .travis.yml file hidden and what is the reason to hide it?

**Comment by joshk** [comment]
I have been thinking about this recently, and am in favour of it.

Thanks for opening this.

**Comment by jasonkarns** [comment]
Agreed. Configuration files should be visible

**Comment by jasonkarns** [comment]
The simplest fix is to just support both .travis.yml as well as travis.yml. However, I think a more robust approach would allow projects to configure the path of the file. Perhaps in the project's dashboard or env var. This way projects could place travis.yml in a `/config` directory of their choosing.

**Comment by joshk** [comment]
Thanks for the suggestion @jasonkarns 

If we are to make a change it would be that `travis.yml` would be fetched first, otherwise `.travis.yml`. We would also update docs, and add extra information to the log so people know of the change, but that it isn't a breaking one.

We will not be making this configurable in the foreseeable future as we believe having a convention out weighs the need for configuration.

**Comment by nemchik** [comment]
Just noticed #5519 was closed as a variation of this issue. I would like to express further interest in the described method in #5519 allowing locations such as `.github/.travis.yml` since that is not explicitly mentioned here yet.

**Comment by BanzaiMan** [comment]
@nemchik Hello, there. Thanks for the comment.

We will be moving our issues discussion to https://travis-ci.community/. In particular, we will discuss this "`.travis.yml` in a configurable location" feature request in https://travis-ci.community/t/allow-to-host-travis-yml-configuration-externally/512.

**Comment by puneetkaursidhu** [comment]
was the change suggested by @joshk implemented?

**Comment by netsettler** [comment]
I think @jasonkarns stated it correctly, that config files required for the build should be visible. My personal reasoning is this: 

There is a contention here between two desires: one is to reduce clutter (so people want things that are seldom used out of sight), the other is a desire to see configurations in a unified place (presumably so they are easy to find when needed). Those would seem to be aesthetic preferences and people naturally differ on those. But I argue not.

The clear tie-breaker, the reason this is not just an aesthetic balance issue, is this: Certain kinds of semantic changes, to be complete, demand changing this file. It's an easy-to-overlook step that leads to program error because when files are invisible and people are using the `ls` or `dir` command to mentally remind themselves of the steps that need happening, it won't show up. 

As an example, let's say, for example, as is going on now for me, we're upgrading from use of `buildout` to use of `poetry`. This means you can get done with a conversion and forget to update this.  It checks out OK locally, and you don't end up finding out until a wasted run on travis that clutters the travis build history, adds extra time, and makes the programmer look like they are not meticulous, but really what has happened is that the travis design has worked hard to tee up this error. It's understandable how we got here, but it seems clear in my mind that travis should err on the side of not helping other tools to hide a need for a semantic change. 

Semantically critical features should not be invisible just to suit someone's view that this is clutter. It's not clutter. We would not put a critical but long-ish and mostly-well-debugged algorithm in `.key-algorithm.py` just because it was big and didn't suit someone's sense of what they wanted to see every day in a directory listing. We'd end up having to two two directory listings every time we needed to see what was going on. And I tire of doing `ls -dal .??*` to see what files might have gotten tucked away.

This is the kind of stuff that belong sin the root directory, which is generally a collection of the pieces needed to fully integrate a piece of software in a semantically useful way with the array of tools and systems it must interact with. 

(Another neutral example, in case you want to reason through the concept I'm laying out, is that `.gitignore`'s control of invisibility is itself invisible. This is a similar source of annoyance to me because this has gigantic semantic implications when someone doesn't check something in because it didn't show up in `git status`, and it really needs to be visible as an important thing to change in some circumstances. I get why people are used to thinking of this as a simply aesthetic matter, but if you think back, you've probably been bitten by failure to update this seemingly minor file, and it's probably traceable to this choice to put it out of sight. It's just not the same kind of thing as the `.git` directory, which people don't need to know about because it's properly tracking metadata that is a consequence of, not the driver of, the application's semantics. Again I get why people would rather hide this file, but I've com to the point of believing that it needs to be visible, too, and for the same reason as I'm saying here. It's an important semantic part of the definition of the project's integration with other tools.)
