### ISSUE TITLE
after looking much don't find any concret example of a new configuration of migration 

### ISSUE THREAD

**Issue by sergiomb2** [travis-ci/travis-ci#5186]
Hi,
Could you point me one dead simple build on new configuration ? 
in this page [1] you talk why , but never how and can't find any howto 

Thanks,

[1] https://docs.travis-ci.com/user/migrating-from-legacy/

**Comment by BanzaiMan** [comment]
https://docs.travis-ci.com/user/migrating-from-legacy/#How-can-I-use-container-based-infrastructure%3F

> How can I use container-based infrastructure? #
> 
> If you see This job is running on container-based infrastructure in your build log it means you are already running builds on our new container-based infrastructure.
> 
> If you don’t, to use the new infrastructure add the following line to your `.travis.yml`:
> 
````yaml
sudo: false
````

**Comment by sergiomb2** [comment]
I added sudo: false , now I'm getting errors on : 
apt-get
What should I do ?

**Comment by BanzaiMan** [comment]
@sergiomb2 Immediately below that section, you see https://docs.travis-ci.com/user/migrating-from-legacy/#How-do-I-install-APT-sources-and-packages%3F.

**Comment by sergiomb2** [comment]
thanks , now btw I got a strange error: 
Disallowing packages: libflickcurl-dev, libgphoto2-2-dev, liblensfun-dev, liblensfun-data, libosmgpsmap-dev
which makes fails the builds with :

configure: error: Package requirements (lensfun) were not met:

No package 'lensfun' found

**Comment by BanzaiMan** [comment]
Please read the documentation shown in the build log. It tells you to follow the process shown in https://github.com/travis-ci/apt-package-whitelist#package-approval-process.

Since this is a documentation issue, and there is nothing further to address, I'm closing this.

**Comment by sergiomb2** [comment]
Still miss an example like : 
https://github.com/sergiomb2/rawstudio/blob/master/.travis.yml

**Comment by BanzaiMan** [comment]
@sergiomb2 I'll copy and paste the process described in the document.

## Package approval process

**PLEASE READ CAREFULLY!**

0. Check the list of approved packages for your build environment (most likely [`ubuntu-precise`](./ubuntu-precise)).
0. If it's not in there, check for existing [issues](https://github.com/travis-ci/apt-package-whitelist/issues)
   and [pull requests](https://github.com/travis-ci/apt-package-whitelist/pulls) requesting the package you
   want, and if one doesn't exist please
   open an issue requesting the package you need in the [this
   repo](https://github.com/travis-ci/apt-package-whitelist/issues/new?title=APT+whitelist+request+for+___PACKAGE___)
   (and be sure to replace `__PACKAGE__` in the issue title).

0. Currently, we are in the process of automating request approval process.
  1. This means that the issues' subject should follow exactly the one indicated.
  That is, there should be **exactly one package** per issue.
  The process would not work with multiple package requests in one issue.
  1. If the source package defines multiple packages, those will be processed at once.
  In this case, list only one.
0. PRs are not accepted, since we have not run tests on them.
0. The automation process will test the source package as described below.
  1. If no issues are found, a PR will be opened, and it will be merged shortly thereafter.
  1. If no matching source packages is found, a comment indicating this is posted on the issue.
  This means that either the package name is incorrect, or that your request requires
  a package repository that is not currently listed in [APT source whitelist](https://github.com/travis-ci/apt-source-whitelist).
  1. The command

    ```shell
    grep -R -i -H -C5 -E --color 'set(uid|euid|gid)' --exclude install-sh .
    ```

  is run on the source package.
  If any file matches, a comment to this effect will be posted on the issue, prompting further examination.
  If no further problems are found in the further examination, it will be added to the list.
