### ISSUE TITLE
Travis not running the input commands under `script:`

### ISSUE THREAD

**Issue by danyaljj** [travis-ci/travis-ci#5191]
Here is my script for `.travis.yml`: 
```
language: java

script:
  - mvn -pl lbjava package
  - cd lbjava-examples; sh compileLBJ.sh; cd ..
```

The code does not seem to follow my commands and it seems like it is running `mvn test`. 
Any ideas how to fix it?

**Comment by BanzaiMan** [comment]
This is intended behavior. From https://docs.travis-ci.com/user/deployment/script:

> `script` must be a scalar pointing to an executable command. If you need to execute multiple commands, write a wrapper script that does all the work for you. Be sure to make the script executable.

**Comment by BanzaiMan** [comment]
Oops. Sorry, my previous comment was completely unrelated.

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem?

**Comment by danyaljj** [comment]
Here is the log: https://travis-ci.com/IllinoisCogComp/lbjava 
Although it it is probably not very informative; it just runs `mvn install`, which is not what I want. How can I forced it to run my commands, before running `mvn install`?

**Comment by BanzaiMan** [comment]
@danyaljj The builds are terminating with an error because `mvn …` command fails 3 times before the build can move on to the next step in the build, which is `cd …`. In particular, the `LBJavaExamples` phase is problematic. Please fix that, and you should be OK.

This is intended behavior. If you want to ignore this error and move on, you can append `|| true` to the `mvn` command to force an exit status of 0 on the command.

I'm closing this, since it is working correctly. If you need extra help, email us at support@travis-ci.com. Thanks.

**Comment by danyaljj** [comment]
@BanzaiMan  The issue is that I need  to run `mvn install` or `mvn compile` or `mvn test`. My scripts are supposed to generate some files which are necessary for `mvn ...`. 

I tested it with Semaphore with the following commands and it passes the test: 

<img width="515" alt="semaphore" src="https://cloud.githubusercontent.com/assets/2441454/11536298/74ac49e2-98dd-11e5-8352-90b8159e28f8.png">

**Comment by BanzaiMan** [comment]
@danyaljj That is very peculiar; the log says it is compilation failure due to symbols being unfound. Where are those missing symbols found?

With an intimate knowledge of the application, you are in a better position to resolve this issue.

**Comment by danyaljj** [comment]
The reason is that it does not run what I wanted (which is `cd lbjava-examples; sh compileLBJ.sh; cd ..`). 
This script is supposed to auto-generate some java files which will be used in the compilation step.

**Comment by BanzaiMan** [comment]
@danyaljj Am I correct to understand that `cd lbjava-examples; sh compileLBJ.sh; cd ..` is a prerequisite to compiling the sources? If so, why are you running that *after* `mvn …`?

**Comment by danyaljj** [comment]
You are partially correct.  The code is a multi-module maven project, and one module is dependent on  `cd lbjava-examples; sh compileLBJ.sh; cd ...` (so you cannot compile **the whole project** without running this).  On the other hand, `cd lbjava-examples; sh compileLBJ.sh; cd ..` is dependent on another **single** module `lbjava` (that's why `mvn -pl lbjava package`). 
Therefore the correct steps for running the code are (the same steps I had for Semaphore)
 1.  `mvn -pl lbjava package`: Compiles a single module, not the whole code. 
 2.  `cd lbjava-examples; sh compileLBJ.sh; cd ...`: generates some java files for other modules. So the whole code wouldn't compile without running this.  
 3.  `mvn test` or `mvn compile` or `mvn test` or any code which compiles the whole code.

**Comment by BanzaiMan** [comment]
Ah, I see what is going on here.

The actual command failing is `eval mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`, which is the default "install" command, since your app is a maven project (https://docs.travis-ci.com/user/languages/java#Dependency-Management).

If you don't need to run this command, you can override it with:

```yaml
install: echo "skip" # or anything that returns 0 status
```

Try this, and close it if it works for you.

Sorry for the confusion.

**Comment by danyaljj** [comment]
Yup! Fixed. Thanks!
