### ISSUE TITLE
Perl v5.20 Critical Failure

### ISSUE THREAD

**Issue by wbraswell** [travis-ci/travis-ci#5226]
My builds started failing today on Perl v5.20 only:

https://travis-ci.org/wbraswell/rperl/jobs/95123818#L124

The following error message should never appear, there should never be a problem looking for 'strict.pm', it is built into the Perl core itself.  This is a serious configuration problem with Perl or the Travis-CI virtual machine itself.

`Can't locate strict.pm in @INC`

You can see all the other versions of Perl (even the new v5.22) are working fine:

https://travis-ci.org/wbraswell/rperl/builds/95123812

**Comment by eserte** [comment]
Me too: https://travis-ci.org/eserte/bbbike/jobs/95150409#L124

As a workaround, you can switch to "5.20-shrplib", which also provides Perl v5.20.

**Comment by BanzaiMan** [comment]
This is a packaging issue on our side. When I created the 5.20.3 archive a while back, it did not set up the alias correctly, so that `5.20` was not recognized correctly. Specifying `5.20.3` should work right now. I am repackaging `5.20` to fix this, but the problem would persist until new image is provisioned and deployed.

**Comment by wbraswell** [comment]
@BanzaiMan 
Seems to be working for me now, thanks!
:+1:
