### ISSUE TITLE
precise/multiverse missing [precise-gce]

### ISSUE THREAD

**Issue by eserte** [travis-ci/travis-ci#5228]
The new precise-gce environment does not seem to include the precise/multiverse repository anymore.

To reproduce: add ` - sudo apt-get install -qq agrep` to .travis.yml. This used to work before two days.

Workaround:
```
 - echo "deb http://de.archive.ubuntu.com/ubuntu/ precise multiverse" | sudo tee -a /etc/apt/sources.list
```

**Comment by eserte** [comment]
May be related to https://github.com/travis-ci/travis-ci/issues/4979.

**Comment by tresf** [comment]
FYI, for those having build failures since Travis transitioned to Trusty 14.04 (was previously Precise 12.04):
 * If you are seeing errors grabbing standard packages already in `universe`, try adding

   ```yml
   - sudo apt-get update -qq
  ```
  to the script per [installing-dependencies/#Installing-Ubuntu-packages](https://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages)

Builds that would previously succeed in Precise 12.04 require the `sudo apt-get update` directive on the newer Trusty 14.04 environment.

**Comment by meatballhat** [comment]
The safest way to operate is to always include `apt-get update`, and in cases when the apt lists cache is warm, this operation should be fairly quick.  That being said, the current `group: edge` images were baked after this change: https://github.com/travis-infrastructure/packer-templates/commit/635d5a1a53fce9ecbffb9dfbd4aa68746a810cbe, which changes the default behavior to *not* remove the apt lists cache.  Pointing at `group: edge` should be relatively safe, and hopefully in the next day everyone on `group: stable` (the default) will also see this change.
