### ISSUE TITLE
Universe source and repository update

### ISSUE THREAD

**Issue by loli** [travis-ci/travis-ci#5244]
Hello,

my last build just failed at the line

    sudo apt-get install python-scipy

signaling

    E: Unable to locate package python-scipy

After preceeding the line with 

    sudo apt-get update
everything runs fine.

Can it be, that after enabling the *universe* package source for precise an update has been forgotten?

Best,
loli

**Comment by meatballhat** [comment]
@loli Thanks for the report!  In order to ensure the APT package list cache is in good shape, you should run `sudo apt-get update`.  One of the optimizations made during the switch to GCE included wiping the APT package list cache before imaging, which is now being reconsidered.  If we end up leaving the APT package list cache in place, it will still be a good idea to run an `apt-get update`, but doing so *should* take considerably less time.
