### ISSUE TITLE
TRAVIS_COMMIT does not update when restarting a PR build

### ISSUE THREAD

**Issue by jawshooah** [travis-ci/travis-ci#5365]
Related: #2666

`TRAVIS_COMMIT` does not update when restarting an existing PR build. This causes problems when the target branch has been updated between the old build and the new one. Here's an [example][broken-build].

[broken-build]: https://travis-ci.org/caskroom/homebrew-cask/jobs/99053987#L2592-L2594

**Comment by BanzaiMan** [comment]
How is your issue different from #2666?

**Comment by jawshooah** [comment]
On second look, it's not. Sorry for the dupe. Still annoying though! :stuck_out_tongue_closed_eyes:

**Comment by jawshooah** [comment]
Well, there is a slight difference: in my case, `TRAVIS_COMMIT` is not updated upon restarting the build. In #2666, @hamiltont reports that `TRAVIS_COMMIT` is not updated between different *jobs* in the *same build*.

Probably the same root cause, but there is a difference.

**Comment by roidrage** [comment]
This is by design, you might say. Builds are distinct resources, and in some ways immutable, which includes the commit range and commit reference that belongs to a build.

If the target branch is updated, we'd recommend pushing a new commit to the branch the PR is sent from or to close/open the PR. I realize this isn't the most convenient way to solve this issue, but it's the most feasible at the moment.

Thank you!
