### ISSUE TITLE
No matching distribution found for mysql-connector-python

### ISSUE THREAD

**Issue by matt-bernhardt** [travis-ci/travis-ci#5369]
I'm not entirely sure that this is related to the precise-gce project, but that is my most likely cause at the moment. All of my test runs on Travis, across branches, are now failing with the following output:

https://travis-ci.org/matt-bernhardt/trapp/jobs/99208251#L141

```
Collecting mysql-connector-python==2.0.4 (from -r /home/travis/build/matt-bernhardt/trapp/requirements.txt (line 2))
  Could not find a version that satisfies the requirement mysql-connector-python==2.0.4 (from -r /home/travis/build/matt-bernhardt/trapp/requirements.txt (line 2)) (from versions: )
No matching distribution found for mysql-connector-python==2.0.4 (from -r /home/travis/build/matt-bernhardt/trapp/requirements.txt (line 2))
```

This applies even to older builds that passed several weeks ago - when I navigate back and refresh them, the build now fails with this message.

It is entirely possible that I'm missing something obvious here - so I'd appreciate any guidance. I recently tried bumping mysql-connector versions up to 2.0.4, which is the current version listed here:

https://pypi.python.org/pypi/mysql-connector-python

**Comment by BanzaiMan** [comment]
If you run this on your machine locally, does it find the version 2.0.4?

**Comment by BanzaiMan** [comment]
The build that now fails from 10 days ago (https://travis-ci.org/matt-bernhardt/trapp/jobs/97801915) is not running on the new infrastructure, so I doubt that this is a problem with the new setup.

**Comment by matt-bernhardt** [comment]
The tests pass with no problems on my local machine. Until this failure started occurring, I hadn't tried updating any version strings for MySQL (I have now, in a feature branch).

**Comment by matt-bernhardt** [comment]
I'm not sure what to make of this, but I managed to get the tests to pass on Travis by switching to a slightly different package. This is the commit that resolved the issue:

https://github.com/matt-bernhardt/trapp/commit/7934c301348826204347c3a622e82ef456b2624e

From mysql-connector-python, I'm now using mysql-connector-python-rf. I don't have an explanation for why the previous library stopped working, but this one now does, both locally and on Travis - so I'm happy for this to be closed?

**Comment by BanzaiMan** [comment]
Great to hear.

**Comment by kiidbrian** [comment]
mysql-connector-python-rf solved this problem for me

**Comment by gotgenes** [comment]
This is an error on the part of the package maintainers for mysql-connector-python. [Here is the relevant issue filed against that package's bug tracker.](http://bugs.mysql.com/bug.php?id=76063) Note that [PyMySQL](https://github.com/PyMySQL/PyMySQL) appears to be a complete drop-in replacement, as a pure-Python MySQL driver that implements the Python DB API 2.0 specification. Additionally, PyMySQL appears to be both actively maintained, uploaded to PyPI (as opposed to hosted on external URLs), and is under the more generous MIT license (as opposed to the GPLv2 license).

Note that mysql-python-connector-rf is not from the mysql-python-connector package maintainer. It is a community member who has created a new "package" to put up a PyPI-hosted distribution of that package so it is installable by pip, thus working around the package maintainer. This is probably against the mysql-python-connector package maintainer's will, since he stated in that issue linked above that he only wants the files hosted externally, not on PyPI.

Taking all this in consideration, I would strongly suggest switching to PyMySQL. Hope this helps.

**Comment by JivanAmara** [comment]
I can confirm PyMySQL appears to work as a drop-in replacement with the slight difference of operations being contained in an extra package for mysql-python-connector.  i.e.
import pymysql
replaces
import mysql.connector

**Comment by juliusakula** [comment]
install **mysql-connector-python** without pip -- > http://stackoverflow.com/questions/31748278/how-do-you-install-mysql-connector-python-development-version-through-pip
