### ISSUE TITLE
npm deployment running multiple times

### ISSUE THREAD

**Issue by louy** [travis-ci/travis-ci#5435]
Consider this build: [urbanmassage/node-rabbitr#49](https://travis-ci.org/urbanmassage/node-rabbitr/builds/101524427).

If you take a look at each job, you'll see that the deployment step was run (and failed for 4 out of 5.)
I believe this isn't the desired behaviour. I have no way to avoid it.

**Comment by BanzaiMan** [comment]
Please see https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A to restrict your deployment to only one job.

**Comment by nknapp** [comment]
Is there a way to configure travis such that the deployment takes place after the tests have passed for *all* platforms. If the tests fail for either node 4 or node 5, I don't want the new version on npm.

OK, since the tagged commit usually only consists of the version bump, and all other commits have already been checked before, this is probably not such a big issue. If there is a way, I would like to know though.

**Comment by BanzaiMan** [comment]
@nknapp See https://github.com/travis-ci/travis-ci/issues/929.

**Comment by nknapp** [comment]
Ah, thank you.
