### ISSUE TITLE
postgreSQL 9.4 without postGIS on trusty beta

### ISSUE THREAD

**Issue by cvvergara** [travis-ci/travis-ci#5445]
The documentation claims that
"All available versions of PostgreSQL come with PostGIS 2.1 packages preinstalled."
https://docs.travis-ci.com/user/using-postgresql/#Using-PostGIS
but its not finding it on 9.4
I have a test here: 
https://travis-ci.org/cvvergara/pgrouting/builds/101918893
all versions run the same script, when doing a
$ locate postgis.control
it only finds for the versions 9.1, 9.2 & 9.3
https://travis-ci.org/cvvergara/pgrouting/jobs/101918897#L643

**Comment by BanzaiMan** [comment]
Paging @gildegoma

**Comment by gildegoma** [comment]
I've verified the three kinds of environments (Precise GCE, Precise Docker/AWS and Trusty GCE).
The problem is only present in the Trusty Beta environment.

![postgresql-9 4-postgis-2 1](https://cloud.githubusercontent.com/assets/434654/12310168/0b106cf0-ba4f-11e5-9255-55edc8a3df11.jpg)

@cvvergara do you absolutely need Trusty (Ubuntu 14.04, gcc-4.8,...) _now_ for this project?

@meatballhat I guess the gap is somewhere in the Packer template references to travis-cookbooks (git sha, or any attribute overrides?). Could you please have a look at this? (I am not familiar with these parts). Thanks :smile:

**Comment by BanzaiMan** [comment]
@gildegoma Could you try it with `group: edge` on Trusty?

**Comment by cvvergara** [comment]
@BanzaiMan 
I will try
The thing is that I have to test on all possible environments, OS, windows, centos etc, because pgrouting is an extension of postGIS

**Comment by cvvergara** [comment]
btw, I just added a line on the before script and I am using postgis now
 - sudo apt-get install -y postgresql-9.4-postgis-2.1

**Comment by gildegoma** [comment]
@BanzaiMan [done](https://travis-ci.org/gildegoma/travis-ci-inspector/builds/102229800) (build not started yet)

@cvvergara sure, `sudo apt-get install -y postgresql-9.4-postgis-2.1` is the easiest workaround (just weird the state of the Trusty Stable image...)

**Comment by cvvergara** [comment]
@BanzaiMan your build passed, I am removing the installing postGIS line and will see what happens

**Comment by cvvergara** [comment]
@BanzaiMan 
Thanks, closing.

**Comment by cvvergara** [comment]
Sorry, It still not working I thought it pssed.
https://travis-ci.org/cvvergara/pgrouting/jobs/102233506

**Comment by gildegoma** [comment]
@BanzaiMan I think that the build referred by @cvvergara is irrelevant, see https://github.com/cvvergara/pgrouting/commit/81a4c8ff1ad5f9ca587d0d3feecbcb1d37c030aa.

**Comment by cvvergara** [comment]
oh, yes I forgot (I had a long night and I was half asleep and forgot the `group: edge`, but today I am fresh as a lettuce!!!

adding  `group: edge` solves the issue.
https://travis-ci.org/cvvergara/pgrouting
(345) 
Thanks for everything. Closing.

**Comment by gildegoma** [comment]
@cvvergara cool :smile:
