### ISSUE TITLE
ChkTeX version old

### ISSUE THREAD

**Issue by khatchad** [travis-ci/travis-ci#5513]
On Travis:
>$ chktex -W
ChkTeX v1.6.4 - Copyright 1995-96 Jens T. Berger Thielemann.

On my notebook:
>$ chktex -W
ChkTeX v1.7.4 - Copyright 1995-96 Jens T. Berger Thielemann.
Compiled with POSIX extended regex support.

Can it be upgraded?

**Comment by BanzaiMan** [comment]
What is `chktex`? Do we provide support for this tool? Do you have a build log URL to show the problem?

**Comment by BanzaiMan** [comment]
Looking at repositories that has this command, https://github.com/search?l=&o=desc&q=%22chktex%22+filename%3A.travis.yml&ref=advsearch&s=indexed&type=Code&utf8=%E2%9C%93, I think that you are using `apt-get` to install `chktex` on Precise. The version of `chktex` available for Precise is 1.6.4 (http://packages.ubuntu.com/precise/chktex), so that's the latest you can get.

Trusty has a newer version (1.7.2; http://packages.ubuntu.com/trusty/chktex), so if you need features of that version, I suggest using that instead. https://docs.travis-ci.com/user/trusty-ci-environment

I'm closing this, since there is nothing for us to do.

**Comment by khatchad** [comment]
Even with the trust distro, I am still getting the same version of chktex.

**Comment by khatchad** [comment]
Ah, nevermind. I added `sudo: required` and it worked.
