### ISSUE TITLE
Environment Variable TRAVIS_JOB_ID Incorrect

### ISSUE THREAD

**Issue by clarkmalmgren** [travis-ci/travis-ci#5570]
Within the last few days, my builds started failing and I have seemed to track it down to an mismatch of the `TRAVIS_JOB_ID`.

Here is an example build: https://travis-ci.org/clarkmalmgren/ezdocker/builds/106907018

The build is failing because when trying to upload the coverage to coveralls, it fails because it can't find a repository for the job.  After adding some additional logging in my gulp build file, I found that the job id in the environment variable is off by one (106907019 instead of 106907018).

![image](https://cloud.githubusercontent.com/assets/5323689/12806248/40778214-cad2-11e5-942e-16b247eec8e4.png)

I thought something must have changed so I re-ran an old build (that had previously succeeded) and got the same exact issue.

The project source is here: https://github.com/clarkmalmgren/ezdocker

**Comment by BanzaiMan** [comment]
Your URL points to a build, which has id 106907018, and you are looking at a job, which has id 106907019, belonging to that build. It might be confusing for a 1-job build, but this is expected behavior. (That these ids are off by 1 is a coincidence.)

I am not sure why your build started failing, but the fact that the previously passing build now fails means that there is something else at play.

**Comment by clarkmalmgren** [comment]
@BanzaiMan that was extremely helpful information, I am going to close out the issue and continue my investigation.  Thanks!
