### ISSUE TITLE
Travis cache directories doesn't work for maven

### ISSUE THREAD

**Issue by krzyk** [travis-ci/travis-ci#5577]
Since some time caching of mavens `$HOME/.m2/repository` stopped working, all dependencies are being downloaded in each build.

Example build: https://travis-ci.com/teamed/xockets-layer/jobs/32213372
.travis.yml contains:
```
cache:                                                                          
  directories:                                                                  
    - $HOME/.m2                                                                 
```

**Comment by BanzaiMan** [comment]
From what I understand, you do not usually build push builds on this repository. This ages the cache your PR builds can use, and eventually the cache expires after some time (45 days as of this writing), and it gets deleted. This is bad news for the PR builds (such as the one you indicated), which cannot find the cache on the first try.

Unfortunately, it is not possible for us to expire the cache based on access time (because of the cache object store). So for now, we suggest running a push build every now and then, and create a new cache for subsequent PR builds.

Thanks.

**Comment by krzyk** [comment]
@BanzaiMan What do you mean by "push builds"?

**Comment by krzyk** [comment]
@BanzaiMan wouldn't a build that puts data inside the cache make this problem disappear? Because it doesn't, each build downloads a new set of artifacts and put them to the cache directory.

**Comment by BanzaiMan** [comment]
@krzyk I was a little hasty to diagnose the problem this way. The cache aging is a problem, but it does not apply here. Sorry about the confusion. (You can ignore this issue.)

Your case, it turns out, is one with the race condition of sorts. You have 2 jobs in the build matrix, one with Linux and another with OS X. Since the two does not have any differentiating factors when it comes to cache names, they are pulled from and pushed to the same location. The OS X job typically finishes last, so that is the one that persists. Your Linux job, then, pulls the cache created by the OS X job, but that does not contain things in `/home/travis/.m2`, so your Linux job has to download everything on each build. (This is basically the issue raised in #5460.)

**Comment by krzyk** [comment]
@BanzaiMan Thanks, that makes more sense :)
