### ISSUE TITLE
Error 137 on Android builds which previously passed

### ISSUE THREAD

**Issue by brarcher** [travis-ci/travis-ci#5582]
Today failures on [this project](https://travis-ci.org/brarcher/budget-watch) are now being observed. Specifically the failure seems to be occurring while downloading artifacts before running unit tests. The failures manifest as the following error message:

```
Process 'Gradle Test Executor 1' finished with non-zero exit value 137
```

No further information is provided. [This issue](https://github.com/travis-ci/travis-ci/issues/4192) mentioned the issue may be relating to the memory available on the host. The failures have been persistent since they started, so it may be that the hosts have been running memory intensive tasks for quite some time.

Considering that the issue may be limited disk space, a build was attempted which no longer uses an android emulator. However, the build continued to fail in the same way.

It is possible that there was a recent change to the backend which reduced the amount of memory available for a job, or have increased the number of jobs running on a host? Is there a way to avoid this issue?

**Comment by brarcher** [comment]
I found that by forcing the build to not occur on containerized executors that the issue is avoided. This is achieved by adding the following to the top level of the .travis.yml configuration:
```
sudo: true
```
If this solution is sufficient and the issue will not be further investigated, this issue can be closed.

**Comment by Nava2** [comment]
Our project has also stopped building due to the memory issue. This is recent, I have rerun previous builds directly and they now fail on Linux. 

We do not run Android, but we do use Ant+Java to run the project ([umple/Umple](https://github.com/umple/Umple)). 

The build passes on OSX and we do run on the container infrastructure. I will try to change to the non-container infrastructure and see if it removes the issue.

**Comment by BanzaiMan** [comment]
This is probably a variation of #4192 and other previously reported issues where a container build gets killed because it (or a build that shares the VM with that build) consumes too much memory and gets terminated by the host.

**Comment by Nava2** [comment]
@BanzaiMan The problem is that these builds passed previously. I actually reran one of the builds thinking that it might be a fluke and it started failing. This [build](https://travis-ci.org/umple/umple/builds/106611697) originally passed. 

Could it be that we've hit a cusp where it is good on one side and bad on the other?

**Comment by bobjacobsen** [comment]
#5597 is about something similar.  Hashes that run fine a while ago are now failing. (139 is getting a kill -9, so these are seeing the same end mechanism)

**Comment by bric3** [comment]
Actually we see the same issue on Mockito project, that uses gradle as well. https://github.com/mockito/mockito/pull/349#issuecomment-194295335

Sometime restarting a build make it work.

**Comment by bric3** [comment]
@bobjacobsen Nope `137` is `kill -9`, the common norm is to exit a process with `128 + signal number`, the JVM does that, bash does that. `139` would be a segmentation fault : SIGSEGV (11)

**Comment by HugoGresse** [comment]
I still have the issue and a rebuild didn't seems to work. Any idea?

**Comment by barbeau** [comment]
Try using this script as a template - https://github.com/googlemaps/android-maps-utils/blob/master/.travis.yml.

In the last few SDK tools releases Android has been all over the place, but the above script should capture necessary changes to make it work.
