### ISSUE TITLE
Bioconductor dependencies not installing for R builds

### ISSUE THREAD

**Issue by rcavalcante** [travis-ci/travis-ci#5608]
Hello, @craigcitro, @hadley and @jimhester,

Something seems to have gone wrong with Bioconductor dependencies for R builds. [Build A](https://travis-ci.org/rcavalcante/annotatr/builds/107826947) errors with the following:

```{bash}
Building with: R CMD build 
0.74s$ R CMD build  .
* checking for file ‘./DESCRIPTION’ ... OK
* preparing ‘annotatr’:
* checking DESCRIPTION meta-information ...It is recommended to use ‘given’ instead of ‘middle’.
 OK
* installing the package to build vignettes
      -----------------------------------
ERROR: dependencies ‘GenomeInfoDb’, ‘GenomicRanges’, ‘IRanges’ are not available for package ‘annotatr’
* removing ‘/tmp/Rtmp7QpxxC/Rinst323872853ba/annotatr’
      -----------------------------------
ERROR: package installation failed
```

Build A was preceded by [Build B](https://travis-ci.org/rcavalcante/annotatr/builds/106896110) which originally passed. To figure out if I or travis-ci was at fault, I tried to rebuild Build B, and got the same error as above. That suggests to me that some dependency or code has changed, but I have no idea **what** changed.

Does anybody have any suggestions? Also, if there is a better place to post this, I'm happy to repost there. Thanks.

**Comment by jimhester** [comment]
This is the correct place for the issue.

The problem is the `.Rprofile` in your project directory, it is overriding the `.Rprofile` travis creates in `~/.Rprofile`. You need to either remove your local `.Rprofile` or put `source("~/.Rprofile")` in your local one.

@hadley, @craigcitro maybe we should set the repositories in Rprofile.site instead of `~/.Rprofile` so this doesn't continue to happen. Ran into this same issue with googlesheets https://github.com/jennybc/googlesheets/pull/199#issuecomment-182179058 and it is going to continue to happen if packarat uses a local `.Rprofile` in its template (https://github.com/rcavalcante/annotatr/blob/master/.Rprofile).

**Comment by jimhester** [comment]
I switched to using `.Rprofile.site` with https://github.com/jimhester/travis-build/commit/f893a52f74b2036ee27f12e7bedce0be65f4790e, so this problem should be fixed once that PR is merged and deployed.

**Comment by craigcitro** [comment]
I like the idea of using `Rprofile.site`, since (from a repo owner's POV) this really is travis-site-specific configuration.

**Comment by rcavalcante** [comment]
Thanks for the quick response! I added the suggested source line and the build passes now. I'll go ahead and close the issue.
