### ISSUE TITLE
texi2dvi missing from R build environment

### ISSUE THREAD

**Issue by oneillkza** [travis-ci/travis-ci#5619]
My builds stopped working sometime this week, giving the following error related to texi2dvi being missing:

```
Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'contiBAIT.tex' failed.
Messages:
sh: 1: /usr/bin/texi2dvi: not found
Calls: <Anonymous> -> texi2pdf -> texi2dvi
Execution halted
The command "R CMD build  ." failed and exited with 1 during .
```

Here's an example of a build that worked fine two weeks ago, but failed when I re-ran it today (same code):

https://travis-ci.org/oneillkza/ContiBAIT/builds/106615350

@craigcitro, @hadley, @jimhester, any thoughts?

**Comment by jimhester** [comment]
I know what the issue is, but it won't be fixed until Monday at the earliest unfortunately.

In the meantime you should be able to get your build working by adding

```yaml
before_install:
  sudo apt-get install texinfo
```

Alternatively if you switch to using container based builds that will also fix the issue. Plus you can then use r-devel and install devel Bioconductor packages.

```yaml
r: devel
sudo: false
cache: packages
bioc_use_devl: true
```

**Comment by oneillkza** [comment]
Thanks, seems to be resolved now!

I'll consider the container-based solution in future. Thanks for the tip!
