### ISSUE TITLE
[UX] White text on blue background looks terrible

### ISSUE THREAD

**Issue by ribasushi** [travis-ci/travis-ci#5625]
The following ANSI color output: `echo -e '\e[37;44m Text \e[0m'` [renders really badly](https://travis-ci.org/ribasushi/dbix-class/jobs/109060156#L1321). A much darker blue should be used in the stylesheet.

**Comment by kentfredric** [comment]
I'd recommend something closer to [`#255AE8`](http://www.color-hex.com/color/255ae8)
![img](http://www.colorhexa.com/1251fb.png)
[`#96CBFE`](http://www.color-hex.com/color/96cbfe)  is just an eyesore.
![img](http://www.colorhexa.com/96cbfe.png)

Xterm by default, ( for example ) uses a much darker blue than I've suggested. but I've suggested a lighter one because I've had problems in the past with blue-on-black being just as common and being equally hard to view with a blue that is too dark.

**Comment by ribasushi** [comment]
@BanzaiMan this continues being a major readability problem :/
https://travis-ci.org/Perl5/DBIx-Class/jobs/334373584#L1541-L1544
