### ISSUE TITLE
Travis says that the repo is not active, while this is wrong

### ISSUE THREAD

**Issue by stof** [travis-ci/travis-ci#5629]
https://travis-ci.org/KnpLabs/KnpMenuBundle shows `This is not an active repository`, which is wrong. The repo has Travis enabled since years (and going to the list of builds still display builds properly)

**Comment by roidrage** [comment]
If this repository is indeed still active, then it's likely it was enabled via manual configuration of the GitHub webhook in the GitHub settings for the repositories instead of enabling the hook on the Travis CI account.

This is easy to fix, you just need to go to the profile for KnpLabs and activate it manually. That should make the message disappear.

**Comment by stof** [comment]
Will it detect that the hook is already there or will it duplicate it ?

**Comment by stof** [comment]
And it might be good to let people know about this change, as this is quite new. The fix is easy, but only once you know what is causing it.

**Comment by roidrage** [comment]
It should detect that the hook is already there assuming it was set up with the service Travis CI on GitHub rather than as a generic webhook.

This change was rolled out quite a few months ago (mid 2015 ish), and we've since been interacting with quite a few folks who've reported this, and haven't really had any further reported issues since.

**Comment by whit537** [comment]
FTR, we got bit by this at https://github.com/gratipay/gratipay.com/issues/3988.

> a quick google search shows many matching [results](http://www.google.com/#q=travis+this+is+not+an+active+repository). Can it because of [this](https://github.com/travis-ci/travis-ci/issues/5629#issuecomment-184246684)?

**Comment by stakach** [comment]
This happened to me too. Even though the repository is active, I retro-actively added some tags for things that happened months ago and then travis deactivated.

**Comment by Roasbeef** [comment]
I'm having this issue right now with one of my repositories (https://github.com/lightningnetwork/lnd/). I've activated the repo countless times over the past week, to only have it show as "not active" a few hours later.
