### ISSUE TITLE
Email notification image seems to be broken

### ISSUE THREAD

**Issue by mafagafogigante** [travis-ci/travis-ci#5660]
![screenshot from 2016-02-19 01-54-32](https://cloud.githubusercontent.com/assets/8271090/13166175/d6321104-d6ab-11e5-857e-cdb6acd920af.png)

I don't know if this is an issue with Gmail or a "global" problem. Either way, it would be nice to solve it as it looks really bad and Travis already has a pretty polished interface otherwise. Not to mention that Gmail users are not a small population.

**Comment by maelvalais** [comment]
Hi,

Same problem here. All of my projects have this issue. I also have gmail as email provider. Seems to be a problem in the email template in [`finished_email.html.erb#L313`](https://github.com/travis-ci/travis-tasks/blob/d6bcc9e6a1994189b9544c412f6692912cd90d29/lib/travis/addons/email/mailer/views/build/finished_email.html.erb#L313).

Here is the right image : https://i0.wp.com/travis-ci.org/images/mailer/mascot-avatar-40px.png?ssl=1
Here is what the email shows: 

```html
<img src=3D"?s=3D40&amp;d=3Dhttps%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2=
Fmascot-avatar-40px.png" style=3D"vertical-align:middle;width:40px;height:4=
0px">
```

Here is the template from `finished_email.html.erb#L313`
```html
<img src="<%= @repository.owner.try(:avatar_url) %>?s=40&d=<%= CGI.escape("https://#{Travis.config.assets.host}/images/mailer/mascot-avatar-40px.png") %>"/>
```

Is the branch `travis-ci/travis-tasks:ha-broken-email` on that?

**Comment by sormuras** [comment]
Same problem, other URL.

The mail source says:
```xml
https://ci4.googleusercontent.com/proxy/kH6o0Z2KZ5nSPlLIBE7TNC6OJwjWAGxpoxruy2SCy7hWksZ6IXESXsgLg1YniMCu7V7uNwr82gmbOnc7_pCrSVNiTQ4hY79nBqkzFEGdlAMJUKIqJ6K07P-_a_LzfNpKcn_yzOi9kFHNciU=s0-d-e1-ft#http://?s=40&d=https%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2Fmascot-avatar-40px.png
```

yields a 404 error. The image encoded in the last past of the URL works:

https://travis-ci.org/images/mailer/mascot-avatar-40px.png

**Comment by maelvalais** [comment]
So the problem only seems to trigger when the repository is under users namespaces (ex: github.com/maelvalais/climso-auto). As far as I noticed, this issue does not affect repos under groups namespaces.
Also, I noticed that even though the image (1) is missing, the image (2) works. But they are supposed to be the same thing in the code.
![capture d ecran 2016-05-16 a 10 08 35](https://cloud.githubusercontent.com/assets/2195781/15284066/5429a4a4-1b4f-11e6-8cc3-8475b8fa9c83.png)
(1) in the code of [`finished_email.html.erb#L313`](https://github.com/travis-ci/travis-tasks/blob/d6bcc9e6a1994189b9544c412f6692912cd90d29/lib/travis/addons/email/mailer/views/build/finished_email.html.erb#L313)
```
<img src="<%= @repository.owner_avatar_url %>?s=40&d=<%= CGI.escape("https://#{Travis.config.assets.host}/images/mailer/mascot-avatar-40px.png") %>"/>
```
The corresponding of (1) in my [mail](https://github.com/travis-ci/travis-ci/files/265806/mail_travis_missing_image.txt):
```
<img src=3D"https://secure.gravatar.com/avatar/a91a803ca626cb853e28a28b6edcd330?s=3D15&amp;d=3Dhttps%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2Fmascot-avatar-15px.png">
```

(2) in the code of [`finished_email.html.erb#L328`](https://github.com/travis-ci/travis-tasks/blob/d6bcc9e6a1994189b9544c412f6692912cd90d29/lib/travis/addons/email/mailer/views/build/finished_email.html.erb#L328):
```
<img src="https://secure.gravatar.com/avatar/<%= Digest::MD5.hexdigest(@commit.author_email) %>?s=15&d=<%= CGI.escape("https://#{Travis.config.assets.host}/images/mailer/mascot-avatar-15px.png") %>">
```
The corresponding of (2) in my [mail](https://github.com/travis-ci/travis-ci/files/265806/mail_travis_missing_image.txt):
```
<img src=3D"https://secure.gravatar.com/avatar/a91a803ca626cb853e28a28b6edcd330?s=3D15&amp;d=3Dhttps%3A%2F%2Ftravis-ci.org%2Fimages%2Fmailer%2Fmascot-avatar-15px.png">
```

Although they should show almost the same image from Gravatar, (1) doesn't show but (2) does. Weird, isn't it? I think the problem is with Gravatar or something like that. What is stored inside `@repository.owner_avatar_url`?

**Comment by maelvalais** [comment]
This issue seems to be solved! 👍

**Comment by BanzaiMan** [comment]
Great. Thanks for the confirmation.
