### ISSUE TITLE
Cocopods repository cache

### ISSUE THREAD

**Issue by jcampbell05** [travis-ci/travis-ci#5661]
Does the cocopods cache also apply to their Repo.

Right now on every install I have to wait for travis to install the entire cocoapods repo.

**Comment by BanzaiMan** [comment]
I see that push builds are disabled in your repository in question. As a result, when a new branch is created and a new pull request is opened, there is no cache it can use. The first PR build will have to create a new cache. https://docs.travis-ci.com/user/caching/#Fetching-and-storing-caches

If you want the first build on the PR builds to speed up, please enable the push build on the base branch or the default branch, so that PR builds can use it.
