### ISSUE TITLE
package build crashes on installing covr from github

### ISSUE THREAD

**Issue by markvanderloo** [travis-ci/travis-ci#5713]
@craigcitro, @hadley, @jimhester

I keep getting build error because installing Jim's covr package fails. It appears that the github api refuses to serv travis-ci requests. 

In `.travis.yml`:
```
r_github_packages:
  - jimhester/covr
```

Here's the error I get:

```
The command "Rscript -e 'devtools::install_github(c("jimhester/covr"), build_vignettes = FALSE)'" failed and exited with 1 during 
```

I added `curl -i` to the `.travis.yml` to see what's going on, and I get

```
$ curl -i https://api.github.com/repos/jimhester/covr/zipball/master
HTTP/1.1 403 Forbidden
Server: GitHub.com
Date: Mon, 29 Feb 2016 12:56:17 GMT

[snip]

{
  "message": "API rate limit exceeded for 52.0.240.122. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

I'm out of wits except setting up somehow oAuth from travis, which I'd rather avoid. 

As an aside, I used to do this with a derivative of a script of Dirk E., based on the `language c` directive and strangely enough that never showed this problem. 

Some links: [travis-ci log](https://travis-ci.org/data-cleaning/lintools) | [github repo](https://github.com/data-cleaning/lintools) | [travis config](https://github.com/data-cleaning/lintools/blob/master/.travis.yml)

**Comment by jimhester** [comment]
Yes this is a known transient issue because GitHub's rate limiting is per IP address, so Travis can exceed them. You can wait a few minutes and re-run your build.

To avoid this in the future you can also setup a secure environment variable called `GITHUB_PAT` at https://travis-ci.org/data-cleaning/lintools/settings with a [GitHub personal access token](https://github.com/settings/tokens) generated without any permissions.

**Comment by markvanderloo** [comment]
Thanks Jim, that clears things up!
