### ISSUE TITLE
Xcode 7 Sporadic test timeout issues

### ISSUE THREAD

**Issue by mpsmith** [travis-ci/travis-ci#5743]
I'm seeing 'No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.'   in an iOS/xcode build at the point when it attempts to launch tests that run in the simulator.  I've gone through the approaches mentioned in other issues that recommend things like pre launching the simulator by id (https://github.com/travis-ci/travis-ci/issues/4986) before running xcodebuild, and piping output through xcpretty (https://github.com/travis-ci/travis-ci/issues/4906)  but the timeout still appears sporadically.  I've even taken all my tests out of the test suites to make sure there is not a stall in a particular test.   

I can run the exact same xcodebuild command locally and it passes reliably every time.

(March 4 2015)

**Comment by ariok** [comment]
Same exact issue here.

**Comment by haoming** [comment]
Same issue too.

**Comment by tonystone** [comment]
Same issue here as well.  Tried all the same suggested fixes.

**Comment by rajohns08** [comment]
Same issue here. Running locally works fine, but stalling on travis.

**Comment by haoming** [comment]
I just resolved a timeout issue which happened everytime instead of sporadically. I'd like to share it here in case others have the same issue.

Here it is:
Please make sure that the scheme specified at the xcodebuild command available in the directory like "ProjectName/ProjectName.xcodeproj/xcshareddata/xcschemes/" in your Git repo. It will stall there without any output if the scheme file is absent.

To make Xcode generate those files, please click the target/scheme button (on the right of the run and stop buttons) on the top bar of Xcode, then click "Manage Schemes ...", and tick the "Shared" checkbox in the window.

If the schemes are not shared, the xcodebuild command can run without any problem at your local project on your local machine, because it still can find the scheme on the non-shared data, which are usually listed in the .gitignore file. But when running on travis, xcodebuild will hang there if it cannot find any scheme, neither shared nor non-shared.

**Comment by rajohns08** [comment]
@haoming my scheme was already shared. Could you share you .travis.yml file that is working, so I can compare?

**Comment by haoming** [comment]
Hi @rajohns08, here you go: https://github.com/SwiftyCache/SwiftyCache/blob/master/.travis.yml

**Comment by rajohns08** [comment]
Today I noticed the `xcodebuild` command was even failing on my local machine when running

```
xcodebuild -project JudgecardXSwift.xcodeproj -scheme JudgecardXSwift -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest build test
```

I ended up getting it to work by simply swapping the `build` and `test` command order:

```
xcodebuild -project JudgecardXSwift.xcodeproj -scheme JudgecardXSwift -destination "platform=iOS Simulator,name=iPhone 6s,OS=latest" test build
```

Swapping the ordering fixed the issue on travis also, however be careful because when I also used `xcpretty`, my build failed but travis reported success. So I'd recommend against using `xcpretty`.

**Comment by tonystone** [comment]
To get a solid build script, I ended up with a variation of what @haoming had in his `.travis.yml` (thanks @haoming for submitting that).  

I made several changes to my file:
1) Shortened the entire build job by taking the multiple targets and moving them into a matrix.
2) Using `xcodebuild` instead of `xctool` (Note, xctool is deprecated at this point for building, see https://github.com/facebook/xctool#building)
3) Added a `set -o pipefail` statement before calling `xcodebuild`
4) Piped the output of `xcodebuild` to `xcpretty`   

Here is my `.travis.yml` file for reference https://github.com/tonystone/geofeatures/blob/master/.travis.yml.

**Comment by haoming** [comment]
Thanks for your updates, @tonystone.

The .travis.yml file I shared for the [SwiftyCache](https://github.com/SwiftyCache/SwiftyCache) project was based on https://github.com/onevcat/Kingfisher/blob/master/.travis.yml. I just added a link to Kingfisher in the comment at the beginning of the file.

Hope Tony's changes can help @mpsmith as well.

**Comment by christophgockel** [comment]
Thank you @tonystone! I had the same problem here. My builds always timed out after `[Info] Collecting info for testables...` when using `xctool`. Tried numerous things in the last two days and the only thing that did the trick was switching `xctool` for `xcodebuild`.
+1 for `set -o pipefail`!

**Comment by seivan** [comment]
I get this to. Especially when generating documentation with Jazzy.

**Comment by johnwahlig** [comment]
Same issue here.
