### ISSUE TITLE
CouchDB seems to not be listening on port 5986

### ISSUE THREAD

**Issue by fenollp** [travis-ci/travis-ci#5747]
[Build never ends](https://travis-ci.org/2600hz/kazoo/builds/113848628) because connection to CouchDB on port 5986 is refused.

As I understand though, CouchDB is configured with the defaults and that means has 598**4** opened.

Maybe it is too hidden in the docs that 127.0.0.1:598**6** should be accessible too (it has something to do with the `_users` database).

Could you open this port?

**Comment by BanzaiMan** [comment]
What process is supposed to be listening on port 5986? https://travis-ci.org/2600hz/kazoo/builds/113848628#L187 shows that CouchDB is running and listening on port 5984.

Port 5986 belongs to Windows PowerShell Default psSession Port. https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers

**Comment by fenollp** [comment]
Hm my mistake I was talking about BigCouch, not exactly CouchDB. 

blog.mattwoodward.com/2012/03/definitive-guide-to-couchdb.html?m=1

Would it be possible for Travis CI to provide a bigcouch service?

**Comment by BanzaiMan** [comment]
BigCouch is an application atop CouchDB, right? Can you set it up yourself? Have you tried it? Did you run into problem doing so?

Adding such an application on top of our default CouchDB is problematic, since that will interfere with other users who do not need or expect it.

I am closing this for now, but if you have a strong case to advance it, do let us know.

**Comment by ptitjes** [comment]
@BanzaiMan I'd like that we reopen this issue, not to have BigCouch, but really to have both 5984 and 5986 ports open to the couchdb service. Indeed, it seems that the configuration (`_config/`) is now only accessible on port 5986.
