### ISSUE TITLE
How to add ip address for custom host names?

### ISSUE THREAD

**Issue by laike9m** [travis-ci/travis-ci#5754]
In https://docs.travis-ci.com/user/hosts/, the example shows:
```
addons:
  hosts:
    - travis.dev
    - joshkalderimis.com
```
So, does it mean I could add ip address like this?
```
addons:
  hosts:
    - 1.2.3.4 travis.dev
    - 5.6.7.8 joshkalderimis.com
```

**Comment by BanzaiMan** [comment]
`hosts` addon is for existing IP addresses so that the name can be resolved for IPv4 connections.

If you need to specify a different IP address, you'll have to set up a DNS server somewhere and tell the build machine to query it.

While I don't think such an endeavor is impossible, I do think it is beyond what most of our users need.

**Comment by jarl-dk** [comment]
I'm sorry: I _do_ understand the question here. However I _do not_ understand the answer.
For example if I use
```
addons:
  hosts:
    - travis.dev
    - joshkalderimis.com
```
What IP addresses will I then get when resolving `travis.dev`?

**Comment by AndreasBackx** [comment]
For anyone coming here in the future @jarl-dk, it refers to `127.0.0.1` from what I've found.
