### ISSUE TITLE
UTF-16 Encoding in `.travis.yml` causes incomplete build

### ISSUE THREAD

**Issue by chris-brown** [travis-ci/travis-ci#5818]
Ive tried many [different approaches](https://github.com/chris-brown/OrderedJobsKata/commits/master/.travis.yml) but im still unable to make any progress so im adding my issue here.

Build: https://travis-ci.org/chris-brown/OrderedJobsKata

I've added the same issue on stack overflow without a comment.
http://stackoverflow.com/questions/35689942/travis-unable-to-find-csharp-solution

Help please.

**Comment by BanzaiMan** [comment]
Paging @joshua-anderson @akoeplinger @nterry

**Comment by akoeplinger** [comment]
Thanks for the report @chris-brown, I sent you https://github.com/chris-brown/OrderedJobsKata/pull/1 to fix the build.

The underlying issue was that you committed the .travis.yml as UTF16, converting it to UTF8 fixed it.

@BanzaiMan this sounds like something you should filter on your end, since the build apparently got routed to csharp correctly but in the script we got bogus values, making it totally non-obvious to the user what is happening. Let me know if I should file a separate issue for that.

**Comment by chris-brown** [comment]
ahh thanks @akoeplinger . that was driving me nuts.

**Comment by BanzaiMan** [comment]
Thanks for the report. I'm reopening this, since this is a bug that needs to be fixed.

**Comment by BanzaiMan** [comment]
The job in question has this incomplete configuration:

```
>> j.config
=> {:language=>"csharp", :".result"=>"configured", :group=>"stable", :dist=>"precise", :os=>"linux"}
```

This is a variation of #4839, but, here, `language` value is set correctly, but not much else.

**Comment by chris-brown** [comment]
I closed my SO question for what it is worth. Good to see you re-open this issue @BanzaiMan. im surpised it hasnt caused issues with alot of windows users. Hopefully once this issue is closed then [this answer](http://stackoverflow.com/questions/35689942/travis-unable-to-find-csharp-solution/36252042#36252042) will no longer be relevant. thanks again

**Comment by BanzaiMan** [comment]
The UTF BOM issue was recently fixed.
