### ISSUE TITLE
(Xcode7.3) OSX SIP feature preventing sudo operation on /usr/bin

### ISSUE THREAD

**Issue by weitjong** [travis-ci/travis-ci#5819]
Our OSX CI jobs are running fine under Xcode 7.1. See https://travis-ci.org/urho3d/Urho3D/builds/118453206. When we attempted to switch to Xcode 7.3, however, we encountered an unexpected error. See https://travis-ci.org/urho3d/Urho3D/builds/118422410. The error was caused by these:

```
ln: /usr/bin/clang: Operation not permitted
ln: /usr/bin/clang++: Operation not permitted
```

The `sudo ln -sf` operation should be successful. The only thing that could prevent this from working is the so-called SIP (System Integrity Protection) aka rootless feature in OSX El Capitan. The question is, why is it being turned on now on Xcode7.3 osx_image?

**Comment by emdantrim** [comment]
This featuer is part of El Capitan, and our images prior to `xcode7.2` are not based on 10.11, but rather 10.10. As such, this bug would not appear until 10.11.

**Comment by emdantrim** [comment]
After some discussion with @Lyoness, I'm a bit hesitant to turn off SIP by default in all of our images in the future, when this is something that might be important for developers to assess in their future builds. As of right now, it seems like a better idea to add /usr/local/bin to your build's `$PATH` (if it's not already there?) and then manipulate that directory instead.

Since we support numerous projects that deal with managing systems like this it seems to me like it would be negligent to disable a default security feature that is likely to break the functionality of other folks' programs that will be tested on our system.

Adding an option to disable SIP in a `.travis.yml` would be ideal for all parties who are involved, but sadly our current build image provisioning process would likely not be able to support such a thing.

**Comment by weitjong** [comment]
Thanks for your time to look into this issue. Although I understand the rationale and also why Apple has SIP, but in this case it is just a nuisance. The VM instance is short live and is only used by CI jobs in question. So, what SIP could possibly protect CI job from harming itself?

**Comment by weitjong** [comment]
And also I would argue the SIP will break for CI jobs than the other way around. Our CI jobs work just fine on Xcode 7.1 and we expect them to be so when we upgrade to 7.3. I suppose others would have the same expectation, no?

**Comment by emdantrim** [comment]
I guess my point here is that the build should work with OS security features turned on, not because we care about compromising the VM, but because your project's build needing security features to be turned off to pass is a fault of your project, not of the user's.

The intention of Travis CI is to provide a standard / typical machine on which you can build your project. Turning off SIP could potententially cause builds to pass when they shouldn't. Homebrew comes to mind in this situation -- if Homebrew was, during a build, manipulating files protected by SIP, it would cause their build to pass rather than fail, and potentially cause them to push out software that fails on a fresh install of OS X. Being that Homebrew is useful for installing things other than just developer tools, I'd prefer that nobody -- Homebrew or their users (who may be experienced or inexperienced) -- push anybody else to disable important security features on their workstations for baseline tools to work.

**Comment by jakirkham** [comment]
I'm not sure if I buy this explanation.

One of the features SIP blocks is the use of [`DYLD_FALLBACK_LIBRARY_PATH` and other loader environment variables]( https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/dyld.1.html) in build scripts. This particular environment variable is of value for ensuring the right libraries are loaded even if they can't initially be found through the usual methods. For instance, we use this in [`conda-build`]( http://conda.pydata.org/docs/building/recipe.html ) when running things like `make check`. We of course then run [`install_name_tool`]( http://osiris.laya.com/coding/dylib_linking.html) after to fix up the paths so that `DYLD_FALLBACK_LIBRARY_PATH` is not needed for any installed packages.

SIP blocks this as it [unsets]( http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1 ) this and other `DYLD_*` variables when starting a new shell (as it comes from [`/bin`]( https://support.apple.com/en-us/HT204899 )). This really throws a wrench in very basic things like running [`make check`]( http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1#comment259559_212954 ). So we simply lack the ability to affect them in this way. If we are able to set the `rpath` during build time (`-Wl,-rpath,<path>/lib` or similar on another compiler), then this can avoid some issues. However, for situations where that is not possible, we are left to resort to more extreme measures like fix `rpath`s with `install_name_tool`.

Running `make check` in my mind is the very purpose of CI. However, it sounds like that is going to get harder with having SIP enabled on Travis.

**Comment by solarce** [comment]
While it is unfortunate that SIP being enable does impact some workflows, since it is the OOB experience in recent versions of OSX, we will continue to leave it enabled in our OSX build environments.

**Comment by grigorye** [comment]
Folks, just a thought. Probably it's possible to consider keeping SIP enabled with exception for debugging? I mean, I do understand the rationale about providing "a standard / typical machine on which you can build your project". But it becomes a bit not that clear when we consider *running* unit tests. I'm currently working on a project where unit tests involve (automated) invocations of developer tools (particularly heap(1) and stringdups(1)) that *need* debugging permissions to work correctly (dump  memory content). So I had to enable SIP without debugging like "csrutil enable --without debug", on Macs where heap/stringdups are used with dumping content. Probably a similar thing might be used for DYLD_ as well?

Currently the status from `csrutil status` looks like this:
```
$ csrutil status
System Integrity Protection status: enabled (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: enabled
	Debugging Restrictions: disabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```

**Comment by rgov** [comment]
> I guess my point here is that the build should work with OS security features turned on ... because your project's build needing security features to be turned off to pass is a fault of your project, not of the user's.

With respect, this assumes that all projects need to fit the mold of running in Apple's locked down environment, but there are plenty of reasons why you might not, and as the environment is further tightened, even more projects will find new reasons to opt-out.

My project complies a kernel extension that is unsigned, and the kext signing SIP restriction is an obstacle. I'd rather not have to provide my personal signing key to Travis CI, especially as Apple's own recommendations suggest, "You should sign a kernel extension using a Developer ID certificate only when it reaches its final stages of testing and is being evaluated for release to customers."

I agree that the default SIP state should match the out-of-box experience for most users, but a configuration option for SIP, with the appropriate disclaimers, would be a godsend. The option would correspond to the value of the `csr-active-config` NVRAM variable set on the VM, which is a bitfield:

![CSR config][https://i0.wp.com/osxarena.com/wp-content/uploads/2015/10/csr-active-config.png]

**Comment by rgov** [comment]
@emdantrim Could this be re-opened, please? I think that's more valuable than filing a new bug due to the useful discussion that happened above.

**Comment by BanzaiMan** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks!

**Comment by emdantrim** [comment]
I was not ignoring this, but was on leave for a while and now am on a different project. Sorry, y'all. ❤️

**Comment by DrTorte** [comment]
I've created a new thread [here](https://travis-ci.community/t/issue-xcode7-3-osx-sip-feature-preventing-sudo-operation-on-usr-bin-migrated-from-github-issues/1501) so if you'd like to continue discussing this, it'll be open there. 😄
