### ISSUE TITLE
Spurious failure on OSX build

### ISSUE THREAD

**Issue by joshtriplett** [travis-ci/travis-ci#5830]
See https://travis-ci.org/libgit2/libgit2/builds/119132094 : five out of six builds completed successfully, but one spuriously stalled out.

(Related: how can I tell Travis to retry a build, and where is that documented?)

**Comment by weitjong** [comment]
We have had this issue with our OSX CI jobs too. It appears that OSX build environment is more susceptible to server load than the container-based Linux build environment. From our observation, the same CI job takes longer time to complete during peak hour and occasionally long running process (without outputting anything in between) may get killed just like that. To prevent that, we have even write a small ruby task just to outputting a '.' in a separate process just to keep the main process alive. However, this is still not bulletproof because we cannot guard all the build processes with this approach.

IMHO, for this case, automating a build retry will make the matter worse. The server load is already high as it is when in happened. I think what Travis team needs to analyze is how to make the OSX less susceptible to the load. i.e. if my job finish within 30 minutes then it should be able to guarantee that it would finish in 30 minutes no matter what times my job runs.

**Comment by BanzaiMan** [comment]
Email us at support@travis-ci.com and we'll get you set up with a debug VM, so you can investigate interactively.

**Comment by BanzaiMan** [comment]
Closing this. If you haven't done so already, please send email to support@travis-ci.com.
