### ISSUE TITLE
Merge Build Race Condition

### ISSUE THREAD

**Issue by deckar01** [travis-ci/travis-ci#5882]
Repro:
1. Open a pull request from one Travis enabled repo (origin/branch) to another (upstream/master).
2. Wait for the build to pass.
3. Commit a breaking change (commit A) to the (origin/branch) branch.
4. Push the (origin/branch at commit A) branch to the (origin) repo.
5. Quickly commit a working change (commit B) to the (origin/branch) branch.
6. Quickly push the (origin/branch at commit B) branch to the (origin) repo.

Behavior:
- Step 4 causes builds to start for (origin/branch at commit A) and (upstream/master at merge commit A').
- Step 6 causes builds to start for (origin/branch at commit B) and (upstream/master at merge commit B').
- The build for (origin/branch at commit A) fails as expected, but the build for (upstream/master at merge commit A') passes even though the merge commit it references contains a breaking change.

Expected behavior:
- The build for (upstream/master at merge commit A') fails regardless of subsequent changes to the branch.

References:

This issue made it appear that I had written a faulty test for [this pull request](https://github.com/tmpvar/jsdom/pull/1444#issuecomment-208009547).
- The branch builds:
  - A https://travis-ci.org/deckar01/jsdom/builds/122064347
  - B https://travis-ci.org/deckar01/jsdom/builds/122064380
- The corresponding merge builds:
  - A' https://travis-ci.org/tmpvar/jsdom/builds/122064352
  - B' https://travis-ci.org/tmpvar/jsdom/builds/122064384

Notes:
- Although the merge build is referencing the correct "commit-commit", the "commit-compare" references the pull request. This seems to indicate that the commit used for pull request builds is resolved dynamically when the build is started. Merge builds should use the "commit-commit" that was recorded when the build was first created.

**Comment by deckar01** [comment]
Reviewing the [build log](https://travis-ci.org/tmpvar/jsdom/jobs/122064353#L117) confirmed that the pull request merge is being referenced dynamically.

```
$ git fetch origin +refs/pull/1444/merge:
remote: Counting objects: 29, done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 29 (delta 20), reused 13 (delta 5), pack-reused 0
Unpacking objects: 100% (29/29), done.
From https://github.com/tmpvar/jsdom
 * branch            refs/pull/1444/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

https://travis-ci.org/tmpvar/jsdom/jobs/122064353#L117

**Comment by BanzaiMan** [comment]
To understand… Are you expecting the PR build to run against the commit of the head branch **at the time the PR was opened**?

**Comment by deckar01** [comment]
I am expecting the build to run against the merge commit that was created when the commit that triggered the build was pushed.

Travis explicitly references the correct merge commit hash on the build page when the build is created, but instead uses the HEAD of the pull request which isn't resolved until the build starts.

**Comment by deckar01** [comment]
@BanzaiMan I haven't heard back from the security team in over 48 hours so I am publishing the vulnerability report here.

> Date: Tue, 12 Apr 2016 23:48:09 -0500
> Subject: Pass Build of Broken Commit
> From: Jared Deckard <jared.deckard@gmail.com>
> To: security@travis-ci.org
>
> Hello,
> 
> I opened issue #5882 and the corresponding fix [travis-build/pull/689](https://github.com/travis-ci/travis-build/issues/698).
> 
> Although making a broken commit look like it's working seems innocuous when the exploit requires providing a working commit within seconds of the first, the working commit can be removed from the pull request without invalidating the passing build for the broken commit.
> 
> This issue effectively allows a malicious actor to spoof the build status of a pull request.
> 
> Proof of concept: https://github.com/travis-ci/travis-build/pull/699
> 
> The severity if this issue is likely low considering developers should catch malicious commits during code review, but issue #5882 should be resolved as soon as possible to be on the safe side.
> 
> Thanks for making Travis so great,
> Jared Deckard

**Comment by BanzaiMan** [comment]
@deckar01 That email did not come through for some reason. Could you try support@travis-ci.com again? Also, please do not do this on a Friday afternoon. Most of our team members are off for the weekend.

**Comment by deckar01** [comment]
> Could you try support@travis-ci.com again?

I just forwarded the email to support@travis-ci.org (not `.com`), but the [guidelines for contributing](https://github.com/travis-ci/travis-build/blob/d9f63f7/CONTRIBUTING.md#security-issues) list the security contact as security@travis-ci.org.

> Also, please do not do this on a Friday afternoon. Most of our team members are off for the weekend.

I would recommend adding a note to the guidelines for contributing regarding the hours requests are normally reviewed.

Thanks for looking into this.

**Comment by BanzaiMan** [comment]
@deckar01 Thanks for the update. We will get back to you.

**Comment by deckar01** [comment]
I think this issue has been resolved. When I double push the old build gets canceled with an error status "!" instead of pass "✓" or fail "X".

@BanzaiMan Thank you and the Travis team for your hard work!

**Comment by oxplot** [comment]
This is still an issue as of today. I have made a test repository at https://github.com/oxplot/travis-race-condition . Here are the steps to reproduce:

1. Setup a repository with [valid and passing `.travis.yml` master](https://github.com/oxplot/travis-race-condition/commits/master)
2. [Setup Travis to build PRs for this repository](https://travis-ci.org/oxplot/travis-race-condition).
3. Create a [new branch](https://github.com/oxplot/travis-race-condition/commits/malicious) with a [broken commit](https://github.com/oxplot/travis-race-condition/commit/ac8ab2a1e1afddff8896453304a4a1049a95c965) and push but **don't yet** create a pull request.
4. Create another [working commit](https://github.com/oxplot/travis-race-condition/pull/3/commits/1138402346c846f52ccc06e4594c4685ca3c85e8) on top of the broken one and **don't push yet**.
5. [Open a PR](https://github.com/oxplot/travis-race-condition/pull/3) for the new branch (this will kick off a [new Travis build](https://travis-ci.org/oxplot/travis-race-condition/builds/150814204)
6. **Immediately** push the [working commit](https://github.com/oxplot/travis-race-condition/pull/3/commits/1138402346c846f52ccc06e4594c4685ca3c85e8) (this will kick off [another Travis build](https://travis-ci.org/oxplot/travis-race-condition/builds/150814212).

Notice that [both builds](https://travis-ci.org/oxplot/travis-race-condition/builds/150814204#L224) will be using the [latest commit](https://travis-ci.org/oxplot/travis-race-condition/builds/150814212#L224). The reason for this is that instead of checking out the specific merge commit created by github, Travis is [checking out a ref](https://travis-ci.org/oxplot/travis-race-condition/builds/150814204#L120) which points to the latest merge commit. So when earlier we pushed two commits to the same PR back to back, we won the race to update that ref before the first CI build had a chance to clone and check it out.

But so far, other than incorrect status for a non-head commit, there is no other issue. However, if we **drop the working commit** (ie `git reset --hard HEAD^`) and **force push the branch** (ie `git push -f`), we end up with a broken head commit that has a passing status and merge-able, thereby bypassing the checks.

**Comment by fotinakis** [comment]
Major +1 here — this is causing a bunch of headache for [Percy](https://percy.io) users who force push to GitHub frequently, because Percy relies on Travis CI giving us the correct commit info through `TRAVIS_COMMIT`. The given commit is frequently wrong because of this, if people force push often.

**Comment by mitsuhiko** [comment]
Does GitHub actually provide that information other than referencing the PR ref when the job runs?

**Comment by fotinakis** [comment]
I don't know exactly what info Travis sees, but yes the GitHub Commit Status API does provide the correct refs in the `parents` key if you request the merge commit itself.

**Comment by fotinakis** [comment]
Here's a real-world example (if helpful to Travis devs debugging):

On https://github.com/getsentry/sentry/pull/4055, there are these two commits:

![screen shot 2016-08-31 at 5 51 09 pm](https://cloud.githubusercontent.com/assets/75300/18151371/9e19bc2c-6fa3-11e6-8d42-e6bbb4e9f945.png)

- The first commit status links to [Travis build 156672595](https://travis-ci.org/getsentry/sentry/builds/156672595).
- The second commit status links to [Travis build 156673163](https://travis-ci.org/getsentry/sentry/builds/156673163).

However, both of the Travis builds show the same commit:

![screen shot 2016-08-31 at 5 54 29 pm](https://cloud.githubusercontent.com/assets/75300/18151437/fdf3a644-6fa3-11e6-86b2-a5aaf9b2ae9b.png)

[Commit 501f766](https://github.com/getsentry/sentry/commit/501f76627fa305a841e45bfe55d398113e2cd410) is the merge commit for the _first_ of the two commits, it seems that in this case Travis didn't even build against the latest merge commit.

**Comment by deckar01** [comment]
There are some important details that got lost in the email chain:

> ...
> 
> We have had conversations with GitHub in the past on how to improve this situation, mostly in regards to keeping the old merge commits reachable for us. As soon as the merge commit changes, the old one is no longer addressed by a named ref, and therefore becomes unfetchable, which is why we switched to using FETCH_HEAD in the first place (see https://github.com/travis-ci/travis-build/commit/1bf906c5c9ab75ced6b48dda47226b65ddda42a6 for a more complete explanation).
> 
> I will follow up with GitHub personally to see if we can fix this. Merging your PR as it is will unfortunately cause many builds to end up in an error. While they will be most likely be followed by a passing or failing build, it is still quite irritating for our users.
> 
> ...
> 
> Konstantin Haase
> Head of Engineering
> support@travis-ci.com

---

I replied:

> I didn't notice that GitHub was pruning old merge commits until I went looking for one.
> 
> It does seem a little inconsistent for GitHub to publish a commit hash in an event that it plans on pruning the next time the branch is committed to.
> 
> Interestingly, rolling back a commit and force pushing does not cause the removed commit's merge commit to be pruned. Since I was primarily testing the PoC scenario I never ran into the pruning behavior that invalidate's my pull request.
> 
> There are alternatives if GitHub pushes back on the issue (or even to insulate from this kind of undefined behavior).
> 
> Relying on GitHub to provide the merge commit is actually relying on and underspecified part of the GitHub API.

**Comment by fotinakis** [comment]
That's great info, thanks @deckar01 — @rkh, were you able to follow up with GitHub?

**Comment by deckar01** [comment]
@BanzaiMan I just ran into this bug again today. This issue is now a year old. Is there anything I can do to get this fixed?

**Comment by Woodz** [comment]
This has been re-raised as #9476

**Comment by fingolfin** [comment]
This issue is two years old now, and still not fixed. I'll try to bump mine (#9476) to prevent some silly bot from auto closing it, but I am still dismayed: It was quite a shock for us to learn that the commit information published on each Travis job can just be nonsense. This undermines our trust in Travis in general. :-(

**Comment by Woodz** [comment]
It seems as though the underlying issue with GitHub pruning stale merge commits is a non-trivial change for both sides to make, so can I propose that in the meantime, Travis builds triggered by a commit that has since been removed at build checkout time are aborted with a message - "Merge commit superseded by <new git commit hash>". This will at least stop Travis from falsely passing builds from failed commits

**Comment by fingolfin** [comment]
I actually implemented a script to print a big warning if the situation is detected, for use in my CI tests. Having an *option* to abort builds/jobs if a mismatch is detected sure sounds interesting.

Right now, the only two workarounds which do not affect aborting the job that I can think of involve either trying to "reconstruct" the merge (the parent commits may after all be already available in the fetch, if all that happened was that master advanced a bit), and the could be replicated. But that does not cover the case were e.g. the PR was rebased (though I guess aborting the build might be the best thing to do then anyway, as the result of a build based on an obsolete version of a PR...); or else (resp. as a fallback), Travis would have to first clone the `ref/pull/NNN/merge` ref somewhere; and only then start the builds, now all fetching from that clone, instead of fetching from GitHub. This way, at least all jobs build from the same state. (I wonder now if I could fake that myself via Travis build stages?)

That said, I'd still hope that GitHub could be convinced to work out a solution -- after all, this should affect *all* CI provides, not just Travis, no?

So perhaps they'd be willing to offer an API for this? Say a transactional system, where a CI provider is allowed to "lock" a merge commit on a PR for a certain time (with some rate throttling to prevent abuse).

**Comment by ProTip** [comment]
This just bit me between stages. Test code changed due to a merge to master and ran against an artifact built in a previous stage on different code..

IMHO Travis should produce a stable code base between jobs/stages. I like idea of fetching the two commits used to create the PR merge ref at the start of the build and using them to materialize the repo at the start of each job.

**Comment by acnagy** [comment]
Hey all! @ProTip pinged me over on the [new forum](https://travis-ci.community), and I just left a [comment that I thought should be crossposted](https://travis-ci.community/t/new-build-stages/65/6?u=acnagy). The tl;dr is that, as I'm sure you gathered, addressing this is a pretty extensive fix, so I'm working on scoping it now, and will update the proper channels once we have news
