### ISSUE TITLE
Error on Android builds - `No output has been received...`

### ISSUE THREAD

**Issue by SandroMachado** [travis-ci/travis-ci#5921]
I am getting this error: `No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.`. But moments before the message, the build is posting logs to the output.

You can check the build log here: https://travis-ci.org/uphold/uphold-sdk-android/jobs/123908174

Is it possible to provide more info regarding this issue? 

Thanks

**Comment by MGaetan89** [comment]
I am having the same issue on my project.

**Comment by SandroMachado** [comment]
I fixed this adding [`travis_wait`](https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received).
The problem was that the command took more than 10min to finish.

**Comment by MGaetan89** [comment]
Thanks, I will try that too.
However, I don't see why my project is suddenly "stuck" for 10 min, when it needed 8-10min for a full compile/build/test before.

**Comment by SandroMachado** [comment]
I my case was a library update that produces the issue. :(

**Comment by MGaetan89** [comment]
It didn't work for me: https://travis-ci.org/MGaetan89/ShowsRage/builds/127314204
The commit that started causing the issue was this one: https://github.com/MGaetan89/ShowsRage/commit/d8864fb0c43614a2a019c2e3b8cac38e4677a907
No library and tool version change, just a simple condition.

I am not sure if the issue comes from my configuration or from Travis itself...
