### ISSUE TITLE
Travis ignoring build requests

### ISSUE THREAD

**Issue by vivienlacourba** [travis-ci/travis-ci#5933]
Hi,

Commits done on the gh-pages branch of the w3c/mediacapture-record repo can be seen in the travis history but no builds are being triggered even if the gh-pages branch is whitelisted in the .travis.yml configuration.

See:
https://travis-ci.org/w3c/mediacapture-record/requests
https://github.com/w3c/mediacapture-record/blob/gh-pages/.travis.yml

Thanks,
Vivien

**Comment by BanzaiMan** [comment]
I looked into this issue and found a bug, but probably not the kind you think.

The issue here is that [your `.travis.yml`](https://github.com/w3c/mediacapture-record/blob/c174060d627f30074bbf7207140710c897548dc9/.travis.yml) contains a YAML syntax error.

In particular,

```yaml
after_success:
  - [[ $TRAVIS_PULL_REQUEST == 'false' ]] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
```

The bare `[[ ]]` makes it look like an array, and subsequent `&` signals the YAML parser to define an anchor, but what follows is invalid.

So, we fail to configure the build, and therefore we cannot detect that `gh-pages` branch is whitelisted.

Then, we report on the first violation we know about, which is `github pages branch`. This is a question of error precedence, and I think we should report on invalid syntax first.

For this particular case, fixing the YAML syntax error should trigger builds as intended.

**Comment by vivienlacourba** [comment]
@BanzaiMan thanks for your help debugging this. I [fixed my .travis.yml](https://github.com/w3c/mediacapture-record/commit/22310409e9a3592a9a6e95b2f0c99c2d2974d231) and learned about `travis lint` while doing so.

**Comment by peterpoliwoda** [comment]
On a related note, have a look if your branches: -only setting isn't set to just a single branch.

```yaml
...
branches:
  only:
  - master
  - yourOtherBranchHere
...
```
