### ISSUE TITLE
_R_CHECK_FORCE_SUGGESTS_ not respected

### ISSUE THREAD

**Issue by jackwasey** [travis-ci/travis-ci#5996]
The recent revisions to the install script now check that the packages were installed but do not account for `_R_CHECK_FORCE_SUGGESTS_ `. This is perhaps also a `devtools` issue https://github.com/hadley/devtools/issues/1171, but strikes me as an interaction in which both sides could be improved, assuming you care about R environment variables at all.

In my particular case, I suggest RODBC, but don't want to `sudo: true` in Travis just so I can install the SQL headers to build it. I don't use RODBC in my tests on Travis, hence my use of `_R_CHECK_FORCE_SUGGESTS_ `. As of late April, the Travis script identifies that RODBC fails to install, and halts the build, whereas before, it failed, but the build continued successfully.

@craigcitro @hadley @jimhester

**Comment by jimhester** [comment]
Checking that all dependant packages were actually successfully installed was always the intended behavior, however it was previously not doing so.

https://github.com/jackwasey/icd/pull/90 installs RODBC using the apt-addon without `sudo: true` and results in a successfull build (https://travis-ci.org/jimhester/icd/builds/127772802).

In general having dependant packages you are not testing on Travis is heavily discouraged and these exceptional cases are better served by authors writing custom `install:` steps rather than adding additional complexity to the general case.

**Comment by hafen** [comment]
+1 on this.  I would not by default fail a Travis CI build because a "suggests" package does not install when _R_CHECK_FORCE_SUGGESTS_=FALSE.  I have a package, datadr, which passes on CRAN even though one of the suggests packages is not installable on a basic system, yet currently fails on Travis CI.  I would think that any package that passes CRAN submission should also pass on Travis CI.

Details:

For datadr, one of the suggests packages, RHIPE, cannot be installed on a basic system (system-level dependencies like Hadoop and a specific version of protocol buffers is required).  We need to include the package in "suggests" to make CRAN happy, since the package has methods that support Hadoop via RHIPE as one potential back end, but the RHIPE dependency is only used (and independently checked) on special systems (clusters with appropriate RHIPE system-level dependencies installed).

This passed a couple months ago (and passed CRAN submission):
https://travis-ci.org/hafen/datadr/builds/119382803

This ran today and did not pass (though still would pass on CRAN):
https://travis-ci.org/hafen/datadr/builds/130703252

**Comment by paleo13** [comment]
I am writing a package that has packages that are not listed on CRAN in "Suggests". AFAIK this is allowed under the CRAN guidelines (for example the [cherry package](https://cran.r-project.org/web/packages/cherry/index.html)). Therefore, I believe package that has a non-CRAN package listed under Suggests should pass under Travis tests. However, this is not the case.

Currently, the following line of code is used to look for package dependencies, install them, and check that they have been successfully installed.

```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = TRUE);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
```
 
By setting the `dependencies=TRUE`, Travis tries to install all the packages listed under 'Depends', 'Imports', 'Suggests', and 'LinkingTo'. But it then fails is any of these packages cannot be installed--even if they are only listed under Suggests.

I suggest that `dependencies=TRUE` be changed to `dependencies=NA`, so that only packages listed under 'Depends', 'Imports' and 'LinkingTo'  will be checked for successful installation.

```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA); devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
```

I do agree that ideally such non-CRAN packages should be installed on Travis for complete testing of one's package. But this is not always feasible. For instance, one of my 'Suggests' packages is a commercial R package 'gurobi'. This package is not open source. Although I suppose I could upload the .tar.gz somewhere have Travis install this manually using `before_install`... I would be uncomfortable doing this.

### Versions

- [Build Report with Failure](https://travis-ci.org/paleo13/rapr/jobs/135493195)
- [.travis.yml](https://github.com/paleo13/rapr/blob/dev/.travis.yml)

**Comment by hadley** [comment]
@jimhester maybe we should bundle this into `install_dev_deps()` to simplify the shell script here? Only checking for successful install of non-suggested packages seems reasonable to me.

**Comment by paleo13** [comment]
I'm still getting build failures on packages that have non-CRAN packages in the Suggests. 

Could you please point me to the correct repo or directory, and I'll make the changes and submit a pull request? :)

**Comment by jimhester** [comment]
@paleo13 https://github.com/travis-ci/travis-build/blob/15dcdbe9ba9c807ba9442136f28155daa33859f4/lib/travis/build/script/r.rb#L365 is the line you would need to alter.
