### ISSUE TITLE
dist: trusty sudo: false creates precise image

### ISSUE THREAD

**Issue by jayvdb** [travis-ci/travis-ci#6025]
using `dist: trusty` and `sudo: false` creates a `precise` image.

```yml
dist: trusty
sudo: false
```

https://docs.travis-ci.com/user/trusty-ci-environment/ says there is only one image for `dist: trusty` and it has sudo access.  Container mode does not exist for `dist: trusty` (#5695).

However if `sudo: false` is used, the result is a `precise` container, and the "Build system information" for this job will show `Build dist: trusty`, but everything else will refer to precise.

Since #4997 has been solved, I think the expected outcome of `dist: trusty` with `sudo: false` is the disable sudo on a trusty image.

**Comment by BanzaiMan** [comment]
Hello. Thanks for taking the time to open this issue.

https://docs.travis-ci.com/user/workers/container-based-infrastructure#Routing-your-build-to-container-based-infrastructure clearly states that `sudo: false` sends jobs to containers, and the Trusty documentation clearly indicates that you need `sudo: required` to use Trusty.

I have to say that this is expected behavior.

We closed #4997 because we added caching support for Trusty, not because we added Trusty support to the container builds.

**Comment by jayvdb** [comment]
> However if sudo: false is used, the result is a precise container, and the "Build system information" for this job will show Build dist: trusty, but everything else will refer to precise.

This problem has been accepted as https://github.com/travis-ci/travis-ci/issues/6025
