### ISSUE TITLE
Upgrade to PHPUnit 4.8

### ISSUE THREAD

**Issue by Soullivaneuh** [travis-ci/travis-ci#6037]
PHP 5.x builds run with PHPUnit 4.5.

This is a very old version. Any plan to upgrade it to 4.8?

BTW, this will permit users to use `phpunit --self-upgrade` that does not exist under 4.5.

**Comment by photodude** [comment]
I know some groups work around this by bringing in PHPUnit with `git clone` or with composer.

**Comment by BanzaiMan** [comment]
The old archives will not get updates. More recent ones, such as 7.0.8, 5.6.23, 5.5.37, will get a recent version of PHPUnit. https://travis-ci.org/BanzaiMan/travis_production_test/builds/142638263

This is due to our generally not re-packaging existing archives, which are used to create build images.

**Comment by BanzaiMan** [comment]
The next build environment update will have recent PHP versions pre-installed, so it will have recent PHPUnit.
