### ISSUE TITLE
Allow a custom "[ci skip]" string override RegEx in travis.yml

### ISSUE THREAD

**Issue by donavon** [travis-ci/travis-ci#6045]
My team members already add "WIP" (work in progress) to the commit message when pushing temporarily (like before they go home so thaty can work on another machine at night). But Travis will build, and in many cases fail, unless they also add "[ci skip]". It would be nice if I could specify a RegEx to travis.yml to look for "WIP" instead (something like `\bWIP\b`).

**Comment by BanzaiMan** [comment]
I don't know if this is going to be feasible. In order to fetch what kind of regular expression you give in `.travis.yml`, we have to fetch `.travis.yml`, but it happens *after* we have received a push event from GitHub (the payload of which contains the commit message) and configured a build to run already.
