### ISSUE TITLE
Support ruby serverspec test for extra test of ansible role

### ISSUE THREAD

**Issue by juju4** [travis-ci/travis-ci#6056]
Hello,

I'm doing ansible role testing inside travis but I want to ideally use same suite between travis and kitchen.
kitchen can do bats and serverspec test.

try to add serverspec manually but not running fine

```
$ cd /home/travis/build/juju4/ansible-mig/ && rake2.0 --trace spec; exit 0
rake aborted!
LoadError: cannot load such file -- rspec/core/rake_task
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:53:in `require'
/home/travis/build/juju4/ansible-mig/Rakefile:2:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:77:in `block in run'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/rvm/gems/ruby-2.2.3/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/bin/rake2.0:37:in `<main>'
```

Inside kitchen/vagrant+virtualbox on my local system, it works fine.

Example
https://travis-ci.org/juju4/ansible-mig

Thanks

Note: can be related to https://github.com/travis-ci/travis-ci/issues/4090 if combining python ruby

**Comment by BanzaiMan** [comment]
Hello. I am not really sure what you are asking.

However, I very much doubt the error you are seeing has anything to do with our "ruby serverspec support".

You are [installing Ruby 2.0.0 and rake with `apt-get`](https://github.com/juju4/ansible-mig/blob/31a81f319741440460fa9c71039130bbb1f12b6e/.travis.yml#L20) and invoking `rake2.0` to run your tests; `rake2.0`—however it is supposed to operate—is failing to find `rake_task` file. Notice that your `rake2.0` invocation ends up invoking files in `/usr/local/rvm/gems/ruby-2.2.3`. This is due to our use of RVM as the Ruby runtime manager. Trying to use Ubuntu packages will be a problem for you.

The Python image, as well as the Trusty image you are using, has RVM preinstalled, so if you want to use a Ruby version newer than the system default (whatever that might be), try:

```yaml
before_insall:
  - rvm use --install 2.2.3 # or any other version
```

**Comment by juju4** [comment]
Hello BanzaiMan,

I tried to do the change you suggested but it doesn't change much
see here https://travis-ci.org/juju4/ansible-mig

I don't say travis is not supporting serverspec. it's more about the combining language factor (python+ruby here). I'm not targeting any ruby version, just need rspec to run the same test than in kitchen-test.

Thanks
