### ISSUE TITLE
Linux Platform Request: Termux as platform!

### ISSUE THREAD

**Issue by gwpl** [travis-ci/travis-ci#6087]
Feature Request / Platform Request.
I'd like to test if my projects build successfully on https://github.com/termux/termux-app / https://termux.com Linux platform. (It's "Linux in your pocket" for android).

As issue touches two projects I allowed myself to file request also to the other project https://github.com/termux/termux-app/issues/95 as to this one.

**Comment by BanzaiMan** [comment]
Could you elaborate on what you are asking? If you are asking to add support running tests for the flavor of Linux that's running on Termux? If so, you can use our [Android](https://docs.travis-ci.com/user/languages/android) support to run them, assuming that you can set up a testing environment in a reasonable amount of time doing that. (You may be able to get your own Docker image, too.)

If you are asking for a build-image level support (i.e., Termux instead of Ubuntu), then I am afraid this is very unlikely to happen.

**Comment by gwpl** [comment]
Thank you for answer!

There is Android Application called Termux:
https://play.google.com/store/apps/details?id=com.termux
that provides linux kind of environemnt, with compilers and other basic tools (like apt package manager) that you can build on top.

Therefore your suggestion to use Travis CI Android support : https://docs.travis-ci.com/user/languages/android sounds like direction to go!

Let me get in touch with Termux developers/community, and maybe find how to use it:
https://github.com/termux/termux-app/issues/95
https://plus.google.com/+GrzegorzWierzowiecki/posts/LDqHphGfU9Z

Best regards!
Greg
