### ISSUE TITLE
[Question] Remove me from travis build email

### ISSUE THREAD

**Issue by karussell** [travis-ci/travis-ci#6094]
Hi,

I'm the author of an open source project using travis ci and we are very happy with it - thanks!

Now it happens that people fork the project and use travis but keep my email as notification email. Is there an option to avoid this somehow or notify the fork its authors? Or even better: verify the email before it is used as notification email?

**Comment by Joshua-Anderson** [comment]
Definitly a hack, but you can use `travis encrypt` to encrypt your email... which prevents it from decrypting on forks and emailing you.

**Comment by photodude** [comment]
I think in the Travis settings for your repository you can put your email in as an "Environment Variables"  or rather than putting your [email for notifications](https://docs.travis-ci.com/user/notifications/) in the `.travis.yml` you put it in by [DEFINING VARIABLES IN REPOSITORY SETTINGS](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings) just "make sure to escape special characters (for bash) accordingly."

**Comment by karussell** [comment]
Thanks @photodude & @Joshua-Anderson for the possibilities and #1094 is indeed a dup. Closing here.

**Comment by ericfont** [comment]
> I think in the Travis settings for your repository you can put your email in as an "Environment Variables" or rather than putting your email for notifications in the .travis.yml you put it in by DEFINING VARIABLES IN REPOSITORY SETTINGS just "make sure to escape special characters (for bash) accordingly."

I thought the same, but I done some testing, and it seems that environment variables don't work for email notification.  If an environment variable is provided as an email notification address, then it seems Travis interprets that as erroneous, and so what actually happens is Travis will fall back to the default of emailing the git committer and author of the pushed commit.
