### ISSUE TITLE
Can't get a certain Environment Variable to work

### ISSUE THREAD

**Issue by ed08imuj** [travis-ci/travis-ci#6103]
I encountered an odd problem that I can not solve on my own. 
We use Travis CI for a university project. We have different programs that should be automatically compiled bei Travis and afterwards included in a docker container. 
One of the programs uses OpenCV. We pre-built the library (we didn't want to build it inside travis/docker because of the long build time) and included it in the docker/assets/openCV directory in github. 
However, the automatic compilation doesn't seem to work -- probably because the OpenCV_DIR path is not being set correctly, which leads to cmake not finding openCV. 

Build Example:
https://travis-ci.org/JoHeinrich/amos-ss16-proj5/builds/132854584

Can you give me a hint what's going wrong?

**Comment by BanzaiMan** [comment]
Your build is not finding the header file. https://travis-ci.org/JoHeinrich/amos-ss16-proj5/builds/132854584#L2845-L2846 You need to tell the compiler to find them, typically by `-I`, but also other means are possible.

I don't know much about OpenCV, but I very much doubt that `$OpenCV_DIR` influences the compiler's search paths.

I am closing this, though, since this does not appear to be a Travis CI issue. If you have other reasons to believe we have something to fix, do let us know.
