### ISSUE TITLE
PHP 7.1

### ISSUE THREAD

**Issue by krakjoe** [travis-ci/travis-ci#6148]
Alpha 1 was released today, could we get 7.1 added please ?

https://travis-ci.org/mkoppanen/imagick/builds/136528185

**Comment by BanzaiMan** [comment]
When https://github.com/php-build/php-build gets an updated definition, we'll build new archives. Thanks.

**Comment by rogeriopradoj** [comment]
@BanzaiMan, we have it: https://github.com/php-build/php-build/commit/8f1f9ea4c04121a408c03d2d24cfe0d73caf3683

@krakjoe: https://github.com/php-build/php-build/issues/382#issuecomment-225435740
>PS.: I saw you have karma in https://github.com/php/php-src repo, (https://people.php.net/krakjoe). Do you mind creating the branch there named PHP-7.1, as the existing PHP-7.0, PHP-5.6, PHP-5.5 etc? I don't have this karma (yet 😺 ): https://people.php.net/rogeriopradoj
The reason is that I'm working on 7.1snapshot for [php-build](https://github.com/php-build/php-build), as we have here at: https://github.com/php-build/php-build/tree/master/share/php-build/definitions.

**Comment by BanzaiMan** [comment]
`7.1.0alpha1` (and alias `7.1.0a1`) is now available.
