### ISSUE TITLE
If script returns a non-zero exit code, I should be able to kill build and stop running following scripts

### ISSUE THREAD

**Issue by BentCoder** [travis-ci/travis-ci#6188]
If I run tests below in given order (or any order), next coming test(s) should never run, if we opt-in to use `fast_fail: true` which could be a new feature in Travis CI. So, if phpspec fails, then behat won't run which takes 15 minutes to run in my case. It is annoying to wait 15 more minutes when you know your build is already broken.

```
script:
   - php-cs-fixer
   - phpspec
   - behat
```

It is described [here](https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build).

> If script returns a non-zero exit code, the build is failed, but continues to run before being marked as failed.

I don't have this limitation in Jenkins. It just dies :)

This is related to: https://github.com/travis-ci/travis-ci/issues/1066

**Comment by BanzaiMan** [comment]
If you want all of them to pass or fail together, you can use `&&`, like so: `php-cs-fixer && phpspec && behat`.

This behavior is unlikely to change.

I'm closing this.

**Comment by mawadi7** [comment]
Thanks @BanzaiMan but this isn't quite practical solution, as script section doesn't have only one line to be && with unit test or whatever blocker might appear, in my case i use travis to build android, and if unit test failed i have to wait x3 time extra to react on whats failed ! otherwise i have to wast my time mentoring the build scripts as it runs to watch out for failure, this issue need to revised
