### ISSUE TITLE
Failure in Travis builds of NUnit under mono 3.2.8

### ISSUE THREAD

**Issue by CharliePoole** [travis-ci/travis-ci#6189]
@joshua-anderson @akoeplinger @nterry

As far as we can tell, the failure described here is due to some
change in the travis infrastructure. See what you think...

We build NUnit on travis using both the latest build of Mono and the
legacy 3.2.8 build. A few days ago, the 3.2.8 build started failing
with this message:

> $ ./build.sh --target "Travis"
> WARNING: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
> Unable to find version '0.6.4' of package 'Cake'.
> Could not find Cake.exe.

The shell script being run is provided by the Cake team and has not
changed for many months. It serves as a bootstrap to download Cake,
which is the script engine we use for our builds. Since this looked
like an infrastructure problem to me, I immediately reran a build that
had run successfully about five hours previously. It failed with the
same message, which seemed to confirm my suspicions. Travis has had
glitches like this before, so we waited for a few days but it hasn't
come back yet.

Here's a recent build that can be rerun to see the problem live:
https://travis-ci.org/nunit/nunit/jobs/137871298

Charlie

**Comment by ChrisMaddock** [comment]
@joshua-anderson @akoeplinger @nterry

Hi all - have done some digging in to this with regards to the NUnit build.

The root cause of this issue appears to be that Mozilla have shut down MXR in favour of DXR.
https://groups.google.com/forum/#!topic/mozilla.dev.platform/_k-ditFrne4

There is an MXR URL hardcoded in to mozroots 3.2.8, which is used by old versions of mono to verify the SSL certificates used by Nuget. (As I understand it, mozroots is essentially deprecated in later versions of mono.)

The old link:
http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1
Is now redirected to:
https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt
However, the redirection doesn't appear to work for mozroots...I haven't looked into why.

(Note in current mono, a third link has been used: [Link](https://github.com/mono/mono/blob/master/mcs/tools/security/mozroots.cs#L48))

Moztools 3.2.8 has a `--url` option, which should permit changing the source url, however I've encountered BufferOverflowExceptions when trying to make use of this. There is also the option to point to a certificates file, however I haven't been able to get that to work without Moztools throwing NumberFormatExceptions. 🙁

The NUnit build calls nuget restore via a shell script and Cake-Build, however, this issue also prevents Travis's standard `- nuget restore packages.config` from working - which suggests to me that a fix would be best within Travis.

I also imagine #6171 is the same root cause.

**Comment by CharliePoole** [comment]
It works! Our latest build just passed. Now I can take 3.2.8 out of allowed failures. Thank you.

**Comment by ChrisMaddock** [comment]
Wow - how's that for a quick turnaround! Brilliant, thanks @akoeplinger !
