### ISSUE TITLE
Weekly Mono is broken

### ISSUE THREAD

**Issue by JustArchi** [travis-ci/travis-ci#6198]
As can be seen https://travis-ci.org/JustArchi/ArchiSteamFarm/jobs/138693726

(It was building nice before, so I guess it's a problem with Mono dependencies. Same build on Mono latest passes)

@joshua-anderson @akoeplinger @nterry

**Comment by JustArchi** [comment]
Extra info: It happens on both container-based ```sudo: false``` as well as ```sudo: required dist: trusty``` VMs.

**Comment by Joshua-Anderson** [comment]
I'm not sure exactly what's up, but it seems like there may be a problem with aot-get

**Comment by nterry** [comment]
Argh! I am sick of broken packages!

**Comment by nterry** [comment]
The 'no ultimately trusted keys' message seems suspicious when loading the
Xamarin gpg key.

**Comment by Joshua-Anderson** [comment]
That message does appear suspicious, but I believe it is harmless... you will find that message on every mono installation, even the successful ones. If you notice next to it, you will find it says one key imported.

**Comment by akoeplinger** [comment]
Yes, this is an issue with the weekly packages in the Xamarin repo, thanks for catching it! I reported it internally.

**Comment by BanzaiMan** [comment]
Is there anything for us to fix?

**Comment by akoeplinger** [comment]
No, it's an issue on our end. I have a fix, it should be out soon.

For the curious: when we turned on building packages for the ARM64 architecture we switched to building packages on Debian 8 (since ARM64 support was introduced there) instead of Debian 7. However, this caused the packages to no longer work on Debian 7 / Ubunt 14.04. The fix is to only build the ARM64 packages on the newer Debian.

**Comment by BanzaiMan** [comment]
@akoeplinger Thanks for the information. I'm closing this now.

**Comment by akoeplinger** [comment]
This is fixed as of Mono weekly 4.5.2.372. Thanks all!

**Comment by JustArchi** [comment]
:+1:
