### ISSUE TITLE
ccache does not work for clang compiler

### ISSUE THREAD

**Issue by chfast** [travis-ci/travis-ci#6201]
If `compiler: clang` and `cache: ccache` the ccache cache does not work.

**Comment by BanzaiMan** [comment]
Could you elaborate what you mean by "does not work"?

**Comment by chfast** [comment]
Yes, sorry.

Simply, object produced by the clang compiler are not cached. I guess the ccache installation does not have symbolic links of name `clang` and `clang++` set up in /usr/lib/cache. So the setting `cache: ccache` does not enable ccache wrapper for clang in this case.

Maybe it is intentional, but is inconsistent with GCC compiler being chosen where `cache: ccache` is enough  to enable caching of objects produces by the GCC compiler.

**Comment by cbeck88** [comment]
There are several things that can cause it, and ways that you can work around it. If you are using `cmake` you can try `SET_PROPERTY(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)` in your `CMakeLists.txt` and then cmake will invoke ccache as normally. There's also some old bug where sometimes you have to set an environment variable in order to use `ccache` with `clang` at all.

**Comment by BanzaiMan** [comment]
Is there something to do here? If there is, please include a build log URL that shows the problem.

**Comment by cbeck88** [comment]
So I have a bunch of notes from a project in the past that detailed various issues that I had with `ccache` on ubuntu trusty and how to work around them. I could dig into them and report specific gotchas that can cause it to silently not work.

The best solution was to install a new version of `ccache` with a more up-to-date version -- it turns out that `ccache` in ubuntu trusty doesn't support some gcc flags `-s` which are essential to `cmake`'s operation, if I recall correctly.

> "Is there something to do here?"

You *could* do something like, make more recent versions of `ccache` available on trusty I guess.

But a better question perhaps is *why*.

Usually there is no point to `ccache` on travis-ci since it's a different machine each time.

Maybe it matters for docker builds?

FWIW it's very fast to compile new `ccache` from source in your home directory IIRC

Sorry for long-winded message, writing is hard :)

**Comment by cbeck88** [comment]
I dug into what I remember of this I guess. I think `CCACHE_CPP_2` was the enviornment variable that I remember. http://peter.eisentraut.org/blog/2014/12/01/ccache-and-clang-part-3/

Also, if I recall, this "new features and improvements" item from CCACHE version 3.2 was extremely important:

``
The -c option is no longer passed to the preprocessor. This fixes problems with clang and Solaris’s C++ compiler.
``

As I recall it basically doesn't work with clang until that feature is in.
