### ISSUE TITLE
redis-server fails in osx

### ISSUE THREAD

**Issue by oleiba** [travis-ci/travis-ci#6270]
```
language: node_js
node_js:
  - '0.12'
os:
  - osx
before_install:
  - git clone https://github.com/creationix/nvm.git /tmp/.nvm
  - source /tmp/.nvm/nvm.sh
  - nvm install $TRAVIS_NODE_VERSION
  -nvm use --delete-prefix $TRAVIS_NODE_VERSION
  - brew update
  - brew install redis
before_script:
  - sh -c "sudo redis-server start"
```
fails after successfully launching redis-server:
```
# Server started, Redis version 3.2.1
 * The server is now ready to accept connections on port 6379
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

replacing the line in `before_script` to `sh -c "sudo redis-server /etc/redis/redis.conf"` is failed too with:
```
Fatal error, can't open config file '/etc/redis/redis.conf'
The command "sh -c "if [ '$DB' = 'redis' ]; then sudo redis-server /etc/redis/redis.conf; fi"" failed and exited with 1 during .
```
and gets the same failure if I use `/etc/redis/6379.conf` as the config file.
I'll note that with linux everything works as expected with an active redis server.

**Comment by BanzaiMan** [comment]
`redis-server` command just starts the server in the foreground, right? It'll be waiting for further input from STDIN, which never comes. You need to send it in the background, and wait for the port 6379 to accept connexions.

Also note that `sudo redis-server start` seems wrong on two accounts. One, Redis listens on an unprivileged port, so any user can start it. Two, `start` will refer to the configuration, which probably doesn't exist.

At any rate, you'd want something like this, so that you can continue.

```yaml
before_script:
  - redis-server
  - until ruby -rsocket -e '$stderr=File.open(File::NULL,"w"); TCPSocket.new("localhost",6379)'; do sleep 1; done
```

**Comment by oleiba** [comment]
Running in background worked (using &), thanks!

**Comment by deadlylaid** [comment]
Thank you So much about running in background of redis-server!
I solved my problem thank you!
