### ISSUE TITLE
rsync on linux builds has stopped working correctly

### ISSUE THREAD

**Issue by SingingBush** [travis-ci/travis-ci#6290]
My build script uses bower to download javascript etc which is then moved into the correct folder using rsync. This has been working fine with travis (and still is on OSX builds) but recently on the Linux build it's stoped working. 

It's essentially trying to prefix my target directory for rsync with the full path of the build dirrectory but there's a double `//` on the end of the prefix.

I've tried:

```
rsync -u bower_components/jquery/dist/jquery.min.js public/js/jquery.min.js
```

and

```
rsync -u bower_components/jquery/dist/jquery.min.js ./public/js/jquery.min.js
```

but both end up the same. It's essentially ending up with:

```
rsync: change_dir#3 "/home/travis/build/SingingBush/eloquent//public/js" failed: No such file or directory (2)
```

**Comment by BanzaiMan** [comment]
Do you have a build log that shows the problem you are describing here?

**Comment by SingingBush** [comment]
The line: 

rsync: change_dir#3 "/home/travis/build/SingingBush/eloquent//public/js" failed: No such file or directory (2)

Is from the build log. My build file (not travis file) was set to rsync to public/js. The full path to the build directory is not something I am doing. Something on travis-ci is prefixing /home/travis/build/SingingBush/eloquent//

**Comment by BanzaiMan** [comment]
Please indicate the URL.

**Comment by BanzaiMan** [comment]
I'll assume you mean this one: https://travis-ci.org/SingingBush/eloquent/builds/143477676

After [this line](https://github.com/SingingBush/eloquent/blob/30089b2cbc74b597ffa158b693395ee76b52b7de/dub.json#L24):

    "mkdir -p public/{js,css,fonts}"

The content under `public` looks like this:

```sh-session
$ find public/
public/
public/styles
public/styles/style.css
public/{js,css,fonts}
public/robots.txt
```

I don' t know how your utility is supposed to invoke the shell, but it is not passing the braces correctly, and you are creating a directory you don't want. I am not familiar with D. (If you want to pursue that, please alert the D maintainers.)

If you create each of these directories (`js`, `css`, `fonts`) separately, the build runs past the `rsync` invocation and whatnot.

It is not clear to me when the trouble started for you, but it is definitely not due to `rsync`. Our build images have not changed in the last 2 months, so I am highly skeptical that we introduced it. My guess is that the language runtime and/or underlying dependencies are to blame, but, again, I am not sure what the real cause is.

Whatever it is, I do not think there is anything for us to do here.
