### ISSUE TITLE
error: cannot call value of non-function type 'URLSession'

### ISSUE THREAD

**Issue by jakjothi** [travis-ci/travis-ci#6308]
Hi I am facing this issue after xcode8 after new beta update https://github.com/travis-ci/docs-travis-ci-com/pull/664

environment: osx
target: 10.11
travis xcode image: xcode8

error: cannot call value of non-function type 'URLSession'
        let session = URLSession.shared()
                      ~~~~~~~~~~~~~~~~~^~

**Comment by bmmarko** [comment]
any news on this ?

**Comment by jakjothi** [comment]
@bmmarko 

use like this 

````
let session = URLSession.shared
````

**Comment by bmmarko** [comment]
Thank you @jakjothi
Actually i had issue with URLSession because i used `request`: var with old notation from Swift 2.0
`let request = NSURLRequest(url:URL)` while Swift 3 has no NS legacy in Class Names, so `URLSession.shared.dataTask(with request: URLRequest)` expets argument of `URLRequest ` class, not `NSURLRequest ` as i thought.

**Comment by jakjothi** [comment]
@bmmarko 

true
