### ISSUE TITLE
How can I figure out why this build was terminated?

### ISSUE THREAD

**Issue by cbeck88** [travis-ci/travis-ci#6336]
Still running (12 of 120): make -j2 --quiet
    
    Still running (13 of 120): make -j2 --quiet
    
    In file included from /home/travis/build/cbeck88/travis-cpp-assistant/deps/gcc-4.9.3-src/libsanitizer/ubsan/ubsan_handlers.cc:13:0:
    
    /home/travis/build/cbeck88/travis-cpp-assistant/deps/gcc-4.9.3-src/libsanitizer/ubsan/ubsan_diag.h: In function ‘void handleTypeMismatchImpl(__ubsan::TypeMismatchData*, __ubsan::ValueHandle, __ubsan::Location)’:
    
    /home/travis/build/cbeck88/travis-cpp-assistant/deps/gcc-4.9.3-src/libsanitizer/ubsan/ubsan_diag.h:192:72: warning: ‘Loc.__ubsan::Location::MemoryLoc’ may be used uninitialized in this function [-Wmaybe-uninitialized]
    
         : Loc(Loc), Level(Level), Message(Message), NumArgs(0), NumRanges(0) {}
    
                                                                            ^
    
    /home/travis/build/cbeck88/travis-cpp-assistant/deps/gcc-4.9.3-src/libsanitizer/ubsan/ubsan_handlers.cc:29:12: note: ‘Loc.__ubsan::Location::MemoryLoc’ was declared here
    
       Location Loc = Data->Loc.acquire();
    
                ^
    
    Still running (14 of 120): make -j2 --quiet
    
    /home/travis/.bash_logout: line 1:  4809 Terminated              travis_jigger $! $cmd

This build was terminated after 15 minutes. It's strange because sometimes travis will let it run for almost an hour, and sometimes it kills it prematurely during `install` phase like this.

Build log: https://travis-ci.org/cbeck88/travis-cpp-assistant/jobs/146017952

**Comment by BanzaiMan** [comment]
Looks like your `install.sh` is failing, probably due to memory exhaustion. The log appears incomplete (and marked a success erroneously) because you are [`source`ing this file](https://travis-ci.org/cbeck88/travis-cpp-assistant/jobs/146017952#L285) , and you [set `errexit`](https://github.com/cbeck88/travis-cpp-assistant/blob/58230ae55f984485265f5c529197e5baff3d5f85/install.sh#L3); when `install.sh` is terminated, the whole build ends without a chance to report the build status correctly.

If your build is consuming too much memory (probably occasionally), you should try GCE (with `sudo: required`), which gives you more memory.

**Comment by cbeck88** [comment]
I see, so `sudo: required` does not interfere with caching? For some reason I thought it did, my info must be out of date.

**Comment by BanzaiMan** [comment]
https://blog.travis-ci.com/2016-05-03-caches-are-coming-to-everyone

**Comment by cbeck88** [comment]
Thanks
