### ISSUE TITLE
cache on OS X always rebuilds the hashdeep

### ISSUE THREAD

**Issue by nagisa** [travis-ci/travis-ci#6368]
For a project with caching enabled hashdeep is always downloaded and built resulting in 2-3 extra minutes of build time. Maybe hashdeep should be pre-installed?

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by nagisa** [comment]
I indeed do. [1] ([raw][1raw]), [2] ([raw][2raw]), [3] ([raw][3raw])…

[1]: https://travis-ci.org/nagisa/rust_libloading/jobs/147849693
[1raw]: https://s3.amazonaws.com/archive.travis-ci.org/jobs/147849693/log.txt
[2]: https://travis-ci.org/nagisa/rust_libloading/jobs/147817893
[2raw]: https://s3.amazonaws.com/archive.travis-ci.org/jobs/147817893/log.txt
[3]: https://travis-ci.org/nagisa/rust_libloading/jobs/147577268
[3raw]: https://s3.amazonaws.com/archive.travis-ci.org/jobs/147577268/log.txt

The relevant (undesired) download/compile happens in `cache.cargo` fold, where it clearly shows travis downloading `https://github.com/jessek/hashdeep/archive/release-4.4.tar.gz`, then running `sh bootstrap.sh`, `./configure --prefix=/usr/local/Cellar/md5deep/4.4` and finally `make install`.

**Comment by BanzaiMan** [comment]
It seems to me that it is working as you indicated.

If `~/.cargo` is caching more than you like—indeed, some of them appears to be `.git` directories (https://travis-ci.org/nagisa/rust_libloading/jobs/147849693#L149-L160), presumably because you are using a `git` checkouts as you dependencies and they change often—then you need to account for such frequent changes when you cache those. You can use the [`before_cache` phase](https://docs.travis-ci.com/user/caching/#before_cache-phase) to do that.

I don't think there is anything to do on our side.

**Comment by nagisa** [comment]
I think it should *not* download `hashdeep`, build or install it on every build. Linux builders do not do that.

**Comment by nagisa** [comment]
I’m not unsatisfied with what is being cached either. I think this should be reopened.

Should I try clarifying what the issue is again?

**Comment by BanzaiMan** [comment]
`hashdeep` is downloaded probably because it is a dependency of `md5deep`, which we require to compute md5 sums of the files to cache.

It is not very clear to me why your job is installing `md5deep`. I can't reproduce it with my repo (https://travis-ci.org/BanzaiMan/travis_production_test/builds/147892105#L54; https://travis-ci.org/BanzaiMan/travis_production_test/builds/147894200). Most OS X images should have them pre-installed, but if it's not, it will. Without it, we will rely on timestamps to check whether or not files are updated. This can lead to many false positives, and unnecessarily uploads.

I do not think we would be updating OS X images that do not have `md5deep`, though.

As for the cache content, as documented in https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache, `cache: cargo` means:

> This caches $HOME/.cargo and $TRAVIS_BUILD_DIR/target.

This was born out of the discussion in https://github.com/travis-ci/travis-ci/issues/4470.

If you do not like what's being cached, you can always override it with `cache.directories`.

**Comment by BanzaiMan** [comment]
We should identify under which conditions `hashdeep` gets rebuilt.
