### ISSUE TITLE
Please provide updated docker images, including a cpp image

### ISSUE THREAD

**Issue by lucasvickers** [travis-ci/travis-ci#6393]
Hello,

The provided docker images referenced in the _[Troubleshooting Locally in Docker Image](https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image)_ section of your documentation are a great idea.

They, however, appear to be at least 2 years old and a bit out of date.  I'm working on a c++ project and two major discepencies between the travis-ci hosted platform and my docker image are:
- cmake 2.8 vs > 3.0
- gcc 4.6 vs 4.8

These are the two major things I noticed, but I'm also noticing my dependency scripts perform differently on the docker image vs the hosted platform.

Would it be possible to update [quay.io](https://quay.io/organization/travisci) with updated images, and perhaps provide a cpp image as well?  Right now I'm limited to pushing a new `travis.yml` config file and seeing what happens 10 minutes later.

Thanks

**Comment by meatballhat** [comment]
@lucasvickers Hey there, I'm working on getting lots of images pushed to quay right now in prep for an ubuntu precise security update and full upgrades for ubuntu trusty.  They are being pushed under different names than those currently being used in production, in part because I don't want to accidentally break the current production setup which used a different image building process and isn't in a great state for emergency maintenance.

You can find these images on quay with the `ci-` prefix, e.g.: https://quay.io/repository/travisci/ci-go.  You'll notice that none of the images have a `latest` tag, which is very much intentional.  We haven't yet settled on a tagging scheme, so for now you'll have to specify one of the `packer-{timestamp}` tags, e.g.:

``` bash
docker pull quay.io/travisci/ci-go:packer-1470674385
```

**Comment by lucasvickers** [comment]
Thanks!  Please update the ticket once you've finalized a naming scheme.  If I run into any issues I'll let you know.

**Comment by meatballhat** [comment]
@lucasvickers Sorry about the long delay.  The current plan is to stick with the `packer-{timestamp}` tags, and I should note that we are in the process of migrating image storage to docker hub, e.g.: https://hub.docker.com/r/travisci/ci-go.  We have no immediate plans to remove the images stored at quay.io.

I'm going to close this out, but please yell if you feel it should be reopened. 💖

**Comment by lucasvickers** [comment]
Having access to the timestamp images is good enough for now.  Thanks!
