### ISSUE TITLE
Simple curl command failing

### ISSUE THREAD

**Issue by rhukster** [travis-ci/travis-ci#6478]
We've been building our packages with Travis for a while, and since the end of last week it's been failing.  The issue seems to be on this command:

```
$ export TRAVIS_TAG=$(curl --fail -s https://api.github.com/repos/getgrav/grav/releases/latest | grep tag_name | head -n 1 | cut -d '"' -f 4)
``` 

This should retrieve the current latest tag from the project in GitHub.  This works when I run it on my test servers, but it's not working with Travis image now.

Working: https://travis-ci.org/getgrav/grav/jobs/151604779

Not working: https://travis-ci.org/getgrav/grav/jobs/152229001

you can see the Tag should be echoed out via `$ echo $TRAVIS_TAG`

**Comment by BanzaiMan** [comment]
Hello, there. A couple of things comes to mind.

As Travis CI is a shared resource, API calls to GitHub can intermittently fail due to [rate limiting for unauthenticated requests](https://developer.github.com/v3/#rate-limiting). You could try authenticating with your own GitHub API key to avoid this issue.

A second (but probably unlikely) possibility is that the output format of the API call changed. I see that you are using "grep", "head" and "cut" to pick out the piece of information you want from the returned output. This is brittle. If GitHub changes the output for whatever reason, your build will fail. You should use a utility that understands JSON and parse it accordingly. On our systems, [`jq`](https://stedolan.github.io/jq/) is available.

**Comment by w00fz** [comment]
We actually have all GitHub APIs calls using authentication, I didn't realize I missed the one in the global evn. Changing [that](https://github.com/getgrav/grav/commit/3007d997bfc343bdb6585faabf1adbdd4263314d) fixed it.

Thank you @BanzaiMan!

**Comment by BanzaiMan** [comment]
Super! I'm closing this now.
