### ISSUE TITLE
C++14, Qt5.7

### ISSUE THREAD

**Issue by mrdeveloperdude** [travis-ci/travis-ci#6503]
Hi!

I am trying out Travis CI for the first time and it was awesome until I noticed that the version of gcc bundled with Trusty image does not support C++14.

In fact any form of Qt5 development will be seriously difficult due to the fact that most Qt5 users download and install Qt instead of relying on ancient librariers that ship with the distro.

Thus I challenge thee to take upon your engineers to make the best C++/Qt5 CI experience out there.

**Comment by pentix** [comment]
I've used travis for some projects with "simple" or without any dependencies before. But when I tried to integrate the travis-ci service for my project which uses some C++11 features and Qt5 I experienced exactly the same difficulties. I spent hours on gathering sources, writing a script that adds a PPA so at least I could use g++ 6.x. (See https://github.com/pentix/qjournalctl/blob/dev/.travis.yml if this could fix your problem) 

Then I noticed compilation did not only fail because of the ancient g++ but also because of the very old Qt 5.0 shipped with Ubuntu 12.10 precise. I failed to find a PPA that includes a modern Qt5.7 compiled for the six year old Ubuntu 12.10. And after all I did not have time nor the passion to sit down and write a "get&build"-script for the current Qt.

Ubuntu(/Debian) is known for not beeing up-to-date but the development with libraries and compilers that were released six years ago feels like hell and is a pain for every developer.

I really appreciate the simplicity of Travis! And I think so do all the paying customers. But it should be possible to get a up-to-date build environment for this. Maybe a current container image of a distribution that supplies up-to-date packages?

Thank you

**Comment by jcelerier** [comment]
You can use these PPAs : 

    
    # For gcc-6
    sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
    sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test

    # For Qt 5.7
    sudo add-apt-repository --yes ppa:beineri/opt-qt57-trusty

    sudo apt-get install -qq g++-6 qt57-meta-full

    # Before build : 
    QT_ENV_SCRIPT=$(find /opt -name 'qt*-env.sh')
    source $QT_ENV_SCRIPT

**Comment by sztomi** [comment]
The previous big C++ issue was closed with the following [post](https://github.com/travis-ci/travis-ci/issues/979#issuecomment-214983894) by @BanzaiMan :

> Trusty has been deployed, and at least some aspects of C++ build experience have improved.

> If there are *specific* points we can improve, please open new issues separately.

I think this thread has a very specific point. Most C++ projects using Travis will waste so much CPU and bandwidth on pulling recent gcc and clang versions out of PPAs and tarballs. If Travis shipped newer versions in their image that would be such a huge win for not only its OSS users but I'm sure for the paid ones as well. Since gcc and clang are moving to defaulting to -std=c++14 it would be great if there were C++14-compatible compilers installed by default on TravisCI as well.

**Comment by jcelerier** [comment]
> Most C++ projects using Travis will waste so much CPU and bandwidth on pulling recent gcc and clang versions out of PPAs and tarballs.

yep, I have thousand of builds that waste ten minutes every time just for downloading newer versions. Contrast with appveyor where you get the latest Qt, boost, etc... generally a few day after their release

**Comment by VioletGiraffe** [comment]
I'm using this Qt 5.9.3 PPA package: https://launchpad.net/~beineri/+archive/ubuntu/opt-qt593-trusty
Older versions are available as well.

On OS X, the brew qt5 package has been very up-to-date so far.

**Comment by jcelerier** [comment]
bump

**Comment by jcelerier** [comment]
bump

**Comment by linville** [comment]
Can we update this to Qt 5.12 (an LTS supported until 2021)?

**Comment by tooomm** [comment]
aaaaannnd bump

**Comment by pentix** [comment]
Still no progress on this, bump! :man_shrugging:

**Comment by VioletGiraffe** [comment]
I solved the problem by installing Qt and GCC myself (see [example](https://github.com/VioletGiraffe/file-commander/blob/master/.travis.yml)), but this creates a lot of unnecessary load on the Travis infrastructure, that's really wasteful!
