### ISSUE TITLE
Target architecture mismatch for Julia

### ISSUE THREAD

**Issue by robertdj** [travis-ci/travis-ci#6548]
@tkelman @ninjin @staticfloat @simonbyrne
I'm having a problem with the nightly build on Travis:
https://travis-ci.org/tknopp/NFFT.jl/jobs/156719103

Even the first command fails:

```
$ julia -e 'versioninfo()'
ERROR: Target architecture mismatch. Please delete or regenerate sys.{so,dll,dylib}.
```

**Comment by tkelman** [comment]
@staticfloat did you manually replace the -latest nightly links or something? you really should not have dobe that with a broken build that didn't have https://github.com/JuliaLang/julia/pull/18311

**Comment by robertdj** [comment]
I did nothing unsual -- I just pushed to the repo. The Travis config doesn't look suspicius to me (apart from a slightly deprecated syntax in `Pkg.test`):
https://github.com/tknopp/NFFT.jl/blob/master/.travis.yml

**Comment by simonbyrne** [comment]
Looks like this was an issue with the nightly Julia build. Should be fixed with next successful 0.6-dev build.

https://github.com/JuliaLang/julia/issues/18317

**Comment by tkelman** [comment]
I've manually moved some files around on S3 to work around this, since there are test issues preventing new nightlies from being created on a regular basis at the moment. The strange thing is why was one bad nightly able to get through?

**Comment by staticfloat** [comment]
> @staticfloat did you manually replace the -latest nightly links or something?

No.  It looks like what happened is that a nightly build actually made it through the tests and triggered a normal upload!  [This build](https://build.julialang.org/builders/package_tarball64/builds/820) was triggered from an upstream builder finishing everything.  It must have been a glitch while I was rebooting all of the buildslaves, all but one of them passed properly, but perhaps if that last one was offline when the others finished, the build went through anyway?

In any case, that nightly doesn't fail any tests because the quickbuild builders that actually run the tests weren't effected, I don't think.

**Comment by tkelman** [comment]
@robertdj this should be fixed for now, please confirm and close.

**Comment by robertdj** [comment]
It works. Thanks a lot for your help.
