### ISSUE TITLE
Numpy install fails on pypy3 only

### ISSUE THREAD

**Issue by arekbulski** [travis-ci/travis-ci#6563]
How can I install numpy? `pip install numpy` fails and `sudo apt-get install python-numpy` works on all (PY3 PY4 and pypy) but not pypy3. 
https://travis-ci.org/construct/construct/builds/157662760
https://github.com/construct/construct/blob/ed6622695d063922fc6095571cef7ecd58c6f0e2/.travis.yml

Possibly connected to #3629

**Comment by BanzaiMan** [comment]
Can PyPy3-2.4.0 compile the current version of numpy?

I don't think `sudo apt-get install python-numpy` "works" so much as I think "it does not cause harm"; it is effectively a no-op in all cases, because it installs numpy to the location that the system Python can find, but not one that your build uses (with virtualenv). The version that `apt-get` installs is much older (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/158336235#L136) than the one that's actually used (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/158336235#L141-L142).

We can look at resolving #3629, so that the user does not have to worry about it.

I'm closing this in favor of #3629.
