### ISSUE TITLE
SBT resolution failure

### ISSUE THREAD

**Issue by thurstonsand** [travis-ci/travis-ci#6641]
In recent builds, travis can no longer resolve SBT reliably. It looks like it happens for some instances, but not others. See this job for an example: https://travis-ci.org/thurstonsand/scala-cass/jobs/160476360

This was a previously passing build, but now it fails due to unresolved dependencies. As far as I can tell it is not environment dependent (meaning Java 7 vs 8 or scala 2.10 vs 2.11), so it seems like it is VM dependent.

**Comment by jbeemster** [comment]
Have been running into this issue today when trying to resolve SBT 0.13.12. However 0.13.0 appears to work just fine.

**Comment by BanzaiMan** [comment]
If a previously passing build starts failing, it is often an issue with underlying dependencies. Please review them and see if anything has changed.

**Comment by jbeemster** [comment]
None of the underlying dependencies had changed between the builds, my solution was to downgrade SBT to 0.13.0 which then allowed the build to go through.

**Comment by BanzaiMan** [comment]
@jbeemster Then it sounds like an issue with SBT itself.

**Comment by jbeemster** [comment]
The relevant error portion from the build: https://travis-ci.org/snowplow/snowplow/builds/163099928#L3526

**Comment by BanzaiMan** [comment]
```
   - 		[FAILED     ] org.scala-sbt#main;0.13.12!main.jar: The HTTP response code for https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.12/jars/main.jar did not indicate a success. See log for more detail. (398ms)
```

I get 200 (after a redirect) on my machine for this file, so I am guessing that we have either a network issue (though 398ms is too short for a timeout) or some other error from the server. Can you get a better error message and/or dump the log content?

**Comment by hanswesterbeek** [comment]
Another example of this issue: https://travis-ci.org/delving/narthex/builds/163059551

**Comment by cquiroz** [comment]
I'm observing the same issue at
https://travis-ci.org/gemini-hlsw/ocs3/builds/163097698

Note that the PR worked fine a day before but it broke once merged. It maybe related to broken http certificates as discussed in sbt gitter

**Comment by BanzaiMan** [comment]
@cquiroz Could you elaborate on the SSL cert issue?

**Comment by hanswesterbeek** [comment]
I don't believe it is sbt-version related. In fact, it reminds of this post. A lot: https://www.lightbend.com/blog/what-happened-to-my-travis-ci

**Comment by cquiroz** [comment]
I'm copying this discussion from gitter:

qq553563608 @qq553563608 Sep 22 21:15
Hi , any master could send me a https://repo.typesafe.com certification ... I got an PKIX cert verification error,,,I have to install that in my keystore??

qq553563608 @qq553563608 Sep 23 06:15
Hi...I found my sbt will find plugins from https://repo.typesafe.com/typesafe/ivy-releases , how can I change it???
Hi...I found my sbt will look for plugins from https://repo.typesafe.com/typesafe/ivy-releases , how can I change it???

Bjørn Madsen @aeons Sep 23 06:15
why do you want to change it?

qq553563608 @qq553563608 Sep 23 06:16
https://repo.typesafe.com will be redirect to https://dl.bintray.com
[error] Server access Error: sun.security.validator.ValidatorException: PKIX pat
h building failed: sun.security.provider.certpath.SunCertPathBuilderException: u
nable to find valid certification path to requested target url=https://repo.type
safe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-start-script/scala2.10/sbt
0.13/0.10.0/ivys/ivy.xml
[error] Server access Error: sun.security.validator.ValidatorException: PKIX pat
h building failed: sun.security.provider.certpath.SunCertPathBuilderException: u
nable to find valid certification path to requested target url=https://repo.scal
a-sbt.org/scalasbt/sbt-plugin-releases/com.typesafe.sbt/sbt-start-script/scala_2
.10/sbt_0.13/0.10.0/ivys/ivy.xml
I got this error...

Bjørn Madsen @aeons Sep 23 06:18
the cert on repo.typesafe.com is valid, so that is an error on your end
in your JVM

ritschwumm @ritschwumm Sep 23 06:18
@qq553563608 sounds like you lack at least one ca certificate

**Comment by BanzaiMan** [comment]
@hanswesterbeek Ah, yeah, thanks for the reminder…

**Comment by slider** [comment]
I'm having the same issues on a private build, also the typesafe repo.

**Comment by shashankgowdal** [comment]
Facing issues with typesafe jars resolution on Travis from 15 minutes.

**Comment by poplav** [comment]
We have been running into these issues the past two days or so, see https://github.com/jupyter-incubator/declarativewidgets/issues/517.  Same as described above.

**Comment by ppires** [comment]
This issue is already open in sbt project: https://github.com/sbt/sbt/issues/2758

**Comment by cotsog** [comment]
Looks like https://github.com/sbt/sbt/issues/2758#issuecomment-250485848 has been fixed:

> The redirect issue was identified and resolved at Bintray, so hopefully this should now work. If there are any further issues, feel free to comment here.
>
> Thanks all for the patience.

Optimistically closing for now. Please reopen if you are still seeing intermittent download failures.

Thank you for your patience!
