### ISSUE TITLE
[macOS] Conflict between numpy installed by pip and brew

### ISSUE THREAD

**Issue by drdanz** [travis-ci/travis-ci#6688]
Until a few days ago, on `os: osx` `osx_image: xcode7.3` the command `brew install opencv` used to install opencv without any issue, but at the moment it looks like that the version of numpy already installed on the system conflicts with the one installed by brew, and therefore the build fails. This is an example of failing build:
https://travis-ci.org/robotology/yarp/jobs/165176482

I tried to remove the numpy package using pip, but this is the result:
https://travis-ci.org/drdanz/yarp/jobs/165860540

**Comment by drdanz** [comment]
Update: I was able to fix macOS builds running this:

```diff
+  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip uninstall numpy; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install opencv; fi
```

**Comment by drdanz** [comment]
Just for reference, since latest update `pip` is no longer available, but `pip2` is available instead.

``` diff
-  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip uninstall numpy; fi
+  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/bin/yes | pip2 uninstall numpy; fi
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install opencv; fi
```

**Comment by patrikhuber** [comment]
Hi,

I'm just wondering why this issue is closed. This issue is still present, and as is apparent, quite many users encounter this (see the referenced commits above) and then have to apply the `pip2 uninstall numpy` workaround. Sure there is this workaround, but installing OpenCV on travis on macOS is quite common, it's an often-used and very well-known dependency. Wouldn't it be better to solve the underlying travis issue so all these users, including me, wouldn't run into this? I bet there's many more users that tried this but failed because they didn't find this issue.
