### ISSUE TITLE
gem error with xcode6.4 image and Bintray deploy

### ISSUE THREAD

**Issue by fredrikaverpil** [travis-ci/travis-ci#6700]
I'm getting this error when using the `xcode6.4` OS X image with a Bintray deploy.

```
Warning, new version of rvm available '1.27.0', you are using older version '1.26.11'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc

ERROR:  Could not find a valid gem 'dpl' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

The command "rvm 1.9.3 --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .

Your build has been stopped.
```

Full output: https://travis-ci.org/fredrikaverpil/pyside2-wheels/builds/166341616

The `continuous-integration/travis-ci/push` build fails but the `continuous-integration/travis-ci/pr` build succeeds. This leads me to think that the Bintray deploy may have something to do with this, as this deploy won't performed for PRs.

I don't use `rvm` or `gem` myself in the build. If you however do perform `rvm get stable; rvm reload;`, you'll get rid of the rvm warnings. But those aren't the reason the build is failing.

**Comment by BanzaiMan** [comment]
Could you try rerunning the build?

**Comment by fredrikaverpil** [comment]
Sure, restarted it just now.

**Comment by BanzaiMan** [comment]
The build failed again. I suppose there is a certificate issue on the OS X image. We will investigate.

**Comment by fredrikaverpil** [comment]
Great, thanks for looking into it.

**Comment by adrianbroher** [comment]
Hello, I'm having the same issue when uploading artifacts via the GitHub Releases provider.  Like @fredrikaverpil I'm using the `xcode6.4` image.  As the warning already indicates it seems to be a certificate issue.  I tried to apply a guide on rubygems about [updating the the root certificates] like:

```
before script:
  - cp GlobalSignRootCA.pem $(dirname $(rvm 1.9.3 --fuzzy do ruby -S gem which rubygems))/rubygems/ssl_certs
```

but had no success, probably because I didn't use the correct root certificate or the certificate requires more to register itself into the system than to just copy it into a directory. As a workaround I'm now reinstalling the ruby 1.9.3 environment with:

```
before_script:
  - rvm reinstall 1.9.3 --disable-binary
```

which seems to update the certificates to the correct version and registers them properly (at least openssl prints some info log lines about how to properly register certificates in a system wide fashion).  This however comes with the cost of 6 minutes more runtime as you can see in the [FreeOrionSDK build].

The general issue however doesn't seem to be new.  Looking into the [Travis-CI Issues] I see #5274 and #4709 which describe the same problem.

[updating the the root certificates]: http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue
[FreeOrionSDK build]: https://travis-ci.org/freeorion/freeorion-sdk/builds/168558357
[Travis-CI Issues]: https://github.com/travis-ci/travis-ci/issues?utf8=%E2%9C%93&q=is%3Aissue%20certificate%20verify%20failed%20

**Comment by fredrikaverpil** [comment]
@adrianbroher many thanks for the `before_script` workaround. I'll try that, because at this point I just need to get my build to stop failing.

Hoping there will be a proper fix for this though. I'm using Travis-CI to build Python wheels and ideally I want to use an as old as possible version of OS X for this.

**Comment by adrianbroher** [comment]
When further investigating this problem I came to the conclusion that this issue is a duplicate of #4709.  The suggest fix in that issue:

```
- sudo security delete-certificate -Z 2F173F7DE99667AFA57AF80AA2D1B12FAC830338 /System/Library/Keychains/SystemRootCertificates.keychain
- rvm osx-ssl-certs update all
```

is way better and faster than my workaround.

**Comment by fredrikaverpil** [comment]
@adrianbroher [your suggestion](https://github.com/travis-ci/travis-ci/issues/6700#issuecomment-258606283) works for me on `xcode6.4` but not on `xcode7.3`.
