### ISSUE TITLE
support .travis.yaml files too

### ISSUE THREAD

**Issue by groovecoder** [travis-ci/travis-ci#672]
To be more flexible, the build trigger should look for `.travis.yaml` files as well as `.yml` files

**Comment by hjacobs** [comment]
http://www.yaml.org/faq.html suggests using `.yaml` were possible:

> Is there an official extension for YAML files?
>
> Please use ".yaml" when possible.

I think the "8.3" times are over long ago :smirk: 

We are also not using `.jsn` instead of `.json` :speak_no_evil: ..

**Comment by BanzaiMan** [comment]
Sorry, but making multiple requests to check for `.travis.yml` and `.travis.yaml` does not make sense at this time.

**Comment by oshalygin** [comment]
Guys, there are a lot of people in the industry that are using the proper extension(`.yaml`) which is recommended by www.yaml.org(see post by @hjacobs ).  

It doesn't seem like a big hurdle to check for both.  What's the pushback?

**Comment by Aethylred** [comment]
Bump, because I opend a duplicate #8068

**Comment by oshalygin** [comment]
Bump because its 2017 and its time to support this file

**Comment by jasonrogena** [comment]
Sucks that you guys refuse to support what is considered standard, and thus make us taint what would be otherwise clean projects.

**Comment by jasonrogena** [comment]
I suggest this issue be reopened

**Comment by petk** [comment]
I also miss having option for `.travis.yaml` in the repos.

**Comment by robfrawley** [comment]
It may be my OCD that primarily drives this, but I also agree with the many other comments expressing how the current config extension constraint is less than optimal: it really annoys me that all the YAML files in my personal projects (and even in all the projects I maintain) utilize the [specification-recommended extension](https://yaml.org/faq.html) of `yaml`, *except for this service's configuration file*, which still requires I use the `yml` variant of the extension.

@BanzaiMan Can you please further expand on [the comment](https://github.com/travis-ci/travis-ci/issues/672#issuecomment-207089771) that "making multiple requests to check for `.travis.yml` and `.travis.yaml` does not make sense at this time." How does it not make sense to support the specification-recommended extension? Doing so seems quite logical to me.

Are you speaking purely from the perspective of it not "making sense" to dedicate employee resources to this issue, as it is low priority? Perhaps that would be understandable, but I'd be more than happy to implement any required fixes to the open-source Travis projects to provide a resolution for this issue, and I am sure others would as well, so are there other reasons why you believe it does not make sense?

@michaelklishin I do not follow [your reasoning for closing this issue](https://github.com/travis-ci/travis-ci/issues/672#issuecomment-7852841) and disagree that supporting both extension would "only cause more confusion". How would adding this feature cause *any* confusion whatsoever? I am, quite literally, *unable to construct a hypothetical where it would*. Alternatively, I could easily see how supporting both `yml` and `yaml` would actually *alleviate confusion* in many cases, and how continuing with the current limitation only *aggravates confusion*.

For example, a new or inexperienced developer would not need to know that they must explicitly use `yml` for their project's Travis configuration file and would be free to use the extension they most likely associate with YAML files: `yaml`. Those with experience in many common frameworks and other tools expect to use the four character length variant of the extension, and some may have not even used the three character version before. Moreover, for those who contribute to a project that uses `yaml` for all files, the singular exception of `.travis.yml` would be a potential cause for confusion; those with no prior YAML experience may even initially believe the two different extensions represent two similar, but different, syntaxes.

Now, are any of my hypotheticals likely? No. But neither are hypotheticals asserting the opposite; this change would not cause utter panic, mayhem and destruction. More projects support multiple extensions than those that do not. Is the issue mostly an aesthetic one for developers? Perhaps. But even so, that doesn't invalidate the issue; developers rightfully expect consistency, and this issue causes projects' files to be named in an inconsistent manner. It shouldn't be a hard sell for Travis to resolve it, and it shouldn't require multiple issues to be filed over a six year time-period, either. But, that is exactly what has happened, and every single time this is brought up in an issue, it is quickly closed with a short and non-specific comment that provides no defense, details, or other information as to why Travis is unwilling to make this change.

Can someone, anyone, please provide some details on why there has been so much push-back over supporting `yaml`; if a reasonably acceptable answer is offered, perhaps people will stop asking for it. Otherwise, perhaps the time to support `yaml` is now.

**Comment by robfrawley** [comment]
*For those interested in seeing this feature implemented, take a moment to read through this comment and follow the forthcomming steps.*

I noticed that Travis group-members had asked that similar issues to this be opened and discussed on the [community forums](https://travis-ci.community) instead of here, on the GitHub tracker (for example, a request to allow for custom configuration file paths, assignable from the website UI, was first created as issue [`travis-ci/travis-ci#5519`](https://github.com/travis-ci/travis-ci/issues/5519), but was later asked to be moved and discussed as [`travis-ci.community/512`](https://travis-ci.community/t/allow-repositories-to-specify-where-travis-yml-should-be-found/512) instead).

__As such, *I've created a request on the community forums for this feature*, where I detailed much of what has already been stated, again: [travis-ci.community/2444](https://travis-ci.community/t/support-the-recommended-yaml-extension-of-yaml-for-travis-ci-project-configurations/2444).__

__If you feel strongly about `travis.yaml` support, be sure to take the time to *go to that forum link* and actually *up-vote that request*.__

The community forum system is completely activity based, so the post I added about this topic will only get attention through sheer numbers. *If you possess any meaningful way to further this goal*, perhaps through a tweet for your rabbid Twitter followers, a programming Facebook group you frequent, a developer-oriented forum you post to regularly, a language-specific group meetup you're attending, or any other apprioriate means, be sure to mention and post the link for others as well. Maybe it will get some traction...

**Comment by chrisk314** [comment]
@michaelklishin the fact that Travis does *not* support the recommended `.yaml` file extension just caused me more confusion, not less. I had to spend time figuring out why my builds weren't running.

**Comment by ctjlewis** [comment]
This might be the most ridiculous issue I've ever come across.

**Comment by robfrawley** [comment]
So, still no additional information on why it is a problem to support the correct file extension of `yaml`?
