### ISSUE TITLE
[Haxe] [osx] Haxelib install fails

### ISSUE THREAD

**Issue by eliasku** [travis-ci/travis-ci#6748]
@andyli, @waneck, @Simn, please take a look at this.

Every job on `osx` is failed (3.2.1 / development)
`linux` works properly (3.2.1 / development)

https://travis-ci.org/eliasku/hxmake/jobs/168767323

```
> haxelib install hxlog
dyld: Library not loaded: @executable_path/libneko.dylib
  Referenced from: /Users/travis/haxe/haxelib
  Reason: image not found
> haxelib exited: 1280
```

**Comment by andyli** [comment]
Reproduced with 10.11 image. It is caused by http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1, since we set `DYLD_FALLBACK_LIBRARY_PATH` in travis-build. I'm looking into installing the binaries into `/usr/local` such that we wouldn't have to mess with the env vars.

At the moment, we can use `osx_image: xcode6.4` to use 10.10 as a temp solution.
