### ISSUE TITLE
Increase api rate limit for cancelling builds?

### ISSUE THREAD

**Issue by goanpeca** [travis-ci/travis-ci#6838]
This is related to

https://github.com/travis-ci/travis-ci/issues/964
https://github.com/travis-ci/travis-ci/issues/5160

Right now the api rate limits does not allow for more thant (10/hour? 5/hour?)

We are working on a [workaround](https://github.com/goanpeca/ci-services) similar to what was proposed by https://github.com/grosser/travis_dedup

Having limits on triggering builds make sense, although I would rather have a more permissive limit. Nevertheless this limitation should probably be way more relaxed for cancelling builds as we are actually trying to keep the system less crowded.

Any chance that the rate limits can be reviewed for cancelling builds? At this point the only solution seems to be to create 1000 github bots.

**Comment by BanzaiMan** [comment]
Could you elaborate on how the API rate limit is related to canceling builds when a new commit is pushed? You should be able to make a POST to cancel builds without eating into the API rate limit (which is for creating a new build with an API call; https://docs.travis-ci.com/user/triggering-builds).

**Comment by goanpeca** [comment]
I am using https://github.com/menegazzo/travispy/ to interact with travis and found that after running my script like 10 times it was then depleted, maybe it is an issue with that library?

I can try and make the requests directly and see if that was the issue.

So just to confirm, querying for the list of active/pending builds and cancelling any of those does not eat from the api rate limit?

Are there any differences in using github auth, or directly an travis_acces_token?

**Comment by BanzaiMan** [comment]
Sorry for the confusion. I checked with others, and found that cancel requests are also currently subject to the rate limit. We will discuss this internally and get back to you.

(By the way, I do not think GitHub rate limit is not in play here, as long as you are reusing this token elsewhere and it is consuming thousands.)

**Comment by goanpeca** [comment]
>Sorry for the confusion. I checked with others, and found that cancel requests are also currently subject to the rate limit. We will discuss this internally and get back to you.

I appreciate it :-)

>(By the way, I do not think GitHub rate limit is not in play here, as long as you are reusing this token elsewhere and it is consuming thousands.)

Yes, dont know what is happening with that library, using my own for now.

@jakirkham

**Comment by BanzaiMan** [comment]
Sorry, I meant that "GitHub rate limit should not be in play here". I updated the comment above.

**Comment by goanpeca** [comment]
Yep I understood :-)

**Comment by jakirkham** [comment]
> ...found that after running my script like 10 times it was then depleted (my github available rate went from 5000 to 0 on these 10 runs and it was not even cancelling builds on all those runs), maybe it is an issue with that library?

Thanks for tagging me and pointing out the GitHub rate limit issues, @goanpeca . Was aware of the Travis CI rate limit issues, but did not know you were running into GitHub rate limit issues too.

FWICT it sounds like issue ( https://github.com/travis-ci/travis-ci/issues/6284 ), which we have encountered before. I still don't know why that happens. However, we did find an effective workaround.

Instead of exchanging the GitHub token for a new Travis token each time, save the Travis token so that is persists and reuse that for many operations. We should be able to store it somewhere securely. Using that, we should be able to eliminate the GitHub rate limit issues.

**Comment by jakirkham** [comment]
> ...found that cancel requests are also currently subject to the rate limit. We will discuss this internally and get back to you.

Any news on what came out of this discussion? Can the cancel requests either be unlimited or have their limit bumped independently of the start request limit?

**Comment by jakirkham** [comment]
Sorry to bump this issue again. Still very interested in being able to cancel extraneous Travis CI jobs. Though 10/hr (unclear on the reset time) is a pretty low limit. Would it be possible to get something higher?

**Comment by BanzaiMan** [comment]
Not at the moment.

**Comment by jakirkham** [comment]
One of the other options we had considered was sending webhooks from an intermediate webservice (instead of directly from the GitHub repo). That way allowing us to filter which things actually were submitted to Travis CI to build. Would this be tenable or would we still have the same rate limit? Any other issues we might run into on this path?

**Comment by BanzaiMan** [comment]
This should be kept alive. We don’t have ETA, however.

**Comment by jakirkham** [comment]
Should this be reopened @BanzaiMan?
