### ISSUE TITLE
Trusty container beta PHP Unable to load dynamic library APC

### ISSUE THREAD

**Issue by photodude** [travis-ci/travis-ci#6853]
Trusty container beta PHP Unable to load dynamic library APC

Sort of related to issue #6842 regarding "Can't connect to local MySQL server through socket" 
Following the suggestion in that issue to "shim" or "alias" the socket I get the following issue.

```php
Warning: PHP Startup: Unable to load dynamic library
'/home/travis/.phpenv/versions/5.4.45/lib/php/extensions/no-debug-zts-20100525/apc.so' -
/home/travis/.phpenv/versions/5.4.45/lib/php/extensions/no-debug-zts-20100525/apc.so:
cannot open shared object file: 
No such file or directory in Unknown on line 0
```

related build
https://travis-ci.org/photodude/joomla-cms/jobs/174819729
using this alias for socket
```php
alias mysql='mysql --socket=/run/mysql-5.5/mysqld.sock'
```

note: seems to be isolated to Container-based Trusty Beta running php 5.4

**Comment by arogachev** [comment]
@photodude I'm facing the same issue. I found that there is no preinstalled APC extension in this folder - `/home/travis/.phpenv/versions/5.4.45/lib/php/extensions/no-debug-zts-20100525/` (used `ls -la` for this folder just for testing purposes in one build).

Then I found this [article](http://olvlvl.com/2016-09-travis-apc):

> In order to have APC working for your PHP version, you actually need to install apcu, since apc has been abandoned in 2012. Also, you need to pick the right version, because v4.0 is only working up to PHP 5.6, while v5.0 is only working from PHP 7.0:

Then I tried to fix it by installing APCu using PECL in `before_install` section:

before_install:
  - if [[ $TRAVIS_PHP_VERSION = "5.4" ]]; then echo yes | pecl install apcu-4.0.11; fi

It took a lot of time to complete the build, I'm guessing this because installation asks to print text (yes / no) couple of times and I'm not sure it was printed / skipped correctly.

But at the end during investigating the [build job](https://travis-ci.org/yiisoft/yii2/jobs/174810372) I found that installation failed:

```
/tmp/pear/install/apcu/apc_sma_api.h:62:33: error: unknown type name ‘zend_uint’
```

and the following errors mention `zend_uint` too.

I look a bit above and saw that:

```
checking for PHP prefix... /home/travis/.phpenv/versions/7.0.7

checking for PHP includes... -I/home/travis/.phpenv/versions/7.0.7/include/php -I/home/travis/.phpenv/versions/7.0.7/include/php/main -I/home/travis/.phpenv/versions/7.0.7/include/php/TSRM -I/home/travis/.phpenv/versions/7.0.7/include/php/Zend -I/home/travis/.phpenv/versions/7.0.7/include/php/ext -I/home/travis/.phpenv/versions/7.0.7/include/php/ext/date/lib

checking for PHP extension directory... /home/travis/.phpenv/versions/7.0.7/lib/php/extensions/no-debug-zts-20151012

checking for PHP installed headers prefix... /home/travis/.phpenv/versions/7.0.7/include/php
```

So seems like pecl tries to install APCu for PHP 7 even the version in this build is 5.4. This is weird. Haven't found solution yet.

**Comment by arogachev** [comment]
I solved it like that:

```yaml
before_install:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.4' ]; then
      pear config-set php_ini /etc/php.ini
      pecl config-set bin_dir /usr/bin/
      yes '' | pecl install apcu-4.0.11
    fi
```

See this related [SO answer](http://stackoverflow.com/a/19575316/4323648).

[This](http://stackoverflow.com/a/21666096/4323648) is useful for skipping prompts during PECL acpu package installation.

**Comment by photodude** [comment]
@arogachev [APC or APCU is already configured to be installed in the repo](https://github.com/photodude/joomla-cms/blob/patch-10/build/travis/unit-tests.sh); I only changed the lines to switch to the Container-based Trusty Beta. 
This is a  Container-based Trusty Beta specific issue

**Comment by arogachev** [comment]
@photodude This is also actual for Standard Ubuntu Trusty using config:

```yaml
dist: trusty
sudo: required
```

**Comment by photodude** [comment]
I'm not having this issue with sudo required trusty builds. apc/apcu installs/works just fine there.

**Comment by photodude** [comment]
Looks like this is only an issue under php 5.4 with Container-based Trusty Beta
https://travis-ci.org/photodude/joomla-cms/jobs/175124842

**Comment by photodude** [comment]
Closing as this no longer seems to be a problem
