### ISSUE TITLE
Hanging Julia build when using ssh-agent

### ISSUE THREAD

**Issue by mortenpi** [travis-ci/travis-ci#6869]
Running the following Julia code in a Travis build
```
mktemp() do path, io
    write(io, "eval `ssh-agent -s`")
    flush(io)
    run(`sh $path`)
end
```
will make the build hang (i.e. it will complete successfully, but the build will not terminate and will time out at 10 minutes). [Examples of builds timing out are available here](https://travis-ci.org/mortenpi/juliarc/builds/175674370).

It started cropping up in builds using Documenter, where we need an SSH key to push to the `gh-pages` branch of the repository, and was reported over the weekend by several people (JuliaDocs/Documenter.jl#351).

cc @tkelman @ninjin @staticfloat @simonbyrne @MichaelHatherly

**Comment by staticfloat** [comment]
My best guess is that this is due to the fact that you're creating an orphaned process here: after `julia` exits, `ssh-agent` sticks around for essentially all eternity, until Travis decides to just kill the whole process tree.  You could fix this a number of ways, one of which is to tack `kill $SSH_AGENT_PID` to the end of your script so as to ensure that it is killed at the end of your session (for bonus resilience, you could add `trap EXIT kill $SSH_AGENT_PID` so that even if your script exits abnormally, bash will still kill the ssh-agent PID).

Another way to do this is implicitly with `ssh-agent /path/to/my/script` to have `ssh-agent` be the invoking force for the command that you want to run with the SSH variables, and `ssh-agent` will then take care of itself once the child command has completed.  You could even invoke `julia` itself with this so that your build scripts don't need to know anything about the SSH variables or setting them; just customize your `.travis.yml` script and invoke `ssh-agent julia` instead of `julia`.

**Comment by MichaelHatherly** [comment]
Thanks for the suggestions @staticfloat. I think we can probably just close this since there's plenty on ways to work around the problem.
