### ISSUE TITLE
How to build only pushed tags

### ISSUE THREAD

**Issue by Jesus89** [travis-ci/travis-ci#6893]
I want to build and deploy only when tags are pushed. By now, no sense in building every push.

I am using  `if [ -z "$TRAVIS_TAG" ]; then exit 0; fi` but I believe there is a better way to do it.

Thanks.

**Comment by BanzaiMan** [comment]
It is not possible to automate this, unfortunately, because at this time we do not differentiate the tag push and the commit push.

If you do not mind some manual step in between your tag push to GitHub and the build on Travis, you can do the following:

1. Turn off all builds, both Pushes and Pull Requests.
1. Using [API](https://docs.travis-ci.com/user/triggering-builds), trigger a build for the tag you desire. The pay load might look like this:
```json
{
  "request": {
    "branch": "YOUR_TAG"
  }
}
```

API builds are not subject to the build settings, but are rate limited (about 10 builds per hour).

**Comment by Jesus89** [comment]
Ok. I will use the API until this can be automated.
Thanks.

**Comment by Himura2la** [comment]
I need this feature also, I have no unit tests to run and there's no need to build on each commit. I guess this feature should reduce the load in Travis servers...

**Comment by franky47** [comment]
Conditional builds could be helpful here:
https://docs.travis-ci.com/user/conditional-builds-stages-jobs/#Conditional-Builds

**Comment by Safihre** [comment]
Thanks @franky47!
For everyone wanting a copy-paste-fix, just add this somewhere to your `travis.yml`:
```yml
# Only build tags
if: tag IS present
```
