### ISSUE TITLE
Github builds with old commit & notes on Make Release

### ISSUE THREAD

**Issue by fuzzball03** [travis-ci/travis-ci#6915]
Please excuse the lack of "good" programming or practices in the github repo here, but I've exhausted all options.

Each time travis builds a release now, it does so twice(This is not new).
Then Travis builds a second time... but for some reason it thinks it's comparing an old commit.
Now every release uses the same commit msg, same date stamp, and same reference to the parent commit.

Here are the releases: https://github.com/fuzzball03/esp-link/releases
_Note how EVERY release there seems to be '5 days old'_

So here is the commit: [Commit 852AD5](https://github.com/fuzzball03/esp-link/commit/852ad502fb9eaa95cc61191e2165d405ffcca7e4)

The first build appears to build correctly... ie...
**BUILD 1**
https://travis-ci.org/fuzzball03/esp-link/builds/177818551
` Update .travis.yml`
`Commit 852ad50`
`Compare 6be6f00..852ad50`
`...`
`Release file: esp-link-testing-852ad50.tgz`

**BUILD 2**
https://travis-ci.org/fuzzball03/esp-link/builds/177818596
` Update .travis.yml`
 `Commit 6fd5938`
`Compare untagged-1a8a587513b54a70b5b6`
`...`
`Release file: esp-link-untagged-1a8a587513b54a70b5b6-6fd5938.tgz`

After pasting this, I'm starting to think this may be a fault of my _Makefile_?

Really, at this point my head hurts...
I'm hoping this is something simple - if not, then perhaps this truly is some kind of bug.

Additional information of any kind... PLEASE ask and I'll be happy to provide it.

Thanks for your time,
Alex

**Comment by BanzaiMan** [comment]
Sorry for not responding sooner.

It is not clear to me what issue you are raising. Your build [#104](https://travis-ci.org/fuzzball03/esp-link/builds/177818551) (BUILD 1 above) is a build on the `testing` branch, triggered by https://github.com/fuzzball03/esp-link/commit/852ad502fb9eaa95cc61191e2165d405ffcca7e4. As such, it has a parent, https://github.com/fuzzball03/esp-link/commit/6be6f00de5f906e86888ab1a5f54ef75436930be, and we have a compare URL, and we show it https://github.com/fuzzball03/esp-link/compare/6be6f00de5f9...852ad502fb9e.

Build [#105](https://travis-ci.org/fuzzball03/esp-link/builds/177818596) (BUILD 2 above), on the other hand, is a tag build, triggered by https://github.com/fuzzball03/esp-link/tree/untagged-1a8a587513b54a70b5b6. There is no compare URL for the tags, really; just the URL to that tag.

You are deploying on every commit https://github.com/fuzzball03/esp-link/blob/9fcee90baffaaa26d4ed6054da6af828e5af0f61/.travis.yml#L17-L28 even though you are using GitHub Releases as the provider. This is probably not what you want. As documented in https://docs.travis-ci.com/user/deployment/releases, you'd want to set

```yaml
deploy:
  provider: releases
  on:
    tags: true
  ⋮ # rest
```

So that the deployment happens only on the tagged commit.

**Comment by BanzaiMan** [comment]
I'm closing this now, but if you think further discussion is warranted, do let us know.
