### ISSUE TITLE
Add TRAVIS_REPO_OWNER and TRAVIS_REPO_NAME environment variables

### ISSUE THREAD

**Issue by HaraldNordgren** [travis-ci/travis-ci#6970]
From https://docs.travis-ci.com/user/environment-variables/:

> `TRAVIS_REPO_SLUG`: The slug (in form: `owner_name/repo_name`) of the repository currently being built. (for example, “travis-ci/travis-build”).

I would like variables

`TRAVIS_REPO_OWNER`: `owner_name`
`TRAVIS_REPO_NAME`: `repo_name`

so that I won't have to do splits in Bash to get these values.

**Comment by kiulkiel** [comment]
Thank you harald. I'm glad to see someone is interested in my work after my
failure. It's still a fresh new project and haven't put much thought into
the name. Owners name well that's me of coarse. As for the project since
termus  was such a epic hit (actually was supposed to be terminus but I
misspelled it; from the walking dead of coarse, seems fitting walking dead
and Remus is now dead, maybe it'll come back to life and be a walking dead
a.i. that would be super sweet) I'm thinking the failed project was #6969 I
wish I could've worked on that project with you. Is that where we both
share the work load. I'm gonna call this "j9 be mine, loveteck  potion #69"
i do have some code typed out but a couple issues. I've got my MIT interns
on it right now but come on they're MIT so might be a few days you
understand. It's for some reason duplicating each line written as tho from
2 different sources. I tried to get it foreword ed up to here to send you
but formats don't correlate. If you have a messaging system that's what
it's writt we need on may be able to update and backup. May come through
that way but not sure. If not I can redo on this or take other ways and get
you a sample. Let me know Jose and look forward to continued collaboration.
Oops I mean Harold sorry hard to keep programmers names all straight. I
hope this one works. I'm trying my best.

**Comment by kiulkiel** [comment]
It is a little racy and not meant for easily offended eyes. Done with care
and some edge. A softer edge but could go harder if wanted

**Comment by HaraldNordgren** [comment]
Is that you Chris (Simpsons artist)??

:laughing::laughing:

**Comment by rjrodger** [comment]
@HaraldNordgren the workaround is:

```
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}
```
See http://stackoverflow.com/questions/19482123/extract-part-of-a-string-using-bash-cut-split

**Comment by carlwright4** [comment]
(#6970)

**Comment by solvingJ** [comment]
These are reversed, should be:
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - export TRAVIS_REPO_NAME=${TRAVIS_REPO_SLUG#*/}

**Comment by HaraldNordgren** [comment]
Any updates on this?
