### ISSUE TITLE
npm Github reference: Permission denied

### ISSUE THREAD

**Issue by strarsis** [travis-ci/travis-ci#7006]
It worked in previous Travis builds, but now suddenly fails.

When using a reference to Github as dependency package source, 
the last Travis builds fail with 'Permission denied' when installing the packages.
It works fine when installing with npm and also should be valid syntax.

Travis build log: https://travis-ci.org/svg/svgo/jobs/182635289#L164

In package.json:
```json
{
  "dependencies": {
     "css-select": "github:fb55/css-select#e02737b8fd5bf8271818cefe8b6dfe7de3584dbd"
  }
}
````

Related PR: https://github.com/svg/svgo/pull/592

**Comment by BanzaiMan** [comment]
https://travis-ci.org/svg/svgo/jobs/182635289#L142 shows that installation of Node.js 4 failed. Probably because of https://github.com/nodejs/build/issues/562. The nodejs.org issue has been resolved, so, assuming that the package source is valid with Node.js 4, if you restart this job it should work.
