### ISSUE TITLE
Upgrade jq to 1.5 on Precise

### ISSUE THREAD

**Issue by freeformz** [travis-ci/travis-ci#7025]
As per https://twitter.com/freeformz/status/808452076401410049, the version of jq in your images is old and doesn't support what's currently documented. Please update. ;-) <3

**Comment by acnagy** [comment]
Hey @freeformz! Thanks for opening this issue - we'll take a look

**Comment by meatballhat** [comment]
@freeformz Sorry for delay!  The jq version on our Trusty stacks is currently 1.5, while the elder Precise stacks are still on 1.4.  I'm trying to avoid anything other than security updates for the Precise stacks, not least because that release is nearing EOL.

In case you haven't already, are you able to [opt into using Trusty](https://docs.travis-ci.com/user/trusty-ci-environment) to get jq 1.5?

**Comment by freeformz** [comment]
SGTM, I'll do that. Thanks!
