### ISSUE TITLE
Variable usage in conditional releases

### ISSUE THREAD

**Issue by pattyr** [travis-ci/travis-ci#7071]
Hello, I'm having trouble using the [Conditional Releases](https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A) feature with a custom variable.

Our `after_success` runs a bash script `check-deploy.sh`:

```ssh
#!/usr/bin/env bash

DEPLOY=false

if [[ ${TRAVIS_BRANCH} == "master" ]]; then
    # only deploy on master
    DEPLOY=true
else
    for f in `git diff --name-only HEAD^`; do
        # only deploy if the changes are to the build directory or the module directory
        if [[ ${f} == "build"* ]] || [[ ${f} == "module"* ]]; then
            DEPLOY=true
        fi
    done
fi
```

We want to use the $DEPLOY result from the `check-deploy.sh` in our .travis.yml `deploy` section:
```
.
.
after_success:
- bash ./build/check-deploy.sh
deploy:
- provider: s3
  .
  .
  on:
    all_branches: true
    condition: "$DEPLOY = true"
    repo: valid/repo
```

Regardless of the result of the bash script, it alway displays the message:
```Skipping a deployment with the s3 provider because a custom condition was not met```

I've tried adding `DEPLOY=false` as an `env:` in `.travis.yml`.
I've tried `export DEPLOY` at the end of the bash script.
I've tried changing the condition to `$DEPLOY == true`.
I've tried removing the condition, which it then does the deploy and no longer says `Skipping a deployment...`, but we want to only deploy when `$DEPLOY = true`.

I'm stumped and wondering if it's even possible; any insight is greatly appreciated! Thank you!

**Comment by BanzaiMan** [comment]
When you run `check-deploy.sh` and set `$DEPLOY` inside that script, the value stays there. It does not affect the value of `$DEPLOY` defined in the build script itself. Therefore, the deployment's custom condition will not be satisfied.

In order to have `after_success` and its subprocess affect the deployment, you will need a different kind of IPC (interprocess communication). One crude way to do it with a simple semaphore file; write (or just simply `touch`) a file in a predetermined location when you want to kick off deployment, then, in the custom condition of your deployment, test for the existence of that file.

Do note that you'll probably want an extra layer of check(s) to prevent any fork from triggering the deployment (encrypting credentials should be sufficient for S3).

**Comment by BanzaiMan** [comment]
To think, `source`-ing the `check-deploy.sh` might work as well.

```yaml
after_success:
- source ./build/check-deploy.sh
⋮ # rest
```

but this is untested.

**Comment by pattyr** [comment]
Thank you for the quick reply! `source`-ing `check-deploy.sh` worked beautifully. Didn't get a chance to try the first suggestion (`touch`) but I feel like that would've worked too.

Thanks again!
