### ISSUE TITLE
Shallow Git Submodules not working

### ISSUE THREAD

**Issue by Nutomic** [travis-ci/travis-ci#7091]
According to #1867 and [#251 (comment}](https://github.com/travis-ci/travis-build/pull/251#issuecomment-254786875), it should be possible to do a shallow clone for submodules with the following config:
```
git:
  submodules_depth: 100
```

I tried this, but get the error `The command "eval git submodule update --init --recursive --depth=10" failed. Retrying, 2 of 3.`

[Link to Build](https://travis-ci.org/syncthing/syncthing-android/builds/187717042)

**Comment by BanzaiMan** [comment]
It is possible. As a result, we are running the command

```
git submodule update --init --recursive --depth=10
```

using the depth given in the configuration (https://github.com/syncthing/syncthing-android/commit/7df0428f0aeb933c2868632a48d23a3594b392c5#diff-354f30a63fb0907d4ad57269548329e3R6) instead of the default (without `--depth=10`).

If the checkout is failing, the commit your build is trying to checkout is not reachable with the parameters given. For example, commit go/golang@2f6557233c5a5c311547144c34b4045640ff9f71 (see https://travis-ci.org/syncthing/syncthing-android/builds/187717042#L343) is more than 2180 commits behind the current `master` HEAD (https://github.com/golang/go/compare/2f6557233c5a5c311547144c34b4045640ff9f71...master). It is not clear to me why the commit is trying to check out this old commit for the submodule; I suggest looking into why.

At any rate, I do not think this is an issue on our side.

**Comment by Nutomic** [comment]
Okay thanks, I misunderstood how the depth parameter works.
