### ISSUE TITLE
Yarn down, all builds fail

### ISSUE THREAD

**Issue by steebchen** [travis-ci/travis-ci#7112]
I am using yarn and currently yarnpkg.com is down (524 Cloudflare timeout) which results into failing builds. It would be useful if the install.sh (https://yarnpkg.com/install.sh) which you are downloading in every build could be cached or add a fallback if it's offline.

EDIT: back online, but still would be an idea though.

**Comment by BanzaiMan** [comment]
I can't find the record now, but I suggested having a local copy of the install script, very much like we do with `nvm`.

However, someone (perhaps @daniel15?) suggested that we should not, because we always want to rely on the latest script.

This is valid, because if we can't download install script from yarnpkg.com, then surely the attempts to install `yarn` on the fly from the archive on yarnpkg.com is doomed to fail anyway. I do not think having these archives "locally" is feasible.

**Comment by BanzaiMan** [comment]
We will have yarn pre-installed on all images (over time), so that some level of service is assured.
