### ISSUE TITLE
None of my repositories are showing in Travis-CI

### ISSUE THREAD

**Issue by libeclipse** [travis-ci/travis-ci#7118]
Just started (or tried to) using Travis again. Logged into the .org site and granted it access to my account. However, none of my repositories show up. Even accessing them directly via the URL just gives an error saying they can't be found. Attached a screenshot.

![screenshot from 2017-01-08 22-20-41](https://cloud.githubusercontent.com/assets/8942495/21754085/bb175a10-d5f0-11e6-9492-b4778a3a7c78.png)

**Comment by BanzaiMan** [comment]
Which repositories are missing?

**Comment by libeclipse** [comment]
All of them

**Comment by libeclipse** [comment]
Update: checked from my phone and the repositories showed up. Might be browser/device specific, although unlikely. Will check on my laptop again and update.

**Comment by BanzaiMan** [comment]
@libeclipse None of your private repositories have any build.

**Comment by libeclipse** [comment]
@banzaiman I'm not talking about my private repositories. I'm talking about my public ones.

**Comment by BanzaiMan** [comment]
@libeclipse Public ones appear only on https://travis-ci.org, and private ones only on https://travis-ci.com for historical reasons.

We intend to unify this in the near future, as this is a source of confusion. Until then, please use the correct host.

I'm closing this, since there is nothing further to do here.

**Comment by libeclipse** [comment]
Ah, okay. I googled but couldn't find a reference to this. Maybe it should
be added somewhere.
