### ISSUE TITLE
Downloading binaries from releases.hashicorp.com issues on container-based Precise

### ISSUE THREAD

**Issue by MariadeAnton** [travis-ci/travis-ci#7131]
We're currently investigating this issue downloading binaries from releases.hashicorp.com on container-based Precise infrastructure:

```yaml
sudo: false
dist: precise
```

Seems it fails to download the binaries, reporting the following error:

```bash
* Unknown SSL protocol error in connection to releases.hashicorp.com:443 
* Closing connection #0
curl: (35) Unknown SSL protocol error in connection to releases.hashicorp.com:443
```

We'll post updates as soon as we know some more.

**Comment by jkehres** [comment]
I'm seeing this same issue today in my project which uses curl to download Terraform as well.

Not sure if this is related but as part of debugging I checked what version of curl Travis is using and found it was version 7.22.0 that was released over 5 years ago on 2011-09-13. Using a 5 year old tool to download files is probably not good. That's 5 years of security fixes and protocol updates that are missing.

I also noticed that the SSL certificate for releases.hashicorp.com was just reissued yesterday (January 9, 2017). Maybe the new certificate and the really old version of curl don't work together. I'm not an SSL expert, though, so this is just a theory.

**Comment by cotsog** [comment]
In the meantime, you can try adding the following to your .travis.yml file:

```
sudo: required
```

This will route your builds on our sudo-enabled Precise infrastructure where the problem doesn't happen.

**Comment by meatballhat** [comment]
In my tests so far, I can confirm that this is isolated to container-based Precise.  https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/190646021

@cotsog's suggestion to route to sudo-enabled will work, and for those who can switch to Trusty, that container-based infrastructure is behaving well:

``` yaml
sudo: false
dist: trusty
```

**Comment by meatballhat** [comment]
For anyone who must stay on Precise + container-based, here is a python script that is known to work that requires python 3.4.3 or greater: https://github.com/meatballhat/cloaked-octo-tyrion/blob/668141ea41575c061f43f25b42563ac8f908ffe3/download-tlsv12

**Comment by cotsog** [comment]
Fastly (who are fronting the releases.hashicorp.com) confirmed that this issue is caused by a change to the Hashicorp endpoint who recently went to support TLS v 1.2 only and removed support for earlier versions (1.0 and 1.1). Unfortunately, the current cURL and related libraries (e.g. OpenSSL) versions on our Precise containers doesn't support TLS v 1.2.

However, our Engineering Team confirmed that this will be fixed with the next update to our Precise containers for which we don't have an ETA at this time. Sorry for the inconvenience.

[As @meatballhat said above](https://github.com/travis-ci/travis-ci/issues/7131#issuecomment-271609004), we are suggesting to move your builds to the container-based Trusty infrastructure in the meantime. We will update this issue when the new Precise containers are released.

Thank you for your patience.

**Comment by sethvargo** [comment]
Hi all,

This is all true - we migrated to TLS 1.2 only and dropped support for earlier versions as part of our security focus. The easiest way to fix this, as @meatballhat said, is to use the beta-trust env:

```yaml
sudo: false
dist: trusty
```

Sorry about that!

**Comment by BanzaiMan** [comment]
I'm closing this in favor of #4757.
