### ISSUE TITLE
ENV_VARS available to all builds?

### ISSUE THREAD

**Issue by nbrady-techempower** [travis-ci/travis-ci#7133]
I'm looking for a way to run a script **before** any of the jobs in my build matrix start. This script would set an environment variable that I want available to all jobs in that matrix. Is there a way to do this right now?

**Comment by BanzaiMan** [comment]
Each job in a build matrix is independent of all the others. They do not share anything.

**Comment by nbrady-techempower** [comment]
@BanzaiMan might it be possible to take advantage of the cache for something like this?

**Comment by BanzaiMan** [comment]
Could you explain what you are trying to accomplish?

**Comment by nbrady-techempower** [comment]
I have about 180 jobs in the build matrix. I have a script that runs before_install in each test that takes some time, but does a git diffing across commit ranges to determine if a particular job should be run based on certain files being modified. This runs for every job, and just exits 0 if that job doesn't need to run. What I was looking for was a way to run the git diffing only once and save a string of data to a global environment variable, and each job would match against that to skip, instead of running the diffing tool each time.

**Comment by BanzaiMan** [comment]
What you describe is not possible at this time.

Here's what I would try instead:

1. Modify the build so that only one job is created by any commit.
1. The build would calculate what jobs to build (with `git diff` or whatever), create a new commit with the new configuration, and then push this commit to GitHub.

Do take care to not create an infinite build loop. It might be a good idea to push the manual commit in 1 and the calculated commit in 2 to different branches (thus avoiding infinite build loop and lightening the load of manual modification of `.travis.yml` in 1).

**Comment by nbrady-techempower** [comment]
That's something we've floated around before. Might be worth giving a go. Thanks for the help!
