### ISSUE TITLE
Cache the entire environment

### ISSUE THREAD

**Issue by LinxiFan** [travis-ci/travis-ci#7136]
Sorry if this is a really simple question ...

I have a python project whose dependencies _never_ change (a few `pip install` and `golang`). However, Travis goes through these steps every time: 
```
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
    - sudo apt-get update -q
    - sudo apt-get -y install golang
```
which takes the bulk of the build time. After a Google search, I see that Travis does not cache the Debian packages. 

Is there any way (other than using Docker) to keep the env persistent? If I have to use Docker, will it make the build faster? Thanks!

**Comment by BanzaiMan** [comment]
If you know *exactly* the files your packages will install, then you can try listing them in your `.travis.yml` (and ensure somehow that all the files do exist, lest your requirement not be met). If you don't, and try to cache something big (like `/usr/bin` and `/usr/lib`), you will end up paying for fetching, expanding, and uploading the cache, probably more than offsetting any saving you got by not running these `apt-get` commands.

**Comment by LinxiFan** [comment]
@BanzaiMan thanks for your idea! That's probably not a good way to install such a package. :(  I guess there's simply no way around. 

I'm curious why no one brings this up more often. For most projects I know, the dependencies don't really change over time. Git commits and pull requests typically update a few lines of code at a time. Doesn't Travis waste a lot of cycles redoing installation? I wonder why it isn't optimized for such a common scenario. Or am I missing something?

**Comment by BanzaiMan** [comment]
The needs vary greatly from one repository to the next. While the desire to speed up the build by caching things is common, the technical details to achieve it is not. For example, your build adds a PPA source and installs the `golang` package (if you just need a Go runtime, you can also consider using `language: go` as well), but another repository may have a completely different set of requirements.

Setting up a build environment from scratch does add time to the build. However, this ensures that the build is run on a clean environment. Persisting build images (for example) would be difficult (not to mention probably expensive) and prone to subtle errors (e.g., the app may fail to function in production because the production environment is different from the CI environment).

I'm closing this now, but if you have additional questions, do not hesitate to ask.
