### ISSUE TITLE
Question about slack notifications

### ISSUE THREAD

**Issue by tonyjchong** [travis-ci/travis-ci#7201]
Hi,

I saw another issue about trying to pass the the travis/slack secrets through an environment variable and was told that particular feature will not be added to the roadmap. 

My question is a bit different. In my travis file, I am defining my version number using an env variable called $VERSION.

Is there a way I can pass the value of $VERSION into the slack notification?

Thanks!

**Comment by BanzaiMan** [comment]
Thanks for taking time to open this issue.

Unfortunately, at this time, it is not possible to use an environment variable defined during the build in any notification. The reason is that notifications are defined at the configuration time, and there is no way for the build script to inform the notifications of any value thus defined during the build.

There may be previous issues on this, though I can't find it at the moment.

**Comment by tonyjchong** [comment]
Thanks for the update @BanzaiMan

**Comment by rudysuharyadi** [comment]
Hi, is there any feature like this in the roadmap?

**Comment by keremcankabadayi** [comment]
Check [this](https://github.com/travis-ci/travis-ci/issues/6387#issuecomment-584772979).
