### ISSUE TITLE
travis_wait caveats (under resource exhausting I guess)

### ISSUE THREAD

**Issue by azat** [travis-ci/travis-ci#7202]
Hi everyone!

There are some issues with `travis_wait`, at least in osx:
- https://travis-ci.org/azat/libevent/jobs/194063156 (`make -j20` analog)
- https://travis-ci.org/azat-archive/travis-playground/builds/194093877 (just `sleep`)

The first one (real build) fails, while the second one is fine. I tried a lot (overwrite that two functions, bash `trap`) but nothing works.

And after I limited number of jobs to 4 - it works:
- https://travis-ci.org/azat/libevent/jobs/194097994 (timeout 30 mins -- works)

Seems that because of too much parallel processes `travis_jigger` killed/hanged and the common error about "no output for 10m received" produced, it will be great to have another error message for this.

**Comment by BanzaiMan** [comment]
`travis_wait` works by sending a process to the background, sleeping for 60 seconds, then check if the background job is still running. When it wakes up, it writes this to the STDOUT, so that the build is not terminated:

```
Still running (N of 30): cmake --build . --target verify
```

In [this failing job](https://travis-ci.org/azat/libevent/jobs/194063156), you see only `(2 of 30)`. This means that `travis_wait` had only 2 chances to wake up before the wall clock progressed 10 minutes and the job was terminated. This is unusual, but my guess is that you are overtaxing the VM by running 20 concurrent threads. Our Mac VMs are nowhere near the capacity such a build demands. So don't define so many threads.

When the build is forcibly terminated like this, there is nothing that build script can do to clean up, including printing friendly messages that you describe. This behavior may change in the future, but this will take some time. (This is tracked elsewhere.)

I'm closing this.
