### ISSUE TITLE
Update system gem version to 2.6.9

### ISSUE THREAD

**Issue by mrcasals** [travis-ci/travis-ci#7204]
TravisCI is failing to install the `rainbow` gem v2.1.1 because of a Ruby error. Updating the `gem` command to the latest version fixes this.

https://github.com/sickill/rainbow/issues/48

Adding `gem update --system` should fix the issue, as reported at the related issue. Is it possible to have this upgrade system-wide?

Thanks!

Edit: See https://travis-ci.org/HospitaletDeLlobregat/decidim-hospitalet/builds/194436866 for an example of a broken build due to this error. Adding the `gem update --system` command as a "before_install" step fixes the error ("install" step): https://travis-ci.org/HospitaletDeLlobregat/decidim-hospitalet/builds/194436866

**Comment by BanzaiMan** [comment]
To confirm, this is an issue with the RubyGems version pre-packaged with Ruby 2.4.0, right?

**Comment by mrcasals** [comment]
@BanzaiMan I'm sincerely not sure about this, but I'd say that's right.

Also, there's a new version released yesterday (v2.6.10).

**Comment by BanzaiMan** [comment]
So, if the version that comes pre-installed with a Ruby release is problematic, we find ourselves in a tenuous situation. One can argue both ways whether or not the standard libraries should be updated to work around the problem.

1. It is a good idea to update, because that leads to cleaner build.
1. It is also a good idea to **not** update, because:
     1. It is what the release looks like.
     1. It alerts to the library authors the problems their users will face when using a particular version of the language.
     1. It is not trivial to update build images based on a bug.

My inclination is to not update.

**Comment by BanzaiMan** [comment]
I'm closing this.
