### ISSUE TITLE
/bin/bash: line 2: -shared: command not found

### ISSUE THREAD

**Issue by nacnudus** [travis-ci/travis-ci#7236]
When building my package on r-devel, I get this error: `/bin/bash: line 2: -shared: command not found`.  More context below.  Complete listing here: https://travis-ci.org/nacnudus/tidyxl/jobs/196188464.  The package builds on Travis r-release, and on rhub r-devel.

```
I/home/travis/R-bin/lib/R/include -DNDEBUG  -I"/home/travis/R/Library/Rcpp/include" -I/home/travis/R-bin/include      -c zip.cpp -o zip.o
/bin/bash: I/home/travis/R-bin/lib/R/include: No such file or directory
make: [zip.o] Error 127 (ignored)
-shared -L/home/travis/R-bin/lib -o tidyxl.so RcppExports.o border.o color.o fill.o font.o gradientFill.o patternFill.o stroke.o styles.o tidyxl.o xf.o xlsxbook.o xlsxcell.o xlsxsheet.o zip.o
/bin/bash: line 2: -shared: command not found
make: *** [tidyxl.so] Error 127
ERROR: compilation failed for package ‘tidyxl’
```

@craigcitro @hadley @jimhester.

**Comment by jimhester** [comment]
This is caused by https://bugs.r-project.org/bugzilla3/show_bug.cgi?id=17189. Essentially R-devel has stricter checks for C++11 support than previous versions of R that the compilers on travis - precise do not meet. You have a few options,

1. Explicitly set `CXX1X` and `CXX1XFLAGS` in your personal `Makevars` (https://github.com/hadley/devtools/blob/d8ab190cd05e4bd2a3688a1eab3324109060b111/.travis.yml#L23-L26). This will work find provided gcc 4.6.3 supports all C++11 features you are using.
2. Use a newer compiler on travis, then do 1. to point to it. Necessary if gcc 4.6.3 does not support a C++11 feature you use.
3. Use `dist: trusty` to use a more recent compiler by default. This won't help currently because only R-release is available on trusty. However in the future once https://github.com/travis-ci/travis-build/pull/946 is merged and deployed this will be the easiest solution.

**Comment by nacnudus** [comment]
Thank you for a very helpful reply.
