### ISSUE TITLE
libtar on ubuntu/precise causes buffer overflows

### ISSUE THREAD

**Issue by ncarrier** [travis-ci/travis-ci#7308]
Hello,
The bug: https://bugs.launchpad.net/ubuntu/+source/libtar/+bug/1038698
affects the ubuntu precise version used by travis.
An example is visible here: https://travis-ci.org/ncarrier/cushions/builds/200501106#L676
I ran the build in a ubuntu:precise docker and could reproduce the issue.
The following patch (attached in the bug report's 11-th comment) fixes the issue: https://bugs.launchpad.net/ubuntu/+source/libtar/+bug/1038698/+attachment/3267942/+files/libtar-1.2.11-encode_buffer_overrun_fix.patch
, I could apply it manually, rebuild libtar-1.2.11 and the overflow doesn't happen again.
Apparently, it has been integrated in subsequent ubuntu versions, but not backported in precise.

**Comment by BanzaiMan** [comment]
Thanks for the report. Could you confirm that it works for Trusty images?

**Comment by ncarrier** [comment]
Yes, I just tested and with trusty it works.

**Comment by BanzaiMan** [comment]
Thanks for the confirmation. If the fix comes to the official Precise release, we may include it in a future (if any) build image update. Unless this issue is critical (for security), we are very unlikely to address this bug, as Precise is being phased out and we concentrate our efforts on Trusty.

Again, thank you for reporting! I'm closing this now.
