### ISSUE TITLE
Why is there not testing for Python 3.0 and 3.1 and pre-2.6?

### ISSUE THREAD

**Issue by Monkeyboy2805** [travis-ci/travis-ci#7310]

**Comment by BanzaiMan** [comment]
There has been no request, and it was not practical to support all versions. We can try building them, now that the process is much more automated. What is the practical impact for adding outdated Python versions?

**Comment by Monkeyboy2805** [comment]
My project is designed to support 3.0-3.7alpha but I can't say this is true without the CI builds.

**Comment by BanzaiMan** [comment]
I tried compiling 2.x for x < 6, but we cannot compile it from source with python-build due to a recent `virtualenv` in use. See, for example: https://travis-ci.org/travis-ci/cpython-builder/jobs/210901924#L381

The [3.0](https://travis-ci.org/travis-ci/cpython-builder/builds/210902290) and [3.1](https://travis-ci.org/travis-ci/cpython-builder/builds/210902253) fail to compile for different reasons.

It is not practical to provide support for these versions, I'm afraid.
