### ISSUE TITLE
Build unknown

### ISSUE THREAD

**Issue by andela-cofor** [travis-ci/travis-ci#7324]
https://github.com/andela/izanagi-cfh

My travis shows all tests passes but badge shows build unknown ???????

**Comment by roidrage** [comment]
The problem seems to be that there's not been a build for the `master` branch yet, which we fall back to when determining the build status.

You can use the following URL to fetch the status for the `staging` branch, which should give you a green badge: https://travis-ci.org/andela/izanagi-cfh.svg?branch=staging

![](https://travis-ci.org/andela/izanagi-cfh.svg?branch=staging)
