### ISSUE TITLE
Installing php

### ISSUE THREAD

**Issue by mdprasadeng** [travis-ci/travis-ci#7352]
I have a private repo with a Java project. The build and deploy are working great. But I need to run a php script as a post deploy step. By default I got phone command not found. And even apt-get install php reported package not found.

Can anyone help? Sorry if I missed some documentation.

**Comment by roidelapluie** [comment]
You need to run sudo apt update (e.g in before_scripts)

**Comment by BanzaiMan** [comment]
@mdprasadeng Hello. As @roidelapluie mentioned, `apt-get install php` was failing because of #7351. This should be fixed now, so restarting your failing job should proceed to install it.

If that is not sufficient for your needs, please email us at support@travis-ci.com with details of your requirements, so that we can help you.

Thanks.

**Comment by BanzaiMan** [comment]
Closing this for now.
