### ISSUE TITLE
Mac OS X JRuby builds usually time out

### ISSUE THREAD

**Issue by ms-ati** [travis-ci/travis-ci#7376]
See, for one example:
https://travis-ci.org/enkessler/childprocess/jobs/204864997

**Comment by BanzaiMan** [comment]
Did you restart it?

**Comment by ms-ati** [comment]
Sorry, I think the project owner restarted it...

**Comment by BanzaiMan** [comment]
Do you have any other example?

**Comment by ms-ati** [comment]
@enkessler it looks like you restarted all the builds with this failure in `childprocess`. Do you have any links to a jruby timeout in Travis so that they can take a look at it?

**Comment by enkessler** [comment]
@ms-ati I usually restart them in order to confirm that it's a false negative and the build is really 'green'.

I've got a branch where I've been playing around with the Appveyor config file. Those changes should have zero impact to the Travis builds or any project functionality but, sure enough, the JRubies keep flickering.

https://travis-ci.org/enkessler/childprocess/builds/205315084
https://travis-ci.org/enkessler/childprocess/builds/205317585
https://travis-ci.org/enkessler/childprocess/builds/205393361
https://travis-ci.org/enkessler/childprocess/builds/205395365

**Comment by BanzaiMan** [comment]
I don't know what your code does, but if you are using signals for IPC, it may not work on JRuby, as warned. https://travis-ci.org/enkessler/childprocess/jobs/205317613#L99-L101

**Comment by BanzaiMan** [comment]
Is there anything for us to do?

**Comment by enkessler** [comment]
@BanzaiMan No, Travis-CI seems fine. This appears to be a fundamental problem with JRuby.

**Comment by BanzaiMan** [comment]
OK. I'm closing this now.
