### ISSUE TITLE
Upgrade Docker on travis-ci

### ISSUE THREAD

**Issue by bebehei** [travis-ci/travis-ci#7380]
Hi guys,

just recently, there had been docker 1.13 released and I'm curious about the deployment date on Travis-CI. I desperately need a feature added only in recent docker-version. What are the plans for deployment of 1.13?

Thanks in advance.

**Comment by dylanscott** [comment]
Until Travis upgrades their docker version, you can [do it yourself](https://gist.github.com/dylanscott/ea6cff4900c50f4e85a58c01477e9473) in your build script.

To the Travis team: The `--cache-from` flag added in Docker 1.13 is of particular usefulness for continuous integration. I just migrated my team off of CircleCI onto Travis specifically because Circle is stuck on an old Docker version and Travis allows me to upgrade to 1.13.

**Comment by bebehei** [comment]
Thanks, but I need `--squash` and found out, this is currently only supported if you run dockerd in experimental mode. So I might have to go with a 3rd party tool.

**Comment by czzarr** [comment]
That would be really useful, `--cache-from` speeds up the docker builds a ton!

**Comment by bebehei** [comment]
docker arrived in version 17.03 on travis. I think this issue (`--cache-from` and `--squash`) can be closed.

**Comment by mcapuccini** [comment]
@bebehei this is still an issue: https://travis-ci.org/kubenow/KubeNow/jobs/315408226#L669, I get error when trying to squash.

**Comment by bebehei** [comment]
@mcapuccini Yes, in meantime I found out, this wasn't valid (And maybe still isn't?). Before docker 17.03 shipped in travis, I started using [docker squash](https://github.com/goldmann/docker-squash), which is a good working replacement.
