### ISSUE TITLE
Changing the base branch on a Github PR does not trigger a new PR build

### ISSUE THREAD

**Issue by peterjwest** [travis-ci/travis-ci#7465]
Let me know if you need more information, but this should be self explanatory

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by peterjwest** [comment]
I don't have any open source projects, will a private one do?

**Comment by BanzaiMan** [comment]
Hmm. Without looking at the actual sequence of events and commits, it might be difficult to troubleshoot. We could still try. Perhaps you'd like to explain in detail here, or send us email at support@travis-ci.com.

**Comment by peterjwest** [comment]
I can make an example on an open source repo

**Comment by peterjwest** [comment]
The sequence of events is simple:
- Create a PR on any Travis repository
- Change the base branch of the PR (i.e. develop -> master)
- The merge commit for a PR build is now different (merging into a different branch), but a new build is not triggered

**Comment by BanzaiMan** [comment]
I don't think the change in the PR generates an event that we listen on. If you close and reopen the PR in question, does it trigger a build you desire?

**Comment by peterjwest** [comment]
Yes that triggers a new PR build, thanks. That will work as a quick fix.

**Comment by BanzaiMan** [comment]
Can we close this?

**Comment by wpzero** [comment]
Yeah, I found, sometime , I push a commit, and this will not trigger a ci test. I don't why, I have to close and reopen a pr. I think there are some bugs.

**Comment by aCampello** [comment]
Just to confirm, closing the PR, waiting for a couple of seconds, and then re-opening is still the fix for this issue.

**Comment by joeyparis** [comment]
This doesn't seem to recreate the build, though, just re-run. e.g., I just took over an older repo. It had a bunch of pull requests against master, which had an old `travis.yml` file referencing now EOL ruby versions leading to failed Travis CI builds. I created a new branch and updated the `travis.yml` file to only test against the still supported ruby versions and pass the tests. I then updated the old pull requests to merge to the new branch, which should now run tests only for what can pass.

Initially, this does nothing (as this issue is about). However, closing the PR and reopening, it just restarts the old build. It doesn't recreate the build based on its new base branch.

This is particularly a problem for me because I do not have write access to these pull requests branches and would have to rely on the original requesters to do this. Since some of these pull requests are nearly 3 years old (but still viable), this isn't ideal.
