### ISSUE TITLE
how travis encrypt work??

### ISSUE THREAD

**Issue by JSpiner** [travis-ci/travis-ci#7495]
I wondered how travis's encrypt work. I searched and found the following issue.
https://github.com/travis-ci/travis-ci/issues/2982
It says, using public/private key to asymmetric encryption files.
But travis decrypt code is like

```script
 openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv
  -in encryptedfile -out outputfile -d
```

I know 'AES-256' is a symmetric key algorithm.
So maybe public and private will be the same.

Q1) If travis encrypt with a symmetric algorithm, is the key stored in the cli program? (Travis-cli) Is this has a security problem?
Q2) If you use an asymmetric algorithm, why decode it as aes?
Q3) Why does not it support encrypting multiple files without archive files? Security problem?

**Comment by BanzaiMan** [comment]
I think you are confusing two different encryption use cases we offer.

[`travis encrypt`](https://docs.travis-ci.com/user/encryption-keys) uses the private key associated with each repository to encrypt what you give it. The API takes your input, and returns the encrypted value. At no point during the process (and later) the private key is exposed to the user.

The `openssl` command you showed is for [encrypting files](https://docs.travis-ci.com/user/encrypting-files). We do not support encrypting multiple files because the second invocation of `travis encrypt-file` overwrites the configuration set by the previous invocation.

**Comment by JSpiner** [comment]
Thanks I understand :+1: 

I LOVE TRAVIS <3
