### ISSUE TITLE
Use `rustup default` instead of `rustup update` for `language: rust` projects

### ISSUE THREAD

**Issue by QuietMisdreavus** [travis-ci/travis-ci#7510]
travis-ci/travis-build#993 recently switched out the method of installing the Rust toolchain to use `rustup.rs`, the officially recommended method. Unfortunately, it seems it used the command `rustup install $TRAVIS_RUST_VERSION` to install the toolchain, which doesn't make the selected toolchain the default for the environment. This can lead to situations where a [repo uses nightly Rust but is still being built with the stable compiler](https://travis-ci.org/SethDusek/define-rust/builds/213998300). Changing out the rustup command for `rustup default $TRAVIS_RUST_VERSION` will fix the issue, since it installs the given version and switches out the active toolchain to the freshly-installed version.

**Comment by BanzaiMan** [comment]
I think the issue was that the invocation skipped `--default-toolchain=$TRAVIS_RUST_VERSION` (https://github.com/travis-ci/travis-build/pull/993/files#diff-8cf3abeb97248b73f98e4a67a8a9b482R24). A tentative fix has been deployed to production. Could you restart affected builds to confirm that it works?

Thank you!

**Comment by QuietMisdreavus** [comment]
[Looks like it works now!](https://travis-ci.org/SethDusek/define-rust/builds/214047405)

I guess adding the `--default-toolchain` argument makes the `rustup default` command unnecessary, since that's already been set up.

**Comment by BanzaiMan** [comment]
Thanks for the prompt confirmation.
