### ISSUE TITLE
Discord notification webhooks

### ISSUE THREAD

**Issue by jleclanche** [travis-ci/travis-ci#7554]
Discord supports slack-compatible webhooks. However, Travis only supports Slack oauth. If slack webhooks were configurable, a discord webhook could be set up by using the discord webhook url with `/slack` appended to it:

https://discordapp.com/developers/docs/resources/webhook

**Comment by BanzaiMan** [comment]
I'm closing this in favor of https://github.com/travis-ci/travis-tasks/pull/71.

**Comment by thasmo** [comment]
@BanzaiMan, why has travis-ci/travis-tasks#71 been locked? Will it be merged?

**Comment by JeromeGill** [comment]
Still not merged? :-1:

**Comment by Purpzie** [comment]
I apologize for commenting on such an old issue, but I'd like to point out that Discord has since released a whole page about supporting open-source projects. 👍 https://discordapp.com/open-source
A lot of applications have started using Discord, and it would be amazing if Travis notifications worked with it.
