### ISSUE TITLE
No builds for this repository

### ISSUE THREAD

**Issue by nmcastelino** [travis-ci/travis-ci#7573]
Hello,
I read the getting started, created the .travis.yml file and pushed it into the repository. It is currently in the master but it still says that there are no builds for the repository.
The link is https://travis-ci.org/ateamwpi/HospitalKiosk
Please help.

**Comment by BanzaiMan** [comment]
Does Travis CI have access to this organization's repositories?

**Comment by nmcastelino** [comment]
Yes it does.
The repository name does show up on the left

**Comment by BanzaiMan** [comment]
Thanks for the information. There may have been a problem with the web hook on GitHub. I've disabled and re-enabled it for you now. Please try pushing another commit and let us know how it goes.

**Comment by BanzaiMan** [comment]
https://travis-ci.org/ateamwpi/HospitalKiosk/builds is showing builds now.

**Comment by iMichaelOwolabi** [comment]
Please I am having similar issue. After adding the .travis.yml file to my repo and pushing several times to the github repo, I stll get "No builds for this repository" message on my dashboard. I have synced my account several times as well but no change. Here is the link https://travis-ci.com/iMichaelOwolabi/store-manager/
![travis dashboard](https://user-images.githubusercontent.com/20207295/47623042-958df880-db0c-11e8-96c1-a85dcbc39785.PNG)

Thanks

**Comment by BanzaiMan** [comment]
@iMichaelOwolabi Your `.travis.yml` has syntax error, so no builds have run. https://travis-ci.com/iMichaelOwolabi/store-manager/requests

In particular, [this line](https://github.com/iMichaelOwolabi/store-manager/blob/0217c756851f778482fa199c746c90868e4cd67e/.travis.yml#L4) has an extra leading white space.

In general, YAML is quite picky in indentation, so please be careful. (I also suggest using at least 2 white spaces for each indentation level, since 1 space could be very hard to distinguish.)

**Comment by iMichaelOwolabi** [comment]
Thanks so much @BanzaiMan  after fixing the white-space error the repo is now building. I am grateful

**Comment by DiegoBrambilla** [comment]
Hello,
I am also experiencing the same problem. I have followed the getting started guide, synced my GitHub profile and I also receive the message "No builds for this repository"
[This repository](https://github.com/DiegoBrambilla/rrna-ampliseq/tree/dev) already has a .travis.yml file, so I didn't have to git push it.
Any words of advice would be most appreciated, thank you.
