### ISSUE TITLE
Test executed by a worker not updated since 2 years

### ISSUE THREAD

**Issue by wysman** [travis-ci/travis-ci#7625]
Hi,

It's look like some workers are very old and MUST be updated.

You can check this build log (18 April 2017).
https://travis-ci.org/photon/utils-mongodb/jobs/223236164

Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e <= 4 feb 2015 !!!

Best regards,

**Comment by BanzaiMan** [comment]
Hello. We posted our plans for the near future here: https://blog.travis-ci.com/2017-04-17-precise-EOL

If you have concrete requests, please check if there are existing ones, and if you don't find any, please open a new one.

Thanks. I'm closing this for now.

**Comment by wysman** [comment]
My issue is about tests failling due old worker.

For exemple, this second repo which need same requirements (php/mongo) as the first link.
It run on a more updated worker (25 Oct 2016). And i really think that my first project link can run successful tests with this version.
https://travis-ci.org/photon/session-mongodb/jobs/223207631

Why all workers (precise) are not up to date with the last chef cookbook ?

Best regards,

**Comment by BanzaiMan** [comment]
Sorry, I jumped to a wrong conclusion with the subject you gave.

The builds you indicated behave differently because they are running on different stacks.

https://travis-ci.org/photon/session-mongodb/jobs/223207631 is running on GCE (`sudo`-enabled) because the repo is old and it defaults to it without `sudo: false`.

https://travis-ci.org/photon/utils-mongodb/jobs/223236164 runs on a container, as the repo is newer.

https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments shows differences.

For operational reasons, we update them separately. Recent updates are recorded in https://docs.travis-ci.com/user/build-environment-updates/.

Does this answer your questions fully?

**Comment by wysman** [comment]
So the never repo run on a more older Cookbooks Version ???

Due old Cookbooks Version, php ext-mongdb is not available in "container" .
Only to have a up to date Cookbooks Version, can i force utils-mongodb to run on GCE ? Maybe enable sudo, without use it ?

Best regards,

**Comment by BanzaiMan** [comment]
Could you elaborate on what you are trying to accomplish? Do you want a MongoDB extension for your PHP runtime?
