### ISSUE TITLE
Travis builds not working for specific user

### ISSUE THREAD

**Issue by adamjstewart** [travis-ci/travis-ci#7662]
Our project, https://github.com/LLNL/spack, uses Travis CI for pull requests. It's generally reliable, but seems to have something against a specific user, @svenevs. For every PR that @svenevs submits (https://github.com/LLNL/spack/pull/3964, https://github.com/LLNL/spack/pull/3966), Travis never runs. Any idea why?

**Comment by BanzaiMan** [comment]
The user has been flagged for potential abuse. Please have them get in touch with us at support@travis-ci.com. Thank you!

**Comment by adamjstewart** [comment]
Thanks for clearing that up. Will do!

**Comment by tasket** [comment]
@BanzaiMan - This has happened to my account, where we noticed it on the following PR:

https://github.com/QubesOS/qubes-core-admin/pull/176#issuecomment-355329343

Travis support has been aware of it for FIVE days, still unresolved...

**Comment by tasket** [comment]
Looking for some similarities between @svenevs PR and mine, I get the feeling Travis considers the words "Do not" to be abusive language. Hmmm...
@marmarek

**Comment by svenevs** [comment]
@tasket I was the culprit in this scenario.  The cause was that when I first started submitting pull requests to repositories that had travis on them, my user name was different (call it `@oldghb`).  I later changed my GitHub name to the current one, but their servers still had me down as `@oldghb` which is why the builds were getting blocked.

I e-mailed travis support and they responded in a reasonable amount of time and helped me get the new username registered.  So the cause was unrelated to the content of the PR.  Note that at this time of year, the delay is likely because their staff have (hopefully!) been on vacation and are returning to a backlog of tickets.

If you or the user submitting pull requests did a github name change, include that in your ticket with Travis.  I can't find the e-mails right now, but I'm pretty sure the conversation started off with me saying "the only think I can think of is I changed my github name from `@oldghb` to `@svenevs`", which immediately gives them the information they need to fix the issue.

**Comment by tasket** [comment]
@svenevs Yes I did a name change (was ttasket) which I have since mentioned to Travis support. Unfortunately when I logged into the Travis site, it merely reified the abuse flag under the new name. So I'll have to wait and see if support comes through for me as it did for you.

Thanks for relating your experience!

**Comment by svenevs** [comment]
Sure thing.  I do not recall if I had actually logged into Travis before contacting support.  I probably didn't, so that may have made things easier to fix for them.
