### ISSUE TITLE
Unable to locate package libjson-c2

### ISSUE THREAD

**Issue by MAGICCC** [travis-ci/travis-ci#7710]
Hey,

Since 2 days my builds are failing since it can't find the mentioned package.
Using ```xenial``` as build OS

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

As we do not support Xenial at this time, if it was working before, it was by accident.

**Comment by MAGICCC** [comment]
Yes that's https://travis-ci.org/freifunk-mwu/peers-ffmz/builds/229131788

Why did you drop Xenial support?

**Comment by BanzaiMan** [comment]
We have never supported Xenial.

**Comment by MAGICCC** [comment]
I see, any plans to support xenial?

**Comment by BanzaiMan** [comment]
Where is a build log that show successful installation of `links on-c2`?

**Comment by MAGICCC** [comment]
Nowhere, but I wonder why it fails on such a random package suddenly

**Comment by BanzaiMan** [comment]
I am not sure if I understand. This package was never successfully installed in any of your previous builds? How is that "random"? If the package is not found in any of the sources defined, naturally it fails to find it. If you know of any repository that provides it, you should add it. Otherwise, there is nothing for us to do here.
