### ISSUE TITLE
Fails to fetch a npm dependency referenced by a commit-ish git url

### ISSUE THREAD

**Issue by flowersinthesand** [travis-ci/travis-ci#7714]
I found that after I added a dependency referenced by a commit-ish git url to `package.json`, https://github.com/cettia/cettia-javascript-client/commit/1d92593f993d9082546c08dc9d09084cb6983ccd#diff-b9cfc7f2cdf78a7f4b91a753d10865a2 (https://travis-ci.org/cettia/cettia-javascript-client/builds/229181060), the build fails.

By inserting npm install script which installs such dependencies to before_script section in .travis.yml, I managed to circumvent this issue for now, https://github.com/cettia/cettia-javascript-client/commit/0732fa7ad132f83bd8100adcdb887c10c5889a37 (https://travis-ci.org/cettia/cettia-javascript-client/builds/229448334)

```diff
diff --git a/.travis.yml b/.travis.yml
index 6b41506..ed20c9c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -6,3 +6,5 @@ node_js:
   - 7
 before_script:
   - npm install -g grunt-cli
+  - npm i cettia/cettia-protocol#f83e99cdc202b4818c2041b1563ee8a6ac8c8f00
+

```

**Comment by BanzaiMan** [comment]
Because your repository has `package.json` and `yarn.lock` files, we use `yarn` as [the `install` step](https://travis-ci.org/cettia/cettia-javascript-client/jobs/229181062#L180-L188). In [`yarn.lock`](https://github.com/cettia/cettia-javascript-client/blob/1d92593f993d9082546c08dc9d09084cb6983ccd/yarn.lock#L579-L586) has `cttia/cettia-javascript-client locked at commit db295015.

If you want to use `npm install` in spite of the presence of `yarn.lock`, you would need to override the default:

```yaml
install:
  - npm install
```

Or, you can re-lock the dependencies with yarn and commit `yarn.lock`.

**Comment by flowersinthesand** [comment]
Ah thanks! I missed it.

Sorry for the false alarm.
