### ISSUE TITLE
perl6 issue

### ISSUE THREAD

**Issue by miriramire** [travis-ci/travis-ci#7762]
We can't upload files in perl6. the prove shows this error:
Perl6 support for Travis-CI is community maintained.
Please open any issues at https://github.com/travis-ci/travis-ci/issues/new
and cc @paultcochrane, @hoelzro, @ugexe, and @tony-o
Thaqnks

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here? This is too scant information to act on.

**Comment by miriramire** [comment]
It was a file that i was testing on travis ci, i was creating a file on
github, when the test was running it showed me that fail.


2017-05-15 16:25 GMT-05:00 Hiro Asari <notifications@github.com>:

**Comment by BanzaiMan** [comment]
Where do you see the failure? You must have a URL.

**Comment by miriramire** [comment]
Yes, this is the URL where it showed me the fail
https://travis-ci.org/miriramire/Desarrollos-Next-U/builds/232582259

2017-05-15 17:13 GMT-05:00 Hiro Asari <notifications@github.com>:

**Comment by BanzaiMan** [comment]
OK. I think there is a misunderstanding here. The build log shows why the build failed: https://travis-ci.org/miriramire/Desarrollos-Next-U/builds/232582259#L978

```sh-session
0.14s$ PERL6LIB=lib prove -v -r --exec=perl6 t/
t/ .. Could not open t/. Failed to stat file: no such file or directory
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 
```

Your repository https://github.com/miriramire/Desarrollos-Next-U/tree/0969f1caaad38ca28797b1814ce0eebeaa363ded has no tests under `t`, which is required for the Perl 6 build. https://docs.travis-ci.com/user/languages/perl6#Default-Test-Script

Please add it.

The message is for the cases when there is actually something to be fixed by the Perl 6 maintainers. There is none here. I'm closing this.
