### ISSUE TITLE
Travis cannot find GHC 7.10 and 8.0: `No such ghc version '7.10'.`

### ISSUE THREAD

**Issue by rudymatela** [travis-ci/travis-ci#7807]
When I specify:

    ghc:
      - "7.10"

Travis cannot find the correct GHC.  It [reports](https://travis-ci.org/rudymatela/speculate/jobs/235258017):

    No such ghc version '7.10'.
    Using default ghc version '7.10.3'.
    ...
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.4.1

I told Travis should use `7.10`.  Travis defaulted to `7.10.3` but ended up using `7.4.1`.

Even If I specify the patch number, the [same thing happens](https://travis-ci.org/rudymatela/speculate/jobs/235648058):

    No such ghc version '7.10.3'.
    Using default ghc version '7.10.3'.
    ...
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.4.1

Still defaulting to `7.4.1`.

[The same also happens to GHC 8.0](https://travis-ci.org/rudymatela/speculate/jobs/235648057), but maybe in this case the reason is because GHC 8.0 is not supported by Travis.  Is that the case?

**Comment by BanzaiMan** [comment]
Here, the problem is the discrepancy between the Precise image you are using and the build script's assumptions about how to resolve ambiguous GHC version specifications.

The Precise image does not have any 7.10 versions, but the build script merrily tries.

The Trusty image does have 7.10.3, so if you set `dist: trusty`, you'd get what you need (https://travis-ci.org/BanzaiMan/travis_production_test/jobs/270171263#L407; you can ignore the error messages there).

We could try failing the build if this sort of version discrepancy is detected.

**Comment by rudymatela** [comment]
Thanks for the reply.

I agree with you that failing the build might be the clearer option for users.  I did not notice that the build was using other GHC than the one I specified only after a while.

Thanks for the tip.  I'll try using trusty from now on.

Feel free to close this issue.

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/travis-build/pull/1052 aims to implement the build termination (as a part of a bigger fix).
