### ISSUE TITLE
Devtools issue

### ISSUE THREAD

**Issue by Ironholds** [travis-ci/travis-ci#7819]
The builds for [mwparser](https://github.com/Ironholds/mwparser)

are producing:

```
Error in loadNamespace(name) : there is no package called ‘devtools’
Calls: message ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
```

This is...pretty confusing because (1) the package doesn't _have_ a devtools dependency and (2) just in case I'm now explicitly requiring devtools and it's still falling over and dying.

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by Ironholds** [comment]
My apologies!

**Comment by craigcitro** [comment]
Hey @Ironholds -- so the issue is that the `script` step implicitly requires `devtools`, since it expects to install it during the `install` step. However, you're overriding the `install` step and not the `script` step.

Quick fix: Rename `install` to `before_install` and you'll be up and running -- this is the right fix in your case, since `install` is also where we install required packages (`reticulate` in your case).

@jimhester should we detect this and error out more gracefully?

**Comment by Ironholds** [comment]
Perfect! Thank you! Want me to leave the ticket open for that question?

**Comment by craigcitro** [comment]
@Ironholds 👍

**Comment by jimhester** [comment]
Just sent a PR to fix this implicit dependency, the error was happening because we use [devtools::check_failures()](https://github.com/jimhester/travis-build/blob/bb57a750ad92710ee70abe0b5dee78fb7f766beb/lib/travis/build/script/r.rb#L238) to summarize the failures from `R CMD check`, but that will fail if devtools is not installed. We now condition this call to only occur if devtools has been installed using the default `install` block.
