### ISSUE TITLE
Builds fail on OS X in packages that use OpenMP (R issue)

### ISSUE THREAD

**Issue by dahtah** [travis-ci/travis-ci#7820]
Since the switch to R 3.4.0, builds that used to compile fine now fail. The issue is described [here](
https://stackoverflow.com/questions/43595457/alternate-compiler-for-installing-r-packages-error-installing-rjava). Quoting:
"This is caused because R 3.4.0 is compiled by CRAN with llvm-4.0.0 (which supports OpenMP), but Apple's fork (installed by default on macOS) does not support OpenMP."

Perhaps a more recent version of llvm can be used?

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by jonclayden** [comment]
As noted in the [above-referenced issue](https://github.com/jonclayden/mmand/issues/4), you can modify the build environment so that R doesn't try to use OpenMP flags, with something like

    before_install:
      - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p ~/.R && echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars; fi

(This is for C++; you'll need `SHLIB_OPENMP_CFLAGS` for C, etc.)

But I think that ideally the default configuration for building R packages on macOS on Travis should be self-consistent, so that the `make` environment reflects the actual capabilities of the compilers available, and AFAICT that is not currently the case.

/cc @craigcitro @jimhester

**Comment by muschellij2** [comment]
Just in case you missed the comment like I did   

```
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; 
  then 
  mkdir -p ~/.R; 
  echo "SHLIB_OPENMP_CXXFLAGS = " >>~/.R/Makevars; 
  echo "SHLIB_OPENMP_CFLAGS = " >>~/.R/Makevars; 
  fi
```
(note the indentation for the YAML format) may be necessary for the C programs as well.

**Comment by dahtah** [comment]
Thanks for the feedback. I think the best solution is use autoconf rather than add a work-around on Travis, and in any case it's more of an R issue. I'm marking this as fixed.
