### ISSUE TITLE
R Language: Build failing with `tlmgr update` failure

### ISSUE THREAD

**Issue by javierluraschi** [travis-ci/travis-ci#7852]
@craigcitro, @hadley and @jimhester: I'm hitting a `The command "tlmgr update --self" failed and exited with 1 during .` error, known fix?

**Some background**: Builds used to succeed in github.com/rstudio/sparklyr, [PR](https://github.com/rstudio/sparklyr/pull/719) was proposed with passing Travis, [merge](https://github.com/rstudio/sparklyr/commits/master) broke Travis, [revert of PR](https://github.com/rstudio/sparklyr/pull/723) is not fixing Travis build.

Travis Logs: https://travis-ci.org/rstudio/sparklyr/builds/239244701?utm_source=github_status&utm_medium=notification

Travis Tail:

```
TeX Live 2016 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.
If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet (verified)
tlmgr: saving backups to /home/travis/texlive/tlpkg/backups
TLUtils::check_file: removing /tmp/ORHyIaTaK_/NpgiEgS8Ks/texlive.infra.tar.xz, sizes differ:
TLUtils::check_file:   TL=200472, arg=194264
TLPDB::_install_package: downloading did not succeed
tlmgr: Installation of new version of texlive.infra failed, trying to unwind.
[1/1, ??:??/??:??] update: texlive.infra [190k] (41280 -> 41476) ... tlmgr: Restoring old package state succeeded.
done
tlmgr: action update returned an error; continuing.
tlmgr: package log updated: /home/travis/texlive/texmf-var/web2c/tlmgr.log
tlmgr: An error has occurred. See above messages. Exiting.
The command "tlmgr update --self" failed and exited with 1 during .
````

**Comment by kevinykuo** [comment]
Wonder if this is related to the TeX Live 2017 release today...

**Comment by Selbosh** [comment]
I am having exactly the same problem, after a trivial commit (that changed an R package version number and nothing else). Notice it is almost exactly a year after [a very similar issue affected the 2016 release](https://github.com/travis-ci/travis-ci/issues/6139).

**Comment by ck37** [comment]
Also running into this with no real change to my repo. https://travis-ci.org/ck37/SuperLearner/jobs/239350199#L465

**Comment by jaredhuling** [comment]
I'm having the same problem and it is persistent

**Comment by vincentvanhees** [comment]
Same problem with my package: https://travis-ci.org/wadpac/GGIR/builds/239497209

**Comment by Robinlovelace** [comment]
Same with stplanr: https://travis-ci.org/ropensci/stplanr

**Comment by martintoreilly** [comment]
Same with the master branch of my package: https://travis-ci.org/alan-turing-institute/network-comparison/builds/239414728

Last night's daily CRON build failed. There have been no code changes to this branch since the last successful build 24 hours previously (https://travis-ci.org/alan-turing-institute/network-comparison/builds/239184783).

**Comment by jimhester** [comment]
This will continue to affect all R packages until https://github.com/travis-ci/travis-build/issues/1072 is merged and deployed. A workaround until this is done is to set `latex: false` in your `.travis.yml`, which will disable installation of TexLive for your build.

Also please :+1: the original issue if you have the same problem rather than posting a new comment.

**Comment by humbertcostas** [comment]
Thanks for the workaround, it works!

**Comment by pcarbo** [comment]
Adding a link here to the [R help page](https://docs.travis-ci.com/user/languages/r) where it explains the `latex: false` option.

**Comment by javierluraschi** [comment]
Thank you @jimhester, the merge you pointed us to fixes this issue. Closing.

**Comment by asardaes** [comment]
I guess this is due to the Tex Live repos, but FYI the OSX builds are still failing, in my case it is apparently due to a [missing font](https://travis-ci.org/asardaes/dtwclust/jobs/239687429#L592).

The Tex Live's repo mismatch is shown [here](https://travis-ci.org/asardaes/dtwclust/jobs/239687429#L378). If the build is going to fail anyway, it might not be the best idea to ignore the results of the `tlmgr` commands.
