### ISSUE TITLE
Using Magick

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#7855]
Is there any way of updating ImageMagick on Travis without building from source? The current version is still 6.x, which doesn't have the magick command

**Comment by BanzaiMan** [comment]
Trusty https://packages.ubuntu.com/trusty/imagemagick has 6.7. If you can find a binary package source that has what you need, you can use the [`apt` addon](https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon) to install it. Otherwise, there is not much we can do at the moment.

**Comment by AllanWang** [comment]
Alright. I guess I'll just keep making it until I find a proper source
