### ISSUE TITLE
XCode 9.0 beta support

### ISSUE THREAD

**Issue by courteouselk** [travis-ci/travis-ci#7865]
Apple had released XCode 9.0 beta (9M136h) couple of days ago.  Builds with Travis CI are failing for Swift 4 updated projects.  Is it possible to add the 9.0 image to OS X build environment?

**Comment by emdantrim** [comment]
Hey there folks,

I am not ignoring this request. At the time that this ticket was opened, availability to the Xcode 9.0 beta was covered under an NDA, and I am waiting to hear that it is relatively generally available before we move to release it for public use.

Apologies for the lack of communication.

**Comment by mattyohe** [comment]
> At the time that this ticket was opened, availability to the Xcode 9.0 beta was covered under an NDA,

IANAL but if you find one that can interpret [Apple's license agreement](http://adcdownload.apple.com/Documentation/License_Agreements__Apple_Developer_Program/Apple_Developer_Program_License_Agreement_20170605.pdf), it explicitly calls out pre-release software from WWDC:
> Apple agrees that You will not be bound by the foregoing confidentiality terms with regard to technical information about pre-release Apple Software and services disclosed by Apple at WWDC (Apple’s Worldwide Developers Conference), except that You may not post screen shots of, write public reviews of, or redistribute any pre-release Apple Software, Apple Services or hardware.

**Comment by ikesyo** [comment]
And also you guys had Xcode 8 beta support one years ago: https://blog.travis-ci.com/2016-06-13-xcode-8-beta-initial-release

**Comment by emdantrim** [comment]
If I recall correctly, 8.0 was a public beta that was not covered under the NDA.

We give people `sudo` on our boxes. They could just `scp` it off the build box. What's the legal difference between "it's a one line `scp` command to acquire this file" and "it's a one line `wget` command to acquire this file"?

Our interpretation of the language in that passage tells us that there is potential risk of it being considered "re-distribution" if we release it while it is under NDA. We will wait until Xcode 9.0 beta (or GM, or GA) is available to non-paid developer accounts.

**Comment by ikesyo** [comment]
Was Xcode 8.2 beta also public beta?

https://blog.travis-ci.com/2016-11-15-xcode-82-is-here

**Comment by courteouselk** [comment]
I have non-paid developer's account and I could download XCode 9.0 beta.

**Comment by mattyohe** [comment]
> We will wait until Xcode 9.0 beta (or GM, or GA) is available to non-paid developer accounts.

@emdantrim Ah interesting. I followed up on this and I had forgotten that there was a time when a user _must_ have registered into the developer program in order to access downloads. I tracked down when this seemed to have changed (in Xcode 6.0) via a pretty [circuitous fashion](https://en.wikipedia.org/w/index.php?title=Xcode&diff=prev&oldid=618620141), but that then led me to find this: https://developer.apple.com/support/beta-software/

Which states:
> Beta versions of Xcode include the latest toolset and SDKs for creating apps that run on upcoming releases of an OS, and are available to all developers on the download page. **Apple Developer Program membership is not required.**

And now I see @courteouselk has now beaten me to this punchline.

**Comment by solarce** [comment]
Hey folks. I manage the build infrastructure team here at Travis and macOS build environment updates is one of my team's responsibilities.

I appreciate that you’re all eager for us to support Xcode 9, but I do feel that I must ask that we refrain from any further discussion on whether previous Xcode betas are public or not and focus on keeping this conversation constructive. 

Focusing on that goal, I’d like to give you all some more details on our internal workflow and what to expect. I’ve generally been involved in Xcode version updates over the past two years, as we're a small team, and we've consistently made betas available if and when they're available to our non-paid Apple Developer login that we use. As outlined in [https://docs.travis-ci.com/user/osx-ci-environment#OS-X-Version](#), we follow a guideline that we feel is a reasonable interpretation of Apple's EULAs

> At this time we are unable to provide pre-release versions of Xcode due to the NDA imposed on them. We do test them internally, and our goal is to make new versions available the same day they come out. If you have any further questions about Xcode pre-release availability, you can send us an email at support@travis-ci.com.
 
This interpretation of things is not one we plan to revisit in the near future.

That being said, on the first day of WWDC and for a few days following, we did check on availability for the initial Xcode 9.0 beta and it was not visible to our non-paid account, which is what informed Emma's previous responses. Based on this and past our past Xcode beta experiences, we'd expected the next beta release to become public. We were not checking to see if the current beta did become public nor did the communications from Apple that we monitor make an announcement to that effect. 

Like @courteouselk, I do also see that we are now able see the Xcode 9 beta download with our non-paid developer account. As to which day the current Xcode 9 beta became available to non-paid developers, that's unclear, but I also feel it's not relevant to a productive discussion. I am giving some more detail on this not because I feel we've made any mistakes but to hopefully give you some more context into how we're approaching this topic and what you can expect in the future.

As to when we'll have Xcode 9 support now that we know it's public. It's likely going to take a few days, as we're approaching the end of the quarter and have other planned work to complete, but we are trying to fit this in. We'll make an update here and on [Twitter](#)(https://twitter.com/travisci) when the new image is ready for testing.

If anyone does still feel like they have unanswered questions regarding our current policy on when we add Xcode betas, please reach to me over email via `bburton at travis-cic.om`. Thanks.

**Comment by courteouselk** [comment]
> Like @courteouselk, I do also see that we are now able see the Xcode 9 beta download with our non-paid developer account. As to which day the current Xcode 9 beta became available to non-paid developers, that's unclear, but I also feel it's not relevant to a productive discussion. I am giving some more detail on this not because I feel we've made any mistakes but to hopefully give you some more context into how we're approaching this topic and what you can expect in the future.
>
> As to when we'll have Xcode 9 support now that we know it's public. It's likely going to take a few days, as we're approaching the end of the quarter and have other planned work to complete, but we are trying to fit this in. We'll make an update here and on Twitter(https://twitter.com/travisci) when the new image is ready for testing.

"Few days" to me this sounds most reasonable.  The question I had was exactly that, a question whether it is possible to add such support.  And it is good to know this _is_ on your radar and that there is no roadblock to make it happen.  Looking forward for the updates.

**Comment by solarce** [comment]
A brief update that this is being worked on but some bugs in some of the tools we use to prepare the image and install things into macOS are needing some fixes to work with Xcode 9, so we're stomping out some 🐛s and hope to have this out in a day or two

**Comment by emdantrim** [comment]
https://twitter.com/travisci/status/880550780368855040 :sparkles:!
