### ISSUE TITLE
Build sits waiting to be queued, never gets queued

### ISSUE THREAD

**Issue by dschinkel** [travis-ci/travis-ci#7913]
None of my new builds will start, period.  I was told by a collegue that Travis is generally having some issues today?

https://travis-ci.com/mayfieldrobotics/gizmo_web_app/jobs/79289809

<img width="1010" alt="screen shot 2017-06-14 at 4 00 04 pm" src="https://user-images.githubusercontent.com/338798/27154427-a7317814-511a-11e7-8f7a-34802d2aeebd.png">

**Comment by BanzaiMan** [comment]
Sorry about the delay. We had build delays earlier today (https://www.traviscistatus.com/incidents/m2vtkbw1p44z), and I believe this is the manifestation of it.

I'm closing this now, since the delay has been resolved, but if you do see the problem, please feel free to get in touch with us at support@travis-ci.com. Thank you.
