### ISSUE TITLE
Perl6 zef module installing issue

### ISSUE THREAD

**Issue by Scimon** [travis-ci/travis-ci#7949]
I have discovered what appears to be a very specific error in Travis with Perl6 and zef.

If your module uses the following 4 modules:

`YAMLish File::Temp Text::Markdown Template::Mustache` 

And you attempt to install them all at once (either directly in the `.travis.yaml` file or via `--deps-only` and the `META6.json` file) the zef install appears to silently break and the build fails.

Installing each individually is fine (In linux, it failed on OSX). Requiring any 3 of the 4 is fine. But all 4 at once seems to break things.

https://travis-ci.org/Scimon/perl6-build-test/builds : Here's the history of the various build tests I made

https://github.com/Scimon/perl6-build-test : Here's the repo I made to do the tests in.

I'm now at a loss, I'm willing to make any further investigations you think would help to nail this down.

CC : @paultcochrane, @hoelzro, @ugexe, and @tony-o

**Comment by ugexe** [comment]
@Scimon This is a rakudo bug specific to OSX and `moar 2017.06`. Specifically it seems to be an issue with spawning processes and the GC, but again this is a known issue (so hopefully resolved for `2017.07`)

Your last travis build attempt appears to try and fix the issue by using `moar 2017.05`, and it should, but your build failed because of a network hiccup when cloning rakudo:
```
$ perl6 --version

/Users/travis/.travis/job_stages: line 54: perl6: command not found
```
so I suspect if you rerun that one failed OSX build that is using `2017.05` that it will pass.

**Comment by ugexe** [comment]
@Scimon I think this is resolved now: https://travis-ci.org/ugexe/perl6-build-test/builds/250583438

**Comment by BanzaiMan** [comment]
Sweet. I'm closing this now. Let us know if there are outstanding issue.
