### ISSUE TITLE
OracleJDK 7: Support appears to be broken as of three days ago

### ISSUE THREAD

**Issue by alexflav23** [travis-ci/travis-ci#7964]
Using the following setting in `.travis.yml`

```yaml
jdk:
  - oraclejdk7
```

However:

```sh
Patching redis-server init script
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
```
And then immediately after:

```sh
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ javac -J-Xmx32m -version
javac 1.8.0_131
Using Scala 2.11.8
```

**Comment by offa** [comment]
I have the [same issue](https://travis-ci.org/offa/NBCndUnit/jobs/245914365). It seems only Oracle JDK is broken, the other still work.

Maybe related to #7019

**Comment by dannil** [comment]
Possibly related to #7884

**Comment by alexflav23** [comment]
Hi @dannil,

The `jdk_switcher` seems to work now, however fails to export the correct JVM path!

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
Updating sbt
```

This is still not fixed as a result!

**Comment by khmarbaise** [comment]
Hi,
exactly [the same issue here:](https://travis-ci.org/jenkinsci/java-client-api/builds/255739332)

> Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
> update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
> 

Changed temporarily to jdk 8 which works...

It would be great if this could be fixed to keep JDK 7 working...

Thanks for that great platform...

Kind regards
Karl Heinz Marbaise

**Comment by iriberri** [comment]
Please, see https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879. I'm closing this as a duplicate.

`oraclejdk7` is unfortunately no longer available in Trusty after our latest updates, since we can no longer support oraclejdk7 on our recent build images due to Oracle's withdrawal. See: http://www.webupd8.org/2017/06/why-oracle-java-7-and-6-installers-no.html

If this is an option for you, I'd recommend switching to `jdk: openjdk7`, which is available in the new Trusty images.

**Comment by khmarbaise** [comment]
Using `jdk: openjdk7` as alternative is very good. Thanks for your answer.
