### ISSUE TITLE
Error with executing bash script added in deploy block of .travis.yml 

### ISSUE THREAD

**Issue by imujjwal96** [travis-ci/travis-ci#7971]
I have added the following in my `.travis.yml` file
    
    deploy:
    - provider: script
      skip_cleanup: true
      script: source <(curl -s https://raw.githubusercontent.com/fossasia/yaydoc/master/generate_ci.sh)
      on:
        branch: master

And I get the error,

    sh: 1: Syntax error: "(" unexpected

The following error occurs when we write `sh` in place of `source`. 
I cannot understand why this is happening here. Any solution for this?

**Comment by BanzaiMan** [comment]
The `script` is sent to Ruby's `system` command, which invokes `sh`, rather than `bash`. I'm guessing that Bourne shell does not like `(` while Bourne Again shell might.

You can try a few things to use `bash` as the interpreter of the script you `curl`:

1. Pass it through to `bash`:

       curl -o- -s https://raw.githubusercontent.com/fossasia/yaydoc/master/generate_ci.sh | bash

1. Invoke `bash` explicitly:

       bash -c 'source <(curl -s https://raw.githubusercontent.com/fossasia/yaydoc/master/generate_ci.sh)'

**Comment by imujjwal96** [comment]
The first approach works like a charm.
Appreciate your time.
