### ISSUE TITLE
Add support for language: shell

### ISSUE THREAD

**Issue by MichaelAquilina** [travis-ci/travis-ci#8012]
Right now it seems like its impossible to set the language for running tests for shell applications. It would be nice to have this added to the list of languages - even if its only just a label to display during the build process.

**Comment by BanzaiMan** [comment]
Use `language: generic` for this purpose.

**Comment by mloskot** [comment]
`generic` should be documented https://docs.travis-ci.com/user/languages/

**Comment by BanzaiMan** [comment]
Closing as a duplicate of https://github.com/travis-ci/docs-travis-ci-com/issues/910 in that case.

**Comment by molovo** [comment]
If anyone sees this and is interested, I built [zvm](https://github.com/molovo/zvm) and [ZUnit](https://zunit.xyz) with a view toward building a community integration specifically for ZSH at some point. I haven't taken it any further so far due to the need to have 4 maintainers, so if anyone sees this issue and is interested in helping out, please get in touch.
