### ISSUE TITLE
Builds not triggering on commit

### ISSUE THREAD

**Issue by oleersoy** [travis-ci/travis-ci#8030]
Performing the following sequence for all my repositories:
1) Add .travis.yml to the repository
2) Via the travis UI make sure the repository is turned on for building (Main build switch)
3) Add the github token
4) Turn on build only if .travis.yml is present

I have 4 repositories building so far and I think this is all I did for them, but I added to more and performed the above steps and they were not building.  So for example for https://github.com/superflycss/utilities-layout I went into settings and clicked on integrations and services and then clicked edit on Travis CI and clicked the Test Service button, at which point the CI integration started working.  

But it should just work without me having to do this right?

I have another repository https://travis-ci.org/superflycss/component-body that's also not building.  I can try the Test Service button for this build as well and see if that kick starts it.  Just want to make sure I don't have something off in my workflow...?

**Comment by BanzaiMan** [comment]
There are no new commits to https://github.com/superflycss/utilities-layout since you enabled Travis CI and fired a test build https://travis-ci.org/superflycss/utilities-layout/builds/249847214.

Same with https://travis-ci.org/superflycss/component-body. Travis CI is enabled, but there is no new commit.

Please read https://docs.travis-ci.com/user/getting-started#To-get-started-with-Travis-CI

> Add the `.travis.yml` file to git, commit and push, to trigger a Travis CI build:
> 
> Travis only runs builds on the commits you push after you’ve enabled the repository in Travis CI.

**Comment by oleersoy** [comment]
OK - Just did a test commit - and it triggers now.  Thanks!
