### ISSUE TITLE
macOS builds getting slower with time.

### ISSUE THREAD

**Issue by jcelerier** [travis-ci/travis-ci#8083]
I noticed that regularly (but over a period of few weeks) my macOS builds (https://github.com/OSSIA/i-score) tend to grow slower. The linux builds stay at the same speed. This had already happened once and at some point the macOS build were unavailable for a few days, then when they were restored they went back to a normal speed. Is it just my mind ? Or is there really some problem with the mac builds ?

**Comment by peterp** [comment]
I think I've been in a queue for at least ~5 minutes.

**Comment by peterp** [comment]
I think something may be wrong, I've been waiting for an macOS build to start for ~20 minutes.

**Comment by kammce** [comment]
I've been waiting about an 2 hours no for my mac os to build.

**Comment by dcommander** [comment]
Same here.  My experience is that it ebbs and flows based on demand.  Their macOS servers seem to be underprovisioned, so when there is a lot of demand, it will queue up for sometimes hours.  Over the Christmas holiday, the builds were quite fast.  Now, as I write this, I've also been waiting for two hours.

**Comment by kammce** [comment]
Actually, I've been waiting nearly a whole day for my builds this past week.

**Comment by Lyoness** [comment]
hi @jcelerier @peterp @kammce @dcommander 

We've been working hard to improve performance.  Part of the issue was SAN I/O performance degradations becoming the bottleneck, especially over time since vCenter weren't designed for the VM churn. 

  We've migrated to new hardware and flash storage several days ago, and we're noticing significant improvements performance & throughput, we hope you've noticed too.

I'm closing this out, please re-open if you are seeing issues.
