### ISSUE TITLE
Travis-wait ant discards output when it times out

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8096]
When I run travis-wait 50 ant <target> and the target times out, I get no output from Ant at all, even after configuring the build script to echo the results incrementally. (There's no reasonable way it can be timing out before the first echo statement.) I need Ant's output *especially* when it doesn't finish, so that I can find out how to split the job further so that it finishes in time. (Travis-wait is necessary too, because one of the individual tests still takes about 15 minutes on Cloud9.)

Here's an example of an affected run: https://travis-ci.org/Pr0methean/uncommons-maths/jobs/253832460

**Comment by BanzaiMan** [comment]
The real issue is that your job is running out of time. When a job gets terminated due to hard time limit (50 minutes), no clean up is run (including any by `travis_wait`).

There is a long standing issue about clean up at the job's termination (e.g., https://github.com/travis-ci/travis-ci/issues/4221). But `travis_wait` in this current implementation is not designed to deal with these timeouts.

I suggest setting the `travis_wait` timeouts shorter, so that it has a chance to dump the log before the job is terminated.

**Comment by Pr0methean** [comment]
I will try a 45-minute timeout. That should be time to at least dump all the buffered output, right? (Setup will continue to take 1-2 minutes until https://github.com/travis-ci/travis-ci/issues/6761 is fixed.)

**Comment by Pr0methean** [comment]
A related issue: travis_wait doesn't seem to detect when the waited-on process has terminated early. Are there any plans to change that?

**Comment by BanzaiMan** [comment]
`travis_wait` checks the status of the child process every 60 seconds. This is by design, and if your child process terminates in a shorter time, you'd have to wait. This is unlikely to change.
