### ISSUE TITLE
R: Build stalls during package dependencies installation

### ISSUE THREAD

**Issue by pat-s** [travis-ci/travis-ci#8107]
@craigcitro and @jimhester

Currently, all our builds are failing during package dependency installation ([build log](https://travis-ci.org/mlr-org/mlr/builds/254463275)) 

```
Rscript -e 'deps <- devtools::dev_package_deps(dependencies = NA);devtools::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'
```

The step was working fine two days ago and nothing has been changed since then. No new package and no change in the [yaml file](https://github.com/pat-s/mlr/blob/master/.travis.yml). 

Normally, this step takes about 10 seconds only. See the [last working build](https://travis-ci.org/mlr-org/mlr/builds/254155951) as a reference. 

We require a lot of [packages](https://github.com/mlr-org/mlr/blob/master/DESCRIPTION) in SUGGESTS. Lowering that number helps and the error does not occur. However, then our build does not succeed due to missing packages during tests. 

We are using package cache and afaics this step only checks which packages need to be updated. I'm unsure if its related to `devtools` (however `devtools` was not updated in the last days) or Travis (my guess atm). 

I'm unsure if a `travis_wait` would help here as I thinks its not about time but rather that something breaks within the command above? If it would help, how would we implement this? This command is issued automatically afaics.

**Comment by jimhester** [comment]
Nothing has changed recently on the travis side, so this is probably due to a travis cache issue. I would recommend deleting your travis cache and re-running a build.

Also I would remove the the [`r_packages:` and `r_github_packges:`](https://github.com/mlr-org/mlr/blob/master/.travis.yml#L26-L34) lines from your `.travis.yml`. These dependencies are better specified as [Remotes](https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd#package-remotes) in the DESCRIPTION. Using remotes will utilize the travis cache to only install the packages if they have changed. This also allows users of your package to install all development dependencies with 
a call to devtools install functions.

**Comment by pat-s** [comment]
Thanks for the suggestions and clarification @jimhester!

**Comment by ck37** [comment]
@jimhester Can you clarify the CRAN submission note at https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd#package-remotes ?

> When you submit your package to CRAN, all of its dependencies must also be available on CRAN. For this reason, release() will warn you if you try to release a package with a Remotes field.

Does this imply that the remotes field has to be removed from DESCRIPTION prior to CRAN submission, or can the release() warning be ignored if we know the packages in Remotes are also available on CRAN?

**Comment by jimhester** [comment]
Yes, all remotes fields should be removed prior to submission to CRAN. You should not be depending on development packages in a CRAN package.
