### ISSUE TITLE
[Question] Should caching be done before after_success?

### ISSUE THREAD

**Issue by AllanWang** [travis-ci/travis-ci#8208]
From [this](https://travis-ci.org/AllanWang/Frost-for-Facebook/builds/261252854) output, we can see a project with a 11 min build time. Of those 11 min, about 100 seconds are spent in caching whatever components are specified in the yml file. Is this necessary to occur before `after_success`, and should a failure to cache items count as a failure? Moving this afterwards would make the upload time almost 2 minutes sooner.

**Comment by mtf90** [comment]
Not OP, but I have the same question. For me however, it is not an issue about performance, but an actual failure in the `after_success` phase.


I have a Maven project `P` that depends on a development version of a library `L`. Thus, in the `before_install` phase, I clone the repository of `L` and `mvn install` it into the local repository. This all works fine for the actual build. Since I rebuild `P` and `L` on every build, I remove their build artifacts from the cache in the `before_cache` phase (this should save space on your end and I want to be able to detect changes due to refactorings, etc.). 

In the `after_success` phase, I run `mvn coveralls:report` to upload the coverage information to coveralls.io. For this, Maven tries to resolve the dependencies to the development version of `L` but cannot find them, since they have already been removed in the `before_cache` phase. For a concrete build, see [here](https://travis-ci.org/LearnLib/learnlib/jobs/305469194) (technically, Maven finds the dependencies for `L`, but only because they have been deployed once months ago -- they are outdated and the core issue remains)


From the top of my head, I see no issues why the caching phase _has_ to run before `after_success`. Of course, this could mean that you potentially cache files that are created in the `after_success` phase, but these also could be cleaned up in the `before_cache` phase. With `after_success` -> `before_cache` you would get the real benefit of having access to your (non-cached) development artifacts in the `after_success` phase.
