### ISSUE TITLE
os/x el capitan configuration

### ISSUE THREAD

**Issue by jpritikin** [travis-ci/travis-ci#8243]
@craigcitro @jimhester We are having a strange problem with CRAN package OpenMx. The CRAN binary builder for OS/X keeps [failing for El Capitan](https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/OpenMx-00check.html). It throws a c++ exception at the beginning of R check. However, we have not managed to reproduce this behavior locally. Everybody we know who tries to build OpenMx on OS/X has succeeded in producing a working binary.

This behavior started when CRAN switched from gcc to clang for OS/X. Unfortunately https://builder.r-hub.io/ does not have a working toolchain for OS/X El Capitan. [The Fortran compiler is broken.](https://builder.r-hub.io/status/OpenMx_2.7.16.tar.gz-5d85f540d0e24d0eb88faad54afc74e4) [Our travis build using gcc continues to work fine.](https://travis-ci.org/OpenMx/OpenMx/jobs/263520351)

I wonder if we might use Travis to reproduce CRAN's exact OS/X build toolchain so we can obtain a defective binary and observe the failure with a debugger. Are you aware of any travis CRAN projects that build OS/X binaries using clang and the exact configuration used by CRAN?

Thank you.

**Comment by jimhester** [comment]
CRAN has always used a clang toolchain on MacOS, however they recently began building with a newer version of llvm rather than the one bundled with the OS. You can download the sources for the particular version used on CRAN from http://r.research.att.com/src/.

If there are issues with r-hub's MacOS builder I would suggest you [open an issue](https://github.com/r-hub/rhub/issues).

We have no plans of providing the CRAN llvm toolchain on travis.

**Comment by BanzaiMan** [comment]
Sounds like there is not much to do here. Please let us know if that's not the case.

**Comment by jpritikin** [comment]
Yeah, I filed an issue with r-hub. Thank you.
