### ISSUE TITLE
Google GCE: Load Balancing IPv6 support and does it help with adding IPv6 connectivity to Travis's GCE VMs?

### ISSUE THREAD

**Issue by gpotter2** [travis-ci/travis-ci#8304]
Hello. Please do not tell me that this is a duplicate of #5261, #3302, #4964, #5200

Google GCE have added IPv6 (at least in alphas): https://googlecloudplatform.uservoice.com/forums/302595-compute-engine/suggestions/8518246-support-ipv6

https://cloud.google.com/compute/docs/load-balancing/ipv6

My question is: are you going to implement this soon ? Would it require changes from inside travis ? Is it on the roadmap ?

**Comment by BanzaiMan** [comment]
Thanks for the ping! We will take it into consideration for our planning in the near future. We have no further details to share at this time./

**Comment by solarce** [comment]
@gpotter2 Unfortunately, you've misinterpreted what that announcement is about, that is **beta** level support for allowing remote IPv6 clients to connect to a GCP Load Balancing instance, so that someone running a web service on GCP could allow people to connect to their web service over IPv6.

It **does not** do anything for providing GCE Virtual Machines with either internal (eth0 or similar) or external IPv6 connectivity, which is what the other issues you've references are ultimately asking about. 

In fact, the LB feature still only uses IPv4 for the traffic from the LB instance to a user's GCE VMs:

> IPv6 termination for HTTP(S), SSL proxy, and TCP proxy load balancing enables you to handle IPv6 requests from your users and **proxy them over IPv4 to your backend instances.** (emphasis mine)

Even when GCE does add native IPv6 networking for GCE VMs, we would likely wait until it was GA before looking at integrating it.

**Comment by gpotter2** [comment]
It seems you are right :/  Sorry for hyping ...

**Comment by solarce** [comment]
@gpotter2 it's not a problem, I understand the desire and we look forward to when we'll be able to easily and consistently provide IPv6 across our compute environments.
