### ISSUE TITLE
on: tags: false not respected

### ISSUE THREAD

**Issue by mh-cbon** [travis-ci/travis-ci#8305]
in deploy section on tags:false is not respected.

build without tags will display

Skipping a deployment with the releases provider because this is not a tagged commit
Skipping a deployment with the bintray provider because this is not a tagged commit

removing the key works.

ref
https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268660018
https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268660283

**Comment by BanzaiMan** [comment]
You are setting `$TRAVIS_TAG` value explicitly. https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268660018#L427 (https://travis-ci.org/mh-cbon/go-bin-deb/jobs/268660018#L427)

If you mess with the default environment variables (https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables), things may not work the way you might otherwise expect.
