### ISSUE TITLE
Default installed version of PHP 7.0.x is very old

### ISSUE THREAD

**Issue by greg-1-anderson** [travis-ci/travis-ci#8358]
Recent versions of Symfony fail testing on PHP 7.0.x on Travis, because Symfony requires PHP >= 7.0.8, and Travis provides PHP 7.0.7 (both Precise and Trusty). 

Example output from `composer install`:
```
   - Installation request for symfony/console v3.3.8 -> satisfiable by symfony/console[v3.3.8].
    - symfony/console v3.3.8 requires php ^5.5.9|>=7.0.8 -> your PHP version (7.0.7) does not satisfy that requirement.
```

Example failed build:
https://travis-ci.org/consolidation/Robo/jobs/272712883

Workarounds:
- Specifically request a later version of PHP (e.g. `php: 7.0.11` instead of `php: 7.0`)
- Don't test with latest versions of Symfony
- Don't test with PHP 7.0.x (PHP 5.6.x and 7.1.x work on Travis with the available versions)

The documentation mentions that a more specific version of PHP can be used, but there does not seem to be a good way to determine what versions of PHP are available. For example, attempting to use today's latest version of PHP on Trusty results in:
```
$ phpenv global 7.0.23 2>/dev/null
7.0.23 is not pre-installed; installing
Downloading archive: https://s3.amazonaws.com/travis-php-archives/binaries/ubuntu/14.04/x86_64/php-7.0.23.tar.bz2
0.15s$ curl -s -o archive.tar.bz2 $archive_url && tar xjf archive.tar.bz2 --directory /
bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```
It would be nice if the default version was a little newer, and if there was an easy way to determine the available versions.

**Comment by BanzaiMan** [comment]
A few things.

1. Precise image will unlikely see any further updates on PHP.
1. Trusty images will be updated with the latest 7.0.x at the time when the image is provisioned.
1. PHP 7.0.23 depends on https://github.com/php-build/php-build/pull/474 (or https://github.com/php-build/php-build/pull/473).

> The documentation mentions that a more specific version of PHP can be used, but there does not seem to be a good way to determine what versions of PHP are available.

You are correct about this. We'll look into improving this part. The problem here is that there are just too many to list, really, and we have not come up with a concise way to display them.

**Comment by greg-1-anderson** [comment]
kk, thanks for considering.
