### ISSUE TITLE
Support BASH_SOURCE

### ISSUE THREAD

**Issue by taqtiqa-mark** [travis-ci/travis-ci#8392]
It can be useful to have something like the following to help debug scripts.
````bash
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
````

This raises an `unbound variable` error if you have `set -u`

**Comment by BanzaiMan** [comment]
Could you elaborate on what you mean by "Support `BASH_SOURCE`"? Our builds run with bash, and it is impossible to not support bash-builtin variables.

Our build script has many unbound variables, so `set -u` is usually a bad idea. See #5434.

**Comment by taqtiqa-mark** [comment]
>  `set -u`  is usually a bad idea. See #5434.
Ack.

**Comment by jakirkham** [comment]
> Our build script has many unbound variables, so `set -u` is usually a bad idea.

As noted elsewhere, it would be nice if that script did `set +u` beforehand.

**Comment by mohsenBanan** [comment]
Setting -u is a good thing. All programming languages default to issuing an error for unbound variables.
If bash too is a prog lang; then it should catch unbound vars.

You should use   ${FUNCNAME-main} (where main is default value when unbound) instead of just ${FUNCNAME}.

For debugging I use TM_trace. You then have what you need in tm_trace, which is an ordinary bash function.

alias TM_trace='tm_fileName=${FUNCNAME-main}; tm_lineNo=$LINENO; tm_trace'

Hope this helps.
