### ISSUE TITLE
/usr/bin is prepended to $PATH inside python, breaking emacs lisp testing

### ISSUE THREAD

**Issue by davidshepherd7** [travis-ci/travis-ci#8486]
Something is adding `/usr/bin` to the *front* of `$PATH` whenever a command is run inside `python`. For example see [this log](https://travis-ci.org/davidshepherd7/electric-operator/jobs/278905112#L832). Based on [this issue](https://github.com/pyenv/pyenv/issues/789) I think it's `pyenv` that is doing this.

One consequence of this is that emacs lisp version management is broken. The problem is this:

* Most (or all) emacs lisp package `.travis.yml` files use `$PATH` to manage the version of emacs to test with.
* A program called `cask` is used for package version management during development (think npm but for emacs).
* `cask` is written in emacs lisp, but is started by a small python wrapper.
* On Travis python scripts seem to be run through `pyenv`.
* `pyenv` adds `/usr/bin` to the *front* of `$PATH`, which overrules anything anyone else has set up!

The result is that the system version of emacs from `/usr/bin` is always used.

I'd be very surprised that this hasn't broken anything else. Modifying the path is a fairly common way to control which version of a program is run, and prepending `/usr/bin` to `$PATH` is likely to break anything that relies on that.

I'm not particularly familiar with the Travis internals, and I'd never heard of pyenv before today, so I don't really know where this bug belongs. Do you think it's an issue that could/should be fixed by Travis?

[Link to the cask issue.](https://github.com/cask/cask/issues/399)
[Link to the pyenv issue](https://github.com/pyenv/pyenv/issues/789)

**Comment by BanzaiMan** [comment]
I think this is a combination of a few things, which amounted to the recent manifestation.

Note that the build in question is using a non-recognized `language` value, `emacs-lisp`.

This means that it is sent to the Ruby image (this is new in Trusty). On this image, `python` initially points to the shim (`/opt/pyenv/shims/python`). With `language: python`, this issue should not manifest, as we activate one of the virtualenvs. Under this setup, the shim ends up injecting `/usr/bin` in the beginning of `$PATH` (which is the reported as https://github.com/pyenv/pyenv/issues/789).

Consequently, when you invoke `python` via `/usr/bin/env`, it will have undesirable `$PATH`.

While we await the pyenv issue to be fixed, there are a couple of things you could try. Neither is tested, however.

1. Remove `/opt/pyenv/shims` from `$PATH`:

        export PATH=$(echo $PATH | tr : "\n" | grep -v /opt/pyenv/shims | tr "\n" :)

1. Invoke `/usr/bin/python` instead of `/usr/bin/env python`.

1. Set `language: python`.

**Comment by davidshepherd7** [comment]
Thanks for the pointers, we should be able to use one of those workarounds :smile:

**Comment by eregon** [comment]
This issue is very surprising as it ends up prepending `/usr/bin` to the `$PATH` when invoked from a Python process. So all efforts to change `$PATH` are in vain.
