### ISSUE TITLE
OSX open-source job limit can be increased on weekends

### ISSUE THREAD

**Issue by Pr0methean** [travis-ci/travis-ci#8489]
According to https://www.traviscistatus.com/, the number of active OSX open-source jobs has not been over 124 since 18:00 PDT yesterday. This indicates to me that at that time on a Friday (or 1 hour after the backlog clears, if there is ever still a backlog as of 17:00 PDT) the number of concurrent OSX jobs per branch for open-source projects can be increased to at least 3 without creating backlogs, and doing so will make the total makespan of many builds a lot shorter. It should probably be lowered back to 2 some time between 05:00 and 07:00 PDT every Monday.

**Comment by DrTorte** [comment]
Hey there,

Thanks for the feedback. We're still looking into how exactly things work out with the limitations, and we don't want to rush back into a situation where there's more delays.

That being said, I'll bring this up and discuss the possibility once we have a bit more data. Thank you!

All the best,

Kris

**Comment by Lyoness** [comment]
Hi @Pr0methean ,

We've been working hard to improve performance so that macOS/OSX open-source should have no backlog even on weekdays. We've migrated to new hardware and flash storage, which has solved our perpetual backlog problem for macOS Builds for Open Source Projects 

 https://www.traviscistatus.com/ 🎉 
Closing out.
