### ISSUE TITLE
How to install NodeJS from nvmrc?

### ISSUE THREAD

**Issue by NickHeiner** [travis-ci/travis-ci#8524]
I'm working with this repo: https://github.com/department-of-veterans-affairs/caseflow.

I'm using the Trusty dist. The [docs say](https://docs.travis-ci.com/user/reference/trusty/#JavaScript-and-Node.js-images):

> JavaScript and Node.js images
>
> nvm is installed and we pre-install at least two of the latest point releases such as 6.9.4 and 7.4.0.
>
> You can specify other versions which will be dynamically installed using nvm.

How can I actually do this? What do I need to put in the `.travis.yml`? I found [this part of the docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Specifying-Node.js-versions-using-.nvmrc), but I'm not sure what my `node_js` key would have if I'm omitting the Node version from it.

**Comment by BanzaiMan** [comment]
I think you've figured this out with https://github.com/department-of-veterans-affairs/caseflow/commit/984fe92884cd3ab22586df7bb093a01d20d06bf9; `nvm install X`.

One thing that is incorrect with the comment is that we do not read `.nvmrc` because you are using `language: ruby`. https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Specifying-Node.js-versions-using-.nvmrc applies only when you are using `language: node_js`.

**Comment by BanzaiMan** [comment]
You'd probably want to use `nvm install $(cat .nvmrc)` instead, so that you don't have to specify the Node.js versions in multiple places.

**Comment by NickHeiner** [comment]
> You'd probably want to use `nvm install $(cat .nvmrc)` instead, so that you don't have to specify the Node.js versions in multiple places.

Good idea! I'll fix that up next time I'm modifying that file.

> [the docs page] applies only when you are using `language: node_js`.

Ok – I think that the docs page could be updated to be a bit clearer on that point.

Thanks for the info. :smile:

**Comment by BanzaiMan** [comment]
> I think that the docs page could be updated to be a bit clearer on that point.

Your suggestions are welcome! Please use the "Improve this page on GitHub" button on the upper right corner. Thank you!
