### ISSUE TITLE
XCode 9 time outs when signing tests.

### ISSUE THREAD

**Issue by scottandrew** [travis-ci/travis-ci#8533]
I am getting the following when running our scripts. 

```
▸ Touching PremiseUITests.xctest
▸ Signing /Users/travis/Library/Developer/Xcode/DerivedData/Premise-abfyrylvozfkokgdvmaowwgzydju/Build/Products/Debug-iphonesimulator/PremiseUITests-Runner.app/PlugIns/PremiseUITests.xctest
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

Not sure why or how to stop it. Sometimes i can restart the build and all is fine. But the last day or so it has just been timing out.

**Comment by pbassut** [comment]
Same problem. Anyone looking into this?

**Comment by pbassut** [comment]
Just to add more info: for me it's when signining a framework.
`▸ Signing /Users/travis/Library/Developer/Xcode/DerivedData/MyApp-dpcwgfdbmpaeunemcianwvhbhhpu/Build/Products/Staging-iphoneos/MyApp.app/Frameworks/MyNetworkFramework.framework`

**Comment by Lyoness** [comment]
@pbassut , is this still an issue? 

We've been working hard to improve performance so that macOS/OSX have far fewer timeout.  We've migrated to new hardware and flash storage, which has solved much of this. 

 I'm closing out, but if you are still experiencing these timeouts, feel free to reopen.

**Comment by pbassut** [comment]
I’m not experiencing them now. The issue just went away. Maybe because of that hardware upgrade?

I’ll reopen this if it comes up again.


Em 30 de janeiro de 2018 às 11:38:41, Carmen Andoh (notifications@github.com<mailto:notifications@github.com>) escreveu:

@pbassut<https://github.com/pbassut> , is this still an issue?

We've been working hard to improve performance so that macOS/OSX have far fewer timeout. We've migrated to new hardware and flash storage, which has solved much of this.

I'm closing out, but if you are still experiencing these timeouts, feel free to reopen.
