### ISSUE TITLE
Travis API is not returning branch name

### ISSUE THREAD

**Issue by abrahamoshel** [travis-ci/travis-ci#8565]
Currently we use these two endpoints for our automation tools. Starting around 1:30pm Central Time we start to not receive the branch name back from the API.

https://api.travis-ci.com/repositories/{{ org_name }}/{{ repo_slug }}/builds/{{ build_id}}.json?access_token={{ auth_token }}

https://api.travis-ci.com/api/{{ repo_slug }}/builds/{{ build_id}}.json?access_token={{ auth_token }}

I have emailed support but just to be sure that this was raised as an issue I am also addressing it here.

Please let us know when this is will be resolved or where else I might be able to go to get this information from the travis API.

Builds that that return the correct information:
https://api.travis-ci.com/repositories/shopsmart/specularity/builds/55916308.json
one that does not
https://api.travis-ci.com/repositories/shopsmart/specularity/builds/56526103.json

**Comment by Dolondro** [comment]
I think this may extend further than just the API, as at approximately the same time, the TRAVIS_BRANCH environment variable is no longer being set on our tagged builds, causing a key part of our deployment setup to fail.

**Comment by SuNflOw1991** [comment]
This could also explain https://github.com/travis-ci/travis-ci/issues/8566.

**Comment by dunnock** [comment]
Same for our builds, as a workaround I had to change build to use $TRAVIS_TAG instead of $TRAVIS_BRANCH

**Comment by iriberri** [comment]
Hi all and thanks for reporting this issue.

This behavior is indeed the result of a change we made yesterday that has been already reverted. This change comes from the discussions in https://github.com/travis-ci/travis-ci/issues/4745 to stop overloading the TRAVIS_BRANCH env var with tag information.

Since this is a change that we expect to apply in the future, I'd recommend adapting any tests relying on TRAVIS_BRANCH to a condition that takes into account both TRAVIS_BRANCH and TRAVIS_TAG, for example:

`[[ $TRAVIS_BRANCH = master || $TRAVIS_TAG = master ]]`

This also applies to folks relying on the `branch` attribute of [API responses for builds](https://developer.travis-ci.com/resource/build#Build) (i.e. `GET /build/{build.id}`). Tag details are available in the `tag` attribute, so I'd recommend checking it too to future-proof your workflows.

For the future release of this feature we will be communicating the change in advance, updating our documentation accordingly as well as making sure that all the possible workflows relying on tags being treated as branches (such as branch safelists) are covered.

Thanks for your understanding.

**Comment by adriancole** [comment]
Thanks for taking time to write this up. Much appreciated. I can understand
it is hard to move things forward and remain compatible with all the
history.

Best,
-A

**Comment by plequang** [comment]
Hi,
I don't know if it's related, but since this morning, slack notifications for builds triggered by a tag do not report the tag name anymore.

Before slack notification looked like :
> Build #146 (xxxxx) of org/repo@v1.0.0 by John passed in 4 min 13 sec
Now:
> Build #147 (xxxxx) of org/repo@ by John passed in 4 min 13 sec

**Comment by iriberri** [comment]
Hi @plequang, could you please send us a link to the builds affected by this issue to support@travis-ci.com? We'll take a further look - thank you!

**Comment by Dolondro** [comment]
For anyone else who is wanting to avoid this issue in the future when the changes iriberri described is implemented, I believe using this : `${TRAVIS_TAG:-${TRAVIS_BRANCH}}` instead will continue to replicate the current functionality
