### ISSUE TITLE
pip version should resolve to version of python specified in .travis.yml

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [travis-ci/travis-ci#8572]
This .travis.yml

    language: python
    python:
      - "3.6"
    sudo: required
      - sudo /opt/python/3.6/bin/pip install pylint
    script:
      - $TRAVIS_BUILD_DIR/bin/lint

will install a pylint version for python2.7. When I ssh'd into my box (which I could have only done with the paid for service on travis.com...) I found that

    $ which -a pip
    /opt/pyenv/shims/pip
    /opt/python/3.6/bin/pip
    /opt/python/3.6/bin/pip
    /home/travis/virtualenv/python3.6.3/bin/pip
    /opt/pyenv/shims/pip
    /usr/local/bin/pip

So I printed $PATH `echo $PATH` and its more of a cluster than that... And then I tried calling `pip3.6` because 

    $ which pip3.6
    /opt/pyenv/shims/pip3.6

and when I ran `sudo pip3.6 install pylint` I got yet another error saying `pip3.6` wasn't a proper executable... So I tried calling the absolute path `/opt/python/3.6/bin/pip` and that installed correctly, then got `pylint: command not found`.

**Comment by BanzaiMan** [comment]
You are using `sudo` to invoke `pip`, which means that the execution is using the root's environment. `which` output is probably irrelevant here.

You can try `sudo -E …`, which preserves the current environment and it may work, but otherwise it seems to me this is expected result.

You may also try reproducing the problem with our Docker image: https://docs.travis-ci.com/user/common-build-problems/#Troubleshooting-Locally-in-a-Docker-Image
