### ISSUE TITLE
MongoDB 3.2 has expired key

### ISSUE THREAD

**Issue by nicolaiarocci** [travis-ci/travis-ci#8576]
I found #8554, that mentions my problem. It should be solved but my build, which requires the mongo service, still fails (see: https://travis-ci.org/CIR2000/adam/jobs/286594993). In this specific build I am trying to remove mongo 3.2 (`sudo rm /etc/apt/sources.list.d/mongodb-3.2.list` in `before_install`) as a temporary fix,  but it does not help.

**Comment by bogdanap** [comment]
Hi @nicolaiarocci.
While we can't suppress the initial key expired error message until we update our stable images, this issue has been hotfixed and the key has been refreshed.
Your issue seems unrelated - mongo is present and starting.

While I'm not really familiar with using mongo, the latest version of the docs seem to mention createUser() rather than addUser(), so maybe that's the problem?! 
Alternatively, I'd look if db authentication is properly set up as well, since that could also explain it.
