### ISSUE TITLE
Automatic deployment on GitHub pages failure: push was not done

### ISSUE THREAD

**Issue by YannGarcia** [travis-ci/travis-ci#8593]
Hello Team,

My purpose is to deploy on gh-pages my HTML help generated by Doxygen during the build stages.
During the Travis deployment stages, I can see on the console output that all HTML files are commited to my gh-page repository. You can find my builds here: https://travis-ci.org/YannGarcia/repo/jobs/288561210.
Unfortunately, after the commit, there is no push. My understanding of the TravisCI documentation is that the deployment to gh-pages should be automatic (if the deploy section of the .travis.yml fine is well defined). Am I wrong?
(Note: I think the GitHub Deploy Token is properly set on my Travis Dashboard.)
You can also find my .travis.yml file here: https://github.com/YannGarcia/repo/blob/master/.travis.yml
So, I think I'm doing something wrong, but I cannot find what is wrong.

Many thanks in advance for your support,

Best Regards,

Yann

**Comment by BanzaiMan** [comment]
You are [latest build on the `master` branch](https://travis-ci.org/YannGarcia/repo/builds/288567909) has two jobs, both of which are deploying (because you have no conditions for deployment). Of these two jobs, [the one](https://travis-ci.org/YannGarcia/repo/jobs/288567911) with `TRAVIS_CONTEXT="WithValgrind"` finished last, so the current commit on the `gh-pages` reflects it https://github.com/YannGarcia/repo/commit/ab77e8f1a05b1aa879c45aaf378821fcae8bff14, which is pointed to by [the logs](https://travis-ci.org/YannGarcia/repo/jobs/288567911#L3375).

As reported in https://github.com/travis-ci/travis-ci/issues/7562, currently the GitHub Pages deployment *always* overwrites the commit history to keep only one.

**Comment by YannGarcia** [comment]
Hello Hiro,

Okay, I understood this. My concern is that there is no git push after the
commit. In consequence, in my repo.git:gh-pages, the html files are not
presents as the virtual machine instance is destroyed after. Am I wrong?

Thanks again for your support,

Yann

On 16 Oct 2017 17:59, "Hiro Asari" <notifications@github.com> wrote:

You are latest build on the master branch
<https://travis-ci.org/YannGarcia/repo/builds/288567909> has two jobs, both
of which are deploying (because you have no conditions for deployment). Of
these two jobs, the one
<https://travis-ci.org/YannGarcia/repo/jobs/288567911> with
TRAVIS_CONTEXT="WithValgrind" finished last, so the current commit on the
gh-pages reflects it YannGarcia/repo@ab77e8f
<https://github.com/YannGarcia/repo/commit/ab77e8f1a05b1aa879c45aaf378821fcae8bff14>,
which is pointed to by the logs
<https://travis-ci.org/YannGarcia/repo/jobs/288567911#L3375>.

As reported in #7562 <https://github.com/travis-ci/travis-ci/issues/7562>,
currently the GitHub Pages deployment *always* overwrites the commit
history to keep only one.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/travis-ci/travis-ci/issues/8593#issuecomment-336933232>,
or mute the thread

**Comment by BanzaiMan** [comment]
> In consequence, in my repo.git:gh-pages, the html files are not
presents as the virtual machine instance is destroyed after. Am I wrong?

That is because you are deploying from both jobs, and the last one is almost completely empty.

```
[master (root-commit) ab77e8f] Deploy YannGarcia/repo to github.com/YannGarcia/repo.git:gh-pages
 4 files changed, 15 insertions(+)
 create mode 100644 README.md
 create mode 100644 _config.yml
 create mode 100644 deployed at Mon Oct 16 13:50:26 UTC 2017 by Deployment Bot (from Travis CI)
 create mode 100644 index.html
```

If you are expecting to find the documents generated by the first job (such as https://travis-ci.org/YannGarcia/repo/jobs/288567910#L2891), then you need to disable the second job from deploying. See https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A.

**Comment by YannGarcia** [comment]
Hello Hiro,

Thanks a lot for your explanation, I got it now.

Have a nice day,

Yann

Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)7 61 00 77 05
Email: *yann.garcia@fscom.fr* <yann.garcia@fscom.fr>
           Yann.Garcia_EXT@etsi.org
Skype: yann.garcia
Google+: garcia.yann@gmail.com

**Comment by YannGarcia** [comment]
Thanks again, it works fine.
Yann

Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6,
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
Avenue des Alpes
<https://maps.google.com/?q=6,%C2%A0+Avenue+des+Alpes&entry=gmail&source=g>
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08
Mobile: +33 (0)7 61 00 77 05
Email: *yann.garcia@fscom.fr* <yann.garcia@fscom.fr>
           Yann.Garcia_EXT@etsi.org
Skype: yann.garcia
Google+: garcia.yann@gmail.com
