### ISSUE TITLE
Request: containerized OSX builds

### ISSUE THREAD

**Issue by xoviat** [travis-ci/travis-ci#8615]
I understand that you guys don't want to enable docker on OSX because it's already backlogged enough, but what I am suggesting here is that you enable docker for a portion of the current OSX workers under your control, and then run containerized builds in them. 

IIRC, according to your own statistics, the average OSX build lasts for 5 minutes. OSX also takes up to three minutes to boot. That suggests that under optimal conditions, switching to containerized builds could significantly increase OSX capacity.

**Comment by danielbayley** [comment]
I wonder if https://veertu.com/anka-technology would be relevant here?

**Comment by Lyoness** [comment]
Hi @xoviat @zaquestion @danielbayley 

Thanks for proposing the container solution.   Unfortunately, containers are not possible in the macOS environment because Apple requires any virtualized apple OS VMs to run on Apple Hardware, not on linux, so xhyve had to be ruled out.   As a result, we don't get to make use of native hypervisors or all the neat stuff going on in linux land.  The resulting system we've built, using VMWare virtualization (the only enterprise virt solution for mac up until recently) with macpros, has its limits.  I won't go into those there, but we've made performance improvements in the last week in the meantime by moving to new hardware and new Flash SANs. 

However, as Daniel posted, Veertu/Anka is promising as native virtualization solution for apple hardware, and that's exactly where we'll be focusing our attention in the coming months.  

I'm closing this out
