### ISSUE TITLE
Build unknown

### ISSUE THREAD

**Issue by LukasBures** [travis-ci/travis-ci#8653]
Hello,
we have a problem with the Travis badge (Build: unknown), the public repository is:
https://github.com/ZencashOfficial/arizen

Code for badge:
`[![Build status][travis-img]][travis-url]`
`[travis-img]: https://img.shields.io/travis/ZencashOfficial/arizen.svg?style=flat-square`
`[travis-url]: https://travis-ci.org/ZencashOfficial/arizen.svg?branch=master`

[![Build Status](https://travis-ci.org/ZencashOfficial/arizen.svg?branch=master)](https://travis-ci.org/ZencashOfficial/arizen)

Badge and build from Travis CI:
![ci](https://user-images.githubusercontent.com/3979946/32090136-45c74674-baee-11e7-81eb-b78c67dc35dc.png)

**Comment by BanzaiMan** [comment]
The badge needs builds with Pushes, but your repository has none. https://travis-ci.org/ZencashOfficial/arizen/builds

We are rejecting the build requests because the activity looks abusive. https://travis-ci.org/ZencashOfficial/arizen/requests

You should see a warning on the radio icon on the upper left corner indicating this. The warning should suggest getting is touch with us at support@travis-ci.com.

I'm closing this, as there is not much else to do here.
