### ISSUE TITLE
Announce failed tests in a PR comment

### ISSUE THREAD

**Issue by bluzi** [travis-ci/travis-ci#8661]
Hey,

Anyway to make a bot that announces failed tests of a PR using a comment?

**Comment by BanzaiMan** [comment]
It is possible, but it'll involve some work on your part.

You would write a web app which:
1. receives [the webhook notification](https://docs.travis-ci.com/user/notifications#Configuring-webhook-notifications)
1. verifies the payload
1. posts the comment to the relevant PR using [the GitHub API](https://developer.github.com/).

You cannot do this with `after_failure`, because PR builds will not have access to secrets (unless you want to broadcast your bot's API token to the public).

**Comment by bluzi** [comment]
Hey @BanzaiMan,

Thanks for the quick response!
Is there a way to retrieve the build log through a WebHook? I need it in order to tell which tests has failed.

**Comment by xoviat** [comment]
See https://docs.travis-ci.com/api/#logs

**Comment by bluzi** [comment]
Another question with the same context - Seems like creating a PR executes build that is related to the PR, but adding commits to a PR results in build that are not related to the PR.

The first build of a PR fires a webhook with `pull_request_number` in its payload, but the second build (and third, and so on) doesn't.

Can you think of a way to connect between a build and its PR? maybe through the branch somehow? 
@BanzaiMan @xoviat

**Comment by BanzaiMan** [comment]
> The first build of a PR fires a webhook with `pull_request_number` in its payload, but the second build (and third, and so on) doesn't.

What do you mean by this? When you open a PR, by default, there will be two builds triggered. One for the push to the topic branch, and the other for the PR (merge of the head branch to the base branch). The former does not contain `pull_request_number`, while the latter does. Subsequent pushes to the topic branch which has an open PR should behave the same way.

**Comment by simonv3** [comment]
Could TravisCI do this without a bot? For example we're using TravisCI for linting and tests, and it would be great to know what failed on the PR itself, without having to go to the build details. 

We're working around this for now with using flowdock notifications.

**Comment by bluzi** [comment]
@simonv3, I already have a solution; see: https://github.com/bluzi/travis-buddy (https://www.travisbuddy.com/)

Currently it's live in 15 different repositories, and it stars every repository that uses it automatically, so you can [visit the stars page](https://github.com/TravisBuddy?tab=stars) and browse the repositories. 

It's easy to integrate, just add few lines to your `travis.yml`.

[See this random PR as an example](https://github.com/didi/cube-ui/pull/47)

**Comment by simonv3** [comment]
That's awesome @bluzi. Unfortunately this is for a private repository :( (though we're working on making things open source!)

**Comment by bluzi** [comment]
I see :)

**Comment by ac427** [comment]
@simonv3 , I wrote something which can add comment to the PR . You can do something like that for private repo. I just started playing with Travis, looks like you can also post notifications using webhooks, you can host webserver to accept payload and post comment via webhooks instead of using the script like I did in my repo 

https://github.com/ac427/travis-sidekick
