### ISSUE TITLE
jasmine tests failing on travis all of a sudden

### ISSUE THREAD

**Issue by tansaku** [travis-ci/travis-ci#8693]
things have been fine for a year, but suddenly we get:

```
4.37s$ USE_JASMINE_RAKE=true bundle exec rake jasmine:ci
rake aborted!
Errno::EADDRNOTAVAIL: Cannot assign requested address - connect(2) for "localhost" port 45433
```

in builds like this one: https://travis-ci.org/AgileVentures/LocalSupport/builds/295449091?utm_source=github_status&utm_medium=notification

We did have this same issue last year ... https://github.com/travis-ci/travis-ci/issues/6452

**Comment by derickr** [comment]
I have been getting the exact same, but in PHP (C), for a IPv6 specific test:

From https://travis-ci.org/xdebug/xdebug/jobs/297510631#L927 :
```
========DIFF========
001+ Log opened at 2017-11-05 21:55:20
002+ I: Connecting to configured address/port: :::43113.
003+ W: Creating socket for ':::43113', connect: Cannot assign requested address.
004+ E: Could not connect to client. :-(
005+ Log closed at 2017-11-05 21:55:20
001- <?xml version="1.0" encoding="iso-8859-1"?>
002- <init xmlns="urn:debugger_protocol_v1" xmlns:xdebug="http://xdebug.org/dbgp/xdebug" fileuri="file:///tmp/xdebug-dbgp-test.php" language="PHP" xdebug:language_version="" protocol_version="1.0" appid="" idekey=""><engine version=""><![CDATA[Xdebug]]></engine><author><![CDATA[Derick Rethans]]></author><url><![CDATA[http://xdebug.org]]></url><copyright><![CDATA[Copyright (c) 2002-%d by Derick Rethans]]></copyright></init>
========DONE========
```

It's this test code: https://github.com/xdebug/xdebug/blob/master/tests/bug00998-ipv6.phpt

Curiously, *this* one works just fine: https://github.com/xdebug/xdebug/blob/master/tests/bug00998-ipv6_localhost.phpt

The only difference is that the first one tries to listen on ``[::]`` (all addresses) and the second one uses ``localhost``.

The IPv4 variant of these tests continues to work with ``0.0.0.0`` and ``localhost``.

It looks like it is no longer allowed to listen on all addresses with IPv6,

**Comment by Bilge** [comment]
I refrained from posting because I assumed it would be a simple hotfix applied as a matter of urgency, but since it's been a week now, let me add that a [commit hash that always passed](https://travis-ci.org/Porter-connectors/HttpConnector/builds/295260655) has now [systematically began to fail](https://travis-ci.org/Porter-connectors/HttpConnector/builds/296221978) since [November 2<sup>nd</sup>](https://travis-ci.org/Porter-connectors/HttpConnector/builds). 

The build now consistently fails with the same error message: "failed to open stream: Cannot assign requested address". The address it's trying to assign is "[::1]:12345", although it's strange that it says "assign" since it should be trying to read rather than bind at that point in the code.

**Comment by nsiregar** [comment]
Is it possible to use `addons` hosts just to set localhost ?
https://docs.travis-ci.com/user/hosts

**Comment by trptcolin** [comment]
@nsiregar that does not fix the issue for me, unfortunately - thanks for the idea though!

**Comment by Bilge** [comment]
I have received word from Travis this issue is being worked on internally. Let's be patient!

**Comment by bel2125** [comment]
Maybe this fix will help here as well:
https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804

**Comment by Bilge** [comment]
The word I have received from Travis today informs that IPv6 was never officially supported and so the fact that it is no longer working is of no particular consequence since it's still not supported. Therefore it would seem we are required to find alternative solutions.

**Comment by BanzaiMan** [comment]
Is this issue about jasmine not working, or about IPv6 `localhost`?

**Comment by Bilge** [comment]
@BanzaiMan If you're asking me, it's about being unable to bind to IPv6 localhost (`::1`).

**Comment by bel2125** [comment]
I think we must distinguish between "full IPv6 network support" and "having an IPv6 [local address](https://en.wikipedia.org/wiki/IPv6_address#Local_addresses)":
For full IPv6 support, you have to take the entire network into account, including security considerations ... a lot of work. 
For a local IPv6 address you just allow the local (virtual) machine to have IPv6 enabled, while the rest of the network can still disable it ... basically no work to do, since it's often a default config.
The local IPv6 will not allow to communicate to the outside world, but it's enough for testing an IPv6 server/client application.

These different things should not be mixed up as "IPv6 support":
There ***was*** local IPv6 support (but no full IPv6 network), there ***is*** local IPv6 support if you activate it yourself (see  https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350090030 of @GiedriusM and the following postings), and from my point of view there ***should be*** local IPv6 support (for IPv6 server/client tests), but none of the comments I read in the multiple related issues that came up recently asked for a full IPv6 network to communicate to an outside world.

**Comment by GiedriusM** [comment]
I second @bel2125 opinion. Many network service related libraries have support for IPv6 and need tests for such environments. Having at least a local IPv6 support is a must for such projects. And if true wide-area IPv6 networking is required, I would argue that in such case a dedicated multi-node setup should be used, instead of a single [Travis] container. So for most (if not all) projects local IPv6 support will be more than enough and all others will be using custom setups anyways.

**Comment by derickr** [comment]
Same for me, just a local IPv6 loopback address would do.

The workaround that @bel2125 points to (https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350090030) doesn't work with ``sudo: false`` and I also need need trusty, so https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-327817604 doesn't do it for me either.

**Comment by Bilge** [comment]
@BanzaiMan Is this issue still on your radar? Do you refute Travis support's claim that (local) IPv6 was never officially supported?

**Comment by tansaku** [comment]
for us the issue if with just trying to use `localhost` - not sure how this relates to IPv6

**Comment by BanzaiMan** [comment]
`::1` loopback should be available as `ip6-localhost`.

**Comment by Bilge** [comment]
For the record, this was never fixed and IPv6 remains broken.
