### ISSUE TITLE
Xcode 9.1 image

### ISSUE THREAD

**Issue by NachoSoto** [travis-ci/travis-ci#8700]
I've unsuccessfully tried to reach support via e-mail and Twitter, so trying here...

The `xcode9.1` image is a beta. [The docs](https://docs.travis-ci.com/user/reference/osx/#Xcode-version) make it sound like it's the "real version" but it's not.
The final version came out 3 days ago, and as a consequence, builds fail because the version of the compiler has changed. Specifically, it doesn't have the latest `Swift 4.0.2`.

Support told me you expected this to be ready 2 days ago, but we're still waiting.

**Comment by Mehdzor** [comment]
This is actually a serious blocker. Since Swift 4.0.2 is not ABI compatible with his ancestors, our whole team just left without CI/CD now. 
So development process is ruined. Travis, please fix.

**Comment by NachoSoto** [comment]
And as with every single release, not only does Travis fail at being ready in a timely manner, but their communication and transparency leaves a lot to be desired.

I already know of 2 companies moving to CircleCI after this, and in thinking about it.

**Comment by NachoSoto** [comment]
Travis, it's been a whole week since Apple released Xcode 9.1, and you haven't even bothered to update your docs to indicate that **the `xcode9.1` image is a beta**.

**Comment by NachoSoto** [comment]
We pay $249 a month, and Travis doesn't even reply to our customer support e-mails. In contrast to that: https://twitter.com/Palleas/status/927637394471387139.

**Comment by Mehdzor** [comment]
Nacho, have you tried mentioning Travis' twitter? Perphaps they'll respond faster there.

**Comment by NachoSoto** [comment]
Same luck, not a single response.

**Comment by Mehdzor** [comment]
Travis, this is just not funny anymore.

**Comment by seivan** [comment]
We're also on the `$249` and our expectation has always been that Travis provides value since it would take much more of our time to do these things ourselves.

Or at least, that was the take on it the last time it came under discussion. So far it hasn't been painless with updates between Xcode version. 
I'd like to see some roadmap on how to fix this in the future as I'd give the benefit of the doubt and assume there is a larger plan at play and that's going to make sure these things don't happen in the future. That would make this *OK* otherwise it's a bad sad to see the decrease in quality. 

I *know* you can do better because you've done it before!

**Comment by Mehdzor** [comment]
I think this is a sign of not giving a thing by Travis.

**Comment by Mehdzor** [comment]
Travis announced an update but builds are still failing tho.
https://twitter.com/travisci/status/928370240274292737

**Comment by NachoSoto** [comment]
🤦🏻‍♂️

**Comment by eneko** [comment]
I can confirm in our case, when using `osx_image: xcode9.1`, we still get the incompatible Swift versions warning:
```
Incompatible Swift version - framework was built with 4.0.2 (swiftlang-900.0.69.2 clang-900.0.38) and the local version is 4.0.1 (swiftlang-900.0.66 clang-900.0.37).
```

This is a clear indicator that the VM is still running Xcode 9.1 beta.

For those using Carthage, try doing `carthage update --no-use-binaries` or `carthage bootstrap`. In our case we run `carthage bootstrap --cache-builds` and our builds pass, but take longer than desired, since all dependencies have to be built from source.

**Comment by Mehdzor** [comment]
Now 9.1 images are just failing on start with an error:
`Download from https://build.travis-ci.com/filter/pty.rb failed. Trying https://build.travis-ci.com/filter/pty.rb ...
ruby: No such file or directory -- /Users/travis/filter.rb (LoadError)`

**Comment by oleksandr-yefremov** [comment]
I hope this means Travis team is fixing this **right now**, because in the job config it says `"osx_image": "xcode9",`, which is weird. 
Anyhow, after 3 times of waiting more than a week, our team decided to move to Gitlab CI with self-hosted Job runner (CircleCI would be another option, but there is a chance they will not keep up with Apple's pace of breaking things in future as well 😄 )

**Comment by Mehdzor** [comment]
Even after getting macs back online the issue persists. 
<img width="422" alt="screen shot 2017-11-09 at 17 53 31" src="https://user-images.githubusercontent.com/5204252/32611703-5e6f64e8-c577-11e7-9c00-933d361e3a5c.png">

**Comment by DrTorte** [comment]
Hey everyone,

We're looking into this right now. We'll post an update as soon as we have one, which we hope is soon. Thanks.

**Comment by DrTorte** [comment]
Hi everyone,

We've resolved this issue now, and you should be good to go. The issue took longer to resolve than anticipated, and was exasperated by an unfortunately timed maintenance window. We plan to provide a breakdown of the events that led to this and how we can work to avoid it in the future.

Thank you all for your understanding, we know how frustrating this is.

**Comment by NachoSoto** [comment]
Still not working:

> [18:23:17]: ▸ error: module compiled with Swift 4.0.2 cannot be imported in Swift 4.0.1

**Comment by NachoSoto** [comment]
@DrTorte thanks, testing it now. I hope you all realize how bad your transparency and communication was throughout this issue. Like I've said, completely unacceptable, especially for us paying customers.

**Comment by eneko** [comment]
Xcode 9.1 image seems to be working great for us now, thank you!
