### ISSUE TITLE
Webhook notifications: on_error not supported ?

### ISSUE THREAD

**Issue by vincent-psarga** [travis-ci/travis-ci#8723]
Hi,

When checking the documentation for web hook notifications, it states that we can use the following keys/events:

    on_success: change # default: always
    on_failure: always # default: always
    on_start: change   # default: never
    on_cancel: always # default: always
    on_error: always # default: always

That said, once using the Yaml linter, it tells than on_cancel and on_error are unexpected
 keys:

    in notifications.webhooks section: unexpected key on_cancel, dropping
    in notifications.webhooks section: unexpected key on_error, dropping

So far in my build, I don't see any notification made when the build error (as it can be seen here for example: https://travis-ci.org/hiptest/hps-javascript-qunit/builds/299123955)

Is it planned to support the on_error in the future ?

**Comment by BanzaiMan** [comment]
The webhooks notification is not firing. The problem is that you cannot use environment variables for notification URLs (as you do here: https://github.com/hiptest/hps-javascript-qunit/blob/a9a3b1929997983538009603f868333a55ac97ff/.travis.yml#L20). The reason is that the notifications are configured before the builds run. This is documented in https://docs.travis-ci.com/user/notifications#Changing-notification-frequency, but probably we can make it more obvious.

**Comment by vincent-psarga** [comment]
Thanks, I understand it better now. That said, is it possible to use secret data in those notifications ? (as I did in the file you mention. I don't want this token to be publicly available obviously ;) )
