### ISSUE TITLE
OSX: sed is broken?

### ISSUE THREAD

**Issue by LebedevRI** [travis-ci/travis-ci#8812]
Hi.
https://travis-ci.org/darktable-org/darktable/jobs/308077343#L2640
```
[76/587] cd /Users/travis/build/darktable-org/darktable/build/src/libs && /usr/local/Cellar/cmake/3.10.0/bin/cmake -E make_directory /Users/travis/build/darktable-org/darktable/build/src/libs/tools/ && /Users/travis/build/darktable-org/darktable/tools/authors_h.sh /Users/travis/build/darktable-org/darktable/AUTHORS /Users/travis/build/darktable-org/darktable/build/src/libs/tools/darktable_authors.h

FAILED: src/libs/tools/darktable_authors.h 

cd /Users/travis/build/darktable-org/darktable/build/src/libs && /usr/local/Cellar/cmake/3.10.0/bin/cmake -E make_directory /Users/travis/build/darktable-org/darktable/build/src/libs/tools/ && /Users/travis/build/darktable-org/darktable/tools/authors_h.sh /Users/travis/build/darktable-org/darktable/AUTHORS /Users/travis/build/darktable-org/darktable/build/src/libs/tools/darktable_authors.h

sed: RE error: illegal byte sequence
```
That is https://github.com/darktable-org/darktable/blob/release-2.4.0rc0/tools/create_release.sh + https://github.com/darktable-org/darktable/blob/release-2.4.0rc0/AUTHORS
It does not seem to happen on linux.

**Comment by mhinz** [comment]
The error happens in [authors_h.sh](https://github.com/darktable-org/darktable/blob/release-2.4.0rc0/tools/authors_h.sh#L35) because of the name of one of the authors.

TravisCI uses [`LC_ALL=en_US.UTF-8`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) by default:

```
$ export LC_ALL=en_US.UTF-8
$ echo "Žilvinas Žaltiena" | sed -e "s/^/\"/g" -e "s/$/\",/g"
sed: RE error: illegal byte sequence

$ export LC_ALL=C
$ echo "Žilvinas Žaltiena" | sed -e "s/^/\"/g" -e "s/$/\",/g"
"Žilvinas Žaltiena",
```

Mind that there are subtle differences between GNU sed (Linux) and BSD sed (macOS). See [this SO answer](https://stackoverflow.com/a/23584470) for the painful details and gotchas.

Alternatively:

```
$ brew install gnu-sed
$ export LC_ALL=en_US.UTF-8
$ echo "Žilvinas Žaltiena" | gsed -e "s/^/\"/g" -e "s/$/\",/g"
"Žilvinas Žaltiena",
```

**Comment by LebedevRI** [comment]
@mhinz thanks, that did it!
https://github.com/darktable-org/darktable/commit/2fac7a457bf7f3b84b6dd9422937cf72ca29fe95
