### ISSUE TITLE
Cannot install gcc with homebrew

### ISSUE THREAD

**Issue by ghost** [travis-ci/travis-ci#8826]
```
==> Installing dependencies for gcc: libmpc, isl
==> Installing gcc dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.0.3_1.sierra.bottle.tar.gz
==> Pouring libmpc-1.0.3_1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.0.3_1: 12 files, 345.0KB
==> Installing gcc dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.18.sierra.bottle.tar.gz
==> Pouring isl-0.18.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.18: 80 files, 3.8MB
==> Installing gcc
==> Downloading https://homebrew.bintray.com/bottles/gcc-7.2.0.sierra.bottle.tar.gz
==> Pouring gcc-7.2.0.sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink include/c++
Target /usr/local/include/c++
already exists. You may want to remove it:
  rm '/usr/local/include/c++'
To force the link and overwrite all conflicting files:
  brew link --overwrite gcc
To list all files that would be deleted:
  brew link --overwrite --dry-run gcc
Possible conflicting files are:
/usr/local/include/c++ -> /usr/local/Caskroom/oclint/0.11,15.6.0/oclint-0.11/include/c++
```

**Comment by BanzaiMan** [comment]
Did you try any of the suggested fixes?

**Comment by xoviat** [comment]
No. I don't know the implications of the suggested fixed. Which fix would you recommend?

**Comment by BanzaiMan** [comment]
I must defer that to Homebrew maintainers.

**Comment by MarkWieczorek** [comment]
For info, we are only trying to install `fftw`, which needs to install a couple of dependencies
````
==> Installing dependencies for fftw: gmp, libmpc, isl, gcc
````
The problem is that we never installed oclint, so I have no idea why this file is even present: `/usr/local/Caskroom/oclint/0.11,15.6.0/oclint-0.11/include/c++`

**Comment by xoviat** [comment]
@BanzaiMan is there any way that you could remove these files from your OSX images?

**Comment by BanzaiMan** [comment]
Sorry. Pressed a wrong button.

**Comment by BanzaiMan** [comment]
You have `sudo` on the Mac. You should be able to remove the file as you see fit.

**Comment by xoviat** [comment]
Yes, but @tueda is expecting you to fix the problem:

https://github.com/vermaseren/form/commit/8e8b0ae7b5b660165e55088db411314b050bf5d0#commitcomment-25966830

Rebuilding images is expensive, but you should fix this on the next rebuild if possible.

**Comment by BanzaiMan** [comment]
Sorry, but it looks like a conflict between packages (`oclint` and `gcc`). I don't think we can resolve it on our side.

**Comment by MarkWieczorek** [comment]
But I never installed `oclint`. Why is this installed by default?

**Comment by tueda** [comment]
In my case, `brew install mpich` triggers this problem because `mpich` depends on Fortran and so Homebrew tries to install `gcc`, even though I'm not using Fortran. (By the way, one of the reasons why I'm testing `mpich` on macOS has originated from the fact that `mpich` is not in the whitelist for Ubuntu travis-ci/apt-package-whitelist#406.)
If providing `oclint` on macOS by default via Caskroom is a Travis's decision, that's OK, we can just follow some workaround. But such a workaround is required for all projects using Homebrew packages on macOS that depend on Fortran (or explicitly gcc).

**Comment by tueda** [comment]
`brew install mpich --without-fortran`, which I mentioned above, seems to be not so good: can't pour the bottle and has to build `mpich` from the source, which can take over 10 minutes somehow. One of test jobs failed due to the "No output has been received in the last 10m0s..." error. (Well, I could add `-v` option to print some build messages...)

**Comment by tueda** [comment]
Now I'm not sure from when `cask oclint` has been there in the Travis macOS image. A strange thing is: the official document of OCLint describes [how to use OCLint on Travis CI](http://oclint-docs.readthedocs.io/en/v0.13/guide/travisci.html) and tells what should be done first, **uninstalling** oclint
```
brew cask uninstall oclint
brew tap oclint/formulae
brew install oclint
```
which doesn't make sense to me. Anyway, the description exists from v0.10.3 (Jun 19, 2016), implying `cask oclint` has been there since (at least) the last year??

**Comment by tueda** [comment]
This looks the same issue, requiring `brew cask uninstall oclint`: travis-ci/docs-travis-ci-com#1283.

**Comment by xoviat** [comment]
I wasn't able to find the build scripts for the OSX images publicly, but
IMO oclint should not be installed by default. Maybe you could grep the OSX
build logs for oclint? One the homebrew side, oclint should probably be
installed since it conflicts.

**Comment by tueda** [comment]
The bootstrap script seems to be [this](https://github.com/travis-infrastructure/osx-image-bootstrap/blob/master/bootstrap.sh), which I found a link from README of [oclint/homebrew-formulae](https://github.com/oclint/homebrew-formulae). Because `oclint` has been supported by Travis from previous OS images, I can imagine simply removing `oclint` may make people using the default `oclint` upset. For now the best way I can come up with would be the workaround of uninstalling `oclint`.

**Comment by j3mdamas** [comment]
Hi guys,

Is there any prediction of when this will be solved? It's been one week since Mac builds have been broken. Is uninstalling `oclint` the solution? How to install gcc with brew if that is not the solution?

**Comment by xoviat** [comment]
The solution is to run "brew cask uninstall oclint." IMO, the default
assumption should be that you shouldn't need to run "uninstall" commands,
but only "install" commands. Do we know how many projects use oclint vs.
gcc? I would guess gcc is much more popular.

**Comment by j3mdamas** [comment]
@xoviat thanks for the reply! I don't want to sound rude, I'd only like to understand the timeline as it seems, like you say, that it affects many people

**Comment by h-2** [comment]
Yes, please fix this. Installing compilers is like one of the most frequent things people do in a CI environment. And the nature of CI being, it now makes all of my updates fail...

Thank you!

**Comment by h-2** [comment]
This does not seem fixed, yet:
https://travis-ci.org/seqan/lambda/jobs/364190342

**Comment by ilovezfs** [comment]
>Sorry, but it looks like a conflict between packages (oclint and gcc). I don't think we can resolve it on our side.

@BanzaiMan you can resolve it by not preinstalling `oclint` in the Travis images. It makes little sense to preinstall something that conflicts with the primary `gcc` formula.

**Comment by PierreMarchand20** [comment]
And it is still quite strange since, as tueda pointed it out, the documentation of oclint still says you need to uninstall the preinstalled version of oclint to reinstall it and use it with Travis CI... so what's the point to have this preinstalled version anyway ?

**Comment by MichaelClerx** [comment]
Ran into this issue today trying to `brew install sundials`. As mentioned above, it's fixed by first running `brew cask uninstall oclint`

**Comment by vmarkovtsev** [comment]
@BanzaiMan ping

**Comment by zbeekman** [comment]
@BanzaiMan Using the new `addon: homebrew:` syntax too if you try to use `packages: gcc` It would simplify my CI workflow INCREDIBLY to use this new feature. It also seems crazy to me that the default environment would be setup in such a way that a package that prevents GCC from a simple `brew install gcc` to fail on linkage would be installed by default.

**Comment by zbeekman** [comment]
Also, in a CMake file `find_package(mpi)` sets `MPI_C_FOUND = FALSE` when open-mpi is installed via homebrew. Doesn't happen locally and doesn't happen with MPICH.

**Comment by PierreMarchand20** [comment]
Well I guess we can open an issue on the new community forum since they closed this issue...

**Comment by PierreMarchand20** [comment]
I added a similar issue here : https://travis-ci.community/t/problem-installing-gcc-on-macos-with-homebrew-incompatibility-with-oclint/783

**Comment by BanzaiMan** [comment]
FWIW We now remove `oclint` on the fly: https://changelog.travis-ci.com/oclint-is-removed-from-mac-builds-79270
