### ISSUE TITLE
strange behaviour for py3.5

### ISSUE THREAD

**Issue by JoyMonteiro** [travis-ci/travis-ci#8889]
Hello,

I have my project building on several versions of python,
and it errored on the python 3.5 build today when a similar build worked fine just a day ago.
On inspection, I found that for some reason, on the python 3.5 build tries to activate
a virtualenv while none of the others do so for their respective python versions

This is the build that errored:
https://travis-ci.org/CliMT/climt/builds/315490586

Which I fixed by manually adding python: 3.5 in
https://travis-ci.org/CliMT/climt/builds/315504494

This is strange, because nowhere in my .travis.yml previously did I ask travis to
use python 3.5 (I used to use python: 3.6 only once globally), and tox takes
care of using the correct python. Any ideas why this issue occurs?

Thanks,
Joy

**Comment by bogdanap** [comment]
Hi @JoyMonteiro.
Unfortunately, this is expected behaviour since our latest [updates](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/), we switched the default Python 3 version from 3.5 to 3.6 (which means Python 3.5 is no longer included by default in our images)

We are aware that our support for Tox at this point isn't great (and thus causing these types of issues), but are working to improve the situation.

Happy to hear you managed to work around the situation though. 😄

**Comment by JoyMonteiro** [comment]
Thanks for the clarification. Yes, things are working fine, just thought I would find out what changed!
