### ISSUE TITLE
New Trusty images breaking all of my Docker builds

### ISSUE THREAD

**Issue by stevebargelt** [travis-ci/travis-ci#8896]
All of my docker build started failing with the Trusty environment: 

```
0.04s
$ git submodule update --init --recursive
0.20s
$ docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
unknown shorthand flag: 'e' in -e=[secure]
See 'docker login --help'.
The command "docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"" failed and exited with 125 during .
Your build has been stopped.
```

I added the suggested "group: deprecated-2017Q4 " to my .travis.yml and the builds work again.

**Comment by edmorley** [comment]
The `-e` option was deprecated several Docker versions ago, and would have been previously outputting:
`Flag --email has been deprecated, will be removed in 17.06.`

The new Travis images update Docker to 17.09.0-ce ([see here](https://docs.travis-ci.com/user/build-environment-updates/2017-12-12/)), which finally removed the deprecated option (see docker/cli#143).

Since the command in the OP also specifies the username, I'm presuming the fix is to just remove the `-e` option entirely and no other changes should be required.

**Comment by cotsog** [comment]
We are recommending @edmorley's suggestion.

Cross-linking to the documented issue and workaround: https://github.com/travis-ci/travis-ci/issues/8870#issuecomment-352458433.
