### ISSUE TITLE
Build hangs for 10 mins then terminated

### ISSUE THREAD

**Issue by cades** [travis-ci/travis-ci#8898]
since today (2017/12/12), my build hangs for 10 mins then terminated. below are last few lines of build log:

```
The command "npm run test:cov" exited with 0.
Skipping a deployment with the script provider because this branch is not permitted

Done. Your build exited with 0.


No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

add `group: deprecated-2017Q4` to `.travis.yml` make it work again.

**Comment by bogdanap** [comment]
@cades  Sorry to hear that. In order to be able to help you, would you mind pasting the URL of a build that's failing please?

**Comment by antiBaconMachine** [comment]
We had a very similar problem. We fixed it by replacing an `exit 0` call with `travis_terminate 0`

**Comment by MorpheusXAUT** [comment]
Same issue here - we have a build step that runs a custom deployment script depending on the $TRAVIS_BRANCH env variable. On all but one branch, the build step is simply stopped with `exit 0;`, which worked fine until the trusty update.
Will try to replace all `exit` calls with `travis_terminate` like antiBaconMachine suggested.
@bogdanap builds are running on travis-ci.com, would a like still be useful to you even if it's not public?

**Comment by radius** [comment]
@bogdanap I'm having the same issue. Here's a link to a failing build:
https://travis-ci.com/Artivest/website/builds/61555801

**Comment by cades** [comment]
@bogdanap here's our failing build URL (travis-ci.com, which is a private build): https://travis-ci.com/Dcard/Dpick-API/builds/61485024

**Comment by MorpheusXAUT** [comment]
@BanzaiMan Just as additional information: we're also seeing this issue on the (sudo-enabled) ruby builders, not only node ones. While we internally use node.js, it's being run in a Docker container and the "failing" part is a plain shell script.

Link to a failing build: https://travis-ci.com/CashQuizz/cashquizz-backend/builds/61506415

**Comment by bkimminich** [comment]
I experienced these timeouts in latest and deprecated `trusty` as well as `precise` environment. But it started happening around the time that new `trusty` came out. See #8909 for details.

**Comment by aaime** [comment]
Same happens a lot for GeoTools and GeoServer, here is a links to a sample failed build:
https://travis-ci.org/geoserver/geoserver/builds/317631169
And our Travis configuration:
https://github.com/geoserver/geoserver/blob/master/.travis.yml

As you can see we are running two commands chained with &&, wondering if that might be related to the problem.

**Comment by andy-plutoflume** [comment]
We are seeing this issue also. The `travis_terminate 0` trick from @antiBaconMachine works for cases where we explicitly `exit 0` but there are other cases that also hang.

**Comment by MorpheusXAUT** [comment]
I've noticed that some of today's builds failed when using `travis_terminate` due to `travis_terminate: command not found`. @antiBaconMachine @andy-plutoflume does the command still work fine for you for recent builds (noticed it with builds starting about 1-1.5 hours ago)?

**Comment by eapache** [comment]
I was seeing the exact same symptoms as this ticket, but it turned out to be because I had been leaving background processes running. Apparently the new image will not stop until *all* the processes you spawn are dead, not just the foreground one. This is a major change and I'd appreciate it if it were added to the changelog docs for the new image somewhere.

**Comment by MorpheusXAUT** [comment]
@eapache if that's the case, it seems like build stages have a completely different problem - our builds always fail on the last of four stages, which consists of a script checking whether the commit was made to a specific branch and executing some deployments afterwards.
If the branches do not match, the script (and thus the build stage) simply exits with 0.

All other stages beforehand complete fine and since we're using sudo-enabled builds, I'm of the impression that a new VM is spun up for each build stage, so no other background processes should be running at that point.

**Comment by attiks** [comment]
I ran into the same issue with a pretty basic travis, see #9013 for travis file
Changing script to "$TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom || travis_terminate 0" does not solve the problem for me

**Comment by attiks** [comment]
My problem got "fixed" by simplifying to travis file to just

```
dist: trusty
language: php

php:
  - 7.1

before_script:
  - cd $TRAVIS_BUILD_DIR
  - composer install

script:
  - $TRAVIS_BUILD_DIR/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
  - $TRAVIS_BUILD_DIR/bin/phpcs -p --report=full $TRAVIS_BUILD_DIR/sites/all/modules/custom
```

**Comment by BanzaiMan** [comment]
Is this not a variation of #8082?

**Comment by BanzaiMan** [comment]
Though a tad different. 😬

**Comment by MorpheusXAUT** [comment]
@BanzaiMan it seems similar, although we are still seeing the issue with no background tasks or other processes running - our last build stage executes a shell script that, as a first step, checks whether the branch name matches `dev`. If it doesn't, it terminates with a call to `exit 0`, which has worked fine for the last months until the update.

Not sure if there's any other background tasks we would have to stop - switching to `travis_terminate` as mentioned above worked as a workaround, but recent builds errored because `travis_terminate` was not found anymore.

**Comment by jrupp** [comment]
Is this being looked into? I don't want to be stuck running a deprecated environment forever.

**Comment by vraravam** [comment]
We are seeing the same exact issue here: https://travis-ci.org/github/getferdi/ferdi/jobs/772518179

As discussed up above, this has been "fixed" and "regressed" off and on. Can we try to keep this thread alive and find the root cause and fix it once and forever?
