### ISSUE TITLE
Builds stuck in "booting"

### ISSUE THREAD

**Issue by raulriera** [travis-ci/travis-ci#8908]
It seems the builds are stuck in `booting`, some of them are been in that state for over 30mins. Maybe related to the macOS capacity problems? https://www.traviscistatus.com

**Comment by BanzaiMan** [comment]
Do you have a build log URL that shows the problem you are describing here?

**Comment by raulriera** [comment]
It just passed https://travis-ci.org/Shopify/FunctionalTableData/builds but you can see from the last 3, that I even cancelled it at some point due to how long it was pending.

**Comment by BanzaiMan** [comment]
Builds can appear "stuck" for various reasons. Your org/account may have too many jobs running already, or your queue is full of Mac jobs waiting to run. Without looking at the queue when it is happening, it is difficult to say what the cause was. While it is not impossible, it is quite time consuming to reconstruct the queue state from logs, I am afraid.

**Comment by raulriera** [comment]
Thanks!

**Comment by tusharmath** [comment]
@BanzaiMan I am facing the same issue in this build — https://travis-ci.org/tusharmath/tusharmath.github.io/branches

**Comment by shubhra-agrawal** [comment]
@BanzaiMan Facing the same issue in this build - https://travis-ci.org/ElucidataInc/ElMaven/builds/412042344

**Comment by discordier** [comment]
Quote @BanzaiMan:
> Builds can appear "stuck" for various reasons. Your org/account may have too many jobs running already,

This brings me to, is there any way to see all jobs in my org/account aside from clicking through all of them? I fail to find any "list" showing me my "personal queue". Am I missing something?
