### ISSUE TITLE
Issues with the Status Page

### ISSUE THREAD

**Issue by Narretz** [travis-ci/travis-ci#9087]
Due to the current backlog build issue, I've checked the status page, and noticed some smaller issues:

- the numbers in the backlog and the diagram don't add up
![travis-status](https://user-images.githubusercontent.com/1153097/35043679-c846b14a-fb8d-11e7-984b-da79b603f9c8.png)

- when you click "View historical uptime", you go to a different page that has the tabs "Incidents" and "Uptime", but there's no link back to the main page. There's also no heading that tells you that you are on the historical page.

- in the "uptime" historical calendar view, you can see on which day there was an outage, but the day is not clickable - it should take you to the incident report for convenience

**Comment by BanzaiMan** [comment]
Thanks for the report.

1. We are missing data due to monitoring processes being down at some time during the time frame you mention. They are responsible for reporting metrics, and unfortunately we do not have them.
1. On the historical uptime page, I see the link back to "Current Status". Do you?
![travis_ci_status_-_uptime_history](https://user-images.githubusercontent.com/25666/35048138-399209b8-fb6a-11e7-81c7-90e93e4d766d.png)
1. This page is managed by a third party. I will pass your feedback to them.

Again, thank you for the report.

**Comment by Narretz** [comment]
1. Oh, that's always difficult. Maybe you can add a note that this data might be out of date
2. I see the link, but I would expect it  below the header, too
3. Cool! The overview page (with api, build processing etc) has the same issue - info about outage, but no link to incident

**Comment by BanzaiMan** [comment]
I'll also pass your feedback along with regards to the location(s) of the link back.

I'm closing this now, since there is no further action to take at this time.

**Comment by BanzaiMan** [comment]
Actually, these things might be customizable. We'll take a look in the future.

**Comment by BanzaiMan** [comment]
No updates.
