### ISSUE TITLE
The travis job is stalled.

### ISSUE THREAD

**Issue by wuhao5** [travis-ci/travis-ci#9102]
One of our build recent jobs was created but never get picked up and running [link](https://travis-ci.org/google/EarlGrey/builds/33062602). We have tried to cancel and restart a few times but no luck. Would you guys be able to take a look and see if there is an availability issue or a quota issue?

Thanks!

**Comment by BanzaiMan** [comment]
The link seems invalid. Please double check.

**Comment by iphydf** [comment]
https://travis-ci.org/google/EarlGrey/builds/330626029 (it was missing a 9 at the end)

**Comment by mhinz** [comment]
See https://www.traviscistatus.com/incidents/mc9x2wmpnvhg. There were issues we the Mac builds that are resolved now.

Due to that the macOS backlog grew quite a bit and now needs some time to get back to the normal level. Check `Backlog macOS Builds for Open Source projects` on [traviscistatus.com](https://www.traviscistatus.com).

**Comment by BanzaiMan** [comment]
These are not stalled. They are waiting for their turns on our Mac infrastructure, which is presently overwhelmed most of the time.

**Comment by jay** [comment]
> These are not stalled. They are waiting for their turns on our Mac infrastructure, which is presently overwhelmed most of the time.

How long is the expected wait? We have Mac builds that haven't been starting for a while now. For example curl/curl#2258 it was like 12 hours and they haven't run.
