### ISSUE TITLE
Rmarkdown rendering fails on r-release with weird bindrcpp error

### ISSUE THREAD

**Issue by hughjonesd** [travis-ci/travis-ci#9205]
see https://travis-ci.org/hughjonesd/huxtable/jobs/339184075 ...

The error message is:

* creating vignettes ... ERROR
Quitting from lines 322-339 (huxtable.Rmd) 
Error: processing vignette 'huxtable.Rmd' failed with diagnostics:
function 'bindrcpp_RcppExport_validate' not provided by package 'bindrcpp'
Execution halted

And the relevant file is https://github.com/hughjonesd/huxtable/blob/master/vignettes/huxtable.Rmd 

I'm not sure how bindrcpp comes into the picture, but presumably it is some kind of rmarkdown issue. R-devel is working OK.

**Comment by BanzaiMan** [comment]
Please mention @craigcitro and @jimhester for R inquiries, as indicated in the build log. Thank you.

**Comment by jimhester** [comment]
You have a number of development packages in your package cache (https://travis-ci.org/hughjonesd/huxtable/jobs/339184075#L1067-L1068). I would recommend clearing it at https://travis-ci.org/hughjonesd/huxtable/caches, since you don't seem to be using any development versions in your .travis.yml currently.

**Comment by hughjonesd** [comment]
Thank you very much for this. Indeed, doing so fixed the problem.
