### ISSUE TITLE
job debug error: job not found (or insufficient access)

### ISSUE THREAD

**Issue by sinkcup** [travis-ci/travis-ci#9217]
I try to debug my organization project on travis-ci.org: https://travis-ci.org/openwrtio/openwrtio.github.io/builds/340525572

docs: https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode-via-API

but error:

```
{
  "@type": "error",
  "error_type": "not_found",
  "error_message": "job not found (or insufficient access)",
  "resource_type": "job"
}
```

**Comment by BanzaiMan** [comment]
As documented in https://docs.travis-ci.com/user/running-build-in-debug-mode/#Restarting-a-job-in-debug-mode:

> This feature is available for private repositories and those public repositories for which the feature is enabled. To have the feature enabled for a public repository, please email us at support@travis-ci.com indicating which ones. Push access to the repository is also required.

This repository did not have the feature on, so your API call would fail. Furthermore, you were making the API call on the build rather than the job, so it would have failed even if the feature had been turned on.

I've revoked the token you inadvertently disclosed for security reasons. When you try again, please double check the new token, and take care to not reveal it again.

Thanks.

**Comment by BanzaiMan** [comment]
I've turned on the debug feature for the repository, by the way.

**Comment by sinkcup** [comment]
@BanzaiMan Thank you very much!
I have find the path of bin by "npm install".

![image](https://user-images.githubusercontent.com/4971414/36156775-0ae909b8-1113-11e8-9462-2dd0c8f4b05d.png)

**Comment by BanzaiMan** [comment]
Great to hear. Is there anything else left to do?

**Comment by sinkcup** [comment]
NO. Yes... because travis-ci not support github project "Deploy key", so I use "npm install gp-pages" to hack it... so I need debug mode to find where is "gh-pages" bin...

see #9213

**Comment by kuskmen** [comment]
@BanzaiMan I've come here and saw your comment and then I realized I need to mail to support. Went back to the page and I don't see the text you quoted, was it deleted? In any case we have a problem, if it was deleted and feature now does not require mail to support, issue is reproducing to me, if the mail is still needed I didn't see any guidelines for sending mail to support.

Anyway, is there specific form or should I say template that I need to fill in order to enable this feature for public repository?

Regards,
kuskmen

**Comment by kuskmen** [comment]
I’ve already got the feature enabled on by writing mail to support, however now the API returns to me acess denied which I assume is because travis does not have push access to that repository?

I saw travis in trusted oauth services in my account but to me it seems that everything is okay, am I missing something?

Regards,
kuskmen

**Comment by kuskmen** [comment]
@BanzaiMan , now I see that to be able to debug job I basically need to have push access to the repository, which I do and I still get access denied: https://github.com/kuskmen/DesignPatterns this is the repository, what I am doing wrong?

**Comment by BanzaiMan** [comment]
The build is currently running on travis-ci.org, so you’ll need to use the .org token and api.travis-ci.org as the endpoint.

**Comment by kuskmen** [comment]
Seems that it is working now, good to have such troubleshoot stuff somewhere :/
