### ISSUE TITLE
Build stuck on old commit

### ISSUE THREAD

**Issue by ajdavis** [travis-ci/travis-ci#9255]
My project Motor is stuck on a 3-year-old commit, around the time I deleted .travis.yml from my repo:

https://travis-ci.org/mongodb/motor

My most recent commit to Motor was today, when I restored .travis.yml to the repository. I've verified the integration webhook has a green checkmark in Motor's integrations settings on GitHub, and that "Build pushed branches" is turned on in the settings. Nevertheless, the project's Travis page shows an ancient commit.

How can I make Travis fetch and build HEAD now?

**Comment by BanzaiMan** [comment]
In https://travis-ci.org/mongodb/motor/requests, you see that many build requests were rejected because the repository settings were such that we only accept those with `.travis.yml` was present.

I see that you have added it and a build ran. https://travis-ci.org/mongodb/motor/builds/344513584

I’m closing this now.

**Comment by ajdavis** [comment]
Correct, thanks. Sorry for the spurious ticket.
