### ISSUE TITLE
Cannot clone METADATA.jl with Julia v0.5 on Linux

### ISSUE THREAD

**Issue by galenlynch** [travis-ci/travis-ci#9264]
@tkelman, @ninjin, @staticfloat, @simonbyrne

I am trying to build my package with TravisCI for the first time in many months, and am no longer able to do so on Julia v0.5. If I go to builds that previously passed and try to build them, I get this error:

`ERROR: GitError(Code:ERROR, Class:Net, SSL error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)`

An example of this error can be found [here](https://travis-ci.org/galenlynch/OpenEphysLoader.jl/jobs/236698357).

I do not get this error in v0.6 linux, or on v0.5 mac.

**Comment by simonbyrne** [comment]
@aviks Is this related to the problem you were having?

**Comment by staticfloat** [comment]
This is because GitHub [recently updated](https://githubengineering.com/crypto-removal-notice/) their HTTPS ciphersuite to only support TLS 1.1+.  See [this discourse page](https://discourse.julialang.org/t/pkg-update-error-base-libgit2-test-fails/9272/6) for more details.  The long and the short of it is; we don't have any plans to release a new version of 0.5 that has an updated libgit2 that would support these newer TLS protocols, so the official advice is to upgrade to Julia 0.6+.

**Comment by galenlynch** [comment]
ok, thanks for the quick response!

**Comment by bghannad** [comment]
Hello everybody, is there anyway around it to use the Julia version 0.5 and add packages ?
I have some super important packages that are just working with v 0.5 and I can not give up on them :/

**Comment by aviks** [comment]
You can try building a version of 0.5 with an updated OpenSSL yourself.

**Comment by uripatish** [comment]
Hey @bghannad , I faced a similar problem, and downloading the packages manually and extracting them to the ~/.julia/v0.5 directory did the trick for me. Hope this might help.
