### ISSUE TITLE
Travis failing on Julia CI

### ISSUE THREAD

**Issue by sbromberger** [travis-ci/travis-ci#9271]
ping @ninjin @tkelman @staticfloat @simonbyrne

See https://travis-ci.org/JuliaGraphs/LightGraphs.jl/builds/346345919

```
$ julia -e 'versioninfo()'
WARNING: Error during initialization of module LinearAlgebra:
ErrorException("could not load library "libopenblas64_"
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/travis/julia/bin/../lib/julia/libquadmath.so.0)")
┌ Error: Error during initialization of module CHOLMOD
│   exception =
│    could not load library "libcholmod"
│    /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.23' not found (required by /home/travis/julia/bin/../lib/julia/libquadmath.so.0)
...
```

**Comment by ninjin** [comment]
Did we move to a newer libc on one of our build machines?

**Comment by staticfloat** [comment]
Oh boy.  This freaked me out good.  I just traced through the whole build system, trying to figure out where these binaries were appearing from, because on the buildbots we definitely constrain the glibc version, and indeed, if you download the latest version that was just built by its versioned URL, it works just fine:
```
$ curl -L 'https://julialangnightlies.s3.amazonaws.com/bin/linux/x64/0.7/julia-79c7bdd9ec-linux64.tar.gz' -O
$ tar zxf julia-79c7bdd9ec-linux64.tar.gz
$ $ ldd -v -r julia-79c7bdd9ec/lib/julia/libquadmath.so.0
        linux-vdso.so.1 =>  (0x00007ffd77dd0000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f5589511000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f558917d000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f55899d5000)

        Version information:
        julia-79c7bdd9ec/lib/julia/libquadmath.so.0:
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.10) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
                libm.so.6 (GLIBC_2.2.5) => /lib64/libm.so.6
        /lib64/libm.so.6:
                libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
```

However, doing this to the `-latest` version of Julia shows something _different_:
```
$ curl -L 'https://julialangnightlies.s3.amazonaws.com/bin/linux/x64/julia-latest-linux64.tar.gz' -O
$ tar zxf julia-latest-linux64.tar.gz
$ ldd -v -r julia-79c7bdd9ec/lib/julia/libquadmath.so.0
julia-79c7bdd9ec/lib/julia/libquadmath.so.0: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by julia-79c7bdd9ec/lib/julia/libquadmath.so.0)
julia-79c7bdd9ec/lib/julia/libquadmath.so.0: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by julia-79c7bdd9ec/lib/julia/libquadmath.so.0)
        linux-vdso.so.1 =>  (0x00007ffdfdb57000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fe0afdaf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fe0afa1b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe0b0273000)
symbol memcpy, version GLIBC_2.14 not defined in file libc.so.6 with link time reference        (julia-79c7bdd9ec/lib/julia/libquadmath.so.0)

        Version information:
        julia-79c7bdd9ec/lib/julia/libquadmath.so.0:
                libc.so.6 (GLIBC_2.3) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.14) => not found
                libc.so.6 (GLIBC_2.10) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
                libm.so.6 (GLIBC_2.23) => not found
                libm.so.6 (GLIBC_2.2.5) => /lib64/libm.so.6
        /lib64/libm.so.6:
                libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib64/libc.so.6
        /lib64/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
```

I could not think of a reason why these two files would be different; the two steps to upload each file are [run one after another](https://github.com/JuliaCI/julia-buildbot/blob/bfe887df449555e58c37236e42ea8a08635aa045/master/package.py#L146-L158), and indeed, even the [buildbot logs](https://build.julialang.org/#/builders/43/builds/819) show this going off without a hitch (see steps 18 and 19).  Looking at the logs in Cyberduck showed the versioned file uploaded at 1:32 AM this morning, and the `-latest` file uploaded at 1:33 AM.  And yet they were different, checksummed differently, and linked to different `glibc` versions.

My worst fear at this point was that we had somehow been targeted by some kind of insane hacker that had gained access to our infrastructure and was replacing our `-latest` binaries with something nefarious, and they had been sloppy when recompiling something.  With a leaden stomach and not a little resignation, I began diffing the two tarballs to see what was different.

To my surprise, I found some familiar, yet incorrect paths embedded within some of the binaries; in particular, one contained the string `/buildworker/worker/build_ubuntu64/build/doc/make.jl`.  This flicked a lightbulb on within my head and immediately flooded my body with relief; the Ubuntu auxilliary buildbots (created not to have their products uploaded, but rather to test and make sure Julia still builds on a slightly different distro than our typical CentOS 6 buildbots) have paths like that, and they were recently moved from an OpenStack host to live instead on our nanosoldier computer.  However, how did this particular binary end up on our AWS server?

It turns out the buildbot configuration has had a race condition hidden within it for the past couple of years; the way file uploads work is that the buildbots finish packaging a tarball, then they upload it to the buildmaster, and the buildmaster uploads it to AWS, so as to avoid the buildbots needing to have the AWS secret keys deployed upon them.  It just so happens that this morning, the CentOS 6 main packager finished its job, and uploaded its file to the build master, which began to dutifully upload the build product up to AWS.  Immediately after, however, the Ubuntu builder finished its job, and because of [the lack of a conditional](https://github.com/JuliaCI/julia-buildbot/pull/70), uploaded its own tarball to the build master (but correctly did not then attempt to upload the tarball to AWS).  However, since the CentOS 6 job was still running, it then took the next tarball and uploaded it to AWS as the `-latest` version.

This has never happened before because our OpenStack builders were significantly slower than the nanosoldier builders, so we have never happened to have an Ubuntu builder finish and transfer its build product (which is named the same as the CentOS 6 build product because they are the same architecture) over to the buildmaster within the 16s window that exists between one upload beginning and the next beginning.

The fix is [comically simple](https://github.com/JuliaCI/julia-buildbot/pull/70); don't upload binaries to the buildmaster that we don't intend to upload the AWS.  At least I'm wide awake now.

**Comment by staticfloat** [comment]
Oh, also I've manually replaced the bad `-latest` version, so this should be working again.

**Comment by BanzaiMan** [comment]
Could you confirm that this could be closed?
