### ISSUE TITLE
Generating a Travis CI Token from a GitHub Token

### ISSUE THREAD

**Issue by asapferg** [travis-ci/travis-ci#9273]
(duplicate of https://github.com/travis-ci/travis.rb/issues/584)

Question on API V3:

With Travis CI API V2, a Travis CI token can be generated using a GitHub token with a request detailed in the [API V2 documentation](https://docs.travis-ci.com/api/#authentication).

In the [API V3 documentation](https://developer.travis-ci.org/authentication), it states that the Travis CLI should be used to generate a compatible Travis CI token from a GitHub token.

Is it possible to generate an API V3 Travis CI token through a direct HTTP request, rather than through the CLI?

**Comment by iriberri** [comment]
Unfortunately, API V3 doesn't have an endpoint to exchange a GitHub token by a Travis API token yet, and we recommend to route this specific "authentication" request to API V2 to get your token programmatically in the meantime. This is can be done since API tokens are valid for both V2 and V3.

To route this request to API V2, you need to drop the `Travis-API-Version: 3` header and add the `Accept: application/vnd.travis-ci.2+json` one to your request to `auth/github`.

Since a couple weeks ago, it's also possible to get your API token from your profile at https://travis-ci.org/profile or https://travis-ci.com/profile.

Hope this helps!

**Comment by mukeshsolanki** [comment]
@iriberri switching to api V2 does not work for me. I get a status code 200 but a html page in response

**Comment by iriberri** [comment]
@mukeshsolanki can you please send us further details about the request you're sending to the API to support@travis-ci.com? We'd be glad to take a look at your case :-) Thanks!
