### ISSUE TITLE
Single after_success callback after *all* builds

### ISSUE THREAD

**Issue by rkistner** [travis-ci/travis-ci#929]
It would be useful to be able to execute some script only if _all_ builds in the build matrix passed. The use case I have in mind is to perform some release process (such as publishing a gem) if all of the builds passed (also see my post in the mailing list [here](https://groups.google.com/forum/?fromgroups=#!topic/travis-ci/zYXTcipm0WA)).

Currently the best (simplest) solution is to configure the script to run in a single build configuration, regardless of the result of the other configurations.

If something like this is implemented, there will be some complexity regarding the environment that the release script runs in. For example, does one of the build workers wait until the rest finished running, or does a new worker get started just for the release process?

**Comment by joshk** [comment]
Hi All

It's been far too long since my last comment.

We are in the planning stages for what we have termed 'Build Stages'. This will allow for pipelined-ish job groups.

We are putting together the feature plans for this year, with this work likely to fall in Q1/Q2 next year.

I will also be adding this to https://next.travis-ci.com in the coming weeks.

Thanks

Josh

**Comment by BanzaiMan** [comment]
To an extent, this issue would be resolved by a recent beta feature, Build Stages. You can find more about this feature in https://docs.travis-ci.com/user/build-stages, and the ongoing discussion in https://github.com/travis-ci/beta-features/issues/11. (Be sure to read the entire issue before adding your comments; some of your concerns are probably already discussed in the issue.)
