### ISSUE TITLE
traviscistatus.com is not findable because noindex is set

### ISSUE THREAD

**Issue by Narretz** [travis-ci/travis-ci#9295]
The source for https://traviscistatus.com contains `<meta name="robots" content"noindex,nofollow" />` which means Google etc won't index the page and if you search "travis status" on Google you won't find this page directly which defeats the purpose.

**Comment by pzrq** [comment]
@Narretz Do you think it might be by design so https://twitter.com/traviscistatus which links to https://www.traviscistatus.com comes up first?

<img width="704" alt="screen shot 2018-03-10 at 7 21 12 am" src="https://user-images.githubusercontent.com/1217010/37228129-a59230ec-2433-11e8-9f1d-d807e93b8251.png">

**Comment by BanzaiMan** [comment]
We've turned off the `<meta>` tag.
