### ISSUE TITLE
Another permission denied 

### ISSUE THREAD

**Issue by boelle** [travis-ci/travis-ci#9321]
I did the google dance and i came up empty

https://travis-ci.org/boelle/stuff-projects/jobs/351695594

i know that it cant get permission on my python script but i have no clue on how to give travis access.

I only run windows and i use githubs windows client to upload, but for this simple project i edit from githubs web interface ( i know i will get flag for this part)

but how do i get arround this one?

the script is intended for the raspberry pi as a thermostat controlling an electrical heating panel.

it will get temp commands via email and if internet connection fails it will default to a static temp
also there is provission for a swtich to activate a bake mode

**Comment by boelle** [comment]
i used sudo in front of the script command and it seems to work, but not sure if that is the 100% correct way to do it?

**Comment by BanzaiMan** [comment]
Hi, there.

The problem here is that `pinkest.py` does not have the execute permission. You “fixed” it not by `Sudo`, but by calling the Python interpreter `python` to execute it.

By using `Sudo`, however, you are now executing the `root` user’s `python`, not one that is defined with the `pyhton` value in `.travis.yml`. You can drop `Sudo` to fix the problem.

Alternatively, you can fix [the shebang line](https://github.com/boelle/stuff-projects/blob/c662afdc2edb9bc613cc6aec574395833cfc3dc7/pinest.py#L1) to read `#! /usr/bin/env pyhton` and add the execute bit.

At any rate, this is not a problem on our side.

**Comment by boelle** [comment]
btw, are there a support forums of some sort?

i need help/guidinace on how to test/emulate a raspberry pi
