### ISSUE TITLE
Unable to upload multiple assets to the same github release

### ISSUE THREAD

**Issue by warrn** [travis-ci/travis-ci#9360]
When I build an application, I want to be able to cross compile my program to other operating systems. You have already built this functionality with gimme, allowing me to build for osx and windows in addition to linux. 

However, when I'm trying to deploy the assets to github releases, what inevitably happens is the first completed build creates a release entry and uploads the asset, followed by the second and third finished builds attempting to do so and failing because I've designated all of the releases to share the same tag_name. The desired result would be all three assets residing in the same release.

To work around this issue, I would have to instead create 3 separate releases for the same build, which is undesirable because it creates 3 separate links to the same commit where the only difference is platform.

Octokit offers functionality for uploading assets to previously existing releases, so the logic can be added to upload assets to previously existing releases should the required fields match. I imagine this would make continuous deployment significantly easier for projects that compile and provide binaries for multiple platforms on github.

[Here](https://travis-ci.org/nelsonw2014/cicd-example/builds/355192002) is my build which I'm trying to currently upload all assets to the same release and failing for obvious reasons. If logic could be created for this use case it would definitely be appreciated.

Thanks!

**Comment by BanzaiMan** [comment]
I find this error rather strange. The error is being raised from this line: https://github.com/travis-ci/dpl/blob/v1.9.1/lib/dpl/provider/releases.rb#L121

```ruby
 api.update_release(release_url, {:draft => false}.merge(options))
```

GitHub API is complaining that the release already exists, but that is precisely the point of `#update_release`.

**Comment by nelsonw2014** [comment]
Okay, so it appears the fix is to set the TRAVIS_TAG env var instead of setting the tag_name inside the deployer. I fixed it in [this build](https://travis-ci.org/nelsonw2014/cicd-example/builds/355623687). 

Maybe modifying the documentation on github releases to specify this work around is in order? Or alternatively, in the deployer you can rely tag_name instead of the TRAVIS_TAG env var?

**Comment by BanzaiMan** [comment]
That is intriguing. So, GitHub lets you update the release if it knows about a tag, but not if you do not specify one.

It appears to be a variation on this theme we mention in https://docs.travis-ci.com/user/deployment/releases/:

> GitHub Releases uses git tags. If the build commit does not have any tags, one will be created in the form of `untagged-*`, where `*` is a random hex string.

**Comment by nelsonw2014** [comment]
That makes sense, but the issue I see is that there's two places where you can supposedly specify the same data, aka the tag. One is TRAVIS_TAG and the other is tag_name. Octokit uses tag_name, and the deployer automatically sets tag_name to the value of TRAVIS_TAG if it is specified. But you can also manually set tag_name using tag_name in the deployer. You shouldn't be able to set the same data from two separate places, nor should there be two separate locations to store what supposedly must be the same data.

**Comment by BanzaiMan** [comment]
`TRAVIS_TAG` is set if the commit has a tag. In general, this is what the Releases deployment provider expects, and this is stated in the docs.

There is a legitimate use case where a non-tagged commit should be able to trigger a release, and in such cases it is useful to allow tags to be either set on the fly (`git tag …`) or via the `tag_name` option, which will be passed to GitHub API client.

We can add this potential pitfall in the docs (when `on.tags: true` is _not_ set), though.

**Comment by nelsonw2014** [comment]
In such a case as you specified now, if you do use tag_name instead of using `git tag ...` or TRAVIS_TAG, the deployer ignores you setting that value while octokit doesn't. I would suggest it would make sense to remove that ability to set it, or to make the deployer aware of it. If neither action is taken, then there exists situations where people set the tag_name and fall down this pitfall. While documentation is helpful, tooling should also guide usage.

**Comment by BanzaiMan** [comment]
> I would suggest it would make sense to remove that ability to set it, or to make the deployer aware of it.

Could you clarify this sentence? There are a few pronouns in it, and it is not clear to me what you are suggesting.

> While documentation is helpful, tooling should also guide usage.

I am not sure what you mean by this. How do you suggest we achieve this goal, when the documentation is the primary means by which the user learns how to use the tool? (Yes, `dpl` is available as a standalone tool, but the vast majority of users do not use it that way.)

**Comment by nelsonw2014** [comment]
I apologize for my confusing writing. I'm saying you should either have deployer recognize the usage of tag_name and use it similar to TRAVIS_TAG, or you should not allow the user to set the value of tag_name. As it stands right now, octokit is recognizing a modified tag_name, but deployer is not, so both tools are using different sources of truth for what tag is being deployed.

Requiring the tooling to not allow this pitfall instead of just documenting the pitfall is a more preferable outcome.

**Comment by BanzaiMan** [comment]
So, I think we can add some messages to indicate how we are setting the `tag_name`, which is eventually sent to GitHub via the API client. Your "use-driven guidance" seems really difficult to achieve in this context, but I think that will help.

Clear documentation, of course, is desirable, independent of such messages.

**Comment by nelsonw2014** [comment]
That should be sufficient. Thank you

**Comment by polarathene** [comment]
This is the issue I encountered and struggled with for the past day until understanding [how to resolve getting assets from multiple jobs to a single draft release](https://github.com/travis-ci/travis-ci/issues/10230#issuecomment-474267634).

Is there any reason that `tag_name` should not be a final fallback?(it'd remove the need for a workaround in the usecase/solution I linked to) 

If a commit has no tags associated to it, the first two checks against current releases `tag_name` values will ignore draft releases, despite the fact they can have a valid `tag_name` set, and thus publish new draft releases(untagged tag, or whatever was provided in `tag_name` for the deploy config).
