### ISSUE TITLE
New Travis notification email layout feedback

### ISSUE THREAD

**Issue by cbeams** [travis-ci/travis-ci#9373]
Greetings all. Longtime @travis-ci user and fan here, and that's why I'm pausing to report that I find the new notification email layout unhelpful.

## Before

Clean, concise and informative:

![image](https://user-images.githubusercontent.com/301810/37763421-50253ba0-2dbf-11e8-9cd2-2d5f4db9bd82.png)

## After

Poor use of vertical and horizontal real estate, superfluous visual elements, non-idiomatic treatment of Git commit comments, including center alignment and forced line breaks that hurt readability:

![image](https://user-images.githubusercontent.com/301810/37763860-70881b0a-2dc0-11e8-9320-86b49d5a6510.png)

Please consider reverting this layout change, or further revising it to return to the previous utilitarian values. Form should follow function, especially where project-critical infrastructure is involved. Travis is plumbing, and while that doesn't mean that its notification emails need to be ugly, they certainly shouldn't waste users' time in an attempt to be pretty.

Thanks for your consideration.

**Comment by scothis** [comment]
The center alignment is heinous, particularly for the commit message.

**Comment by ajashton** [comment]
My email client blocks images by default, and the alt-text in that case is a bit wild (several of the decorative images don't need alt-text at all):

![screenshot from 2018-03-22 09 48 08](https://user-images.githubusercontent.com/126952/37774612-11f8e776-2db7-11e8-836d-5d16581d1173.png)

Previous layout worked wonderfully without images:

![screenshot from 2018-03-22 09 53 02](https://user-images.githubusercontent.com/126952/37774611-11e1057a-2db7-11e8-9c29-e3fee4e43ad5.png)

**Comment by BanzaiMan** [comment]
Thanks for the feedback, everyone! We will work on further improvements. Stay tuned!

**Comment by enebo** [comment]
![travisci](https://user-images.githubusercontent.com/19819/37832789-a022ab48-2e77-11e8-8aeb-88517680d2ab.png)

I am going to walk through what I recall being my experience with the new format in hopes it helps show anything which can help this new format for UX.

So when I got this new format email the build in question had an error.  The changeset text is about the only thing which appears be a link in this email as at a glance it is all text.  For some reason my knowledge of the text I was looking for from the old screen was not in my short-term memory.  Went to click on the Error 'X' graphic.  Nope just an image.  Looked below, "Nope that text is gray, who makes gray links?".  I then clicked around reorienting which each of text may be links and where they go to.  Finally, back to the gray text.  Got it.

From now on I will realize the "Build xxx" will be a link to the specific build.  Writing it probably sounds obvious but my experience of gray controls being disabled controls in UI; this really threw me off.  The lack of affordance or some visual cue differentiating plain text from links is off putting even when I suspect it will go somewhere.  If you were a brand new user receiving your first email you might just think this is a big formatted text email with one link to the changeset (I guess that is rare in the modern web but it used to be more common)?

I agree with others that I do not normally run browser maximized so squishing things horizontally so a background image looks nice is less desirable than a design which will likely put it all on one screen.  My screenshot does not show the full value but when we have large multi-paragraph commit messages  not getting 80-110 column text output will be less desirable.  In my default config it cut columns at 43 chars.  Old one was able to display to 80 columns (more on this at bottom) on my display.

Finally text like 'jruby / jruby' going to travis-ci vs github?  That seems ambiguous since that is how the project is named on both web sites.  The little usb-like-form branch icon on the line below really is not enough in my opiinion to differentiate between the two lines.  I did not recall it was the branch icon until I wrote this up (another thing probably obvious in retrospect - maybe tooltip it).

Not related to the old or the new format but I will throw it in as bonus feedback.  red/green is a nice metaphor for many people, but it is pretty horrible if you are color blind.  Having error being gray no doubt makes that even more confusing. [note: I am not color blind so this does not affect me]

I hope this did not come off as thinking I hate the new format.  As an older person I appreciate the larger text.  I think between old and new if you could get back to a display which gives more horizontal real estate to the frame; you can get closer to being as wide the old text format for commits msgs but still be a larger font.

**Comment by headius** [comment]
Errored build link being grey is a really confusing choice. At least fix that! 😀
