### ISSUE TITLE
Build is timing out due to no log output

### ISSUE THREAD

**Issue by kanehara** [travis-ci/travis-ci#9475]
Several of our builds have timed out due to the log not outputting:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

We are able to run the scripts manually with no issue.  Builds in the past with the same Travis build config were passing fine.

Failing build reference: https://travis-ci.com/reviewtrackers/rtx-app/builds/70560056?utm_source=github_status&utm_medium=notification

**Comment by dongcai** [comment]
I got the same issue. My failed build is here:
https://travis-ci.org/dongcai/react-redux-semantic-ui/jobs/368770931
It hung on here:
```
$ cross-env NODE_PATH=api NODE_ENV=test jest api
 PASS  api/__tests__/api-test.js
```
It's supposed to run api/actions/__tests__/...
It works fine locally, like:
```
 PASS  api/actions/__tests__/widget-update-notest.js
 PASS  api/actions/__tests__/loadInfo-test.js
 PASS  api/actions/__tests__/widget-load-notest.js
 PASS  api/__tests__/api-test.js

Test Suites: 4 passed, 4 total
Tests:       14 passed, 14 total
Snapshots:   0 total
Time:        2.015s
Ran all test suites matching /api/i.
```
The error message from Travis-Ci does not help too much. Any suggestions? Thanks!

**Comment by dongcai** [comment]
Finally, I figured out my issue. It's related to a third-party module named 'sinon', which is used in some test cases. The version was set to ^4.0.1. Somehow on my local, it had worked fine, but on Travis-CI, it did not. It could be the difference between `npm install` vs `yarn install` causing different version installed. I found that if I installed an exact version of 4.01 on my local, I could reproduce the issue I had on Travis-CI. And I fixed it by setting the 'sinon' version to be ^4.5.0.
@kanehara you may check whatever dependencies you have upgraded since last time it works.
