### ISSUE TITLE
Maven seemingly broken recently due to varying IP addresses

### ISSUE THREAD

**Issue by ToxicBakery** [travis-ci/travis-ci#9555]
When publishing to maven central it appears that the IP address is rotating per upload causing gradle based builds to fail with multi module projects. Looking at sonatype I can see multiple staging repositories generated from a single build and each repository appears to have been uploaded from a different IP address. Sonatype appears to require a consistent upload IP address for the duration of uploads for a multi part project as mentioned here 

[OSSRH-37302](https://issues.sonatype.org/projects/OSSRH/issues/OSSRH-37302).
>a new repository is created whenever there's a new combination of username + IP address + groupId

---

I have not run into this problem in the past so intitially I thought that gradle may be to blame as my last release build was under gradle 4.0 while the problem appeared after switching to 4.6. Rolling back to gradle 4.0 produced generally similar results as 4.6 leading me to assume the failure is on sonatypes until I found the issue describing the IP address requirement. I now believe the issue is on the side of Travis CI and presumably some recent infrastructure change. 

If my assertion is accurate, does a work around exist to force a specific IP for docker instances?

[Example Build - Job 373318000](https://travis-ci.org/ToxicBakery/kfin-state-machine/jobs/373318000)

Examples of what I see in sonatype:

Multiple uploads all from the same build
![screenshot from 2018-04-30 22-52-50](https://user-images.githubusercontent.com/1614281/39459767-d76df978-4ccb-11e8-8e44-c012caa2ed29.png)

Examples of partial project uploads with varying ip addresses:
![screenshot from 2018-04-30 22-55-55](https://user-images.githubusercontent.com/1614281/39459774-e4251110-4ccb-11e8-85ef-37d311676586.png)

![screenshot from 2018-04-30 22-56-12](https://user-images.githubusercontent.com/1614281/39459779-edd501a2-4ccb-11e8-875b-ed5aac32bcdb.png)

![screenshot from 2018-04-30 22-56-50](https://user-images.githubusercontent.com/1614281/39459780-efcbba28-4ccb-11e8-9ffe-a99bd6cf8bc7.png)

**Comment by ToxicBakery** [comment]
Looking back it seems my original tag used the travis jdk `oraclejdk8` image while my 2.0 tag is now using docker. I rebuilt my 1.0 tag twice and it appears to upload to sonatype nominally. I'll give it a go not using docker however it appears that this may be isolated to builds run inside docker which is confusing as a past travis ci issue (from 2013) mentioned all docker instances being run NAT to the same outbound IP however it's understandable if this has changed in 5 years.

**Comment by ToxicBakery** [comment]
This also appears to occur when using Android as the language so I can no longer deploy android libraries to maven central. The exact same issue, two modules produced four unique staging repositories on maven central due to parts of the upload coming from different IP addresses.

**Comment by ToxicBakery** [comment]
References to the issue on Nexus
https://groups.google.com/a/glists.sonatype.com/forum/?hl=en#!topic/nexus-users/zjYUZHrOjP4

Source reference
https://issues.sonatype.org/browse/OSSRH-6262

It seems the blame can be shared but it sucks that this used to work fine on Travis and plenty of blogs suggest using the maven-publish plugin for library uploads and this is now broken.

**Comment by meip** [comment]
I can also confirm that using the docker functionality on travis will somehow break the staging stuff. Even adding the `stagingProfileId` as suggested multiple times doesn't help.

We reverted this commit to make the build working again:
https://github.com/swisscom/open-service-broker/commit/db885dd3e46cf19cf064c04b2cbb4ec022473b3a#diff-354f30a63fb0907d4ad57269548329e3

I'm also not sure where the problem has to be nailed down further and this comment leads a bit into another direction since we use Gradle instead of Maven and it outlines a difference between the two very similar plugin names:
https://issues.sonatype.org/browse/OSSRH-40386?focusedCommentId=493561&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-493561

**Comment by ToxicBakery** [comment]
With the lack of communication from the Travis team, I gave up and migrated to CircleCI as it does not have the multiple outbound ip issue. I wish Travis would have announced this change as I imagine it causes issues for other services as well considering it's pretty unusual to hop IP addresses multiple times over a few seconds.

**Comment by leonard84** [comment]
Hm, I ran into the same problem. I does not seem to be restricted to docker.

**Comment by ToxicBakery** [comment]
Correct, usage of sudo also triggers the issue.

**Comment by BanzaiMan** [comment]
This seems like a variation of our load balancing solution, described here: https://blog.travis-ci.com/2018-07-23-the-tale-of-ftp-at-travis-ci

Something like a VPN _might_ help you. https://docs.travis-ci.com/user/common-build-problems/?utm_source=blog&utm_medium=web&utm_campaign=ftp_blog#ftpsmtpother-protocol-does-not-work

Assuming that it is a manifestation of the load balancing issue, I am closing this issue. If you believe otherwise, do let us know.

**Comment by joeha480** [comment]
@BanzaiMan How would I use the openvpn solution in an open source project? Doesn't this require a server to tunnel to?
