### ISSUE TITLE
Suggestion: upgrade linux environment to modern version

### ISSUE THREAD

**Issue by xsun2001** [travis-ci/travis-ci#9569]
The latest ubuntu LTS version is 18.04, but I notice that travis.ci is still using 14.04 or 12.04. It should not be a big problem, but I met a lot of trouble when configuring a modern c++ toolchain because of outdated os and outdated software package. It is my mistake that causes my build failing, but it is really not easy to make them work correctly. I do know that it is really head to upgrade so many travis.ci build nodes. However, I think it is necessary for you to stay with time. And if possible, I wondered how to config g++7, clang-6 and cmake 3.11 in a linux environment. I feel sorry for my poor English.

**Comment by qis** [comment]
@travis-ci It would be interesting to see a study on how many of your customers are forced to install modern versions of third party software.

**Comment by FibreFoX** [comment]
Already got posted :( with no progress sinde 2017
https://github.com/travis-ci/travis-ci/issues/5821

**Comment by DrTorte** [comment]
Hello,

We've recently released the Xenial image, and we have a dedicated category for it on the [Community Forums](https://travis-ci.community/c/environments/xenial). With other recent updates, such as migrating to VM based infrastructure only, we'll be able to provide more frequent OS updates.

As we're moving to the community forum rather than GitHub issues, I'll be closing this issue. We'll be glad to talk to you over on the forum though! 😄 

Thanks and happy building!
