### ISSUE TITLE
DLang: Several compiler versions failing to download

### ISSUE THREAD

**Issue by Abscissa** [travis-ci/travis-ci#9613]
I've just suddenly started getting failures to download several different D compiler versions (http 404):

https://travis-ci.org/mysql-d/mysql-native/builds/378472129

The (known) affected compilers are:
- dmd-2.071.2
- dmd-2.070.2
- dmd-2.069.2
- dmd-2.068.2
- ldc-1.0.0
- ldc-0.17.5
- ldc-0.17.1
- ldc-0.17.0
- gdc-4.8.5

There might be other versions not in my .travis.ym that fail as well.

Compilers that appear unaffected and still seem to work are LDC v1.1.1 and up, and DMD v2.072.2 and up.

Ping @MartinNowak and @wilzbach.

**Comment by wilzbach** [comment]
The problem looks to be that code.dlang.org was offline (the versions you list are those that don't come with a bundled dub) - there's already a fix for it: https://github.com/dlang/installer/pull/273
which uses a more stable mirror as a fallback.
Though it looks like that one hasn't been deployed yet :/
I will look into the deployment issue tomorrow.

**Comment by Abscissa** [comment]
It would be trivial for me to toss a dub binary up onto my own server and have my .travis.yml download it. It'd take me about ten minutes. Is there a way I can trick the installer script into not bothering to download dub? Or to opt-out of the installer script so I can use a custom-hacked version of it instead?

**Comment by wilzbach** [comment]
See also: https://github.com/vibe-d/vibe.d/pull/2160

I think I found the problem: http://code.dlang.org/download/LATEST points to 1.9.0, but the binary is not available on http://code.dlang.org/download
CC @s-ludwig

As mentioned dlang/installer#273 adds a backup to the automatically generated binaries (https://github.com/dlang/dub/releases) and I just managed to deploy the current master of https://github.com/dlang/installer to dlang.org/install.sh, so builds should hopefully stop failing.

> Is there a way I can trick the installer script into not bothering to download dub? 

Not at the moment. For old versions that ship without dub, it will always try to download dub because the Travis test command is "dub test".

>  Or to opt-out of the installer script

Don't select D as a language? There's `generic` (see https://github.com/travis-ci/travis-ci/issues/4895)
Though now you shouldn't need to do so.

>  so I can use a custom-hacked version of it instead?

If you still experience issues, you can also try to use a patched version of the installer, like e.g. Vibe.d is doing:

https://github.com/vibe-d/vibe.d/blob/master/.travis.yml#L64

**Comment by wilzbach** [comment]
Urgh it's still failing because code.dlang.org/download/LATEST is proposing 1.9.0, but used to promote e.g. v1.8.0 before.
@s-ludwig maybe it's time to retire the downloads from code.dlang.org (or at least from the install script)?
Anyhow I just sibmitted https://github.com/dlang/installer/pull/324 and will redeploy once this one has been merged.

**Comment by wilzbach** [comment]
> will redeploy once this one has been merged.

Deployed and seems to be working (tested with a previously failing vibe.d job - https://travis-ci.org/vibe-d/vibe.d/jobs/377195968)

**Comment by s-ludwig** [comment]
Yes, I'd also be for retiring the code.dlang.org based downloads. Ideally, a separate dub archive/installer would be hosted on downloads.dlang.org, so that it has the same sources of failure as the compiler downloads.

**Comment by wilzbach** [comment]
> Ideally, a separate dub archive/installer would be hosted on downloads.dlang.org, so that it has the same sources of failure as the compiler downloads.

Not sure that's worth spending time on.
Both downloads.dlang.org as well as GitHub Releases use S3 ;-)
Also it's a bit harder to restrict access to only individual files for the S3 (especially if one isn't the admin of it), so I think for now the GitHub Releases seem to work out fine.
We could even think of hooking AppVeyor up to build the Windows binaries there automatically too. For DScanner and DCD I even use Travis directly with Wine. That might work too ...

**Comment by Abscissa** [comment]
stupid pretend-bugs-magically-disappear-on-their-own-bot

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!
