### ISSUE TITLE
Setting go version to "1.10.x" installs 1.10.1 even when 1.10.2 is already available

### ISSUE THREAD

**Issue by cezarsa** [travis-ci/travis-ci#9652]
Example in https://travis-ci.org/tsuru/tsuru/jobs/382649678.

.travis.yml is configured with:

```
go:
  - 1.10.x
```

The build output shows:

```
$ go version
go version go1.10.1 linux/amd64
```

Go `1.10.2` was released May 1st, is there a manual process necessary to bump `.x` to the latest patch? Interestingly calling `gimme 1.10.x` directly installs `1.10.2` correctly.

**Comment by myitcv** [comment]
I'll also note that `1.x` picks up the `go1.11beta` release which I don't think is right:

```
$ GIMME_OUTPUT="$(gimme 1.x | tee -a $HOME/.bashrc)" && eval "$GIMME_OUTPUT"
go version go1.11beta1 linux/amd64
```

https://travis-ci.org/myitcv/x/builds/398586790?utm_source=github_status&utm_medium=notification

Happy to file another issue if this is unrelated.

**Comment by nickw444** [comment]
+1 also having the issue with `1.x` picking up `go1.11beta1`

Build here: https://travis-ci.org/nickw444/miio-go/builds/398504110

**Comment by dmitshur** [comment]
> `1.x` picking up `go1.11beta1`

This was issue https://github.com/travis-ci/gimme/issues/152 in `gimme`. It has recently been resolved. However, as I understand, what's remaining is for Travis CI to update to a newer version of `gimme` (and for `gimme` to cut a newer release, since v1.5.0 is its current latest).

> I'll note here that stable does exhibit the correct behaviour, so I'll switch to that.

@myitcv Is `stable` documented anywhere? I'm not seeing it at https://docs.travis-ci.com/user/languages/go/.

**Comment by dmitshur** [comment]
I believe this issue is resolved as of https://github.com/travis-ci/travis-build/pull/1442#issuecomment-413131247. @cezarsa Please restart your builds and confirm, then feel free to close this issue if so.

**Comment by BanzaiMan** [comment]
Closing this optimistically.
