### ISSUE TITLE
Variable encryption as a collaborator

### ISSUE THREAD

**Issue by 1138-4EB** [travis-ci/travis-ci#9670]
I am a member, but not the owner, of an organization. There is a repo in the organization where a Team has Admin level access. I am a member of the team.

I am trying to reproduce the same steps that I use in my own repos in order to encrypt dockerhub credentials:

```
gem install travis --no-rdoc --no-ri

git clone $REPO ./tmp-repo && cd tmp-repo

travis login --org --auto
travis encrypt DOCKER_USER=$USERNAME --add
travis encrypt DOCKER_PASS=$PASSWORD --add
```

Variables are apparently encrypted and properly added to the `.travis.yml` file. During the build, something is decrypted: https://travis-ci.com/ghdl/docker/builds/74583180#L388-L389 But the content is not correct, because the login fails: https://travis-ci.com/ghdl/docker/builds/74583180#L7858-L7859

I'd like to know if this is a supported use case, or if variable encryption can only be done by owners of the organization.

**Comment by iriberri** [comment]
Hi @1138-4EB, thanks for reporting this issue!

As you mention, according to the logs for that build it doesn't seem like the decryption is working.

From the commands you shared with us, this could be caused by (at least) two different issues:
* The Travis CLI is encrypting the value against travis-ci.org, which would make it impossible for travis-ci.com to decrypt it
* The Travis CLI is encrypting the value against a fork of the repository, instead of the target repo (in this case, `ghdl/docker`.

Travis encrypts/decrypts these values by using the keys of the project in Travis CI, which is different for each repository. This is why running this against travis-ci.org instead of travis-ci.com (or vice versa, if the repository exists in both infrastructures for some reason), or running it for a fork of the project wouldn't work, since all these repos are technically different.

To sort this out, and in this case where you're building in travis-ci.com, I recommend:

```
travis logout --pro
travis login --pro
travis encrypt DOCKER_USER=$USERNAME --add --pro -r ghdl/docker --debug
travis encrypt DOCKER_PASS=$PASSWORD --add --pro -r ghdl/docker --debug
```

The `--pro` argument will route the request to travis-ci.com, and the `-r` argument will specify the name of the project that should be use for encryption, in case the CLI is detecting something else (a fork, the old name of a repo that was renamed...). The `--debug` argument is not really needed, but this way the CLI will print some extra output and this will allow to see more details on the requests it's running.

Would you like to give this a try and let us know how it goes?

Thanks!

**Comment by 1138-4EB** [comment]
Por supuesto :D. It must be the first issue you pointed, because i) I did not use the `--pro` swtich, and ii) there is no fork of that repo. Let me try, and I'll keep you posted.

**Comment by 1138-4EB** [comment]
Done. It works seamlessly now: https://travis-ci.com/ghdl/docker/builds/75364781 Thanks a lot!

I think that I was confused because I thought that `--pro` was related to paid services, not to the domain itself. Since our project is open and free, we had never used the `.com` domain. It might be useful to rename `--pro` to `--com` to avoid confusion, now that non-pro projects can be hosted on travis-ci.com. It is shown [here](https://github.com/travis-ci/travis.rb#general-api-commands), but that might not be straightforward.
