### ISSUE TITLE
json: cannot unmarshal string into Go struct field RequestResponse.branch_name ...

### ISSUE THREAD

**Issue by BanzaiMan** [travis-ci/travis-ci#9672]
https://github.com/travis-ci/docs-travis-ci-com/issues/1858
----

I'm getting issues from the API: "json: cannot unmarshal string into Go struct field RequestResponse.branch_name ...".

It started happening today.

This page https://developer.travis-ci.com/resource/requests#Requests does state that 'branch_name' will be a string.

But was this recently changed?

**Comment by BanzaiMan** [comment]
https://github.com/travis-ci/docs-travis-ci-com/issues/1858#issuecomment-392547822

> @HaraldNordgren: I seem likely that https://github.com/travis-ci/travis-api/pull/766 is the root cause here. I think this should be enough to fully re-produce our issue: https://play.golang.org/p/PZkAutPRCAH

**Comment by HaraldNordgren** [comment]
I seem likely that https://github.com/travis-ci/travis-api/pull/766 is the root cause here.

I think this should be enough to fully re-produce our issue: https://play.golang.org/p/PZkAutPRCAH

Basically, we tied our expected response very closely to what the API returned at one point, and now you guys aligned it to the docs it starts failing. The good news for us is that we likely don't need this specific data, so one solution is just to reduce the response body and completely ignore extra fields.

**Comment by carlad** [comment]
Hey @HaraldNordgren, I've had a chat with the api developers here. That patch does now return the payload with the branch_name as a string, as it's supposed to. So you will need to change the struct on your end to conform with this change. Hope that helps.
