### ISSUE TITLE
Travis builds started freezing with no log output

### ISSUE THREAD

**Issue by Runemoro** [travis-ci/travis-ci#9675]
Since a few commits ago, my Travis builds are freezing on `compileJava` with no log output. I tried deleting the cache and I undid the changes I made to my `build.gradle` in the latest commit, but they're still not working. What could be wrong?

https://travis-ci.org/DimensionalDevelopment/VanillaFix

**Comment by thomas-p-wilson** [comment]
I'm having a similar issue, although I'm finding that the build freezes at random times, rather than specifically at the beginning with no log info. Consider https://travis-ci.org/CoinBub/daemon-interface-dash:

I originally had a multi-job build with a post-build stage for code-climate reporting. One out of three jobs would fail, and it would be a roll of the dice as to which of the jobs failed. When the build failed, sometimes it froze while performing an `apt install`, sometimes while performing a `curl` and othertimes it would freeze at some intermediary, travis-specific stage. I've been struggling with this for three full days now. I finally pared down my build to just a single job, and even that single job is randomly failing.

I'm hoping that adding my voice will yield some more information about what could be going wrong. I never had this trouble with CircleCI, but I've had a good number of stability issues since switching back to Travis, which I used to prefer. Hopefully we can get this resolved quickly.

**Comment by thomas-p-wilson** [comment]
Additionally, consider this build: https://travis-ci.org/CoinBub/daemon-interface-poli/builds/389829590

`pip install --user awscli` fails only _sometimes_, in this case complaining about SSL-related stuffs...

**Comment by thomas-p-wilson** [comment]
@Runemoro, unsure of which build it is that contains no log output. I'm guessing https://travis-ci.org/DimensionalDevelopment/VanillaFix/builds/385048019 is one of them?

**Comment by Runemoro** [comment]
Yes, that's one of the builds that froze. A few hours after posting this issue, the problem went away without me doing anything and builds started completing though.

**Comment by thomas-p-wilson** [comment]
Sounds right. I've been having intermittent problems over the past couple
days, no one specific area of my build failing. Hopefully one of the Travis
folks can investigate soon.
