### ISSUE TITLE
Elasticbeanstalk deployment error about S3 bucket region.

### ISSUE THREAD

**Issue by AntonyBaasan** [travis-ci/travis-ci#9747]
```deploy:
  provider: elasticbeanstalk
  access_key_id: ....
  secret_access_key:
    secure: ...
  region: "us-east-2"  
  app: "example-app-name"
  env: "example-app-environment"
  bucket_name: "elasticbeanstalk-us-east-2-123766920165"
```
My deployment fails with error:
`S3 client configured for "us-east-2" but the bucket "elasticbeanstalk-us-east-2-123766920165" is in "us-east-2"; Please configure the proper region to avoid multiple unnecessary redirects and signing attempts`

Both my enviroment and S3 bucket are in `us-east-2` region, but looks like `aws-sdk-resources-2.11.68` is complaining about that?

Can you please tell me where I can find a solution?

![48](https://user-images.githubusercontent.com/4986601/41428005-c31ed716-6fd6-11e8-990a-316c6030a4f3.JPG)

**Comment by AntonyBaasan** [comment]
This was a permission issue on the AWS side. My bad.
I gave `AWSElasticBeanstalkFullAccess`  permission and it works OK.
More about the permission https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/AWSHowTo.iam.managed-policies.html

**Comment by ninth-mind** [comment]
I am having the exact same problem with Travis CI. So I created a new IAM user to have the `AWSElasticBeanstalkFullAccess` policy. Included that encrypted `access_key_id` and `secret_access_key` but my build is still failing. However, what is curious, is that the build will actually still deploy on Elastic Beanstalk. I can see the .zip files in my S3 bucket, and the new code is pushed and deployed. 

Any thoughts on why the travis build would still be failing?

**Comment by tmaximini** [comment]
I have the same issue, see here: https://github.com/travis-ci/dpl/issues/956
My IAM user has `AWSElasticBeanstalkFullAccess` as well.
@ninth-mind did you solve this issue? I don't think my app gets deployed though.

**Comment by ninth-mind** [comment]
@tmaximini : nope. I stopped using AWS as I kept running into problems like this one. Moved everything to Digital Ocean droplet running Dokku, and everything was easy as pie.

**Comment by charanreddy2646** [comment]
> I have the same issue, see here: [travis-ci/dpl#956](https://github.com/travis-ci/dpl/issues/956)
> My IAM user has `AWSElasticBeanstalkFullAccess` as well.
> @ninth-mind did you solve this issue? I don't think my app gets deployed though.

Hello,

Are you able to solve the issue, my build also fails saying failed to deploy.

**Comment by tomdaly** [comment]
Apologies for commenting on a closed issue, but I found this issue and [another](https://github.com/travis-ci/dpl/issues/956) describing almost the same problem. After a couple of days trying to fix this, I found a solution.

The problem is definitely due to the AWS access key ID and secret access key being incorrect, but the error message given is useless.
The fix:
* Install Travis CLI using steps from [this link](https://docs.travis-ci.com/user/encryption-keys#usage) (if using travis-ci**.com** instead of travis-ci**.org** ensure to login using travis login --pro first!)
* Copy access key ID from AWS IAM console
* Run `travis encrypt --add deploy.access_key_id` in the directory containing your repository (add `--pro` to command if using travis-ci.com) then paste in access key, press Ctrl-D and it saves the encrypted key to travis.yml
* Copy secret access key from AWS IAM console
* Run `travis encrypt --add deploy.secret_access_key` (again add `--pro` to command if usinv travis-ci.com)

It might be useful to add `skip_cleanup: true` property under `deploy:` in travis.yml to prevent travis deleting build output before it uploads to AWS
I also had to add a `zip_file:` property under `deploy:` to ensure that the correct .jar file was uploaded to S3, but YMMV
