### ISSUE TITLE
Travis all schemes building when only a few specified

### ISSUE THREAD

**Issue by rob-nash** [travis-ci/travis-ci#9806]
I have three schemes in my Xcode project

 - Gradient-iOS (Framework target)
 - Gradient-macOS (Framework target)
 - Gradient-Demo (App target)

The following isn't working on Travis.

    language: swift
    xcode_project: Gradient.xcodeproj
    osx_image: xcode9.3
    xcode_sdk: iphonesimulator11.3
    xcode_scheme:
     - Gradient-iOS
     - Gradient-macOS
    
    script: 
     - xcodebuild clean build

All of the schemes run. The scheme `Gradient-Demo` fails with code-signing related issues. I don't want to fix it. I just don't want that scheme to run at all.

https://travis-ci.org/rob-nash/Gradient/builds/396823889

I can't find any documentation or blog posts describing this issue. Seems like a bug, so thought it would be appropriate to raise it here.

**Comment by mjm** [comment]
Thanks for reaching out to us!

The `xcode_sdk`, `xcode_scheme`, and `xcode_project` config keys (and the other xcode-related ones) will inform what our default `script` runs. However, if you add your own `script` to your .travis.yml, we'll run that as is, without alteration, instead of our default script.

You can still take advantage of these config keys, but it will be a little more explicit. Each of those config values also gets exported as an environment variable during the build, which you can use in your script:

- `xcode_scheme` becomes `$TRAVIS_XCODE_SCHEME`
- `xcode_sdk` becomes `$TRAVIS_XCODE_SDK`
- `xcode_project` becomes `$TRAVIS_XCODE_PROJECT`

So you could update your script to be:

```
script:
- xcodebuild clean build -scheme "$TRAVIS_XCODE_SCHEME" -project "$TRAVIS_XCODE_PROJECT" -sdk "$TRAVIS_XCODE_SDK"
```

If you do, I think things would work as you expect. I'll look into us adding some more documentation about this.

**Comment by rob-nash** [comment]
thanks @mjm
