### ISSUE TITLE
Delivering output and annotations using Github Checks API ?

### ISSUE THREAD

**Issue by nojb** [travis-ci/travis-ci#9828]
Hello,

Are there any plans to support output/annotations using the Github Checks API (cf https://developer.github.com/v3/checks/runs/#update-a-check-run) during a Travis build?

Thanks!

**Comment by webknjaz** [comment]
Hi @nojb,

I've built a CLI for hitting Checks API: https://github.com/webknjaz/check-in.
I'm about to test it in some CIs I maintain for delivering linter messages and project-specific info.
Feel free to `pip install check-in` and try it out with your own test integration :)

I didn't really document it, but you can ping me for help.

**Comment by nojb** [comment]
@webknjaz Thanks, but your tool seems to require control of the Github App that sends the annotations; I would like to attach annotations to Travis-controlled builds; I am not sure it is possible to do that "from outside" (for one, how to get the various IDs which are required?).

**Comment by webknjaz** [comment]
Yes, it will not use Travis's GitHub App integration. It will show up as a separate check suite of your own app. But it is a valid workaround until they come up with something. For now they don't even parse test results from reports like other services do, so there's other missing pre-requisites and since there's no public announcement about prioritizing such work I assume that it is not yet planned at this point.
By now I've only heard of Shippable working on using this API.
Other thing would be is that having own tool would be cross-CI.

To do it, you need to create your own GitHub App. You can have it in private access, visible to you or organization.
It will give you ID on the settings page and you'll need to generate and download the private key from there.
Then, you can set up dotenv file with CLI arguments, which don't change across tool runs.

When ready, you run post_check and it will output run id, which you can then reuse in update_check.

https://twitter.com/webKnjaZ/status/1003564360491589632?s=19

**Comment by webknjaz** [comment]
Unstale

**Comment by DrTorte** [comment]
Hello,

We're moving our community communications to the [Travis CI Community Forum](https://travis-ci.community) and will no longer be supporting GitHub issues. If this hasn't been solved, please go ahead and create a new thread on the Forum and we'll be better able to help you there. We're looking forward to seeing you there.

If you need support, you can reach our support team here: [support@travis-ci.com](mailto:support@travis-ci.com).

Thanks and happy building!

**Comment by discordier** [comment]
Has been moved here: https://travis-ci.community/t/delivering-output-and-annotations-using-github-checks-api-migrated-github-issue/1263/5

Hope this helps others searching where the discussion moved.
