### ISSUE TITLE
Notifications are being sent despite being disabled in .travis.yml

### ISSUE THREAD

**Issue by mjm** [travis-ci/travis-ci#9910]
I've got a repository whose configuration seems like it should have email notifications turned off: https://github.com/travis-ci/packer-templates-mac/blob/0562edaac27c77afbcbb872dafc4be0215d6911e/.travis.yml

However, I'm still getting emails for builds on this repo.

**Comment by iriberri** [comment]
Hi @mjm! :D Could you please share a link to a build for which you received the email, or, does this happen for all builds in `packer-templates-mac`? I'm happy to take a further look!

**Comment by mjm** [comment]
It's happening for every build that would send a notification by default. For a while, the builds were failing, so I got an email for all of them up until the first one that made it go green. Since then, I haven't gotten any because they've been green, and I think that's expected behavior by default (without notifications turned off).

Here's an arbitrary one that did send an email, if that helps investigation: https://travis-ci.com/travis-ci/packer-templates-mac/builds/79982408

**Comment by iriberri** [comment]
Thanks @mjm! I'm seeing something interesting here.

The notification config in your build seems to has been parsed as:

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1730320/43317094-cffabe14-919b-11e8-989e-1c1dee097919.png">

Whereas a build test of mine, with the same options, is getting:

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1730320/43317103-da8067a8-919b-11e8-9819-b439918a0908.png">

Trying to figure out what causes this difference, because I believe this may be root of the issue. I do see `travis-tasks` logging that it's sending the email, so it looks like it's indeed receiving some wrong/unexpected config.

**Comment by mjm** [comment]
Cool, thanks for looking at this @iriberri! Looks like it's only an issue for builds on our Travis CI orgs, which is something.

**Comment by mjm** [comment]
This is still an issue, I believe.

**Comment by DrTorte** [comment]
Migrating to the forum! [Please see this link](https://travis-ci.community/t/issue-notifications-are-being-sent-despite-being-disabled-in-travis-yml-migrated-github-issue/1221).

Thanks and happy building!
