### ISSUE TITLE
macOS builds limited to 1024x768 display resolution?

### ISSUE THREAD

**Issue by fniephaus** [travis-ci/travis-ci#9998]
According to the following, macOS builds use a display resolution of `1024x768` by default:
```
Traviss-Mac-1284:~ travis$ system_profiler SPDisplaysDataType | grep Resolution
          Resolution: 1024 x 768
```

Is there any way to adjust the display resolution of Travis' virtual macOS environment? It seems that tools like [screenresolution](https://github.com/jhford/screenresolution) don't work unfortunately.

**Comment by fniephaus** [comment]
Apparently, this seems to somewhat work:
```bash
Traviss-Mac-1284:~ travis$ "/Library/Application Support/VMware Tools/vmware-resolutionSet" 1920 1080
Requested resolution: 1920x1080
Effective resolution: 1176x885
Traviss-Mac-1284:~ travis$ system_profiler SPDisplaysDataType | grep Resolution
          Resolution: 1176 x 885
```

Not the resolution requested, but maybe large enough for our use case.

**Comment by fniephaus** [comment]
> If the effective resolution is smaller than requested, follow [KB 1003](http://kb.vmware.com/kb/1003) to increase the video memory size of the virtual machine.

**Comment by jmozmoz** [comment]
So is there a way to change the video memory in travis.yml?

**Comment by fniephaus** [comment]
> So is there a way to change the video memory in travis.yml?

@jmozmoz I don't think so as this is set within the virtualization software and cannot be changed in the travis.yml (yet).

**Comment by DrTorte** [comment]
Hey there,

I've made sure this is being tracked internally, and we're looking at a potential solution to it by increasing the available VRAM (from the current 4MB.) We'll provide an update if we're able to do so, although no timelines are set at this stage beyond a cursory investigation. 

In the meanwhile, I'll be closing this issue here, and directing any further conversation to our [Travis CI Community Forum](https://travis-ci.community)! We'll be glad to chat with you there about anything further regarding this or other subjects.

Thanks and happy building!
